CREATE TABLE mktg_ops_tbls.adb_nmswebapp (
    iwebappid integer NOT NULL ENCODE raw distkey,
    iadvanced smallint NOT NULL ENCODE az64,
    iappstate smallint NOT NULL ENCODE az64,
    iapptype smallint NOT NULL ENCODE az64,
    ibuiltin smallint NOT NULL ENCODE az64,
    icreatedbyid integer NOT NULL ENCODE az64,
    idefaultdictionaryid integer NOT NULL ENCODE az64,
    idefaultoriginid integer NOT NULL ENCODE az64,
    ideliverymappingid integer NOT NULL ENCODE az64,
    ifolderid integer NOT NULL ENCODE az64,
    ifolderprocessid integer NOT NULL ENCODE az64,
    ihashtmlpage smallint NOT NULL ENCODE az64,
    iidcounter integer NOT NULL ENCODE az64,
    iismodel smallint NOT NULL ENCODE az64,
    imodifiedbyid integer NOT NULL ENCODE az64,
    ioperationid integer NOT NULL ENCODE az64,
    ioperatorid integer NOT NULL ENCODE az64,
    irenderingid integer NOT NULL ENCODE az64,
    istate smallint NOT NULL ENCODE az64,
    itranslationstatus smallint NOT NULL ENCODE az64,
    mdata character varying(4500) ENCODE lzo,
    sdefaultlanguage character varying(255) ENCODE lzo,
    sdesc character varying(512) ENCODE lzo,
    sdesignlanguage character varying(255) ENCODE lzo,
    sinternalname character varying(64) ENCODE lzo,
    slabel character varying(128) ENCODE lzo,
    slibrary character varying(255) ENCODE lzo,
    snature character varying(64) ENCODE lzo,
    stimezone character varying(64) ENCODE lzo,
    tscreated timestamp without time zone ENCODE az64,
    tsend timestamp without time zone ENCODE az64,
    tslastmodified timestamp without time zone ENCODE az64,
    tspublication timestamp without time zone ENCODE az64,
    tsstart timestamp without time zone ENCODE az64,
    ipurl smallint NOT NULL ENCODE az64,
    isocial smallint NOT NULL ENCODE az64,
    isocialaccountid integer NOT NULL ENCODE az64,
    isurvey smallint NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( iwebappid );