CREATE TABLE mktg_ops_tbls.adb_nmsoperation (
    dcomputedcost double precision NOT NULL ENCODE raw,
    dduration double precision ENCODE raw,
    destimatedcost double precision NOT NULL ENCODE raw,
    dfixedcost double precision NOT NULL ENCODE raw,
    dperiodcovered double precision ENCODE raw,
    drealcost double precision NOT NULL ENCODE raw,
    iassignedition smallint NOT NULL ENCODE az64,
    ibudgetid integer NOT NULL ENCODE az64,
    ibudgetstatus smallint NOT NULL ENCODE az64,
    ibuiltin smallint NOT NULL ENCODE az64,
    icancelstate smallint NOT NULL ENCODE az64,
    icentrallocaltype smallint NOT NULL ENCODE az64,
    icommitmentlevel smallint NOT NULL ENCODE az64,
    icomputationstate smallint NOT NULL ENCODE az64,
    icreatedbyid integer NOT NULL ENCODE az64,
    idisablenotification smallint NOT NULL ENCODE az64,
    iexternalvalidation smallint NOT NULL ENCODE az64,
    ifcpgroupid integer NOT NULL ENCODE az64,
    iforecasted smallint NOT NULL ENCODE az64,
    iismodel smallint NOT NULL ENCODE az64,
    ilinkedoperationid integer NOT NULL ENCODE az64,
    ilocalorgunitid integer NOT NULL ENCODE az64,
    imessagetype smallint NOT NULL ENCODE az64,
    imodifiedbyid integer NOT NULL ENCODE az64,
    inbdocument smallint NOT NULL ENCODE az64,
    inbvalidation smallint NOT NULL ENCODE az64,
    ioperationid integer NOT NULL ENCODE az64,
    iownerid integer NOT NULL ENCODE az64,
    ipriority smallint NOT NULL ENCODE az64,
    iprogramid integer NOT NULL ENCODE az64,
    iprogramprocessid integer NOT NULL ENCODE az64,
    isandboxmode smallint NOT NULL ENCODE az64,
    isharedmode smallint NOT NULL ENCODE az64,
    itype smallint NOT NULL ENCODE az64,
    iusebudget smallint NOT NULL ENCODE az64,
    iusebudgetvalidation smallint NOT NULL ENCODE az64,
    iusecentrallocal smallint NOT NULL ENCODE az64,
    iusecontentvalidation smallint NOT NULL ENCODE az64,
    iuseextractionvalidation smallint NOT NULL ENCODE az64,
    iusefcpvalidation smallint NOT NULL ENCODE az64,
    iuselinkeddeliveryvalidation smallint NOT NULL ENCODE az64,
    iusetargetvalidation smallint NOT NULL ENCODE az64,
    ivalidationmode smallint NOT NULL ENCODE az64,
    iwebapptype smallint NOT NULL ENCODE az64,
    mdata character varying(4000) ENCODE lzo,
    sinternalname character varying(64) ENCODE lzo,
    slabel character varying(128) ENCODE lzo,
    slogin character varying(64) ENCODE lzo,
    snature character varying(64) ENCODE lzo,
    tscreated timestamp without time zone ENCODE az64,
    tsend timestamp without time zone ENCODE az64,
    tslastcomputed timestamp without time zone ENCODE az64,
    tslastmodified timestamp without time zone ENCODE az64,
    tsstart timestamp without time zone ENCODE az64,
    davg_investment_per_cust double precision NOT NULL ENCODE raw,
    dcommission_per_cust double precision NOT NULL ENCODE raw,
    destprovcost double precision NOT NULL ENCODE raw,
    dmargin_benefit_per_cust double precision NOT NULL ENCODE raw,
    dperc_hi_sales double precision NOT NULL ENCODE raw,
    dperc_reviews_attended double precision NOT NULL ENCODE raw,
    dperc_reviews_booked double precision NOT NULL ENCODE raw,
    dperc_fp_sales double precision NOT NULL ENCODE raw,
    dperc_sav_sales double precision NOT NULL ENCODE raw,
    dperc_sfs_referrals double precision NOT NULL ENCODE raw,
    dperc_sfs_sales double precision NOT NULL ENCODE raw,
    dperc_will_sales double precision NOT NULL ENCODE raw,
    droi double precision NOT NULL ENCODE raw,
    idropfilerequired smallint NOT NULL ENCODE az64,
    iexpected_volume integer NOT NULL ENCODE az64,
    ifk_actions integer NOT NULL ENCODE az64,
    ifk_incometypes integer NOT NULL ENCODE az64,
    ifk_reactions integer NOT NULL ENCODE az64,
    ifk_cmp_hierarchies integer NOT NULL ENCODE az64,
    iusetask smallint NOT NULL ENCODE az64,
    iusetaskcreation smallint NOT NULL ENCODE az64,
    iwebanalyticsaccountid integer NOT NULL ENCODE az64,
    scmp_deliverycode character varying(36) ENCODE lzo,
    scmp_lettercode character varying(6) ENCODE lzo,
    scmp_letternotes character varying(60) ENCODE lzo,
    scmp_nature character varying(64) ENCODE lzo,
    iistriggeredcampaign smallint NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE AUTO;