CREATE TABLE mktg_ops_tbls.adb_nmsservice (
    iboolean1 smallint ENCODE az64,
    iboolean2 smallint ENCODE az64,
    iboolean3 smallint ENCODE az64,
    icreatedbyid integer ENCODE az64,
    ifolderid integer ENCODE az64,
    imode smallint ENCODE az64,
    imodifiedbyid integer ENCODE az64,
    iserviceid integer ENCODE az64,
    isubscenarioid integer ENCODE az64,
    itype smallint ENCODE az64,
    iunlimited smallint ENCODE az64,
    iunsubscenarioid integer ENCODE az64,
    sdesc character varying(512) ENCODE lzo,
    slabel character varying(128) ENCODE lzo,
    sname character varying(64) ENCODE lzo,
    stext1 character varying(180) ENCODE lzo,
    stext2 character varying(180) ENCODE lzo,
    stext3 character varying(180) ENCODE lzo,
    stext4 character varying(180) ENCODE lzo,
    stext5 character varying(180) ENCODE lzo,
    tscreated timestamp without time zone ENCODE az64,
    tslastmodified timestamp without time zone ENCODE az64,
    tsvalidity double precision ENCODE raw,
    iaudience integer ENCODE az64,
    imobileappstargetmappingid integer ENCODE az64,
    isyncsubscription smallint ENCODE az64,
    ivisitorfolderid integer ENCODE az64,
    saccesstoken character varying(250) ENCODE lzo,
    saccesstokensecret character varying(250) ENCODE lzo,
    scategory character varying(128) ENCODE lzo,
    sconsumerkey character varying(250) ENCODE lzo,
    sconsumersecret character varying(250) ENCODE lzo,
    sexternalid character varying(64) ENCODE lzo,
    sexternalpicture character varying(128) ENCODE lzo,
    sexternalurl character varying(128) ENCODE lzo,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;