CREATE TABLE mktg_ops_tbls.adb_nmswebapplogrcpdata (
    iwebapplogid integer NOT NULL ENCODE az64,
    byte0 smallint ENCODE az64,
    byte1 smallint ENCODE az64,
    byte2 smallint ENCODE az64,
    byte3 smallint ENCODE az64,
    byte4 smallint ENCODE az64,
    byte5 smallint ENCODE az64,
    byte6 smallint ENCODE az64,
    byte7 smallint ENCODE az64,
    byte8 smallint ENCODE az64,
    byte9 smallint ENCODE az64,
    byte10 smallint ENCODE az64,
    byte11 smallint ENCODE az64,
    byte12 smallint ENCODE az64,
    byte13 smallint ENCODE az64,
    byte14 smallint ENCODE az64,
    byte15 smallint ENCODE az64,
    byte16 smallint ENCODE az64,
    byte17 smallint ENCODE az64,
    byte18 smallint ENCODE az64,
    byte19 smallint ENCODE az64,
    byte20 smallint ENCODE az64,
    byte21 smallint ENCODE az64,
    byte22 smallint ENCODE az64,
    byte23 smallint ENCODE az64,
    boolean0 smallint ENCODE az64,
    boolean1 smallint ENCODE az64,
    boolean2 smallint ENCODE az64,
    boolean3 smallint ENCODE az64,
    boolean4 smallint ENCODE az64,
    boolean5 smallint ENCODE az64,
    boolean6 smallint ENCODE az64,
    boolean7 smallint ENCODE az64,
    boolean8 smallint ENCODE az64,
    boolean9 smallint ENCODE az64,
    boolean10 smallint ENCODE az64,
    boolean11 smallint ENCODE az64,
    boolean12 smallint ENCODE az64,
    boolean13 smallint ENCODE az64,
    boolean14 smallint ENCODE az64,
    boolean15 smallint ENCODE az64,
    boolean16 smallint ENCODE az64,
    boolean17 smallint ENCODE az64,
    boolean18 smallint ENCODE az64,
    boolean19 smallint ENCODE az64,
    boolean20 smallint ENCODE az64,
    boolean21 smallint ENCODE az64,
    boolean22 smallint ENCODE az64,
    boolean23 smallint ENCODE az64,
    boolean24 smallint ENCODE az64,
    boolean25 smallint ENCODE az64,
    boolean26 smallint ENCODE az64,
    boolean27 smallint ENCODE az64,
    boolean28 smallint ENCODE az64,
    boolean29 smallint ENCODE az64,
    boolean30 smallint ENCODE az64,
    boolean31 smallint ENCODE az64,
    boolean32 smallint ENCODE az64,
    boolean33 smallint ENCODE az64,
    string0 character varying(300) ENCODE lzo,
    string1 character varying(255) ENCODE lzo,
    string10 character varying(255) ENCODE lzo,
    string11 character varying(255) ENCODE lzo,
    string12 character varying(255) ENCODE lzo,
    string13 character varying(255) ENCODE lzo,
    string14 character varying(255) ENCODE lzo,
    string15 character varying(255) ENCODE lzo,
    string16 character varying(255) ENCODE lzo,
    string2 character varying(300) ENCODE lzo,
    string3 character varying(300) ENCODE lzo,
    string4 character varying(255) ENCODE lzo,
    string5 character varying(255) ENCODE lzo,
    string6 character varying(255) ENCODE lzo,
    string7 character varying(255) ENCODE lzo,
    string8 character varying(255) ENCODE lzo,
    string9 character varying(255) ENCODE lzo,
    string17 character varying(255) ENCODE lzo,
    string18 character varying(255) ENCODE lzo,
    string19 character varying(255) ENCODE lzo,
    string20 character varying(255) ENCODE lzo,
    string21 character varying(255) ENCODE lzo,
    string22 character varying(255) ENCODE lzo,
    string23 character varying(255) ENCODE lzo,
    string24 character varying(255) ENCODE lzo,
    string25 character varying(255) ENCODE lzo,
    string26 character varying(255) ENCODE lzo,
    string27 character varying(255) ENCODE lzo,
    string28 character varying(255) ENCODE lzo,
    string29 character varying(255) ENCODE lzo,
    string30 character varying(255) ENCODE lzo,
    string31 character varying(255) ENCODE lzo,
    string32 character varying(255) ENCODE lzo,
    string33 character varying(255) ENCODE lzo,
    string34 character varying(255) ENCODE lzo,
    string35 character varying(255) ENCODE lzo,
    string36 character varying(255) ENCODE lzo,
    string37 character varying(255) ENCODE lzo,
    string38 character varying(255) ENCODE lzo,
    string39 character varying(255) ENCODE lzo,
    string40 character varying(255) ENCODE lzo,
    string41 character varying(255) ENCODE lzo,
    string42 character varying(255) ENCODE lzo,
    string43 character varying(255) ENCODE lzo,
    string44 character varying(255) ENCODE lzo,
    string45 character varying(255) ENCODE lzo,
    string46 character varying(255) ENCODE lzo,
    string47 character varying(255) ENCODE lzo,
    string48 character varying(255) ENCODE lzo,
    int641 bigint ENCODE az64,
    long0 integer ENCODE az64,
    string50 character varying(255) ENCODE lzo,
    string51 character varying(255) ENCODE lzo,
    string52 character varying(255) ENCODE lzo,
    mdata character varying(10000) ENCODE lzo,
    datetime0 timestamp without time zone ENCODE az64,
    string49 character varying(255) ENCODE lzo,
    string53 character varying(255) ENCODE lzo,
    string54 character varying(255) ENCODE lzo,
    string55 character varying(255) ENCODE lzo,
    string56 character varying(255) ENCODE lzo,
    string57 character varying(255) ENCODE lzo,
    string58 character varying(255) ENCODE lzo,
    string59 character varying(255) ENCODE lzo,
    string60 character varying(255) ENCODE lzo,
    string61 character varying(255) ENCODE lzo,
    string62 character varying(255) ENCODE lzo,
    string63 character varying(255) ENCODE lzo,
    string64 character varying(255) ENCODE lzo,
    string65 character varying(255) ENCODE lzo,
    string71 character varying(255) ENCODE lzo,
    string72 character varying(255) ENCODE lzo,
    string73 character varying(255) ENCODE lzo,
    string74 character varying(255) ENCODE lzo,
    string76 character varying(255) ENCODE lzo,
    string66 character varying(255) ENCODE lzo,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;