CREATE TABLE mktg_ops_tbls.adb_nmstrackingurl (
    ichecksum integer NOT NULL ENCODE az64,
    ideliveryid integer NOT NULL ENCODE az64,
    ifolderid integer NOT NULL ENCODE az64,
    ioccurrence smallint NOT NULL ENCODE az64,
    iofferid integer NOT NULL ENCODE az64,
    istep smallint NOT NULL ENCODE az64,
    itrackingurlid integer NOT NULL ENCODE az64,
    itype smallint NOT NULL ENCODE az64,
    iwebappid integer NOT NULL ENCODE az64,
    iwithparams smallint NOT NULL ENCODE az64,
    scategory character varying(100) ENCODE lzo,
    sgoal character varying(64) ENCODE lzo,
    slabel character varying(300) ENCODE lzo,
    ssource character varying(1000) ENCODE lzo,
    stagid character varying(128) ENCODE lzo,
    strackername character varying(32) ENCODE lzo,
    tsvalidity timestamp without time zone ENCODE az64,
    ipurlid integer NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;