CREATE TABLE mktg_ops_tbls.adb_xtkworkflow (
    iaggregateid integer NOT NULL ENCODE az64,
    ibuiltin smallint NOT NULL ENCODE az64,
    icreatedbyid integer NOT NULL ENCODE az64,
    icurrentorderid integer NOT NULL ENCODE az64,
    ierrorlimit integer NOT NULL ENCODE az64,
    ifailed smallint NOT NULL ENCODE az64,
    ifolderid integer NOT NULL ENCODE az64,
    ifolderprocessid integer NOT NULL ENCODE az64,
    iforecasted smallint NOT NULL ENCODE az64,
    ihistory integer NOT NULL ENCODE az64,
    iinprocess smallint NOT NULL ENCODE az64,
    iismodel smallint NOT NULL ENCODE az64,
    imodifiedbyid integer NOT NULL ENCODE az64,
    ionerror smallint NOT NULL ENCODE az64,
    ioperationid integer NOT NULL ENCODE az64,
    iorder integer NOT NULL ENCODE az64,
    iport integer NOT NULL ENCODE az64,
    ipriority smallint NOT NULL ENCODE az64,
    iprocessid integer NOT NULL ENCODE az64,
    iproduction smallint NOT NULL ENCODE az64,
    irecurrentmdl smallint NOT NULL ENCODE az64,
    iroutingoperationid integer NOT NULL ENCODE az64,
    istartstate smallint NOT NULL ENCODE az64,
    istate smallint NOT NULL ENCODE az64,
    istatus smallint NOT NULL ENCODE az64,
    isupervisorid integer NOT NULL ENCODE az64,
    iunlockedcount integer NOT NULL ENCODE az64,
    iworkflowid integer NOT NULL ENCODE az64 distkey,
    mdata character varying(4800) ENCODE lzo,
    mvisualstate character varying(4800) ENCODE lzo,
    sdesc character varying(2400) ENCODE lzo,
    sform character varying(96) ENCODE lzo,
    shostname character varying(76) ENCODE lzo,
    sinternalname character varying(76) ENCODE lzo,
    slabel character varying(153) ENCODE lzo,
    slogin character varying(76) ENCODE lzo,
    snextprocessingafn character varying(48) ENCODE lzo,
    snextprocessinghost character varying(76) ENCODE lzo,
    stimezone character varying(76) ENCODE lzo,
    tscreated timestamp without time zone ENCODE az64,
    tsexpiration timestamp without time zone ENCODE az64,
    tslastmodified timestamp without time zone ENCODE az64,
    tslaststart timestamp without time zone ENCODE az64,
    tsnextprocessing timestamp without time zone ENCODE az64,
    tsprocess timestamp without time zone ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( iworkflowid );