CREATE TABLE mktg_ops_tbls.adb_nmsdelivery (
    damount double precision NOT NULL ENCODE raw,
    dcomputedcost double precision NOT NULL ENCODE raw,
    ddelayextraction double precision ENCODE raw,
    dduration double precision NOT NULL ENCODE raw,
    destimatedcost double precision NOT NULL ENCODE raw,
    drate double precision NOT NULL ENCODE raw,
    drealcost double precision NOT NULL ENCODE raw,
    dretryperiod double precision ENCODE raw,
    dtotalestimatedmargin double precision NOT NULL ENCODE raw,
    dtotalestimatedrealized double precision NOT NULL ENCODE raw,
    ianalysisstep smallint NOT NULL ENCODE az64,
    iarticle integer NOT NULL ENCODE az64,
    iassignedition smallint NOT NULL ENCODE az64,
    ibudgetid integer NOT NULL ENCODE az64,
    ibudgetstatus smallint NOT NULL ENCODE az64,
    ibuiltin smallint NOT NULL ENCODE az64,
    icommitmentlevel smallint NOT NULL ENCODE az64,
    icomputationstate smallint NOT NULL ENCODE az64,
    icontentstatus smallint NOT NULL ENCODE az64,
    icreatedbyid integer NOT NULL ENCODE az64,
    ictrlgrpreject integer NOT NULL ENCODE az64,
    icurrentorderid integer NOT NULL ENCODE az64,
    idelayed smallint NOT NULL ENCODE az64,
    ideletestatus smallint NOT NULL ENCODE az64,
    ideliveryid integer NOT NULL ENCODE az64,
    ideliverymode smallint NOT NULL ENCODE az64,
    ideliveryoutlineid integer NOT NULL ENCODE az64,
    ideliveryproviderid integer NOT NULL ENCODE az64,
    idirty smallint NOT NULL ENCODE az64,
    idisablenotification smallint NOT NULL ENCODE az64,
    idisabled integer NOT NULL ENCODE az64,
    ierror integer NOT NULL ENCODE az64,
    ierrorpending integer NOT NULL ENCODE az64,
    iexternalvalidation smallint NOT NULL ENCODE az64,
    iextractionstatus smallint NOT NULL ENCODE az64,
    ifcp smallint NOT NULL ENCODE az64,
    ifcporseedcount integer NOT NULL ENCODE az64,
    ifolderid integer NOT NULL ENCODE az64,
    ifolderprocessid integer NOT NULL ENCODE az64,
    iforecasted smallint NOT NULL ENCODE az64,
    iforward integer NOT NULL ENCODE az64,
    ihasattachments smallint NOT NULL ENCODE az64,
    ihtml integer NOT NULL ENCODE az64,
    iimportreject integer NOT NULL ENCODE az64,
    iinsertmode smallint NOT NULL ENCODE az64,
    iinvaliddomain integer NOT NULL ENCODE az64,
    iismodel smallint NOT NULL ENCODE az64,
    ilinkeddeliveryid integer NOT NULL ENCODE az64,
    imailboxfull integer NOT NULL ENCODE az64,
    imappingid integer NOT NULL ENCODE az64,
    imaxretry smallint NOT NULL ENCODE az64,
    imessagetype smallint NOT NULL ENCODE az64,
    imidremoteid integer NOT NULL ENCODE az64,
    imidsourcing smallint NOT NULL ENCODE az64,
    imirrorpage integer NOT NULL ENCODE az64,
    imodifiedbyid integer NOT NULL ENCODE az64,
    imsgpriority smallint NOT NULL ENCODE az64,
    imultipart integer NOT NULL ENCODE az64,
    ineedmirrorpage smallint NOT NULL ENCODE az64,
    inewquarantine integer NOT NULL ENCODE az64,
    inotconnected integer NOT NULL ENCODE az64,
    iofferanonymouscategoryid integer NOT NULL ENCODE az64,
    ioffercategoryid integer NOT NULL ENCODE az64,
    iofferspaceid integer NOT NULL ENCODE az64,
    ioperationid integer NOT NULL ENCODE az64,
    ioptout integer NOT NULL ENCODE az64,
    iowneroperationid integer NOT NULL ENCODE az64,
    ipersonclick integer NOT NULL ENCODE az64,
    ipriority smallint NOT NULL ENCODE az64,
    iprocessed integer NOT NULL ENCODE az64,
    iproofeddeliveryid integer NOT NULL ENCODE az64,
    ipropositioncount integer NOT NULL ENCODE az64,
    irecipientclick integer NOT NULL ENCODE az64,
    irecipientopen integer NOT NULL ENCODE az64,
    irecurringdeliveryid integer NOT NULL ENCODE az64,
    irefused integer NOT NULL ENCODE az64,
    ireject integer NOT NULL ENCODE az64,
    iretry smallint NOT NULL ENCODE az64,
    iroutingdeliveryid integer NOT NULL ENCODE az64,
    isandboxmode smallint NOT NULL ENCODE az64,
    isandboxstatus smallint NOT NULL ENCODE az64,
    iseedprocessed integer NOT NULL ENCODE az64,
    isent integer NOT NULL ENCODE az64,
    istate smallint NOT NULL ENCODE az64,
    istatus smallint NOT NULL ENCODE az64,
    isuccess integer NOT NULL ENCODE az64,
    isuccesswithoutseeds integer NOT NULL ENCODE az64,
    isuppliermodelid integer NOT NULL ENCODE az64,
    itargetstatus smallint NOT NULL ENCODE az64,
    itext integer NOT NULL ENCODE az64,
    itodeliver integer NOT NULL ENCODE az64,
    itovalidate integer NOT NULL ENCODE az64,
    itotalrecipientclick integer NOT NULL ENCODE az64,
    itotalrecipientopen integer NOT NULL ENCODE az64,
    itotalwebpage integer NOT NULL ENCODE az64,
    itrackingpending integer NOT NULL ENCODE az64,
    itransaction integer NOT NULL ENCODE az64,
    itypologyid integer NOT NULL ENCODE az64,
    iunknownuser integer NOT NULL ENCODE az64,
    iunreachable integer NOT NULL ENCODE az64,
    iurl integer NOT NULL ENCODE az64,
    iusebudgetvalidation smallint NOT NULL ENCODE az64,
    iusecontentvalidation smallint NOT NULL ENCODE az64,
    iusedce smallint NOT NULL ENCODE az64,
    iuseextractionvalidation smallint NOT NULL ENCODE az64,
    iusefcpvalidation smallint NOT NULL ENCODE az64,
    iuselinkeddeliveryvalidation smallint NOT NULL ENCODE az64,
    iusetargetvalidation smallint NOT NULL ENCODE az64,
    ivalidationmode smallint NOT NULL ENCODE az64,
    iwebpage integer NOT NULL ENCODE az64,
    iwebrespurged smallint NOT NULL ENCODE az64,
    iweight integer NOT NULL ENCODE az64,
    iweighttype smallint NOT NULL ENCODE az64,
    iworkflowid integer NOT NULL ENCODE az64,
    mdata character varying(4500) ENCODE lzo,
    sdeliverycode character varying(36) ENCODE lzo,
    sdesc character varying(512) ENCODE lzo,
    sipaffinity character varying(64) ENCODE lzo,
    sinternalname character varying(100) ENCODE lzo,
    sjobtype character varying(32) ENCODE lzo,
    slabel character varying(128) ENCODE lzo,
    slogin character varying(64) ENCODE lzo,
    snature character varying(64) ENCODE lzo,
    svalidationmode character varying(16) ENCODE lzo,
    sxtkschema character varying(80) ENCODE lzo,
    tsbroadend timestamp without time zone ENCODE az64,
    tsbroadstart timestamp without time zone ENCODE az64,
    tscontact timestamp without time zone ENCODE az64,
    tscontentmodtime timestamp without time zone ENCODE az64,
    tscreated timestamp without time zone ENCODE az64,
    tsdelete timestamp without time zone ENCODE az64,
    tsend timestamp without time zone ENCODE az64,
    tsexpectedbudget timestamp without time zone ENCODE az64,
    tsexpectedcontent timestamp without time zone ENCODE az64,
    tsexpectededition timestamp without time zone ENCODE az64,
    tsexpectedexternal timestamp without time zone ENCODE az64,
    tsexpectedextraction timestamp without time zone ENCODE az64,
    tsexpectedfcp timestamp without time zone ENCODE az64,
    tsexpectedforecast timestamp without time zone ENCODE az64,
    tsexpectedtarget timestamp without time zone ENCODE az64,
    tsextracted timestamp without time zone ENCODE az64,
    tsextraction timestamp without time zone ENCODE az64,
    tslastcomputed timestamp without time zone ENCODE az64,
    tslasterrorcomputation timestamp without time zone ENCODE az64,
    tslastmodified timestamp without time zone ENCODE az64,
    tslasttrackingcomputation timestamp without time zone ENCODE az64,
    tsnextpass timestamp without time zone ENCODE az64,
    tspassstart timestamp without time zone ENCODE az64,
    tsreminderbudget timestamp without time zone ENCODE az64,
    tsremindercontent timestamp without time zone ENCODE az64,
    tsreminderedition timestamp without time zone ENCODE az64,
    tsreminderexternal timestamp without time zone ENCODE az64,
    tsreminderextraction timestamp without time zone ENCODE az64,
    tsreminderfcp timestamp without time zone ENCODE az64,
    tsreminderforecast timestamp without time zone ENCODE az64,
    tsremindertarget timestamp without time zone ENCODE az64,
    tsscenariomodtime timestamp without time zone ENCODE az64,
    tsstart timestamp without time zone ENCODE az64,
    tsvalidity timestamp without time zone ENCODE az64,
    tswebvalidity timestamp without time zone ENCODE az64,
    spublishingname character varying(80) ENCODE lzo,
    spublishingnamespace character varying(16) ENCODE lzo,
    ipublicationstatus smallint NOT NULL ENCODE az64,
    seventtype character varying(255) ENCODE lzo,
    dtotalmargin double precision NOT NULL ENCODE raw,
    dtotalrealized double precision NOT NULL ENCODE raw,
    icmsaccountid integer NOT NULL ENCODE az64,
    iusetaskcreation smallint NOT NULL ENCODE az64,
    iwebanalyticsaccountid integer NOT NULL ENCODE az64,
    scampaignsourcecode character varying(50) ENCODE lzo,
    streatmentsubsourcecode character varying(50) ENCODE lzo,
    tsmaildrop timestamp without time zone ENCODE az64,
    ixpromoindicator smallint NOT NULL ENCODE az64,
    ihidemessageflag smallint NOT NULL ENCODE az64,
    iistriggeredmessageindicator smallint NOT NULL ENCODE az64,
    scid character varying(50) ENCODE lzo,
    sxpromofrom character varying(25) ENCODE lzo,
    sxpromoto character varying(25) ENCODE lzo,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE AUTO
SORTKEY ( damount );