CREATE TABLE mktg_ops_tbls.adb_nmsrecipient (
    iaddrerrorcount integer NOT NULL ENCODE az64,
    iaddrquality integer NOT NULL ENCODE az64,
    iblacklist smallint NOT NULL ENCODE az64,
    iblacklistemail smallint NOT NULL ENCODE az64,
    iblacklistfax smallint NOT NULL ENCODE az64,
    iblacklistmobile smallint NOT NULL ENCODE az64,
    iblacklistphone smallint NOT NULL ENCODE az64,
    iblacklistpostalmail smallint NOT NULL ENCODE az64,
    iboolean1 smallint NOT NULL ENCODE az64,
    iboolean2 smallint NOT NULL ENCODE az64,
    iboolean3 smallint NOT NULL ENCODE az64,
    iemailformat smallint NOT NULL ENCODE az64,
    ifolderid integer NOT NULL ENCODE az64,
    igender smallint NOT NULL ENCODE az64,
    irecipientid integer NOT NULL ENCODE raw distkey,
    istatus smallint NOT NULL ENCODE az64,
    mdata character varying(4000) ENCODE lzo,
    saccount character varying(30) ENCODE lzo,
    saddress1 character varying(150) ENCODE lzo,
    saddress2 character varying(150) ENCODE lzo,
    saddress3 character varying(150) ENCODE lzo,
    saddress4 character varying(150) ENCODE lzo,
    scity character varying(75) ENCODE lzo,
    scompany character varying(80) ENCODE lzo,
    scountrycode character varying(3) ENCODE lzo,
    semail character varying(128) ENCODE lzo,
    sfax character varying(32) ENCODE lzo,
    sfirstname character varying(100) ENCODE lzo,
    slanguage character varying(32) ENCODE lzo,
    slastname character varying(100) ENCODE lzo,
    smiddlename character varying(30) ENCODE lzo,
    smobilephone character varying(32) ENCODE lzo,
    sorigin character varying(80) ENCODE lzo,
    sphone character varying(32) ENCODE lzo,
    ssalutation character varying(20) ENCODE lzo,
    sstatecode character varying(3) ENCODE lzo,
    stext1 character varying(180) ENCODE lzo,
    stext2 character varying(180) ENCODE lzo,
    stext3 character varying(180) ENCODE lzo,
    stext4 character varying(180) ENCODE lzo,
    stext5 character varying(180) ENCODE lzo,
    szipcode character varying(20) ENCODE lzo,
    tsaddrlastcheck timestamp without time zone ENCODE az64,
    tsbirth timestamp without time zone ENCODE az64,
    tscreated timestamp without time zone ENCODE az64,
    tslastmodified timestamp without time zone ENCODE az64,
    bicnst_mstr_id bigint NOT NULL ENCODE az64,
    birecipientid bigint NOT NULL ENCODE az64,
    dlastdonationamt double precision NOT NULL ENCODE raw,
    iblacklistemail_bio smallint NOT NULL ENCODE az64,
    iblacklistemail_fr smallint NOT NULL ENCODE az64,
    iblacklistemail_phss smallint NOT NULL ENCODE az64,
    iblacklistemail_vms smallint NOT NULL ENCODE az64,
    iblacklistmobile_bio smallint NOT NULL ENCODE az64,
    iblacklistmobile_fr smallint NOT NULL ENCODE az64,
    iblacklistmobile_phss smallint NOT NULL ENCODE az64,
    iblacklistmobile_vms smallint NOT NULL ENCODE az64,
    iblacklistphone_bio smallint NOT NULL ENCODE az64,
    iblacklistphone_fr smallint NOT NULL ENCODE az64,
    iblacklistphone_phss smallint NOT NULL ENCODE az64,
    iblacklistphone_vms smallint NOT NULL ENCODE az64,
    iblacklistpostalmail_bio smallint NOT NULL ENCODE az64,
    iblacklistpostalmail_fr smallint NOT NULL ENCODE az64,
    iblacklistpostalmail_phss smallint NOT NULL ENCODE az64,
    iblacklistpostalmail_vms smallint NOT NULL ENCODE az64,
    iblacklist_bio smallint NOT NULL ENCODE az64,
    iblacklist_fr smallint NOT NULL ENCODE az64,
    iblacklist_phss smallint NOT NULL ENCODE az64,
    iblacklist_vms smallint NOT NULL ENCODE az64,
    ifr_field_unit_dimension_id integer NOT NULL ENCODE az64,
    ifr_mkt_field_unit_dimension_id integer NOT NULL ENCODE az64,
    iisbio smallint NOT NULL ENCODE az64,
    iisfr smallint NOT NULL ENCODE az64,
    iisphss smallint NOT NULL ENCODE az64,
    iisvms smallint NOT NULL ENCODE az64,
    saddress1_bio character varying(150) ENCODE lzo,
    saddress1_fr character varying(150) ENCODE lzo,
    saddress1_phss character varying(150) ENCODE lzo,
    saddress1_vms character varying(150) ENCODE lzo,
    saddress2_bio character varying(150) ENCODE lzo,
    saddress2_fr character varying(150) ENCODE lzo,
    saddress2_phss character varying(150) ENCODE lzo,
    saddress2_vms character varying(150) ENCODE lzo,
    saddress3_bio character varying(150) ENCODE lzo,
    saddress3_fr character varying(150) ENCODE lzo,
    saddress3_phss character varying(150) ENCODE lzo,
    saddress3_vms character varying(150) ENCODE lzo,
    saddress4_bio character varying(150) ENCODE lzo,
    saddress4_fr character varying(150) ENCODE lzo,
    saddress4_phss character varying(150) ENCODE lzo,
    saddress4_vms character varying(150) ENCODE lzo,
    sbioaddrquality character varying(255) ENCODE lzo,
    sbio_em_email character varying(128) ENCODE lzo,
    scity_bio character varying(75) ENCODE lzo,
    scity_fr character varying(75) ENCODE lzo,
    scity_phss character varying(75) ENCODE lzo,
    scity_vms character varying(75) ENCODE lzo,
    scountrycode_bio character varying(3) ENCODE lzo,
    scountrycode_fr character varying(3) ENCODE lzo,
    scountrycode_phss character varying(3) ENCODE lzo,
    scountrycode_vms character varying(3) ENCODE lzo,
    sfraddrquality character varying(255) ENCODE lzo,
    sfr_em_email character varying(128) ENCODE lzo,
    sline6 character varying(80) ENCODE lzo,
    smobilephone_bio character varying(32) ENCODE lzo,
    smobilephone_fr character varying(32) ENCODE lzo,
    smobilephone_phss character varying(32) ENCODE lzo,
    smobilephone_vms character varying(32) ENCODE lzo,
    sofferorigin character varying(100) ENCODE lzo,
    sphone_bio character varying(32) ENCODE lzo,
    sphone_fr character varying(32) ENCODE lzo,
    sphone_phss character varying(32) ENCODE lzo,
    sphone_vms character varying(32) ENCODE lzo,
    sphssaddrquality character varying(255) ENCODE lzo,
    sphss_em_email character varying(128) ENCODE lzo,
    sprofilepicture character varying(1000) ENCODE lzo,
    srolename character varying(100) ENCODE lzo,
    sstatecode_bio character varying(3) ENCODE lzo,
    sstatecode_fr character varying(3) ENCODE lzo,
    sstatecode_phss character varying(3) ENCODE lzo,
    sstatecode_vms character varying(3) ENCODE lzo,
    svmsaddrquality character varying(255) ENCODE lzo,
    svms_em_email character varying(128) ENCODE lzo,
    szipcode_bio character varying(20) ENCODE lzo,
    szipcode_fr character varying(20) ENCODE lzo,
    szipcode_phss character varying(20) ENCODE lzo,
    szipcode_vms character varying(20) ENCODE lzo,
    tslastdonation timestamp without time zone ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64,
    PRIMARY KEY (irecipientid)
)
DISTSTYLE KEY
SORTKEY ( irecipientid );