CREATE TABLE mktg_ops_tbls.adb_vlntr_srvy_rspns (
    snapshot_date timestamp without time zone ENCODE az64,
    history_record_date timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    audience_member_id integer ENCODE az64,
    cnst_mstr_id integer ENCODE az64,
    last_name character varying(255) ENCODE lzo,
    email character varying(255) ENCODE lzo,
    abstract character varying(255) ENCODE lzo,
    a8_my_volun_2_arc_mission character varying(255) ENCODE lzo,
    b8_expect_of_me character varying(255) ENCODE lzo,
    c8_arc_training_prepared_me character varying(255) ENCODE lzo,
    d8_empl_volun_teamwork character varying(255) ENCODE lzo,
    e8_valued_member character varying(255) ENCODE lzo,
    f8_sprvsr_mgr_respect character varying(255) ENCODE lzo,
    g8_shared_vision_coworkers character varying(255) ENCODE lzo,
    h8_diverse_ideas_valued character varying(255) ENCODE lzo,
    i8_cont_as_arc_volun character varying(255) ENCODE lzo,
    employment_status character varying(255) ENCODE lzo,
    highest_education character varying(255) ENCODE lzo,
    l12mo_have_you character varying(2000) ENCODE lzo,
    l12mo_hrs_each_mo_volun character varying(255) ENCODE lzo,
    r_u_hispanic_spanish_latino character varying(255) ENCODE lzo,
    rc_volunteer_experience_commen character varying(255) ENCODE lzo,
    rc_volunteer_experience_overal character varying(255) ENCODE lzo,
    recomdn_arc_2_org_or_volutr character varying(255) ENCODE lzo,
    thoughts_on_experiences character varying(255) ENCODE lzo,
    usefulness_of_volunteer_connec character varying(255) ENCODE lzo,
    usefulness_of_volunteer_connec2 character varying(255) ENCODE lzo,
    usefulness_of_volunteer_connec3 character varying(255) ENCODE lzo,
    volunteer_areas_prev_12_months character varying(2000) ENCODE lzo,
    volunteer_areas_prev_12_month0 character varying(255) ENCODE lzo,
    volunteer_length character varying(255) ENCODE lzo,
    why_score character varying(255) ENCODE lzo,
    tech_experience_computer character varying(255) ENCODE lzo,
    tech_experience_email character varying(255) ENCODE lzo,
    tech_experience_exchange character varying(255) ENCODE lzo,
    tech_experience_edge character varying(255) ENCODE lzo,
    dw_create_ts timestamp without time zone ENCODE az64,
    dw_updt_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character(4) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE ALL;