CREATE TABLE mktg_ops_tbls.aprm_wb_apnd_outbnd_msg_snt (
    snapshot_ts timestamp without time zone NOT NULL ENCODE az64,
    abstract character varying(4000) ENCODE lzo,
    actvty_id integer ENCODE az64,
    audience_mbr_id integer ENCODE az64,
    channel_id integer ENCODE az64,
    data_src_id integer ENCODE az64,
    data_src_key character varying(75) ENCODE lzo,
    delivered_ts timestamp without time zone ENCODE az64,
    delivery_profile character varying(75) ENCODE lzo,
    dmn character varying(255) ENCODE lzo,
    dmn_id integer ENCODE az64,
    email_addr character varying(255) ENCODE lzo,
    email_delivery_method character varying(75) ENCODE lzo,
    email_id integer ENCODE az64,
    form_id integer ENCODE az64,
    form_ttl character varying(75) ENCODE lzo,
    forwarding_email_addr character varying(255) ENCODE lzo,
    from_display_nm character varying(255) ENCODE lzo,
    hist_rec_ts timestamp without time zone ENCODE az64,
    hist_rec_id integer ENCODE az64,
    interaction_id integer ENCODE az64,
    lead_id integer ENCODE az64,
    reply_to_address character varying(255) ENCODE lzo,
    sgmt_id integer ENCODE az64,
    sgmtn_id integer ENCODE az64,
    sent_ts timestamp without time zone ENCODE az64,
    step_id integer ENCODE az64,
    subscriber_key character varying(36) ENCODE lzo,
    forwarded_email integer ENCODE az64,
    srcsys_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_create_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;