CREATE TABLE mktg_ops_tbls.aprm_wb_apnd_mcrst_mtrcs (
    snapshot_ts timestamp without time zone NOT NULL ENCODE az64,
    abstract character varying(4000) ENCODE lzo,
    actvty_id integer ENCODE az64,
    audience_mbr_id integer ENCODE az64,
    data_src_id integer ENCODE az64,
    data_src_key character varying(75) ENCODE lzo,
    email_id integer ENCODE az64,
    hist_rec_ts timestamp without time zone ENCODE az64,
    hist_rec_id integer ENCODE az64,
    hit_ts timestamp without time zone ENCODE az64,
    interaction_id integer ENCODE az64,
    ip_addr character varying(50) ENCODE lzo,
    lead_id integer ENCODE az64,
    metric_id integer ENCODE az64,
    metric_typ character varying(765) ENCODE lzo,
    microsite_id integer ENCODE az64,
    microsite_pg_id integer ENCODE az64,
    outbnd_msg_id integer ENCODE az64,
    refer_dmn character varying(256) ENCODE lzo,
    refer_url character varying(2084) ENCODE lzo,
    sgmt_id integer ENCODE az64,
    sgmtn_id integer ENCODE az64,
    step_id integer ENCODE az64,
    ttl character varying(75) ENCODE lzo,
    srcsys_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_create_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;