CREATE TABLE mktg_ops_tbls.aprm_wb_apnd_bio_dnr_stsfctn_srvy (
    snapshot_ts timestamp without time zone ENCODE az64,
    cnst_mstr_id integer ENCODE az64,
    donat_key integer ENCODE az64,
    age_band_key integer ENCODE az64,
    blood_type_key integer ENCODE az64,
    donat_dt_key integer ENCODE az64,
    donor_key integer ENCODE az64,
    drive_key integer ENCODE az64,
    drive_site_key integer ENCODE az64,
    phleb_key integer ENCODE az64,
    race_key integer ENCODE az64,
    region_key integer ENCODE az64,
    sponsor_key integer ENCODE az64,
    nk_donat_dt date ENCODE az64,
    first_donat_ind smallint DEFAULT 0 ENCODE az64,
    em_cnst_email character varying(100) ENCODE lzo,
    last_nm character varying(50) ENCODE lzo,
    audnc_mbr_id integer ENCODE az64,
    hstry_rcrd_id integer ENCODE az64,
    hstry_rcrd_ts timestamp without time zone ENCODE az64,
    abstract character varying(255) ENCODE lzo,
    cnst_mbl_phn character varying(15) ENCODE lzo,
    donatn_exprnc_ad_rtng character varying(1) ENCODE lzo,
    donatn_in_6mth character varying(10) ENCODE lzo,
    donatn_tm character varying(1) ENCODE lzo,
    hh_mnr_ad_rtng character varying(1) ENCODE lzo,
    ok_arc_2_cntct_flg character varying(10) ENCODE lzo,
    ok_arc_2_txt_flg character varying(10) ENCODE lzo,
    phleb_crts_ad_rtng character varying(1) ENCODE lzo,
    phleb_skl_ad_rtng character varying(1) ENCODE lzo,
    rcmnd_frnd_dntng_bld character varying(2) ENCODE lzo,
    thanked_for_donation character varying(10) ENCODE lzo,
    prmptd_comnictn_chan character varying(50) ENCODE lzo,
    interest_lvl character varying(2) ENCODE lzo
)
DISTSTYLE ALL;