CREATE TABLE mktg_ops_tbls.aprm_wb_apnd_rmv_frm_lst (
    snapshot_ts timestamp without time zone NOT NULL ENCODE az64,
    abstract character varying(4000) ENCODE lzo,
    actvty_id integer ENCODE az64,
    actvty_ttl character varying(75) ENCODE lzo,
    audience_mbr_id integer ENCODE az64,
    channel_id integer ENCODE az64,
    data_src_id integer ENCODE az64,
    data_src_key character varying(75) ENCODE lzo,
    email_id integer ENCODE az64,
    hist_rec_ts timestamp without time zone ENCODE az64,
    hist_rec_id integer ENCODE az64,
    interaction_id integer ENCODE az64,
    opt_out_form_id integer ENCODE az64,
    opt_out_form_ttl character varying(75) ENCODE lzo,
    opt_out_rsn character varying(100) ENCODE lzo,
    opt_out_typ character varying(75) ENCODE lzo,
    subscriber_key character varying(36) ENCODE lzo,
    typ_id character varying(765) ENCODE lzo,
    srcsys_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;