CREATE TABLE mktg_ops_tbls.aprm_email_sent (
    cnst_mstr_id bigint NOT NULL ENCODE az64,
    hist_rec_id integer ENCODE az64,
    hist_rec_ts timestamp without time zone ENCODE az64,
    eml_gen_run_id integer ENCODE az64,
    outbnd_id integer ENCODE az64,
    outbnd_ttl character varying(150) ENCODE lzo,
    sent_ts timestamp without time zone ENCODE az64,
    dlvrd_ts timestamp without time zone ENCODE az64,
    actvty_id integer ENCODE az64,
    actvty_ttl character varying(75) ENCODE lzo,
    sgmtn_id integer ENCODE az64,
    sgmtn_title character varying(75) ENCODE lzo,
    sgmt_id integer ENCODE az64,
    sgmt_title character varying(75) ENCODE lzo,
    from_display_nm character varying(255) ENCODE lzo,
    from_email character varying(255) ENCODE lzo,
    reply_to_email character varying(255) ENCODE lzo,
    to_email character varying(255) ENCODE lzo,
    to_display_nm character varying(255) ENCODE lzo,
    to_domain character varying(175) ENCODE lzo,
    is_forwarded integer ENCODE az64,
    forwarding_email character varying(255) ENCODE lzo,
    abstract character varying(500) ENCODE lzo,
    email_id integer NOT NULL ENCODE az64,
    contxt_cd character(1) ENCODE lzo,
    srcsys_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_create_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64,
    UNIQUE (cnst_mstr_id, hist_rec_id, email_id, contxt_cd)
)
DISTSTYLE ALL;