CREATE TABLE mktg_ops_tbls.aprm_wb_apnd_segmntn (
    snapshot_ts timestamp without time zone NOT NULL ENCODE az64,
    actvty character varying(75) ENCODE lzo,
    cell_dfntn character varying(765) ENCODE lzo,
    connection_grp character varying(75) ENCODE lzo,
    context_id integer ENCODE az64,
    cnt_num_hist character varying(765) ENCODE lzo,
    cnt_num_job_id integer ENCODE az64,
    dsc character varying(2000) ENCODE lzo,
    last_cnt_num_ts timestamp without time zone ENCODE az64,
    last_mod_by character varying(765) ENCODE lzo,
    last_mod_ts timestamp without time zone ENCODE az64,
    last_run_ts timestamp without time zone ENCODE az64,
    quick_cnt_num_attr character varying(75) ENCODE lzo,
    sgmtn_id integer ENCODE az64,
    started_by_user_id integer ENCODE az64,
    ttl character varying(75) ENCODE lzo,
    universe character varying(75) ENCODE lzo,
    vldtn_rqrmt character varying(765) ENCODE lzo,
    cnt_num integer ENCODE az64,
    last_cnt_num_lngth numeric(28,12) ENCODE az64,
    last_run_lngth numeric(28,12) ENCODE az64,
    run_sgmt integer ENCODE az64,
    stopping integer ENCODE az64,
    zoom_factor integer ENCODE az64,
    srcsys_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;