CREATE TABLE mktg_ops_tbls.aprm_wb_apnd_cm_segmnt (
    snapshot_ts timestamp without time zone NOT NULL ENCODE az64,
    context_id integer ENCODE az64,
    dsc character varying(255) ENCODE lzo,
    last_mod_by character varying(765) ENCODE lzo,
    last_mod_ts timestamp without time zone ENCODE az64,
    parent_sgmt character varying(75) ENCODE lzo,
    persist_opt character varying(765) ENCODE lzo,
    persistent character varying(765) ENCODE lzo,
    regenerate_tbl character varying(765) ENCODE lzo,
    sgmt_lst_cnt_num_ts timestamp without time zone ENCODE az64,
    sgmt_lst_run_ts timestamp without time zone ENCODE az64,
    sgmt_typ character varying(765) ENCODE lzo,
    sgmtn_id integer ENCODE az64,
    count_num integer ENCODE az64,
    err integer ENCODE az64,
    last_cnt_num_lngth integer ENCODE az64,
    last_run_lngth integer ENCODE az64,
    mbr_cnt_num integer ENCODE az64,
    pstn_left integer ENCODE az64,
    pstn_top integer ENCODE az64,
    id integer ENCODE az64,
    sgmt_ttl character varying(75) ENCODE lzo,
    srcsys_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_create_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;