CREATE TABLE mktg_ops_tbls.arc_cdi_smry_extrct (
    hh_la_id character varying(50) ENCODE lzo,
    age_oldest_adlt_hh integer ENCODE az64,
    age_youngest_adlt_hh integer ENCODE az64,
    male_presnce_ind smallint ENCODE az64,
    female_presnce_ind smallint ENCODE az64,
    first_email_ld_dt date ENCODE az64,
    first_email_ld_src character varying(10) ENCODE lzo,
    recent_email_ld_dt date ENCODE az64,
    recent_email_ld_src character varying(10) ENCODE lzo,
    email_fr_src_cnt integer ENCODE az64,
    email_total_cnt integer ENCODE az64,
    recent_email_optout_dt date ENCODE az64,
    first_email_optout_dt date ENCODE az64,
    total_email_optout_cnt integer ENCODE az64,
    first_addr_ld_dt date ENCODE az64,
    first_addr_ld_src character varying(10) ENCODE lzo,
    recent_addr_ld_dt date ENCODE az64,
    recent_addr_ld_src character varying(10) ENCODE lzo,
    addr_fr_src_cnt integer ENCODE az64,
    addr_total_cnt integer ENCODE az64,
    recent_addr_optout_dt date ENCODE az64,
    first_addr_optout_dt date ENCODE az64,
    total_addr_optout_cnt integer ENCODE az64,
    first_phn_ld_dt date ENCODE az64,
    first_phn_ld_src character varying(10) ENCODE lzo,
    recent_phn_ld_dt date ENCODE az64,
    recent_phn_ld_src character varying(10) ENCODE lzo,
    phn_fr_src_cnt integer ENCODE az64,
    phn_total_cnt integer ENCODE az64,
    recent_phn_optout_dt date ENCODE az64,
    first_phn_optout_dt date ENCODE az64,
    total_phn_optout_cnt integer ENCODE az64
)
DISTSTYLE ALL;