CREATE TABLE mktg_ops_tbls.arc_phss_smry_bkp (
    cnst_mstr_id bigint NOT NULL ENCODE az64,
    cnst_hsld_id character varying(18) ENCODE lzo,
    length_of_engagmnt integer ENCODE az64,
    yr_takn_crs integer ENCODE az64,
    fst_crs_cmptn_dt date ENCODE az64,
    last_rgstn_mthd character varying(20) ENCODE lzo,
    last_crs_cmptn_dt date ENCODE az64,
    last_crs_cmptn character varying(100) ENCODE lzo,
    last_crs_subject_area character varying(100) ENCODE lzo,
    last_crs_delivery_typ character varying(50) ENCODE lzo,
    nxt_rc_crs_delivery_typ character varying(50) ENCODE lzo,
    lftm_crs_complt_cnt integer ENCODE az64,
    lftm_pro_cpr_crs_complt_cnt integer ENCODE az64,
    lftm_lay_cpr_crs_complt_cnt integer ENCODE az64,
    lftm_aqtcs_crs_complt_cnt integer ENCODE az64,
    lftm_caregvng_crs_complt_cnt integer ENCODE az64,
    lftm_nrse_trn_crs_complt_cnt integer ENCODE az64,
    lftm_othr_crs_complt_cnt integer ENCODE az64,
    lftm_crs_spnd_amt numeric(18,2) ENCODE az64,
    lftm_coupon_svngs_amt numeric(18,2) ENCODE az64,
    lftm_avg_cst_per_crs_amt numeric(18,2) ENCODE az64,
    lftm_w_b_cmplt_pct numeric(18,2) ENCODE az64,
    lftm_clrm_cmplt_pct numeric(18,2) ENCODE az64,
    lftm_clrm_cmplt_arc_cnt numeric(18,2) ENCODE az64,
    lftm_clrm_cmplt_wp_cnt numeric(18,2) ENCODE az64,
    lftm_clrm_cmplt_ot_cnt numeric(18,2) ENCODE az64,
    lftm_bl_wc_cmplt_pct numeric(18,2) ENCODE az64,
    lftm_othr_cmplt_pct numeric(18,2) ENCODE az64,
    lftm_ap_crs_cmplt_pct numeric(18,2) ENCODE az64,
    lftm_fs_crs_cmplt_pct numeric(18,2) ENCODE az64,
    lftm_cmnty_crs_cmplt_pct numeric(18,2) ENCODE az64,
    lftm_othr_crs_cmplt_pct numeric(18,2) ENCODE az64,
    lftm_stndt_drp_class_rt integer ENCODE az64,
    lftm_arc_cancld_class_rt integer ENCODE az64,
    lftm_stndt_fail_class_cnt integer ENCODE az64,
    last_pro_cpr_crs_dt date ENCODE az64,
    last_pro_cpr_recert_dt date ENCODE az64,
    fst_pro_cpr_crs_dt date ENCODE az64,
    last_pro_cpr_tot_spnd_amt numeric(18,2) ENCODE az64,
    last_lay_cpr_crs_dt date ENCODE az64,
    last_lay_cpr_recert_dt date ENCODE az64,
    fst_lay_cpr_crs_dt date ENCODE az64,
    last_lay_cpr_tot_spnd_amt numeric(18,2) ENCODE az64,
    last_aqtcs_crs_dt date ENCODE az64,
    last_aqtcs_recert_dt date ENCODE az64,
    fst_aqtcs_crs_dt date ENCODE az64,
    last_aqtcs_tot_spnd_amt numeric(18,2) ENCODE az64,
    last_caregiving_crs_dt date ENCODE az64,
    last_caregiving_recert_dt date ENCODE az64,
    fst_caregiving_crs_dt date ENCODE az64,
    last_caregiving_tot_spnd_amt numeric(18,2) ENCODE az64,
    last_nrse_trn_crs_dt date ENCODE az64,
    last_nrse_trn_recert_dt date ENCODE az64,
    fst_nrse_trn_crs_dt date ENCODE az64,
    last_nrse_trn_tot_spnd_amt numeric(18,2) ENCODE az64,
    last_othr_crs_dt date ENCODE az64,
    last_othr_recert_dt date ENCODE az64,
    fst_othr_crs_dt date ENCODE az64,
    last_othr_tot_spnd_amt numeric(18,2) ENCODE az64,
    tot_cmpnts_cmplt_cnt integer ENCODE az64,
    tot_cmpnt_cmplt_1yrcert_cnt integer ENCODE az64,
    tot_cmpnt_cmplt_2yrcert_cnt integer ENCODE az64,
    tot_cmpnt_cmplt_3yrcert_cnt integer ENCODE az64,
    tot_cmpnts_passed_cnt integer ENCODE az64,
    tot_cmpnts_fld_cnt integer ENCODE az64,
    tot_cmpnts_nt_evltd_cnt integer ENCODE az64,
    tot_cmpnts_nt_pending_cnt integer ENCODE az64,
    prf_mthd_cntct character varying(50) ENCODE lzo,
    upcmng_recert_1_dt date ENCODE az64,
    upcmng_recert_1_crs_nm character varying(1020) ENCODE lzo,
    upcmng_recert_2_dt date ENCODE az64,
    upcmng_recert_2_crs_nm character varying(1020) ENCODE lzo,
    upcmng_recert_3_dt date ENCODE az64,
    upcmng_recert_3_crs_nm character varying(1020) ENCODE lzo,
    upcmng_refresh_1_typ character varying(20) ENCODE lzo,
    upcmng_refresh_1_crs_nm character varying(1020) ENCODE lzo,
    upcmng_refresh_2_typ character varying(20) ENCODE lzo,
    upcmng_refresh_2_crs_nm character varying(1020) ENCODE lzo,
    upcmng_refresh_3_typ character varying(20) ENCODE lzo,
    upcmng_refresh_3_crs_nm character varying(1020) ENCODE lzo,
    lst_cancltn_dt date ENCODE az64,
    lst_cancltn_class_nm character varying(1020) ENCODE lzo,
    course_taker_ind smallint ENCODE az64,
    rcs_buyer_ind smallint ENCODE az64,
    first_dmw_store_dt date ENCODE az64,
    last_dmw_store_dt date ENCODE az64,
    first_dmw_course_dt date ENCODE az64,
    last_dmw_course_dt date ENCODE az64,
    instr_cnt integer ENCODE az64,
    bst_cnt integer ENCODE az64,
    nat_cnt integer ENCODE az64,
    spanish_cnt integer ENCODE az64,
    course_cnt integer ENCODE az64,
    unique_student_cnt integer ENCODE az64,
    student_match_cnt integer ENCODE az64,
    instr_flg character varying(3) ENCODE lzo,
    bst_only_flg character varying(3) ENCODE lzo,
    nat_only_flg character varying(3) ENCODE lzo,
    spanish_only_flg character varying(3) ENCODE lzo,
    student_only_flg character varying(3) ENCODE lzo,
    student_bill_prsn_flg character varying(3) ENCODE lzo,
    last_engmnt_dt date ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;