CREATE TABLE mktg_ops_tbls.arc_biomed_txn_bkp (
    cnst_mstr_id bigint ENCODE az64,
    donat_key bigint ENCODE az64,
    nk_donat_num character varying(18) ENCODE lzo,
    nk_donat_dt date ENCODE az64,
    apptmt_dt date ENCODE az64,
    nk_supplier character varying(4) ENCODE lzo,
    age_band_key integer ENCODE az64,
    bag_type_key integer ENCODE az64,
    bdr_rev_dt_key integer DEFAULT 0 ENCODE az64,
    blood_type_key integer ENCODE az64,
    donat_dt_key integer ENCODE az64,
    donor_key integer ENCODE az64,
    drive_key integer ENCODE az64,
    drive_site_key integer ENCODE az64,
    hold_reason_key integer ENCODE az64,
    patient_key integer ENCODE az64,
    phleb_key integer ENCODE az64,
    phleb_status_key integer ENCODE az64,
    race_key integer ENCODE az64,
    region_key integer ENCODE az64,
    site_key integer ENCODE az64,
    sponsor_key integer ENCODE az64,
    supplier_key integer ENCODE az64,
    nk_key_donor character varying(7) ENCODE lzo,
    nk_legacy_donor_id character varying(20) ENCODE lzo,
    nk_drive_id character varying(9) ENCODE lzo,
    nk_ep_drive_id character varying(4) ENCODE lzo,
    nk_drive_site_id character varying(9) ENCODE lzo,
    nk_sponsor_id character varying(9) ENCODE lzo,
    nk_region_id character varying(5) ENCODE lzo,
    nk_site_cd character varying(4) ENCODE lzo,
    nk_ep_abo_id character varying(25) ENCODE lzo,
    nk_prod_cd character varying(5) ENCODE lzo,
    nk_bdr_rev_dt date ENCODE az64,
    nk_bdr_rev_stat character varying(100) ENCODE lzo,
    donat_status_cd character varying(1) ENCODE lzo,
    donat_status_dsc character varying(30) ENCODE lzo,
    regis_ts timestamp without time zone ENCODE az64,
    phleb_start_ts timestamp without time zone ENCODE az64,
    phleb_stop_ts timestamp without time zone ENCODE az64,
    phleb_duration_sec integer ENCODE az64,
    phleb_duration_tm character varying(8) ENCODE lzo,
    draw_to_vol_qty integer ENCODE az64,
    drawn_vol_qty integer ENCODE az64,
    drawn_sample_vol_qty integer ENCODE az64,
    drawn_rbc_vol_qty integer ENCODE az64,
    drawn_plasma_vol_qty integer ENCODE az64,
    anticoag_vol_qty integer ENCODE az64,
    adverse_donor_rxn character varying(100) ENCODE lzo,
    adv_donor_rxn_ind smallint DEFAULT 0 ENCODE az64,
    cmv_status character varying(30) ENCODE lzo,
    platelet_cnt integer ENCODE az64,
    height integer ENCODE az64,
    dbl_rbc_ind smallint DEFAULT 0 ENCODE az64,
    weight integer ENCODE az64,
    blood_pressure character varying(7) ENCODE lzo,
    pulse integer ENCODE az64,
    temp numeric(11,2) ENCODE az64,
    hemoglobin numeric(11,2) ENCODE az64,
    questionnaire_typ character varying(1) ENCODE lzo,
    lot_num character varying(20) ENCODE lzo,
    anticoag_dsc character varying(15) ENCODE lzo,
    laptop_num character varying(3) ENCODE lzo,
    phleb_ind smallint DEFAULT 1 ENCODE az64,
    med_screen_ind smallint DEFAULT 0 ENCODE az64,
    prodctv_proc_ind smallint DEFAULT 0 ENCODE az64,
    prodctv_invalid_proc_ind smallint DEFAULT 0 ENCODE az64,
    prodctv_unit_wb_cnt integer ENCODE az64,
    prodctv_unit_pltpheresis_cnt integer ENCODE az64,
    prodctv_unit_red_cell_cnt integer ENCODE az64,
    prodctv_unit_plspheresis_cnt integer ENCODE az64,
    prodctv_unit_dbl_red_cell_cnt integer ENCODE az64,
    first_donat_ind smallint DEFAULT 0 ENCODE az64,
    deferral_ind smallint DEFAULT 0 ENCODE az64,
    dbl_vp_ind smallint DEFAULT 0 ENCODE az64,
    discont_ind smallint DEFAULT 0 ENCODE az64,
    finalization_ind smallint DEFAULT 1 ENCODE az64,
    appt_ind smallint DEFAULT 0 ENCODE az64,
    walk_in_ind smallint ENCODE az64,
    apptmt_show_ind smallint ENCODE az64,
    donation_ind smallint ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL DEFAULT 0 ENCODE az64
)
DISTSTYLE ALL;