CREATE TABLE mktg_ops_tbls.arc_crm_ent_prfl (
    cnst_mstr_id bigint NOT NULL ENCODE az64,
    cnst_hsld_id character(18) NOT NULL ENCODE lzo,
    prim_org_nm character varying(100) ENCODE lzo,
    cnst_addr_st_cd character varying(10) ENCODE lzo,
    cnst_addr_zip_cd character varying(10) ENCODE lzo,
    cnst_addr_zip_4_cd character varying(10) ENCODE lzo,
    cnst_incm_amt numeric(13,2) ENCODE az64,
    cnst_dscrtnry_spndg_amt numeric(13,2) ENCODE az64,
    cnst_dscrtnry_spndg_index character varying(20) ENCODE lzo,
    cnst_ethn_nm character varying(100) ENCODE lzo,
    cnst_edctnl_bkgrnd_nm character varying(100) ENCODE lzo,
    cnst_lfstg_nm character varying(100) ENCODE lzo,
    cnst_pltcl_prty_nm character varying(100) ENCODE lzo,
    cnst_rlgn_nm character varying(100) ENCODE lzo,
    cnst_thrd_prty_segmtn_group_nm character varying(100) ENCODE lzo,
    fr_extng_dnr_ind smallint ENCODE az64,
    fr_cur_rcrng_dnr_ind smallint ENCODE az64,
    cur_tifny_crcle_ind smallint ENCODE az64,
    cur_hmntrn_crcle_ind smallint ENCODE az64,
    arc_ldrshp_scty_ind smallint ENCODE az64,
    presdnts_cncl_ind smallint ENCODE az64,
    chrmn_cncl_ind smallint ENCODE az64,
    fr_mjr_dnr_ind smallint ENCODE az64,
    plnd_gvng_ind smallint ENCODE az64,
    yng_hmntrn_ind smallint ENCODE az64,
    fr_lftm_dntn_cnt integer ENCODE az64,
    fr_cfy_dntn_cnt integer ENCODE az64,
    fr_last_dntn_dt date ENCODE az64,
    fr_fst_dntn_dt date ENCODE az64,
    fr_lftm_dntn_amt numeric(13,2) ENCODE az64,
    fr_cfy_dntn_amt numeric(13,2) ENCODE az64,
    fr_lftm_avg_dntn_amt numeric(13,2) ENCODE az64,
    fr_cfy_avg_dntn_amt numeric(13,2) ENCODE az64,
    fr_max_one_tm_dntn_amt numeric(13,2) ENCODE az64,
    fr_cfy_max_sgl_dntn_amt numeric(13,2) ENCODE az64,
    fr_cfy_prefd_dnr_chan_nm character varying(100) ENCODE lzo,
    fr_cfym1_prefd_dnr_chan_nm character varying(100) ENCODE lzo,
    extng_lrnr_ind smallint ENCODE az64,
    cur_rcrng_lrnr_ind smallint ENCODE az64,
    fa_cpr_pro_ind smallint ENCODE az64,
    fa_cpr_lymn_ind smallint ENCODE az64,
    aqua_ind smallint ENCODE az64,
    swmng_ind smallint ENCODE az64,
    bldbrn_pthgns_ind smallint ENCODE az64,
    bbysit_ind smallint ENCODE az64,
    instrctr_ind smallint ENCODE az64,
    lftm_crse_cnt integer ENCODE az64,
    cfym1_crse_cnt integer ENCODE az64,
    last_crse_nm character varying(100) ENCODE lzo,
    last_crse_dt date ENCODE az64,
    last_crse_exp_dt date ENCODE az64,
    fst_crse_dt date ENCODE az64,
    lftm_crse_amt numeric(13,2) ENCODE az64,
    cfym1_crse_amt numeric(13,2) ENCODE az64,
    lftm_avg_crse_amt numeric(13,2) ENCODE az64,
    cfym1_avg_crse_amt numeric(13,2) ENCODE az64,
    lftm_prefd_crse_typ_dsc character varying(100) ENCODE lzo,
    cfym1_prefd_crse_typ_dsc character varying(100) ENCODE lzo,
    lftm_prefd_crse_regis_chan_nm character varying(100) ENCODE lzo,
    cfym1_prefd_crse_regis_chan_nm character varying(100) ENCODE lzo,
    bl_dnr_ind smallint ENCODE az64,
    rcrng_bl_dnr_ind smallint ENCODE az64,
    bl_typ character varying(100) ENCODE lzo,
    last_red_bl_cell_dntn_dt date ENCODE az64,
    last_pltlt_dntn_dt date ENCODE az64,
    lftm_bl_dntn_cnt integer ENCODE az64,
    cfym1_bl_dntn_cnt integer ENCODE az64,
    last_bl_dntn_dt date ENCODE az64,
    next_bl_dntn_elgblty_dt date ENCODE az64,
    fst_bl_dntn_dt date ENCODE az64,
    lftm_prfd_bl_dntn_rgs_chan_nm character varying(100) ENCODE lzo,
    cfym1_prfd_bl_dntn_rgs_chan_nm character varying(100) ENCODE lzo,
    volntr_ind smallint ENCODE az64,
    rcrng_volntr_ind smallint ENCODE az64,
    lftm_volntr_cnt integer ENCODE az64,
    cfym1_volntr_cnt integer ENCODE az64,
    last_volntr_dt date ENCODE az64,
    next_volntr_elgblty_dt date ENCODE az64,
    fst_volntr_dt date ENCODE az64,
    lftm_prefd_volntr_typ_dsc character varying(100) ENCODE lzo,
    cfym1_prefd_volntr_typ_dsc character varying(100) ENCODE lzo,
    arc_oln_regis_ind smallint ENCODE az64,
    last_arc_oln_str_prchs_dt date ENCODE az64,
    last_arc_oln_dntn_dt date ENCODE az64,
    arc_oln_acct_prfl_cmpltd_ind smallint ENCODE az64,
    avg_arc_oln_wbst_tm character varying(64) ENCODE lzo,
    cnst_thrd_prty_segmtn_clstr_nm character varying(100) ENCODE lzo,
    arc_unit_key numeric(9,0) ENCODE az64,
    fundrsng_unit_key numeric(9,0) ENCODE az64,
    phss_unit_key numeric(9,0) ENCODE az64,
    biocml_unit_key numeric(9,0) ENCODE az64
)
DISTSTYLE ALL;