CREATE TABLE mktg_ops_tbls.arc_fr_txn_tst (
    trans_id bigint NOT NULL ENCODE az64,
    cnst_fsa_key bigint NOT NULL ENCODE az64,
    affl_prfl_acct_fsa_key bigint ENCODE az64,
    cnst_mstr_id bigint NOT NULL ENCODE az64,
    inflncng_cnst_mstr_id bigint NOT NULL ENCODE az64,
    hh_la_id character varying(30) ENCODE lzo,
    trans_srcsys_cd character varying(10) NOT NULL ENCODE lzo,
    cnst_data_src_cd character varying(10) NOT NULL ENCODE lzo,
    cnst_hsld_id character varying(18) ENCODE lzo,
    trans_srcsys_nm character varying(100) ENCODE lzo,
    trans_chpt_affl character varying(150) ENCODE lzo,
    ta_acct_id integer ENCODE az64,
    cnvo_cnst_id character varying(20) ENCODE lzo,
    aprimo_cnst_id character varying(20) ENCODE lzo,
    bzd_unique_trans_id character varying(50) ENCODE lzo,
    alt_trans_id character varying(40) ENCODE lzo,
    fr_trans_cnst_prsn_prfx character varying(100) ENCODE lzo,
    fr_trans_cnst_prsn_f_nm character varying(100) ENCODE lzo,
    fr_trans_cnst_prsn_m_nm character varying(100) ENCODE lzo,
    fr_trans_cnst_prsn_l_nm character varying(100) ENCODE lzo,
    fr_trans_cnst_prsn_sfx_n character varying(100) ENCODE lzo,
    fr_trans_cnst_line_1_add character varying(255) ENCODE lzo,
    fr_trans_cnst_line_2_add character varying(255) ENCODE lzo,
    fr_trans_cnst_city_nm character varying(100) ENCODE lzo,
    fr_trans_cnst_st_cd character varying(10) ENCODE lzo,
    fr_trans_cnst_zip_cd character varying(20) ENCODE lzo,
    fr_trans_cnst_zip_4_cd character varying(20) ENCODE lzo,
    fr_trans_cnst_hm_phn character varying(40) ENCODE lzo,
    fr_trans_cnst_buss_phn character varying(40) ENCODE lzo,
    fr_trans_cnst_mbl_phn character varying(40) ENCODE lzo,
    fr_trans_cnst_email_addr character varying(255) ENCODE lzo,
    fr_cnst_intl_sustnr_enrl date ENCODE az64,
    fr_pmt_amt numeric(13,2) ENCODE az64,
    pmt_typ_key bigint ENCODE az64,
    fr_dntn_src_chan_nm character varying(100) ENCODE lzo,
    channel_typ_key bigint ENCODE az64,
    comnictn_src_cd character varying(40) ENCODE lzo,
    comnictn_src_dsc character varying(100) ENCODE lzo,
    fr_affl_unit_key integer ENCODE az64,
    fr_affl_cd character varying(10) ENCODE lzo,
    fr_distr_dntn_ind smallint ENCODE az64,
    fr_impctd_area_dntn_ind smallint ENCODE az64,
    fr_hldy_dntn_ind smallint ENCODE az64,
    fr_yr_end_dntn_ind smallint ENCODE az64,
    fr_memorial_dntn_cd character(1) ENCODE lzo,
    fr_memorial_dntn_dsc character varying(150) ENCODE lzo,
    giftran_typ_dsc character varying(150) ENCODE lzo,
    trans_fund_cd character varying(40) ENCODE lzo,
    trans_fund_dsc character varying(150) ENCODE lzo,
    deposit_dt date ENCODE az64,
    deposit_dt_key integer ENCODE az64,
    orig_deposit_dt date ENCODE az64,
    orig_deposit_dt_key integer ENCODE az64,
    dntn_gift_dt date ENCODE az64,
    dntn_gift_dt_key integer ENCODE az64,
    tm_aprch_insert_dt date ENCODE az64,
    fr_pckge_cd character varying(100) ENCODE lzo,
    fr_pmt_plan_dsc character varying(100) ENCODE lzo,
    fr_trans_insert_nm character varying(100) ENCODE lzo,
    fr_trans_order_num character varying(150) ENCODE lzo,
    fr_merchant_id integer ENCODE az64,
    fr_sub_src_cd character varying(50) ENCODE lzo,
    fcc_key bigint ENCODE az64,
    cnst_typ_cd character(2) ENCODE lzo,
    nk_ta_nm_id integer ENCODE az64,
    cnst_org_nm character varying(150) ENCODE lzo,
    recurring_ind integer ENCODE az64,
    recurng_start_dt timestamp without time zone ENCODE az64,
    aprm_subsrc_cd character varying(50) ENCODE lzo,
    aprm_src_cd character varying(40) ENCODE lzo,
    soft_credit_ind smallint ENCODE az64,
    split_gift_ind smallint ENCODE az64,
    note_txt character varying(256) ENCODE lzo,
    email_segmnt_key integer ENCODE az64,
    online_channel_key integer ENCODE az64,
    online_channel_cd character varying(40) ENCODE lzo,
    txn_channel character varying(255) ENCODE lzo,
    gl_debit_acct_key bigint ENCODE az64,
    gl_credit_acct_key bigint ENCODE az64,
    mktg_list_key bigint ENCODE az64,
    fmd_txn_ind smallint ENCODE az64,
    rco_dntn_id character varying(765) ENCODE lzo,
    rco_subscription_id character varying(765) ENCODE lzo,
    subscription_id character varying(765) ENCODE lzo,
    gift_id character varying(20) ENCODE lzo,
    gift_grp_id character varying(20) ENCODE lzo,
    bzl_gift_mult_ask_lnk_ind smallint DEFAULT 0 ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64,
    UNIQUE (trans_id)
)
DISTSTYLE ALL;