CREATE TABLE mktg_ops_tbls.arc_biomed_txn (
    cnst_mstr_id bigint ENCODE az64,
    donat_key bigint ENCODE az64,
    nk_donat_num bigint ENCODE az64,
    nk_donat_dt date ENCODE az64 distkey,
    apptmt_dt date ENCODE az64,
    nk_supplier character varying(36) ENCODE bytedict,
    age_band_key double precision ENCODE raw,
    bag_type_key character varying(10) ENCODE bytedict,
    bdr_rev_dt_key character varying(1) ENCODE lzo,
    blood_type_key integer ENCODE az64,
    donat_dt_key date ENCODE az64,
    donor_key bigint ENCODE az64,
    drive_key character varying(50) ENCODE lzo,
    drive_site_key character varying(256) ENCODE lzo,
    hold_reason_key character varying(5000) ENCODE lzo,
    patient_key character varying(1) ENCODE lzo,
    phleb_key integer ENCODE az64,
    phleb_status_key integer ENCODE az64,
    race_key integer ENCODE az64,
    region_key integer ENCODE az64,
    site_key character varying(1) ENCODE lzo,
    sponsor_key bigint ENCODE az64,
    supplier_key character varying(1) ENCODE lzo,
    nk_key_donor bigint ENCODE az64,
    nk_legacy_donor_id character varying(255) ENCODE lzo,
    nk_drive_id bigint ENCODE az64,
    nk_ep_drive_id character varying(9) ENCODE lzo,
    nk_drive_site_id bigint ENCODE az64,
    nk_sponsor_id character varying(500) ENCODE lzo,
    nk_region_id integer ENCODE az64,
    nk_site_cd character varying(100) ENCODE lzo,
    nk_ep_abo_id character varying(150) ENCODE bytedict,
    nk_prod_cd character varying(20) ENCODE lzo,
    nk_bdr_rev_dt character varying(1) ENCODE lzo,
    nk_bdr_rev_stat character varying(1) ENCODE lzo,
    donat_status_cd character varying(36) ENCODE lzo,
    donat_status_dsc character varying(1) ENCODE lzo,
    regis_ts timestamp without time zone ENCODE az64,
    phleb_start_ts character varying(1) ENCODE lzo,
    phleb_stop_ts character varying(1) ENCODE lzo,
    phleb_duration_sec character varying(1) ENCODE lzo,
    phleb_duration_tm character varying(1) ENCODE lzo,
    draw_to_vol_qty character varying(1) ENCODE lzo,
    drawn_vol_qty integer ENCODE az64,
    drawn_sample_vol_qty character varying(1) ENCODE lzo,
    drawn_rbc_vol_qty integer ENCODE az64,
    drawn_plasma_vol_qty integer ENCODE az64,
    anticoag_vol_qty character varying(10) ENCODE lzo,
    adverse_donor_rxn character varying(1) ENCODE lzo,
    adv_donor_rxn_ind integer ENCODE az64,
    cmv_status smallint ENCODE az64,
    platelet_cnt character varying(1) ENCODE lzo,
    height integer ENCODE az64,
    dbl_rbc_ind character varying(1) ENCODE lzo,
    weight integer ENCODE az64,
    blood_pressure character varying(511) ENCODE lzo,
    pulse character varying(255) ENCODE lzo,
    temp character varying(255) ENCODE lzo,
    hemoglobin character varying(255) ENCODE lzo,
    questionnaire_typ character varying(1) ENCODE lzo,
    lot_num character varying(50) ENCODE lzo,
    anticoag_dsc character varying(30) ENCODE lzo,
    laptop_num character varying(3) ENCODE lzo,
    phleb_ind integer ENCODE az64,
    med_screen_ind character varying(1) ENCODE lzo,
    prodctv_proc_ind integer ENCODE az64,
    prodctv_invalid_proc_ind character varying(1) ENCODE lzo,
    prodctv_unit_wb_cnt integer ENCODE az64,
    prodctv_unit_pltpheresis_cnt integer ENCODE az64,
    prodctv_unit_red_cell_cnt integer ENCODE az64,
    prodctv_unit_plspheresis_cnt integer ENCODE az64,
    prodctv_unit_dbl_red_cell_cnt integer ENCODE az64,
    first_donat_ind integer ENCODE az64,
    deferral_ind integer ENCODE az64,
    dbl_vp_ind integer ENCODE az64,
    discont_ind integer ENCODE az64,
    finalization_ind character varying(1) ENCODE lzo,
    appt_ind integer ENCODE az64,
    walk_in_ind integer ENCODE az64,
    apptmt_show_ind integer ENCODE az64,
    donation_ind integer ENCODE az64,
    dw_trans_ts timestamp with time zone ENCODE az64,
    appl_src_cd character varying(4) ENCODE lzo,
    load_id integer ENCODE az64,
    audit_key character varying(1) ENCODE lzo,
    srcsys_ts character varying(1) ENCODE lzo,
    row_stat_cd character varying(1) ENCODE lzo
)
DISTSTYLE KEY;