CREATE TABLE mktg_ops_tbls.arc_fr_txn_extrct (
    trans_id bigint ENCODE az64,
    cnst_mstr_id bigint ENCODE az64,
    hh_la_id character varying(30) ENCODE lzo,
    trans_chpt_affl character varying(150) ENCODE lzo,
    ta_acct_id integer ENCODE az64,
    fr_cnst_intl_sustnr_enrl date ENCODE az64,
    channel_typ_key bigint ENCODE az64,
    comnictn_src_cd character varying(40) ENCODE lzo,
    comnictn_src_dsc character varying(100) ENCODE lzo,
    fr_affl_cd character varying(10) ENCODE lzo,
    fr_distr_dntn_ind integer ENCODE az64,
    fr_impctd_area_dntn_ind integer ENCODE az64,
    fr_hldy_dntn_ind integer ENCODE az64,
    fr_yr_end_dntn_ind integer ENCODE az64,
    fr_memorial_dntn_cd character varying(1) ENCODE lzo,
    fr_memorial_dntn_dsc character varying(150) ENCODE lzo,
    giftran_typ_dsc character varying(150) ENCODE lzo,
    trans_fund_cd character varying(40) ENCODE lzo,
    trans_fund_dsc character varying(150) ENCODE lzo,
    deposit_dt date ENCODE az64,
    dntn_gift_dt date ENCODE az64,
    fr_pmt_amt integer ENCODE az64,
    pmt_typ_key bigint ENCODE az64,
    cnst_typ_cd character varying(2) ENCODE lzo,
    cnst_org_nm character varying(150) ENCODE lzo,
    recurring_ind integer ENCODE az64,
    recurng_start_dt timestamp without time zone ENCODE az64,
    fr_dntn_src_chan_nm character varying(100) ENCODE lzo
)
DISTSTYLE ALL;