CREATE TABLE mktg_ops_tbls.arc_biomed_txn_ext_staff (
    cnst_mstr_id bigint ENCODE az64,
    donat_key bigint ENCODE az64,
    nk_donat_num character varying(18) NOT NULL ENCODE lzo,
    nk_donat_dt date NOT NULL ENCODE az64,
    nk_supplier character varying(4) NOT NULL ENCODE lzo,
    donat_dt_key integer NOT NULL ENCODE az64,
    supplier_key integer NOT NULL ENCODE az64,
    bdr_rev_staff_key integer NOT NULL ENCODE az64,
    hh_staff_key integer NOT NULL ENCODE az64,
    phleb_start1_staff_key integer NOT NULL ENCODE az64,
    phleb_end1_staff_key integer NOT NULL ENCODE az64,
    phleb_start2_staff_key integer NOT NULL ENCODE az64,
    phleb_end2_staff_key integer NOT NULL ENCODE az64,
    phleb_start3_staff_key integer NOT NULL ENCODE az64,
    phleb_end3_staff_key integer NOT NULL ENCODE az64,
    phleb_start4_staff_key integer NOT NULL ENCODE az64,
    phleb_end4_staff_key integer NOT NULL ENCODE az64,
    drv_apprvr_staff_key integer NOT NULL ENCODE az64,
    phys_exam_staff_key integer NOT NULL ENCODE az64,
    donor_regis_staff_key integer NOT NULL ENCODE az64,
    item_ship_staff_key integer NOT NULL ENCODE az64,
    flex1_staff_key integer NOT NULL ENCODE az64,
    flex2_staff_key integer NOT NULL ENCODE az64,
    flex3_staff_key integer NOT NULL ENCODE az64,
    flex4_staff_key integer NOT NULL ENCODE az64,
    flex5_staff_key integer NOT NULL ENCODE az64,
    nk_bdr_rev_staff_id character varying(20) ENCODE lzo,
    nk_hh_staff_id character varying(20) ENCODE lzo,
    nk_phleb_start1_staff_id character varying(20) ENCODE lzo,
    nk_phleb_end1_staff_id character varying(20) ENCODE lzo,
    nk_phleb_start2_staff_id character varying(20) ENCODE lzo,
    nk_phleb_end2_staff_id character varying(20) ENCODE lzo,
    nk_phleb_start3_staff_id character varying(20) ENCODE lzo,
    nk_phleb_end3_staff_id character varying(20) ENCODE lzo,
    nk_phleb_start4_staff_id character varying(20) ENCODE lzo,
    nk_phleb_end4_staff_id character varying(20) ENCODE lzo,
    nk_drv_apprvr_staff_id character varying(20) ENCODE lzo,
    nk_phys_exam_staff_id character varying(20) ENCODE lzo,
    nk_donor_regis_staff_id character varying(20) ENCODE lzo,
    nk_item_ship_staff_id character varying(20) ENCODE lzo,
    nk_flex1_staff_id character varying(20) ENCODE lzo,
    nk_flex2_staff_id character varying(20) ENCODE lzo,
    nk_flex3_staff_id character varying(20) ENCODE lzo,
    nk_flex4_staff_id character varying(20) ENCODE lzo,
    nk_flex5_staff_id character varying(20) ENCODE lzo,
    audit_key character varying(20) NOT NULL ENCODE lzo,
    srcsys_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_create_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64,
    UNIQUE (nk_donat_num, nk_donat_dt, nk_supplier)
)
DISTSTYLE ALL;