CREATE TABLE mktg_ops_tbls.awb_dntn_xtrct (
    trans_id bigint ENCODE az64,
    rtrans_idco_dntn_id integer ENCODE az64,
    cnst_mstr_id bigint ENCODE az64,
    gift_ts timestamp without time zone ENCODE az64,
    last_update_ts timestamp without time zone ENCODE az64,
    fr_pmt_amt numeric(13,2) ENCODE az64,
    trans_fund_cd character varying(40) ENCODE lzo,
    trans_fund_dsc character varying(150) ENCODE lzo,
    fr_distr_dntn_ind smallint ENCODE az64,
    pmt_typ_cd character varying(10) ENCODE lzo,
    pmt_typ_dsc character varying(100) ENCODE lzo,
    recurring_ind smallint ENCODE az64,
    first_time_recurring_ind smallint ENCODE az64,
    rco_subscription_id character varying(255) ENCODE lzo,
    cnst_typ_cd character varying(2) ENCODE lzo,
    org_typ_cd character varying(5) ENCODE lzo,
    derived_channel character varying(255) ENCODE lzo,
    segment character varying(40) ENCODE lzo,
    fr_trans_cnst_zip_cd character varying(20) ENCODE lzo,
    managed_donor_ind smallint ENCODE az64,
    src_cd character varying(50) ENCODE lzo,
    subsrc_cd character varying(255) ENCODE lzo,
    motivtn_cd character varying(40) ENCODE lzo,
    cnst_gift_seqnc_num integer ENCODE az64,
    oln_sustnr_gift_seqnc_num integer ENCODE az64,
    oln_sustnr_gift_cnt smallint ENCODE az64,
    oln_sustnr_gift_amt numeric(13,2) ENCODE az64,
    offln_sustnr_id integer ENCODE az64,
    offln_sustnr_gift_seqnc_num integer ENCODE az64,
    offln_sustnr_gift_cnt smallint ENCODE az64,
    offln_sustnr_gift_amt numeric(13,2) ENCODE az64,
    awb_extrct_dt timestamp without time zone ENCODE az64
)
DISTSTYLE ALL;