CREATE TABLE mktg_ops_tbls.bz_cnst_birth_best (
    cnst_mstr_id bigint NOT NULL ENCODE raw distkey,
    pid character varying(20) ENCODE lzo,
    cnst_srcsys_id character varying(255) ENCODE lzo,
    arc_srcsys_cd character varying(10) NOT NULL ENCODE lzo,
    cnst_birth_dy_num numeric(2,0) ENCODE az64,
    cnst_birth_mth_num numeric(2,0) ENCODE az64,
    cnst_birth_yr_num numeric(4,0) ENCODE az64,
    bzd_char_month character varying(2) ENCODE lzo,
    bzd_char_day character varying(2) ENCODE lzo,
    bzd_char_yr character varying(4) ENCODE lzo,
    bzd_birth_dt date ENCODE az64,
    bzd_altered_dt_flg character(1) ENCODE lzo,
    bzd_derived_age integer ENCODE az64,
    experian_age integer ENCODE az64,
    experian_birth_yrmth integer ENCODE az64,
    experian_derived_age integer ENCODE az64,
    bb_age_cd integer ENCODE az64,
    simio_birth_dt_yr_num smallint ENCODE az64,
    simio_birth_dt_mth_num smallint ENCODE az64,
    simio_derived_birth_dt date ENCODE az64,
    simio_derived_age smallint ENCODE az64,
    cnst_birth_strt_ts timestamp without time zone ENCODE az64,
    cnst_birth_end_dt date ENCODE az64,
    gen_segmnt_key integer ENCODE az64,
    generation_segmnt_cd character(1) ENCODE lzo,
    generation_segmnt_dsc character varying(100) ENCODE lzo,
    cnst_birth_best_los_ind smallint ENCODE az64,
    trans_key bigint ENCODE az64,
    user_id character varying(100) ENCODE lzo,
    dw_srcsys_trans_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character varying(4) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );