CREATE TABLE mktg_ops_tbls.bz_fact_response_pg (
    cnst_mstr_id bigint NOT NULL ENCODE raw distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE az64,
    cnst_hsld_id character varying(18) ENCODE lzo,
    cnst_comnictn_key bigint NOT NULL ENCODE az64,
    src_key bigint NOT NULL ENCODE az64,
    comnictn_src_key bigint NOT NULL ENCODE az64,
    arcpg_comnictn_src_key bigint NOT NULL ENCODE az64,
    comnictn_typ_key bigint NOT NULL ENCODE az64,
    response_typ_key bigint NOT NULL ENCODE az64,
    chan_typ_key bigint NOT NULL ENCODE az64,
    unit_key integer NOT NULL ENCODE az64,
    amt_typ_key bigint NOT NULL ENCODE az64,
    response_dt_key integer NOT NULL ENCODE az64,
    fr_last_ta_acct_id integer ENCODE az64,
    nk_response_dt date ENCODE az64,
    nk_tapg_comnictn_seq numeric(3,0) ENCODE az64,
    nk_tapg_comnictn_seq_page numeric(3,0) ENCODE az64,
    comnictn_dsc character varying(300) ENCODE bytedict,
    offer_id integer ENCODE az64,
    treatment_id integer ENCODE az64,
    activity_id integer ENCODE az64,
    segmntn_id integer ENCODE az64,
    segmnt_id integer ENCODE az64,
    outbnd_id integer ENCODE az64,
    email_id integer ENCODE az64,
    cell_id integer ENCODE az64,
    cell_src_cd character varying(20) ENCODE lzo,
    cell_subsrc_cd character varying(40) ENCODE lzo,
    run_dt date ENCODE az64,
    run_id integer ENCODE az64,
    lead_amt numeric(11,2) ENCODE az64,
    closed_amt numeric(11,2) ENCODE az64,
    update_dt date ENCODE az64,
    note_txt character varying(1000) ENCODE lzo,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64,
    srcsys_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );