CREATE TABLE mktg_ops_tbls.bz_fact_interaction_pg (
    cnst_mstr_id bigint NOT NULL ENCODE raw distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE az64,
    cnst_hsld_id character varying(18) ENCODE lzo,
    cnst_comnictn_key bigint NOT NULL ENCODE az64,
    src_key bigint NOT NULL ENCODE az64,
    comnictn_src_key bigint NOT NULL ENCODE az64,
    arcpg_comnictn_src_key bigint NOT NULL ENCODE az64,
    comnictn_typ_key bigint NOT NULL ENCODE az64,
    chan_typ_key bigint NOT NULL ENCODE az64,
    unit_key integer NOT NULL ENCODE az64,
    amt_typ_key bigint NOT NULL ENCODE az64,
    fr_last_ta_acct_id integer ENCODE az64,
    nk_tapg_comnictn_dt date ENCODE az64,
    nk_tapg_comnictn_seq numeric(3,0) ENCODE az64,
    nk_tapg_comnictn_seq_page numeric(3,0) ENCODE az64,
    comnictn_dsc character varying(300) ENCODE lzo,
    offer_id integer ENCODE az64,
    treatment_id integer ENCODE az64,
    activity_id integer ENCODE az64,
    segementation_id integer ENCODE az64,
    segment_id integer ENCODE az64,
    outbnd_id integer ENCODE az64,
    email_id integer ENCODE az64,
    cell_id integer ENCODE az64,
    cell_src_cd character varying(20) ENCODE lzo,
    cell_subsrc_cd character varying(40) ENCODE lzo,
    email_sent_dt date ENCODE az64,
    to_domain character varying(175) ENCODE lzo,
    drop_dt date ENCODE az64,
    run_dt date ENCODE az64,
    run_id integer ENCODE az64,
    update_dt date ENCODE az64,
    last_dntn_dt date ENCODE az64,
    last_dntn_amt numeric(13,2) ENCODE az64,
    chpt_affl character varying(150) ENCODE lzo,
    submitter_nm character varying(150) ENCODE lzo,
    chpt_id character varying(20) ENCODE lzo,
    pg_amt numeric(13,2) ENCODE az64,
    pg_response_cnt integer ENCODE az64,
    note_txt character varying(10000) ENCODE lzo,
    mailed_ind smallint ENCODE az64,
    supressed_ind smallint ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64,
    srcsys_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );