CREATE TABLE mktg_ops_tbls.bzf_cnst_chrctrstc_simio (
    cnst_mstr_id bigint ENCODE raw distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    hh_la_id character varying(30) ENCODE lzo,
    dm_cnst_prsn_prfx_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_f_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_m_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_l_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_suffix_nm character varying(50) ENCODE lzo,
    dm_cnst_line_1_addr character varying(100) ENCODE lzo,
    dm_cnst_line_2_addr character varying(100) ENCODE lzo,
    dm_cnst_city_nm character varying(100) ENCODE lzo,
    dm_cnst_st_cd character(2) ENCODE lzo,
    dm_cnst_zip_5_cd character(5) ENCODE lzo,
    dm_cnst_zip_4_cd character(4) ENCODE lzo,
    lst_arc_patrng_dt date ENCODE az64,
    cnst_start_dt date ENCODE az64,
    run_ts timestamp without time zone ENCODE az64,
    updated_set character varying(50) ENCODE lzo,
    address2 character varying(50) ENCODE lzo,
    city character varying(50) ENCODE lzo,
    state character(2) ENCODE lzo,
    simio_individual_id character varying(50) ENCODE lzo,
    pid character varying(50) ENCODE lzo,
    file_nm character varying(50) ENCODE lzo,
    eductn_cd character(1) ENCODE lzo,
    home_loan_yr smallint ENCODE az64,
    home_loan_typ_cd character(1) ENCODE lzo,
    home_loan_to_val_cd character(1) ENCODE lzo,
    home_val_decile smallint ENCODE az64,
    home_insrnc_exp_dt_mth smallint ENCODE az64,
    home_sq_ft_cd character varying(4) ENCODE lzo,
    home_built_yr smallint ENCODE az64,
    invest_resdntl_proprty_cnt character varying(3) ENCODE lzo,
    marital_stat_cd character(1) ENCODE lzo,
    hh_net_worth_cd character(1) ENCODE lzo,
    lines_of_credit_cnt smallint ENCODE az64,
    occuptn_cd character(1) ENCODE lzo,
    discrtnry_spend_intl_travl integer ENCODE az64,
    dntn_contrbtn_ind smallint ENCODE az64,
    mail_ordr_buyr_cd character(1) ENCODE lzo,
    onln_purchs_flg character(1) ENCODE lzo,
    boat_insrnc_scr smallint ENCODE az64,
    satellite_tv_scr smallint ENCODE az64,
    cable_tv_scr smallint ENCODE az64,
    num_ordrs_lwscl_catlg_cd character(1) ENCODE lzo,
    avg_offln_prch_amt_cd character(1) ENCODE lzo,
    prchs_decmbr_amt_cd character(1) ENCODE lzo,
    offln_amt_cd character(1) ENCODE lzo,
    num_ordrs_offln_500_999_cd character(1) ENCODE lzo,
    num_ordrs_offln_1k_pls_cd character(1) ENCODE lzo,
    avg_onln_prch_amt_cd character(1) ENCODE lzo,
    num_ordrs_onln_50_under_cd character(1) ENCODE lzo,
    num_ordrs_onln_1k_pls_cd character(1) ENCODE lzo,
    lst_onln_ordr_num_wks smallint ENCODE az64,
    lst_any_ordr_num_wks smallint ENCODE az64,
    vhcl_yr smallint ENCODE az64,
    cause_suprtd_chartbl_ind smallint ENCODE az64,
    cause_suprtd_intl_aid_ind smallint ENCODE az64,
    religion_dsc character varying(30) ENCODE lzo,
    poltcl_party_dsc character varying(30) ENCODE lzo,
    gender_cd character(1) ENCODE lzo,
    adult_age_18_24_ml_ind smallint ENCODE az64,
    adult_age_18_24_fml_ind smallint ENCODE az64,
    adult_age_18_24_unk_ind smallint ENCODE az64,
    adult_age_25_34_ml_ind smallint ENCODE az64,
    adult_age_25_34_fml_ind smallint ENCODE az64,
    adult_age_25_34_unk_ind smallint ENCODE az64,
    adult_age_35_44_ml_ind smallint ENCODE az64,
    adult_age_35_44_fml_ind smallint ENCODE az64,
    adult_age_35_44_unk_ind smallint ENCODE az64,
    adult_age_45_54_ml_ind smallint ENCODE az64,
    adult_age_45_54_fml_ind smallint ENCODE az64,
    adult_age_45_54_unk_ind smallint ENCODE az64,
    adult_age_55_64_ml_ind smallint ENCODE az64,
    adult_age_55_64_fml_ind smallint ENCODE az64,
    adult_age_55_64_unk_ind smallint ENCODE az64,
    adult_age_65_74_ml_ind smallint ENCODE az64,
    adult_age_65_74_fml_ind smallint ENCODE az64,
    adult_age_65_74_unk_ind smallint ENCODE az64,
    adult_age_75_pls_ml_ind smallint ENCODE az64,
    adult_age_75_pls_fml_ind smallint ENCODE az64,
    adult_age_75_pls_unk_ind smallint ENCODE az64,
    child_age_00_02_ml_ind smallint ENCODE az64,
    child_age_00_02_fml_ind smallint ENCODE az64,
    child_age_00_02_unk_ind smallint ENCODE az64,
    child_age_03_05_ml_ind smallint ENCODE az64,
    child_age_03_05_fml_ind smallint ENCODE az64,
    child_age_03_05_unk_ind smallint ENCODE az64,
    child_age_06_10_ml_ind smallint ENCODE az64,
    child_age_06_10_fml_ind smallint ENCODE az64,
    child_age_06_10_unk_ind smallint ENCODE az64,
    child_age_11_15_ml_ind smallint ENCODE az64,
    child_age_11_15_fml_ind smallint ENCODE az64,
    child_age_11_15_unk_ind smallint ENCODE az64,
    child_age_16_17_ml_ind smallint ENCODE az64,
    child_age_16_17_fml_ind smallint ENCODE az64,
    child_age_16_17_unk_ind smallint ENCODE az64,
    birth_dt_yr smallint ENCODE az64,
    country_of_origin_cd character(2) ENCODE lzo,
    travl_ind smallint ENCODE az64,
    hh_size smallint ENCODE az64,
    hh_num_childrn smallint ENCODE az64,
    senior_adult_in_hh_flg character(1) ENCODE lzo,
    hisp_lang_pref_cd character(1) ENCODE lzo,
    prem_credit_card_ind smallint ENCODE az64,
    invest_prsnl_ind smallint ENCODE az64,
    invest_re_ind smallint ENCODE az64,
    invest_stock_ind smallint ENCODE az64,
    invest_any_past_12_mths_scr smallint ENCODE az64,
    invest_stock_past_12_mths_scr smallint ENCODE az64,
    likely_investr_flg character(1) ENCODE lzo,
    econmc_stablty_scr smallint ENCODE az64,
    veteran_ind smallint ENCODE az64,
    dwelng_typ_cd character(1) ENCODE lzo,
    home_length_resdnce smallint ENCODE az64,
    home_val_cd character(1) ENCODE lzo,
    home_ownr_rentr_cd character(1) ENCODE lzo,
    home_purchs_dt_yyyymm integer ENCODE az64,
    video_games_ind smallint ENCODE az64,
    grandchild_ind smallint ENCODE az64,
    travl_cruise_ind smallint ENCODE az64,
    travl_domstc_ind smallint ENCODE az64,
    avg_poltcl_contrbtn_amt numeric(12,2) ENCODE az64,
    race_cd character(1) ENCODE lzo,
    mail_ordr_dnr_cd character(1) ENCODE lzo,
    pmt_mthd_cash_amt character varying(3) ENCODE lzo,
    pmt_mthd_cc_amt character varying(3) ENCODE lzo,
    num_ordrs_offln_cd character(1) ENCODE lzo,
    lst_offln_ordr_num_wks smallint ENCODE az64,
    votng_freq_cd smallint ENCODE az64,
    gen_electn_votr_ind smallint ENCODE az64,
    birth_dt_mth smallint ENCODE az64,
    occuptn_dtl_cd character varying(4) ENCODE lzo,
    hh_income_cd character(1) ENCODE lzo,
    home_purchs_dt_rp_yyyymm integer ENCODE az64,
    num_ordrs_upscl_catlg_cd character(1) ENCODE lzo,
    home_eqty_amt_cd character varying(2) ENCODE lzo,
    home_loan_amt_cd character varying(6) ENCODE lzo,
    collctbls_antqs_ind smallint ENCODE az64,
    hh_membr_boat_yacht_club smallint ENCODE az64,
    wealth_scr smallint ENCODE az64,
    community_charty_ind smallint ENCODE az64,
    interest_mil_hist_flg character(1) ENCODE lzo,
    buy_actvty_weeks_since_lst_any_ordr smallint ENCODE az64,
    buy_actvty_weeks_since_lst_offln_ordr smallint ENCODE az64,
    buy_actvty_weeks_since_lst_onln_ordr smallint ENCODE az64,
    buy_actvty_num_ordrs_cash smallint ENCODE az64,
    buy_actvty_num_ordrs_cc smallint ENCODE az64,
    buy_actvty_purchsd_dec integer ENCODE az64,
    buy_actvty_total_offln_ordrs_500_999 smallint ENCODE az64,
    buy_actvty_total_offln_ordrs_1k_pls smallint ENCODE az64,
    buy_actvty_total_onln_ordrs_under_50 smallint ENCODE az64,
    buy_actvty_total_onln_ordrs_1k_pls smallint ENCODE az64,
    wealth_scr_segmnt smallint ENCODE az64,
    consumr_prominence_prsn_scr smallint ENCODE az64,
    income_scr character varying(3) ENCODE lzo,
    cable_tv_intrnt_scr smallint ENCODE az64,
    heavy_transctrs_scr smallint ENCODE az64,
    dw_trans_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );