CREATE TABLE mktg_ops_tbls.bzf_cnst_scr (
    cnst_mstr_id bigint NOT NULL ENCODE raw distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE raw,
    hh_la_id bigint ENCODE az64,
    pgcga_scrid bigint ENCODE az64,
    pgcga_scrval character varying(20) ENCODE lzo,
    pgcga_scrts timestamp without time zone ENCODE az64,
    pgwg_scrid bigint ENCODE az64,
    pgwg_scrval character varying(20) ENCODE lzo,
    pgwg_scrts timestamp without time zone ENCODE az64,
    maj1k_scrid bigint ENCODE az64,
    maj1k_scrval character varying(20) ENCODE lzo,
    maj1k_scrts timestamp without time zone ENCODE az64,
    pgbeq_scrid bigint ENCODE az64,
    pgbeq_scrval character varying(20) ENCODE lzo,
    pgbeq_scrts timestamp without time zone ENCODE az64,
    dis1k_scrid bigint ENCODE az64,
    dis1k_scrval character varying(20) ENCODE lzo,
    dis1k_scrts timestamp without time zone ENCODE az64,
    arc_loyalty_insight1_scrid bigint ENCODE az64,
    arc_loyalty_insight1_scrval character varying(20) ENCODE lzo,
    arc_loyalty_insight1_scrts timestamp without time zone ENCODE az64,
    arc_loyalty_insight2_scrid bigint ENCODE az64,
    arc_loyalty_insight2_scrval character varying(20) ENCODE lzo,
    arc_loyalty_insight2_scrts timestamp without time zone ENCODE az64,
    arc_conv_tag1_scrid bigint ENCODE az64,
    arc_conv_tag1_scrval character varying(20) ENCODE lzo,
    arc_conv_tag1_scrts timestamp without time zone ENCODE az64,
    arc_conv_tag2_scrid bigint ENCODE az64,
    arc_conv_tag2_scrval character varying(20) ENCODE lzo,
    arc_conv_tag2_scrts timestamp without time zone ENCODE az64,
    arc_lapsed_tag1_scrid bigint ENCODE az64,
    arc_lapsed_tag1_scrval character varying(20) ENCODE lzo,
    arc_lapsed_tag1_scrts timestamp without time zone ENCODE az64,
    arc_lapsed_tag2_scrid bigint ENCODE az64,
    arc_lapsed_tag2_scrval character varying(20) ENCODE lzo,
    arc_lapsed_tag2_scrts timestamp without time zone ENCODE az64,
    latest_scrid bigint ENCODE az64,
    latest_scrval character varying(20) ENCODE lzo,
    latest_scrts timestamp without time zone ENCODE az64,
    latest_scr_cd character varying(40) ENCODE lzo,
    nhq_conv_tag1_scrid bigint ENCODE az64,
    nhq_conv_tag1_scrval character varying(20) ENCODE lzo,
    nhq_conv_tag1_scrts timestamp without time zone ENCODE az64,
    nhq_conv_tag2_scrid bigint ENCODE az64,
    nhq_conv_tag2_scrval character varying(20) ENCODE lzo,
    nhq_conv_tag2_scrts timestamp without time zone ENCODE az64,
    nhq_conv_tag3_scrid bigint ENCODE az64,
    nhq_conv_tag3_scrval character varying(20) ENCODE lzo,
    nhq_conv_tag3_scrts timestamp without time zone ENCODE az64,
    nhq_conv_tag4_scrid bigint ENCODE az64,
    nhq_conv_tag4_scrval character varying(20) ENCODE lzo,
    nhq_conv_tag4_scrts timestamp without time zone ENCODE az64,
    chpt_conv_tag1_scrid bigint ENCODE az64,
    chpt_conv_tag1_scrval character varying(20) ENCODE lzo,
    chpt_conv_tag1_scrts timestamp without time zone ENCODE az64,
    chpt_conv_tag2_scrid bigint ENCODE az64,
    chpt_conv_tag2_scrval character varying(20) ENCODE lzo,
    chpt_conv_tag2_scrts timestamp without time zone ENCODE az64,
    chpt_conv_tag3_scrid bigint ENCODE az64,
    chpt_conv_tag3_scrval character varying(20) ENCODE lzo,
    chpt_conv_tag3_scrts timestamp without time zone ENCODE az64,
    chpt_conv_tag4_scrid bigint ENCODE az64,
    chpt_conv_tag4_scrval character varying(20) ENCODE lzo,
    chpt_conv_tag4_scrts timestamp without time zone ENCODE az64,
    nhq_lapsed_tag1_scrid bigint ENCODE az64,
    nhq_lapsed_tag1_scrval character varying(20) ENCODE lzo,
    nhq_lapsed_tag1_scrts timestamp without time zone ENCODE az64,
    nhq_lapsed_tag2_scrid bigint ENCODE az64,
    nhq_lapsed_tag2_scrval character varying(20) ENCODE lzo,
    nhq_lapsed_tag2_scrts timestamp without time zone ENCODE az64,
    chpt_lapsed_tag1_scrid bigint ENCODE az64,
    chpt_lapsed_tag1_scrval character varying(20) ENCODE lzo,
    chpt_lapsed_tag1_scrts timestamp without time zone ENCODE az64,
    chpt_lapsed_tag2_scrid bigint ENCODE az64,
    chpt_lapsed_tag2_scrval character varying(20) ENCODE lzo,
    chpt_lapsed_tag2_scrts timestamp without time zone ENCODE az64,
    tatm_scrid bigint ENCODE az64,
    tatm_scrval character varying(20) ENCODE lzo,
    tatm_scrts timestamp without time zone ENCODE az64,
    tasustnr_scrid bigint ENCODE az64,
    tasustnr_scrval character varying(20) ENCODE lzo,
    tasustnr_scrts timestamp without time zone ENCODE az64,
    am_tm_ind_scrid bigint ENCODE az64,
    am_tm_ind_scrval character varying(20) ENCODE lzo,
    am_tm_ind_scrts timestamp without time zone ENCODE az64,
    am_sust_ind_scrid bigint ENCODE az64,
    am_sust_ind_scrval character varying(20) ENCODE lzo,
    am_sust_ind_scrts timestamp without time zone ENCODE az64,
    am_insights_scrid bigint ENCODE az64,
    am_insights_scrval character varying(20) ENCODE lzo,
    am_insights_scrts timestamp without time zone ENCODE az64,
    lm_tm_ind_scrid bigint ENCODE az64,
    lm_tm_ind_scrval character varying(20) ENCODE lzo,
    lm_tm_ind_scrts timestamp without time zone ENCODE az64,
    lm_sust_ind_scrid bigint ENCODE az64,
    lm_sust_ind_scrval character varying(20) ENCODE lzo,
    lm_sust_ind_scrts timestamp without time zone ENCODE az64,
    lm_lapsed_tag_scrid bigint ENCODE az64,
    lm_lapsed_tag_scrval character varying(20) ENCODE lzo,
    lm_lapsed_tag_scrts timestamp without time zone ENCODE az64,
    im_lapsed_tag_scrid bigint ENCODE az64,
    im_lapsed_tag_scrval character varying(20) ENCODE lzo,
    im_lapsed_tag_scrts timestamp without time zone ENCODE az64,
    ad_tm_ind_scrid bigint ENCODE az64,
    ad_tm_ind_scrval character varying(20) ENCODE lzo,
    ad_tm_ind_scrts timestamp without time zone ENCODE az64,
    ad_conv_tag_scrid bigint ENCODE az64,
    ad_conv_tag_scrval character varying(20) ENCODE lzo,
    ad_conv_tag_scrts timestamp without time zone ENCODE az64,
    ad_insights_scrid bigint ENCODE az64,
    ad_insights_scrval character varying(20) ENCODE lzo,
    ad_insights_scrts timestamp without time zone ENCODE az64,
    ld_tm_ind_scrid bigint ENCODE az64,
    ld_tm_ind_scrval character varying(20) ENCODE lzo,
    ld_tm_ind_scrts timestamp without time zone ENCODE az64,
    ld_conv_tag_scrid bigint ENCODE az64,
    ld_conv_tag_scrval character varying(20) ENCODE lzo,
    ld_conv_tag_scrts timestamp without time zone ENCODE az64,
    id_conv_tag_scrid bigint ENCODE az64,
    id_conv_tag_scrval character varying(20) ENCODE lzo,
    id_conv_tag_scrts timestamp without time zone ENCODE az64,
    am_web_ind_scrid bigint ENCODE az64,
    am_web_ind_scrval character varying(20) ENCODE lzo,
    am_web_ind_scrts timestamp without time zone ENCODE az64,
    lm_web_ind_scrid bigint ENCODE az64,
    lm_web_ind_scrval character varying(20) ENCODE lzo,
    lm_web_ind_scrts timestamp without time zone ENCODE az64,
    lm_lapsed_insights_scrid bigint ENCODE az64,
    lm_lapsed_insights_scrval character varying(20) ENCODE lzo,
    lm_lapsed_insights_scrts timestamp without time zone ENCODE az64,
    im_lapsed_insights_scrid bigint ENCODE az64,
    im_lapsed_insights_scrval character varying(20) ENCODE lzo,
    im_lapsed_insights_scrts timestamp without time zone ENCODE az64,
    ad_web_ind_scrid bigint ENCODE az64,
    ad_web_ind_scrval character varying(20) ENCODE lzo,
    ad_web_ind_scrts timestamp without time zone ENCODE az64,
    ad_sus_ind_scrid bigint ENCODE az64,
    ad_sus_ind_scrval character varying(20) ENCODE lzo,
    ad_sus_ind_scrts timestamp without time zone ENCODE az64,
    ld_web_ind_scrid bigint ENCODE az64,
    ld_web_ind_scrval character varying(20) ENCODE lzo,
    ld_web_ind_scrts timestamp without time zone ENCODE az64,
    ld_sus_ind_scrid bigint ENCODE az64,
    ld_sus_ind_scrval character varying(20) ENCODE lzo,
    ld_sus_ind_scrts timestamp without time zone ENCODE az64,
    ld_lapsed_insights_scrid bigint ENCODE az64,
    ld_lapsed_insights_scrval character varying(20) ENCODE lzo,
    ld_lapsed_insights_scrts timestamp without time zone ENCODE az64,
    id_lapsed_insights_scrid bigint ENCODE az64,
    id_lapsed_insights_scrval character varying(20) ENCODE lzo,
    id_lapsed_insights_scrts timestamp without time zone ENCODE az64,
    un_conv_tag_scrid bigint ENCODE az64,
    un_conv_tag_scrval character varying(20) ENCODE lzo,
    un_conv_tag_scrts timestamp without time zone ENCODE az64,
    biomed_xpromo_scrid bigint ENCODE az64,
    biomed_xpromo_scrval character varying(20) ENCODE lzo,
    biomed_xpromo_scrts timestamp without time zone ENCODE az64,
    biomed_x_lob_conv_scrid bigint ENCODE az64,
    biomed_x_lob_conv_scrval double precision ENCODE raw,
    biomed_x_lob_conv_scrts timestamp without time zone ENCODE az64,
    bio2fr_conv_scrid bigint ENCODE az64,
    bio2fr_conv_scrval character varying(20) ENCODE lzo,
    bio2fr_conv_scrts timestamp without time zone ENCODE az64,
    cap2500_non_fr_scrid bigint ENCODE az64,
    cap2500_non_fr_scrval bigint ENCODE az64,
    cap2500_non_fr_scrts timestamp without time zone ENCODE az64,
    mods_bio2fr_lookalike_scrid bigint ENCODE az64,
    mods_bio2fr_lookalike_scrval numeric(20,4) ENCODE az64,
    mods_bio2fr_lookalike_scrts timestamp without time zone ENCODE az64,
    mods_phss2fr_lookalike_scrid bigint ENCODE az64,
    mods_phss2fr_lookalike_scrval character varying(20) ENCODE lzo,
    mods_phss2fr_lookalike_scrts timestamp without time zone ENCODE az64,
    mods_vms2fr_lookalike_scrid bigint ENCODE az64,
    mods_vms2fr_lookalike_scrval character varying(20) ENCODE lzo,
    mods_vms2fr_lookalike_scrts timestamp without time zone ENCODE az64,
    mods_conv_fr_dm_scrid bigint ENCODE az64,
    mods_conv_fr_dm_scrval numeric(20,4) ENCODE az64,
    mods_conv_fr_dm_scrts timestamp without time zone ENCODE az64,
    mods_conv_fr_dm_ry_scrid bigint ENCODE az64,
    mods_conv_fr_dm_ry_scrval numeric(20,4) ENCODE az64,
    mods_conv_fr_dm_ry_scrts timestamp without time zone ENCODE az64,
    mods_fr_em_scrid bigint ENCODE az64,
    mods_fr_em_scrval numeric(20,4) ENCODE az64,
    mods_fr_em_scrts timestamp without time zone ENCODE az64,
    mods_conv_fr_em_scrid bigint ENCODE az64,
    mods_conv_fr_em_scrval numeric(20,4) ENCODE az64,
    mods_conv_fr_em_scrts timestamp without time zone ENCODE az64,
    mods_fr_lapsed_scrid bigint ENCODE az64,
    mods_fr_lapsed_scrval numeric(20,4) ENCODE az64,
    mods_fr_lapsed_scrts timestamp without time zone ENCODE az64,
    mods_fr_dod_scrid bigint ENCODE az64,
    mods_fr_dod_scrval numeric(20,4) ENCODE az64,
    mods_fr_dod_scrts timestamp without time zone ENCODE az64,
    dm_direct_mail_scrid bigint ENCODE az64,
    dm_direct_mail_scrval numeric(20,4) ENCODE az64,
    dm_direct_mail_scrts timestamp without time zone ENCODE az64,
    dm_donor_persona_scrid bigint ENCODE az64,
    dm_donor_persona_scrval numeric(20,4) ENCODE az64,
    dm_donor_persona_scrts timestamp without time zone ENCODE az64,
    dm_eoy_scrid bigint ENCODE az64,
    dm_eoy_scrval numeric(20,4) ENCODE az64,
    dm_eoy_scrts timestamp without time zone ENCODE az64,
    dm_gt_scrid bigint ENCODE az64,
    dm_gt_scrval numeric(20,4) ENCODE az64,
    dm_gt_scrts timestamp without time zone ENCODE az64,
    dm_phil_insights_scrid bigint ENCODE az64,
    dm_phil_insights_scrval numeric(20,4) ENCODE az64,
    dm_phil_insights_scrts timestamp without time zone ENCODE az64,
    dm_sustainer_scrid bigint ENCODE az64,
    dm_sustainer_scrval numeric(20,4) ENCODE az64,
    dm_sustainer_scrts timestamp without time zone ENCODE az64,
    dm_telemarketing_scrid bigint ENCODE az64,
    dm_telemarketing_scrval numeric(20,4) ENCODE az64,
    dm_telemarketing_scrts timestamp without time zone ENCODE az64,
    dm_web_scrid bigint ENCODE az64,
    dm_web_scrval numeric(20,4) ENCODE az64,
    dm_web_scrts timestamp without time zone ENCODE az64,
    dm_gift_array_scrid bigint ENCODE az64,
    dm_gift_array_scrval numeric(20,4) ENCODE az64,
    dm_gift_array_scrts timestamp without time zone ENCODE az64,
    mods_fr_cultiv_scrid bigint ENCODE az64,
    mods_fr_cultiv_scrval numeric(20,4) ENCODE az64,
    mods_fr_cultiv_scrts timestamp without time zone ENCODE az64,
    major_gift_capacity_scrid bigint ENCODE az64,
    major_gift_capacity_scrval numeric(20,4) ENCODE az64,
    major_gift_capacity_scrts timestamp without time zone ENCODE az64,
    p2p_diy_scrid bigint ENCODE az64,
    p2p_diy_scrval numeric(20,4) ENCODE az64,
    p2p_diy_scrts timestamp without time zone ENCODE az64,
    p2p_org_event_scrid bigint ENCODE az64,
    p2p_org_event_scrval numeric(20,4) ENCODE az64,
    p2p_org_event_scrts timestamp without time zone ENCODE az64,
    p2p_persona_scrid bigint ENCODE az64,
    p2p_persona_scrval numeric(20,4) ENCODE az64,
    p2p_persona_scrts timestamp without time zone ENCODE az64,
    bb_agecode_scrid bigint ENCODE az64,
    bb_agecode_scrval integer ENCODE az64,
    bb_agecode_scrts timestamp without time zone ENCODE az64,
    propnsty_1k_cumu_missn_scrid bigint ENCODE az64,
    propnsty_1k_cumu_missn_scrval integer ENCODE az64,
    propnsty_1k_cumu_missn_scrts timestamp without time zone ENCODE az64,
    propnsty_1k_cumu_distr_scrid bigint ENCODE az64,
    propnsty_1k_cumu_distr_scrval integer ENCODE az64,
    propnsty_1k_cumu_distr_scrts timestamp without time zone ENCODE az64,
    propnsty_distr_dntn_12mnths_scrid bigint ENCODE az64,
    propnsty_distr_dntn_12mnths_scrval integer ENCODE az64,
    propnsty_distr_dntn_12mnths_scrts timestamp without time zone ENCODE az64,
    propnsty_distr_dnr_to_missn_dnr_scrid bigint ENCODE az64,
    propnsty_distr_dnr_to_missn_dnr_scrval integer ENCODE az64,
    propnsty_distr_dnr_to_missn_dnr_scrts timestamp without time zone ENCODE az64,
    sustainer_acquisition_scrid bigint ENCODE az64,
    sustainer_acquisition_scrval integer ENCODE az64,
    sustainer_acquisition_scrts timestamp without time zone ENCODE az64,
    sustainer_lapsed_scrid bigint ENCODE az64,
    sustainer_lapsed_scrval integer ENCODE az64,
    sustainer_lapsed_scrts timestamp without time zone ENCODE az64,
    propnsty_75_999_scrid bigint ENCODE az64,
    propnsty_75_999_scrval integer ENCODE az64,
    propnsty_75_999_scrts timestamp without time zone ENCODE az64,
    grey_to_blue_sky_conv_scrid bigint ENCODE az64,
    grey_to_blue_sky_conv_scrval integer ENCODE az64,
    grey_to_blue_sky_conv_scrts timestamp without time zone ENCODE az64,
    sustnr_churn_propnsty_nxt_3_mnths_scrid bigint ENCODE az64,
    sustnr_churn_propnsty_nxt_3_mnths_scrval integer ENCODE az64,
    sustnr_churn_propnsty_nxt_3_mnths_scrts timestamp without time zone ENCODE az64,
    bsd_cd character varying(10) ENCODE lzo,
    tm_scrval character varying(20) ENCODE lzo,
    sus_scrval character varying(20) ENCODE lzo,
    insights_scrval character varying(20) ENCODE lzo,
    web_scrval character varying(20) ENCODE lzo,
    conv_tag_scrval character varying(20) ENCODE lzo
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id, orig_cnst_mstr_id );