CREATE TABLE mktg_ops_tbls.bzfc_adb_recipient_updt_delta (
    igender smallint ENCODE az64,
    irecipientid integer ENCODE az64 distkey,
    saddress1 character varying(100) ENCODE lzo,
    saddress2 character varying(100) ENCODE lzo,
    scity character varying(100) ENCODE lzo,
    semail character varying(200) ENCODE lzo,
    sfirstname character varying(200) ENCODE lzo,
    slastname character varying(50) ENCODE lzo,
    smiddlename character varying(50) ENCODE lzo,
    smobilephone character varying(50) ENCODE lzo,
    sorigin character varying(80) ENCODE lzo,
    sphone character varying(50) ENCODE lzo,
    ssalutation character varying(20) ENCODE lzo,
    sstatecode character(2) ENCODE lzo,
    szipcode character(5) ENCODE lzo,
    tsbirth timestamp without time zone ENCODE az64,
    tslastmodified timestamp with time zone ENCODE az64,
    tscreated timestamp without time zone ENCODE az64,
    bicnst_mstr_id bigint ENCODE az64,
    birecipientid bigint ENCODE az64,
    dlastdonationamt numeric(13,2) ENCODE az64,
    ifr_field_unit_dimension_id integer ENCODE az64,
    fr_field_chapter_cd character(5) ENCODE lzo,
    fr_field_region_cd character(5) ENCODE lzo,
    ifr_mkt_field_unit_dimension_id integer ENCODE az64,
    fr_mkt_chapter_cd character(5) ENCODE lzo,
    fr_mkt_region_cd character(5) ENCODE lzo,
    iisbio smallint ENCODE az64,
    iisfr smallint ENCODE az64,
    iisphss smallint ENCODE az64,
    iisvms smallint ENCODE az64,
    saddress1_bio character varying(100) ENCODE lzo,
    saddress1_fr character varying(100) ENCODE lzo,
    saddress1_phss character varying(100) ENCODE lzo,
    saddress1_vms character varying(100) ENCODE lzo,
    saddress2_bio character varying(100) ENCODE lzo,
    saddress2_fr character varying(100) ENCODE lzo,
    saddress2_phss character varying(100) ENCODE lzo,
    saddress2_vms character varying(100) ENCODE lzo,
    sbio_em_email character varying(100) ENCODE lzo,
    scity_bio character varying(100) ENCODE lzo,
    scity_fr character varying(100) ENCODE lzo,
    scity_phss character varying(100) ENCODE lzo,
    scity_vms character varying(100) ENCODE lzo,
    sfraddrquality character varying(40) ENCODE lzo,
    sfr_em_email character varying(200) ENCODE lzo,
    sbioaddrquality character varying(40) ENCODE lzo,
    scompany character varying(80) ENCODE lzo,
    smobilephone_bio character varying(50) ENCODE lzo,
    smobilephone_fr character varying(50) ENCODE lzo,
    smobilephone_phss character varying(50) ENCODE lzo,
    smobilephone_vms character varying(50) ENCODE lzo,
    sphone_bio character varying(50) ENCODE lzo,
    sphone_fr character varying(50) ENCODE lzo,
    sphone_phss character varying(50) ENCODE lzo,
    sphone_vms character varying(50) ENCODE lzo,
    sphssaddrquality character varying(40) ENCODE lzo,
    sphss_em_email character varying(200) ENCODE lzo,
    sstatecode_bio character(2) ENCODE lzo,
    sstatecode_fr character(2) ENCODE lzo,
    sstatecode_phss character(2) ENCODE lzo,
    sstatecode_vms character(2) ENCODE lzo,
    svmsaddrquality character varying(40) ENCODE lzo,
    svms_em_email character varying(100) ENCODE lzo,
    szipcode_bio character(5) ENCODE lzo,
    szipcode_fr character(5) ENCODE lzo,
    szipcode_phss character(5) ENCODE lzo,
    szipcode_vms character(5) ENCODE lzo,
    bidm_namelocatorkey bigint ENCODE az64,
    biem_namelocatorkey bigint ENCODE az64,
    biemaillocatorkey bigint ENCODE az64,
    biaddrlocatorkey bigint ENCODE az64,
    biprimphonelocatorkey bigint ENCODE az64,
    bimblphonelocatorkey bigint ENCODE az64,
    sdm_firstname_fr character varying(50) ENCODE lzo,
    sdm_middlename_fr character varying(50) ENCODE lzo,
    sdm_lastname_fr character varying(50) ENCODE lzo,
    sdm_firstname_bio character varying(50) ENCODE lzo,
    sdm_middlename_bio character varying(50) ENCODE lzo,
    sdm_lastname_bio character varying(50) ENCODE lzo,
    sdm_firstname_phss character varying(50) ENCODE lzo,
    sdm_middlename_phss character varying(50) ENCODE lzo,
    sdm_lastname_phss character varying(50) ENCODE lzo,
    sdm_firstname_vms character varying(50) ENCODE lzo,
    sdm_middlename_vms character varying(50) ENCODE lzo,
    sdm_lastname_vms character varying(50) ENCODE lzo,
    sem_firstname_fr character varying(200) ENCODE lzo,
    sem_middlename_fr character varying(50) ENCODE lzo,
    sem_lastname_fr character varying(50) ENCODE lzo,
    sem_firstname_bio character varying(50) ENCODE lzo,
    sem_middlename_bio character varying(50) ENCODE lzo,
    sem_lastname_bio character varying(50) ENCODE lzo,
    sem_firstname_phss character varying(200) ENCODE lzo,
    sem_middlename_phss character varying(50) ENCODE lzo,
    sem_lastname_phss character varying(50) ENCODE lzo,
    sem_firstname_vms character varying(50) ENCODE lzo,
    sem_middlename_vms character varying(50) ENCODE lzo,
    sem_lastname_vms character varying(50) ENCODE lzo,
    semailquality_fr character varying(40) ENCODE lzo,
    semailquality_bio character varying(40) ENCODE lzo,
    semailquality_phss character varying(40) ENCODE lzo,
    semailquality_vms character varying(40) ENCODE lzo,
    saddress4_fr character varying(100) ENCODE lzo,
    saddress4_bio character varying(100) ENCODE lzo,
    saddress4_phss character varying(100) ENCODE lzo,
    saddress4_vms character varying(100) ENCODE lzo,
    tslastdonation date ENCODE az64,
    sfr_ok_to_email_flg character varying(1) ENCODE lzo,
    dw_trans_ts timestamp with time zone ENCODE az64,
    row_stat_cd character varying(1) ENCODE lzo,
    appl_src_cd character varying(3) ENCODE lzo
)
DISTSTYLE KEY;