CREATE TABLE mktg_ops_tbls.bzfc_active_cnst_snpsht (
    snpsht_dt date ENCODE az64,
    cnst_mstr_id bigint ENCODE az64 distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    cnst_typ_cd character varying(2) ENCODE lzo,
    active_fr_ind smallint ENCODE az64,
    active_fr_flg character varying(1) ENCODE lzo,
    active_no_trans_fr_ind smallint ENCODE az64,
    active_no_trans_fr_flg character varying(1) ENCODE lzo,
    active_all_trans_fr_ind integer ENCODE az64,
    active_all_trans_fr_flg character varying(1) ENCODE lzo,
    fr_first_dntn_dt date ENCODE az64,
    fr_patronage_day_cnt integer ENCODE az64,
    fr_last_dntn_dt date ENCODE az64,
    rolling_2yr_dntn_amt numeric(14,2) ENCODE az64,
    fr_month_lapsed_ind smallint ENCODE az64,
    fr_new_cnst_ind smallint ENCODE az64,
    active_fr_mbl_ind smallint ENCODE az64,
    active_fr_mbl_flg character varying(1) ENCODE lzo,
    mbl_gift_cnt integer ENCODE az64,
    mbl_gift_amt numeric(14,2) ENCODE az64,
    active_bio_ind smallint ENCODE az64,
    active_bio_flg character varying(1) ENCODE lzo,
    active_no_trans_bio_ind smallint ENCODE az64,
    active_no_trans_bio_flg character varying(1) ENCODE lzo,
    active_all_trans_bio_ind integer ENCODE az64,
    active_all_trans_bio_flg character varying(1) ENCODE lzo,
    first_bio_donat_dt date ENCODE az64,
    bio_patronage_day_cnt integer ENCODE az64,
    last_donat_dt date ENCODE az64,
    rolling_2yr_proc_cnt integer ENCODE az64,
    bio_month_lapsed_ind smallint ENCODE az64,
    bio_new_cnst_ind smallint ENCODE az64,
    active_vms_ind smallint ENCODE az64,
    active_vms_flg character varying(1) ENCODE lzo,
    first_vol_dt date ENCODE az64,
    vol_patronage_day_cnt integer ENCODE az64,
    active_rcs_ind smallint ENCODE az64,
    active_rcs_flg character varying(1) ENCODE lzo,
    first_rcs_order_dt date ENCODE az64,
    rcs_patronage_day_cnt integer ENCODE az64,
    last_rcs_order_dt date ENCODE az64,
    rcs_month_lapsed_ind smallint ENCODE az64,
    rcs_new_cnst_ind smallint ENCODE az64,
    active_dmw_ind smallint ENCODE az64,
    active_dmw_flg character varying(1) ENCODE lzo,
    active_dmw_course_ind smallint ENCODE az64,
    active_dmw_course_flg character varying(1) ENCODE lzo,
    active_dmw_store_ind smallint ENCODE az64,
    active_dmw_store_flg character varying(1) ENCODE lzo,
    first_dmw_order_dt date ENCODE az64,
    dmw_patronage_day_cnt integer ENCODE az64,
    last_dmw_order_dt date ENCODE az64,
    active_phss_ind smallint ENCODE az64,
    active_phss_flg character varying(1) ENCODE lzo,
    active_phss_rcs_ind smallint ENCODE az64,
    active_phss_rcs_flg character varying(1) ENCODE lzo,
    first_crs_cmptn_dt date ENCODE az64,
    phss_patronage_day_cnt integer ENCODE az64,
    last_crs_cmptn_dt date ENCODE az64,
    phss_month_lapsed_ind smallint ENCODE az64,
    phss_new_cnst_ind smallint ENCODE az64,
    active_cnst_ind smallint ENCODE az64,
    active_cnst_flg character varying(1) ENCODE lzo,
    active_all_trans_cnst_ind smallint ENCODE az64,
    active_all_trans_cnst_flg character varying(1) ENCODE lzo,
    multi_lob_ind smallint ENCODE az64,
    multi_lob_flg character varying(1) ENCODE lzo,
    multi_lob_all_trans_ind smallint ENCODE az64,
    multi_lob_all_trans_flg character varying(1) ENCODE lzo,
    active_multi_ever_ind smallint ENCODE az64,
    active_multi_ever_flg character varying(1) ENCODE lzo,
    last_update_dt date ENCODE az64,
    first_mbl_gift_dt date ENCODE az64,
    last_mbl_gift_dt date ENCODE az64
)
DISTSTYLE KEY;