CREATE TABLE mktg_ops_tbls.bzfc_fact_donation (
    cnst_fsa_key bigint ENCODE az64,
    cnst_mstr_id bigint ENCODE az64 distkey,
    trans_id bigint ENCODE az64,
    comnictn_src_cd character varying(40) ENCODE lzo,
    aprm_src_cd character varying(40) ENCODE lzo,
    aprm_subsrc_cd character varying(50) ENCODE lzo,
    channel_typ_key bigint ENCODE az64,
    nk_ta_nm_id integer ENCODE az64,
    fr_affl_unit_key integer ENCODE az64,
    non_tgt_gift_ind smallint ENCODE az64,
    non_tgt_gift_amt numeric(13,2) ENCODE az64,
    non_tgt_dm_gift_ind smallint ENCODE az64,
    non_tgt_dm_gift_amt numeric(13,2) ENCODE az64,
    non_tgt_em_gift_ind smallint ENCODE az64,
    non_tgt_em_gift_amt numeric(13,2) ENCODE az64,
    non_tgt_segementation_id integer ENCODE az64,
    non_tgt_outbnd_id integer ENCODE az64,
    non_tgt_activity_id integer ENCODE az64,
    non_tgt_treatment_id integer ENCODE az64,
    non_tgt_fund_key bigint ENCODE az64,
    non_tgt_cell_src_cd character varying(40) ENCODE lzo,
    non_tgt_cell_subsrc_cd character varying(50) ENCODE lzo,
    non_tgt_intrctn_dt date ENCODE az64,
    non_tgt_intrctn_dt_key integer ENCODE az64,
    tgt_dm_segementation_id integer ENCODE az64,
    tgt_dm_outbnd_id integer ENCODE az64,
    tgt_dm_activity_id integer ENCODE az64,
    tgt_dm_treatment_id integer ENCODE az64,
    tgt_dm_fund_key bigint ENCODE az64,
    tgt_dm_cell_src_cd character varying(20) ENCODE lzo,
    tgt_dm_cell_subsrc_cd character varying(40) ENCODE lzo,
    tgt_dm_gift_ind smallint ENCODE az64,
    tgt_dm_gift_amt numeric(13,2) ENCODE az64,
    tgt_dm_intrctn_dt date ENCODE az64,
    tgt_dm_intrctn_dt_key integer ENCODE az64,
    tgt_em_segementation_id integer ENCODE az64,
    tgt_em_outbnd_id integer ENCODE az64,
    tgt_em_activity_id integer ENCODE az64,
    tgt_em_treatment_id integer ENCODE az64,
    tgt_em_fund_key bigint ENCODE az64,
    tgt_em_cell_src_cd character varying(20) ENCODE lzo,
    tgt_em_cell_subsrc_cd character varying(40) ENCODE lzo,
    tgt_em_gift_ind smallint ENCODE az64,
    tgt_em_gift_amt numeric(13,2) ENCODE az64,
    tgt_em_intrctn_dt date ENCODE az64,
    tgt_em_intrctn_dt_key integer ENCODE az64,
    indrct_em_segementation_id integer ENCODE az64,
    indrct_em_outbnd_id integer ENCODE az64,
    indrct_em_activity_id integer ENCODE az64,
    indrct_em_treatment_id integer ENCODE az64,
    indrct_em_fund_key bigint ENCODE az64,
    indrct_em_donat_ind smallint ENCODE az64,
    indrct_em_cell_src_cd character varying(20) ENCODE lzo,
    indrct_em_cell_subsrc_cd character varying(40) ENCODE lzo,
    indrct_em_sent_dt date ENCODE az64,
    indrct_em_dt_key integer ENCODE az64,
    indrct_em_attrbtn_cnt smallint ENCODE az64,
    indrct_dm_segementation_id integer ENCODE az64,
    indrct_dm_outbnd_id integer ENCODE az64,
    indrct_dm_activity_id integer ENCODE az64,
    indrct_dm_treatment_id integer ENCODE az64,
    indrct_dm_fund_key bigint ENCODE az64,
    indrct_dm_donat_ind smallint ENCODE az64,
    indrct_attrbtn_ind smallint ENCODE az64,
    indrct_dm_cell_src_cd character varying(20) ENCODE lzo,
    indrct_dm_cell_subsrc_cd character varying(40) ENCODE lzo,
    indrct_dm_mailed_dt date ENCODE az64,
    indrct_dm_mailed_dt_key integer ENCODE az64,
    indrct_dm_attrbtn_cnt smallint ENCODE az64,
    acqstn_typ_cd character varying(3) ENCODE lzo,
    multi_indrct_attrib_ind smallint ENCODE az64,
    intrctn_dt date ENCODE raw,
    intrctn_atrbtn_typ_cd character varying(4) ENCODE lzo,
    intrctn_dt_key integer ENCODE az64,
    intrctn_segementation_id integer ENCODE az64,
    intrctn_outbnd_id integer ENCODE az64,
    intrctn_activity_id integer ENCODE az64,
    intrctn_treatment_id integer ENCODE az64,
    intrctn_fund_key bigint ENCODE az64,
    intrctn_attrbtn_ind smallint ENCODE az64,
    intrctn_cell_src_cd character varying(40) ENCODE lzo,
    intrctn_cell_subsrc_cd character varying(50) ENCODE lzo,
    dntn_fr_pmt_amt numeric(13,2) ENCODE az64,
    dntn_gift_dt date ENCODE az64,
    dntn_gift_dt_key integer ENCODE az64,
    orig_deposit_dt date ENCODE az64,
    orig_deposit_dt_key integer ENCODE az64,
    deposit_dt date ENCODE az64,
    deposit_dt_key integer ENCODE az64,
    recurring_ind integer ENCODE az64,
    recurng_start_dt timestamp without time zone ENCODE az64,
    soft_credit_ind smallint ENCODE az64,
    days_btwn_intrctn_txn_num integer ENCODE az64,
    first_dntn_ind integer ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( intrctn_dt );