CREATE TABLE mktg_ops_tbls.bzfc_fact_intrctn_em_smry (
    cnst_mstr_id bigint ENCODE az64,
    primary_cnst_mstr_id bigint ENCODE raw distkey,
    sent_hist_rec_id integer ENCODE az64,
    sent_hist_rec_ts timestamp without time zone ENCODE az64,
    eml_gen_run_id integer ENCODE az64,
    actvty_id integer ENCODE az64,
    actvty_ttl character varying(75) ENCODE lzo,
    sgmtn_id integer ENCODE az64,
    sgmtn_title character varying(75) ENCODE lzo,
    sgmt_id integer ENCODE az64,
    sgmt_title character varying(75) ENCODE lzo,
    outbnd_id integer ENCODE az64,
    outbnd_ttl character varying(200) ENCODE lzo,
    email_id integer ENCODE az64,
    sent_abstract character varying(500) ENCODE lzo,
    sent_dt date ENCODE az64,
    dlvrd_dt date ENCODE az64,
    to_email character varying(500) ENCODE lzo,
    to_domain character varying(175) ENCODE lzo,
    from_email character varying(500) ENCODE lzo,
    from_display_nm character varying(500) ENCODE lzo,
    reply_to_email character varying(500) ENCODE lzo,
    forwarding_email character varying(255) ENCODE lzo,
    is_forwarded_ind integer ENCODE az64,
    bounce_hist_rec_id integer ENCODE az64,
    asbounce_hist_rec_ts timestamp without time zone ENCODE az64,
    bncd_ctgy_id integer ENCODE az64,
    bncd_ctgy_ttl character varying(75) ENCODE lzo,
    bncd_subctgy_ttl character varying(2100) ENCODE lzo,
    bounce_abstract character varying(500) ENCODE lzo,
    remove_optout_form_id integer ENCODE az64,
    remove_optout_form_ttl character varying(75) ENCODE lzo,
    remove_abstract character varying(500) ENCODE lzo,
    remove_min_hist_rec_id integer ENCODE az64,
    remove_min_hist_rec_ts timestamp without time zone ENCODE az64,
    remove_max_hist_rec_id integer ENCODE az64,
    remove_max_hist_rec_ts timestamp without time zone ENCODE az64,
    open_tracking_hist_rec_id integer ENCODE az64,
    open_tracking_hist_rec_ts timestamp without time zone ENCODE az64,
    open_tracking_abstract character varying(500) ENCODE lzo,
    min_unsubscrb_dt date ENCODE az64,
    max_unsubscrb_dt date ENCODE az64,
    unsubscrb_min_hist_rec_id integer ENCODE az64,
    unsubscrb_max_hist_rec_id integer ENCODE az64,
    sent_ind smallint ENCODE az64,
    delivered_ind smallint ENCODE az64,
    bounced_ind smallint ENCODE az64,
    hard_bounce_ind smallint ENCODE az64,
    soft_bounce_ind smallint ENCODE az64,
    block_bounce_ind smallint ENCODE az64,
    technical_bounce_ind smallint ENCODE az64,
    unknown_bounce_ind smallint ENCODE az64,
    opened_ind smallint ENCODE az64,
    unique_render_ind smallint ENCODE az64,
    total_renders_cnt integer ENCODE az64,
    total_open_cnt integer ENCODE az64,
    removed_ind smallint ENCODE az64,
    spam_complnt_cnt integer ENCODE az64,
    spam_complnt_ind smallint ENCODE az64,
    unsbscrb_ind smallint ENCODE az64,
    unsbscrb_cnt integer ENCODE az64,
    total_click_cnt integer ENCODE az64,
    unique_click_cnt integer ENCODE az64,
    first_link_click_dt date ENCODE az64,
    last_link_click_dt date ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( primary_cnst_mstr_id );