CREATE TABLE mktg_ops_tbls.bzfc_sms_profile (
    src_mobile_num character varying(20) ENCODE lzo,
    mobile_num character varying(12) ENCODE lzo,
    time_zone_dsc character varying(20) ENCODE bytedict,
    ok_to_text_flg character varying(1) ENCODE lzo,
    active_carrier_nm character varying(34) ENCODE bytedict,
    active_create_ts timestamp without time zone ENCODE az64,
    active_status character varying(17) ENCODE lzo,
    active_source_typ character varying(14) ENCODE bytedict,
    active_source_nm character varying(26) ENCODE bytedict,
    active_status_dsc smallint ENCODE az64,
    active_opt_out_dt smallint ENCODE az64,
    active_opt_out_source smallint ENCODE az64,
    active_subscrbr_ind smallint ENCODE az64,
    unsbscrb_carrier_nm character varying(100) ENCODE lzo,
    unsbscrb_created_ts timestamp without time zone ENCODE az64,
    unsbscrb_status character varying(50) ENCODE lzo,
    unsbscrb_source_typ character varying(50) ENCODE lzo,
    unsbscrb_source_nm character varying(50) ENCODE lzo,
    unsbscrb_status_dsc character varying(50) ENCODE lzo,
    unsbscrb_opt_out_dt timestamp without time zone ENCODE az64,
    unsbscrb_opt_out_source character varying(50) ENCODE lzo,
    unsbscrb_ind smallint ENCODE az64,
    adobe_first_unsbscrb_ts timestamp without time zone ENCODE az64,
    adobe_first_unsbscrb_dt date ENCODE az64,
    adobe_last_unsbscrb_ts timestamp without time zone ENCODE az64,
    adobe_last_unsbscrb_dt date ENCODE az64,
    adobe_opt_out_ind smallint ENCODE az64,
    first_adobe_opt_in_ts timestamp without time zone ENCODE az64,
    first_adobe_opt_in_dt date ENCODE az64,
    last_adobe_opt_in_ts timestamp without time zone ENCODE az64,
    last_adobe_opt_in_dt date ENCODE az64,
    adobe_opt_in_ind smallint ENCODE az64,
    first_mc_opt_in_ts timestamp without time zone ENCODE az64,
    last_mc_opt_in_ts timestamp without time zone ENCODE az64,
    first_mc_opt_out_ts timestamp without time zone ENCODE az64,
    last_mc_opt_out_ts timestamp without time zone ENCODE az64,
    mc_opt_out_cnt integer ENCODE az64,
    first_rco_phn_opt_in_ts timestamp without time zone ENCODE az64,
    first_rco_phn_opt_in_dt date ENCODE az64,
    last_rco_phn_opt_in_ts timestamp without time zone ENCODE az64,
    last_rco_phn_opt_in_dt date ENCODE az64,
    rco_opt_in_cnt integer ENCODE az64,
    rco_opt_in_ind smallint ENCODE az64,
    major_donor_suprsn_ind smallint ENCODE az64,
    sf_green_mangd_acct_ind smallint ENCODE az64
)
DISTSTYLE AUTO;