CREATE TABLE mktg_ops_tbls.bzfc_fact_surv_resp (
    survey_key integer NOT NULL ENCODE az64,
    survey_start_dt_key integer ENCODE az64,
    survey_end_dt_key integer ENCODE az64,
    respondent_key integer ENCODE az64,
    unit_key integer ENCODE az64,
    unit_nm character varying(57) ENCODE lzo,
    cnst_mstr_id bigint ENCODE az64 distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    vol_key bigint ENCODE az64,
    nk_survey_start_ts timestamp without time zone ENCODE az64,
    nk_survey_end_ts timestamp without time zone ENCODE az64,
    nk_survey_start_dt date ENCODE az64,
    nk_survey_end_dt date ENCODE az64,
    zip_cd character varying(10) ENCODE lzo,
    cs_region_nm character varying(30) ENCODE lzo,
    division_dsc character varying(40) ENCODE lzo,
    wave_nmbr smallint ENCODE az64,
    volunteer_length character varying(50) ENCODE lzo,
    vol_area_blood_services smallint ENCODE az64,
    vol_area_community_services smallint ENCODE az64,
    vol_area_disaster_services smallint ENCODE az64,
    vol_area_fundraising_financial smallint ENCODE az64,
    vol_area_general_admin smallint ENCODE az64,
    vol_area_health_safety smallint ENCODE az64,
    vol_area_international smallint ENCODE az64,
    vol_area_leadership smallint ENCODE az64,
    vol_area_armed_forces smallint ENCODE az64,
    vol_area_volunteer smallint ENCODE az64,
    vol_area_youth smallint ENCODE az64,
    vol_area_other smallint ENCODE az64,
    vol_area_no_answer character varying(3) ENCODE lzo,
    rc_vol_experience_overal character varying(200) ENCODE lzo,
    recomdn_arc_2_org_or_volutr character varying(200) ENCODE lzo,
    a8_my_volun_2_arc_mission character varying(50) ENCODE lzo,
    b8_expect_of_me character varying(50) ENCODE lzo,
    c8_arc_training_prepared_me character varying(50) ENCODE lzo,
    d8_empl_volun_teamwork character varying(50) ENCODE lzo,
    e8_valued_member character varying(50) ENCODE lzo,
    f8_sprvsr_mgr_respect character varying(50) ENCODE lzo,
    g8_shared_vision_coworkers character varying(50) ENCODE lzo,
    h8_diverse_ideas_valued character varying(50) ENCODE lzo,
    i8_cont_as_arc_volun character varying(50) ENCODE lzo,
    l12mo_hrs_each_mo_volun character varying(100) ENCODE lzo,
    l12mo_have_you_donated_blood smallint ENCODE az64,
    l12mo_have_you_donated_money smallint ENCODE az64,
    l12mo_have_you_downloaded smallint ENCODE az64,
    l12mo_have_you_hlth_sfty_crse smallint ENCODE az64,
    l12mo_have_you_none smallint ENCODE az64,
    l12mo_have_you_no_answer smallint ENCODE az64,
    usefulness_of_volunteer_connec character varying(50) ENCODE lzo,
    usefulness_of_volunteer_connec2 character varying(50) ENCODE lzo,
    usefulness_of_volunteer_connec3 character varying(50) ENCODE lzo,
    tech_experience_computer character varying(50) ENCODE lzo,
    tech_experience_email character varying(50) ENCODE lzo,
    tech_experience_exchange character varying(50) ENCODE lzo,
    tech_experience_edge character varying(50) ENCODE lzo,
    unit_zip character varying(5) ENCODE lzo,
    unit_district_cd character varying(15) ENCODE lzo,
    unit_district_nm character varying(150) ENCODE lzo,
    geo_lat_lon_id character varying(150) ENCODE lzo,
    geo_centriod_lat numeric(13,6) ENCODE az64,
    geo_centriod_lon numeric(13,6) ENCODE az64
)
DISTSTYLE KEY;