CREATE TABLE mktg_ops_tbls.bzfc_bio_dnr_segment_dashbrd (
    region_key integer ENCODE zstd distkey,
    region_id character(5) ENCODE zstd,
    region_nm character varying(40) ENCODE zstd,
    division_cd character(4) ENCODE zstd,
    division_dsc character varying(30) ENCODE zstd,
    ldrshp_cd character(5) ENCODE zstd,
    ldrshp_nm character varying(100) ENCODE zstd,
    gender_cd character varying(20) ENCODE zstd,
    race_key integer ENCODE zstd,
    race_dsc character varying(40) ENCODE zstd,
    blood_type_key integer ENCODE zstd,
    abo character(3) ENCODE zstd,
    age_band_key integer ENCODE zstd,
    age_band_dsc character varying(10) ENCODE zstd,
    generation_segmnt_key integer ENCODE zstd,
    generation_segmnt_cd character varying(20) ENCODE zstd,
    generation_segmnt_dsc character varying(50) ENCODE zstd,
    life_stage_wb character varying(30) ENCODE zstd,
    drive_typ_wb character varying(20) ENCODE zstd,
    life_stage_2rc character varying(30) ENCODE zstd,
    drive_typ_2rc character varying(20) ENCODE zstd,
    life_stage_redcell_typ_cd character varying(20) ENCODE zstd,
    life_stage_redcell character varying(30) ENCODE zstd,
    drive_typ_redcell character varying(20) ENCODE zstd,
    life_stage_plasma character varying(30) ENCODE zstd,
    drive_typ_plasma character varying(20) ENCODE zstd,
    life_stage_plt character varying(30) ENCODE zstd,
    drive_typ_plt character varying(20) ENCODE zstd,
    life_stage_apheresis_typ_cd character varying(30) ENCODE zstd,
    life_stage_apheresis character varying(30) ENCODE zstd,
    drive_typ_apheresis character varying(20) ENCODE zstd,
    life_stage_current_typ_cd character varying(20) ENCODE zstd,
    life_stage_current character varying(30) ENCODE zstd,
    drive_typ_current character varying(20) ENCODE zstd,
    life_stage_sub_cat character varying(40) ENCODE zstd,
    life_stage_sub_cat_sort integer ENCODE zstd,
    any_chan_accessible_flg character varying(1) ENCODE zstd,
    em_chan_accessible_flg character varying(1) ENCODE zstd,
    dm_chan_accessible_flg character varying(1) ENCODE zstd,
    txt_chan_accessible_flg character varying(1) ENCODE zstd,
    phn_chan_accessible_flg character varying(1) ENCODE zstd,
    app_chan_accessible_flg character varying(1) ENCODE zstd,
    special_donor_notif_flg character varying(1) ENCODE zstd,
    sickle_cell_donor_flg character varying(1) ENCODE zstd,
    cmv_status character varying(30) ENCODE zstd,
    perm_defer_flg character varying(1) ENCODE zstd,
    red_cell_temp_defer_flg character varying(1) ENCODE zstd,
    cnst_cnt integer ENCODE zstd
)
DISTSTYLE KEY
SORTKEY ( region_id, division_cd, gender_cd );