CREATE TABLE mktg_ops_tbls.bzfc_fact_interaction_all (
    cnst_mstr_id bigint ENCODE zstd,
    primary_cnst_mstr_id bigint ENCODE zstd,
    cnst_hsld_id character varying(18) ENCODE zstd,
    cnst_comnictn_key bigint ENCODE zstd,
    comnictn_src_key bigint ENCODE zstd,
    comnictn_typ_key bigint ENCODE zstd,
    chan_typ_key bigint ENCODE zstd,
    unit_key integer ENCODE zstd,
    amt_typ_key integer ENCODE zstd,
    nk_tapg_comnictn_dt date ENCODE zstd,
    nk_tapg_comnictn_seq smallint ENCODE zstd,
    nk_tapg_comnictn_seq_page smallint ENCODE zstd,
    comnictn_dsc character varying(100) ENCODE zstd,
    cell_id integer ENCODE zstd,
    cell_src_cd character varying(20) ENCODE zstd,
    cell_subsrc_cd character varying(40) ENCODE zstd,
    motivtn_cd character varying(20) ENCODE zstd,
    fr_last_ta_acct_id integer ENCODE zstd,
    finder_num character varying(45) ENCODE zstd,
    offer_id integer ENCODE zstd,
    treatment_id integer ENCODE zstd,
    activity_id integer ENCODE zstd,
    segementation_id integer ENCODE zstd,
    segment_id integer ENCODE zstd,
    outbnd_id integer ENCODE zstd,
    email_id integer ENCODE zstd,
    email_sent_dt date ENCODE zstd,
    to_domain character varying(175) ENCODE zstd,
    drop_dt date ENCODE zstd,
    update_dt date ENCODE zstd,
    last_dntn_dt date ENCODE zstd,
    last_dntn_amt numeric(13,2) ENCODE zstd,
    chpt_affl character varying(150) ENCODE zstd,
    submitter_nm character varying(150) ENCODE zstd,
    chpt_id character varying(20) ENCODE zstd,
    cntct_dt date ENCODE zstd,
    run_dt date ENCODE zstd,
    run_id integer ENCODE zstd,
    mailed_ind smallint ENCODE zstd,
    supressed_ind smallint ENCODE zstd,
    mail_drop_cnt integer ENCODE zstd,
    src_seq_num integer ENCODE zstd,
    sub_src_seq_num integer ENCODE zstd,
    appl_src_cd character varying(4) ENCODE zstd,
    load_id integer ENCODE zstd,
    dw_trans_ts timestamp without time zone ENCODE zstd
)
DISTSTYLE ALL
SORTKEY ( primary_cnst_mstr_id );