CREATE TABLE mktg_ops_tbls.bzfc_cnst_cdi_phss_email_prfl (
    cnst_mstr_id bigint ENCODE lzo distkey,
    email_addr character varying(100) ENCODE lzo,
    ok_to_email_flg character varying(1) ENCODE lzo,
    sw_unsubscrb_cnt integer ENCODE lzo,
    sw_unsubscrb_flg character varying(1) ENCODE lzo,
    sw_bounce_cnt integer ENCODE lzo,
    sw_bounce_flg character varying(1) ENCODE lzo,
    mc_unsubscrb_cnt integer ENCODE lzo,
    mc_bounce_cnt integer ENCODE lzo,
    phsf_do_not_email_ind smallint ENCODE lzo,
    phsf_opt_out_ind smallint ENCODE lzo,
    phsf_hard_bounce_cnt integer ENCODE lzo,
    phsf_first_bounce_dt date ENCODE lzo,
    phsf_last_bounce_dt date ENCODE lzo,
    phsf_first_bounce_reason character varying(255) ENCODE lzo,
    phsf_last_bounce_reason character varying(255) ENCODE lzo,
    sfmc_total_bounce_cnt integer ENCODE lzo,
    sfmc_block_bounce_cnt integer ENCODE lzo,
    sfmc_hard_bounce_cnt integer ENCODE lzo,
    sfmc_soft_bounce_cnt integer ENCODE lzo,
    sfmc_technical_bounce_cnt integer ENCODE lzo,
    sfmc_unknown_bounce_cnt integer ENCODE lzo,
    sfmc_total_soft_bounce_cnt integer ENCODE lzo,
    sfmc_first_bounce_reason character varying(3000) ENCODE lzo,
    sfmc_last_bounce_reason character varying(3000) ENCODE lzo,
    sfmc_first_bounce_dt date ENCODE lzo,
    sfmc_last_bounce_dt date ENCODE lzo,
    sfmc_unsubscrb_cnt integer ENCODE lzo,
    sfmc_first_unsubscrb_dt date ENCODE lzo,
    sfmc_last_unsubscrb_dt date ENCODE lzo,
    sfmc_unsubscrb_click_cnt integer ENCODE lzo,
    unk_opt_out_ind smallint ENCODE lzo,
    first_spam_rejct_dt date ENCODE lzo,
    last_spam_rejct_dt date ENCODE lzo,
    spam_rejct_cnt integer ENCODE lzo,
    valdtn_status character varying(30) ENCODE lzo,
    valdtn_dt date ENCODE lzo,
    bad_domain_ind smallint ENCODE lzo,
    profile_last_update_dt date ENCODE lzo
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );