CREATE TABLE mktg_ops_tbls.bzfc_fact_dmail_interaction (
    cnst_mstr_id bigint ENCODE zstd distkey,
    orig_cnst_mstr_id bigint ENCODE zstd,
    recipient_key integer ENCODE zstd,
    nk_recipient_id integer ENCODE zstd,
    recipient_zip_cd character(5) ENCODE zstd,
    cnst_hsld_id character varying(18) ENCODE zstd,
    nk_intrctn_id integer ENCODE zstd,
    delivery_key integer ENCODE zstd,
    nk_delivery_id integer ENCODE zstd,
    campaign_key integer ENCODE zstd,
    nk_operation_id integer ENCODE zstd,
    src_key bigint ENCODE zstd,
    comnictn_src_key bigint ENCODE zstd,
    comnictn_typ_key bigint ENCODE zstd,
    chan_typ_key bigint ENCODE zstd,
    chan_typ_dsc character varying(50) ENCODE zstd,
    unit_key integer ENCODE zstd,
    nk_ecode character varying(5) ENCODE zstd,
    intrctn_status_key integer ENCODE zstd,
    nk_intrctn_status_dsc character varying(50) ENCODE zstd,
    treatmnt_key integer ENCODE zstd,
    nk_treatmnt_id integer ENCODE zstd,
    src_cd character varying(20) ENCODE zstd,
    subsrc_cd character varying(40) ENCODE zstd,
    file_cd character varying(10) ENCODE zstd,
    motivtn_cd character varying(20) ENCODE zstd,
    rpt_cell_cd_key integer ENCODE zstd,
    rpt_cell_cd_id integer ENCODE zstd,
    intrctn_dt_key integer ENCODE zstd,
    intrctn_dt date ENCODE zstd,
    list_run_dt_key integer ENCODE zstd,
    list_run_dt date ENCODE zstd,
    mail_drop1_dt date ENCODE zstd,
    mail_drop1_motivtn_cd character varying(20) ENCODE zstd,
    mail_drop2_dt date ENCODE zstd,
    mail_drop2_motivtn_cd character varying(20) ENCODE zstd,
    mail_drop3_dt date ENCODE zstd,
    mail_drop3_motivtn_cd character varying(20) ENCODE zstd,
    mail_drop4_dt date ENCODE zstd,
    mail_drop4_motivtn_cd character varying(20) ENCODE zstd,
    mail_drop5_dt date ENCODE zstd,
    mail_drop5_motivtn_cd character varying(20) ENCODE zstd,
    segmnt_key integer ENCODE zstd,
    nk_segmnt_cd character varying(50) ENCODE zstd,
    gen_segmnt_key integer ENCODE zstd,
    fr_last_ta_acct_id integer ENCODE zstd,
    offer_key integer ENCODE zstd,
    dm_locator_prsn_nm_key bigint ENCODE zstd,
    dm_locator_addr_key bigint ENCODE zstd,
    mailed_ind smallint ENCODE zstd,
    supressed_ind integer ENCODE zstd,
    finder_num character varying(20) ENCODE zstd,
    mail_drop_cnt integer ENCODE zstd,
    last_dntn_dt date ENCODE zstd,
    last_dntn_amt numeric(13,2) ENCODE zstd,
    dm_intrctn_ind smallint ENCODE zstd,
    target_tag_scr character varying(20) ENCODE zstd,
    vigintile smallint ENCODE zstd,
    mods_fr_scr numeric(13,4) ENCODE zstd,
    srcsys_trans_ts timestamp without time zone NOT NULL ENCODE zstd,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE zstd,
    row_stat_cd character(1) NOT NULL ENCODE zstd,
    appl_src_cd character varying(4) NOT NULL ENCODE zstd,
    load_id integer NOT NULL ENCODE zstd
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );