CREATE TABLE mktg_ops_tbls.bzfc_fact_interaction (
    cnst_mstr_id bigint NOT NULL ENCODE raw distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE az64,
    cnst_hsld_id character varying(18) ENCODE lzo,
    cell_id integer ENCODE az64,
    cell_src_cd character varying(20) ENCODE lzo,
    cell_subsrc_cd character varying(40) ENCODE lzo,
    fr_last_ta_acct_id integer ENCODE az64,
    offer_id integer ENCODE az64,
    treatment_id integer ENCODE az64,
    activity_id integer ENCODE az64,
    segementation_id integer ENCODE az64,
    segment_id integer ENCODE az64,
    outbnd_id integer ENCODE az64,
    email_id integer ENCODE az64,
    email_sent_dt date ENCODE az64,
    to_domain character varying(175) ENCODE lzo,
    drop_dt date ENCODE az64,
    update_dt date ENCODE az64,
    last_dntn_dt date ENCODE az64,
    last_dntn_amt numeric(13,2) ENCODE az64,
    chpt_affl character varying(150) ENCODE lzo,
    submitter_nm character varying(150) ENCODE lzo,
    chpt_id character varying(20) ENCODE lzo,
    cntct_dt date ENCODE az64,
    run_dt date ENCODE az64,
    run_id integer ENCODE az64,
    mailed_ind smallint ENCODE az64,
    supressed_ind smallint ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );