CREATE TABLE mktg_ops_tbls.cnst_cdi_smry_vms_prfr (
    cnst_mstr_id bigint ENCODE az64 distkey,
    cnst_hsld_id character varying(36) ENCODE lzo,
    cnst_arc_deceased_cd character(2) ENCODE lzo,
    dm_cnst_data_src_cd character varying(10) ENCODE lzo,
    dm_cnst_prsn_prfx_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_f_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_m_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_l_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_sfx_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_full_nm character varying(100) ENCODE lzo,
    dm_cnst_alias_in_saltn_nm character varying(120) ENCODE lzo,
    dm_cnst_alias_out_saltn_nm character varying(120) ENCODE lzo,
    dm_locator_addr_key bigint ENCODE az64,
    dm_cnst_addr_assessmnt_ctg character varying(40) ENCODE lzo,
    dpv_cd character varying(1) ENCODE lzo,
    dm_cnst_line_1_addr character varying(100) ENCODE lzo,
    dm_cnst_line_2_addr character varying(100) ENCODE lzo,
    dm_cnst_city_nm character varying(100) ENCODE lzo,
    dm_cnst_st_cd character(2) ENCODE lzo,
    dm_cnst_zip_5_cd character(5) ENCODE lzo,
    dm_cnst_zip_4_cd character(4) ENCODE lzo,
    dm_cnst_addr_county_nm character varying(100) ENCODE lzo,
    dm_cnst_email character varying(100) ENCODE lzo,
    dm_cnst_org_nm character varying(150) ENCODE lzo,
    dm_cnst_typ_dsc character varying(50) ENCODE lzo,
    em_cnst_data_src_cd character varying(10) ENCODE lzo,
    em_cnst_prsn_prfx_nm character varying(50) ENCODE lzo,
    em_cnst_prsn_f_nm character varying(200) ENCODE lzo,
    em_cnst_prsn_m_nm character varying(200) ENCODE lzo,
    em_cnst_prsn_l_nm character varying(150) ENCODE lzo,
    em_cnst_prsn_sfx_nm character varying(50) ENCODE lzo,
    em_cnst_prsn_full_nm character varying(502) ENCODE lzo,
    em_cnst_alias_in_saltn_nm character varying(120) ENCODE lzo,
    em_cnst_alias_out_saltn_nm character varying(120) ENCODE lzo,
    em_locator_addr_key bigint ENCODE az64,
    em_cnst_line_1_addr character varying(200) ENCODE lzo,
    em_cnst_line_2_addr character varying(200) ENCODE lzo,
    em_cnst_city_nm character varying(200) ENCODE lzo,
    em_cnst_st_cd character(200) ENCODE lzo,
    em_cnst_zip_5_cd character(5) ENCODE lzo,
    em_cnst_zip_4_cd character(4) ENCODE lzo,
    em_cnst_addr_county_nm character varying(100) ENCODE lzo,
    em_cnst_email character varying(200) ENCODE lzo,
    em_cnst_email_key bigint ENCODE az64,
    em_cnst_email_assessmnt_ctg character varying(128) ENCODE lzo,
    em_cnst_org_nm character varying(150) ENCODE lzo,
    em_cnst_typ_dsc character varying(50) ENCODE lzo,
    email_dlvrbl_ind integer ENCODE az64,
    prim_cnst_phn character varying(50) ENCODE lzo,
    prim_cnst_phn_source character varying(25) ENCODE lzo,
    prim_cnst_phn_typ_dsc character varying(5) ENCODE lzo,
    cnst_work_phn character varying(50) ENCODE lzo,
    cnst_work_phn_source character varying(25) ENCODE lzo,
    cnst_work_phn_typ_dsc character varying(20) ENCODE lzo,
    cnst_mbl_phn character varying(50) ENCODE lzo,
    cnst_mbl_phn_source character varying(25) ENCODE lzo,
    cnst_mbl_phn_typ_dsc character varying(20) ENCODE lzo,
    do_not_call_hm_phn_ind integer ENCODE az64,
    do_not_call_mbl_phn_ind integer ENCODE az64,
    do_not_call_work_phn_ind integer ENCODE az64,
    do_not_email_ind integer ENCODE az64,
    do_not_mail_ind integer ENCODE az64,
    do_not_txt_ind integer ENCODE az64,
    cnst_3rd_prty_segmtn_group_nm character varying(4) ENCODE lzo,
    unit_key integer ENCODE az64,
    affl_lock_ind integer ENCODE az64,
    unit_cd character varying(20) ENCODE lzo,
    vol_status character varying(1020) ENCODE lzo,
    status_typ character varying(1020) ENCODE lzo,
    last_member_num character varying(20) ENCODE lzo,
    initial_vol_dt date ENCODE az64,
    inactivation_reason_dsc character varying(1020) ENCODE lzo,
    ethnicity character varying(1020) ENCODE lzo,
    is_hispanic character varying(20) ENCODE lzo
)
DISTSTYLE KEY;