CREATE TABLE mktg_ops_tbls.cnst_cdi_smry_phss_prfr_stg (
    cnst_mstr_id bigint ENCODE az64 distkey,
    cnst_hsld_id character varying(36) ENCODE lzo,
    cnst_arc_deceased_cd character(2) ENCODE lzo,
    cnst_data_src_cd character varying(10) ENCODE lzo,
    dm_cnst_prsn_prfx_nm character varying(50) ENCODE lzo,
    cnst_prsn_f_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_m_nm character varying(50) ENCODE lzo,
    cnst_prsn_l_nm character varying(50) ENCODE lzo,
    dm_cnst_prsn_sfx_nm character varying(50) ENCODE lzo,
    locator_addr_key bigint ENCODE az64,
    cnst_addr_assessmnt_ctg character varying(40) ENCODE lzo,
    dpv_cd character varying(1) ENCODE lzo,
    cnst_addr_typ_cd character varying(5) ENCODE lzo,
    cnst_line_1_addr character varying(100) ENCODE lzo,
    cnst_line_2_addr character varying(100) ENCODE lzo,
    cnst_city_nm character varying(100) ENCODE lzo,
    cnst_st_cd character(2) ENCODE lzo,
    cnst_zip_5_cd character(5) ENCODE lzo,
    cnst_zip_4_cd character(4) ENCODE lzo,
    cnst_email character varying(100) ENCODE lzo,
    cnst_org_nm character varying(150) ENCODE lzo,
    cnst_typ_dsc character varying(50) ENCODE lzo,
    em_cnst_data_src_cd character varying(10) ENCODE lzo,
    em_cnst_prsn_prfx_nm character varying(150) ENCODE lzo,
    em_cnst_prsn_f_nm character varying(200) ENCODE lzo,
    em_cnst_prsn_m_nm character varying(150) ENCODE lzo,
    em_cnst_prsn_l_nm character varying(50) ENCODE lzo,
    em_cnst_prsn_sfx_nm character varying(150) ENCODE lzo,
    em_cnst_line_1_addr character varying(200) ENCODE lzo,
    em_cnst_line_2_addr character varying(200) ENCODE lzo,
    em_cnst_city_nm character varying(200) ENCODE lzo,
    em_cnst_st_cd character(200) ENCODE lzo,
    em_cnst_zip_5_cd character(5) ENCODE lzo,
    em_cnst_zip_4_cd character(4) ENCODE lzo,
    em_cnst_email character varying(200) ENCODE lzo,
    em_cnst_email_key bigint ENCODE az64,
    em_cnst_email_assessmnt_ctg character varying(128) ENCODE lzo,
    em_cnst_org_nm character varying(150) ENCODE lzo,
    em_cnst_typ_dsc character varying(50) ENCODE lzo,
    email_dlvrbl_ind integer ENCODE az64,
    prim_cnst_phn character varying(50) ENCODE lzo,
    prim_cnst_phn_source character varying(25) ENCODE lzo,
    prim_cnst_phn_typ_dsc character varying(20) ENCODE lzo,
    cnt_mobl_phn character varying(15) ENCODE lzo,
    cnst_mbl_typ_desc character varying(5) ENCODE lzo,
    phss_do_not_call_hm_phn_ind integer ENCODE az64,
    phss_do_not_call_mbl_phn_ind integer ENCODE az64,
    phss_do_not_call_work_phn_ind integer ENCODE az64,
    phss_do_not_email_ind integer ENCODE az64,
    phss_do_not_mail_ind integer ENCODE az64,
    phss_do_not_txt_ind integer ENCODE az64,
    cnt_tshrd_prty_sgmnt_grp_nm character varying(4) ENCODE lzo,
    unit_key integer ENCODE az64,
    unit_cd character(5) ENCODE lzo,
    mktg_unit_key integer ENCODE az64,
    mktg_unit_cd character(5) ENCODE lzo
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );