CREATE TABLE mktg_ops_tbls.dim_phone_campgn (
    campgn_id integer ENCODE zstd,
    campgn_cd character varying(10) ENCODE zstd,
    campgn_typ character varying(30) ENCODE zstd,
    campgn_dsc character varying(100) ENCODE zstd,
    program_typ character varying(30) ENCODE zstd,
    fyr integer ENCODE zstd,
    qtr smallint ENCODE zstd,
    start_dt date ENCODE zstd,
    end_dt date ENCODE zstd,
    billing_typ character varying(20) ENCODE zstd,
    bill_rate numeric(15,2) ENCODE zstd,
    rcrd_cnt integer ENCODE zstd,
    cmpltd_cnt integer ENCODE zstd,
    pldgd_gift_cnt integer ENCODE zstd,
    pldgd_rev_amt numeric(15,2) ENCODE zstd,
    flfld_gift_cnt integer ENCODE zstd,
    flfld_rev_amt numeric(15,2) ENCODE zstd,
    elctrnc_gift_cnt integer ENCODE zstd,
    elctrnc_gift_rev_amt numeric(15,2) ENCODE zstd,
    pldgd_rcrng_gift_cnt integer ENCODE zstd,
    pldgd_rcrng_gift_rev_amt numeric(15,2) ENCODE zstd,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE zstd,
    row_stat_cd character(1) NOT NULL ENCODE zstd,
    appl_src_cd character varying(4) NOT NULL ENCODE zstd,
    load_id integer NOT NULL ENCODE zstd,
    src_unq_row_id bigint ENCODE az64,
    src_file_name character varying(256) ENCODE lzo,
    etl_run_ts timestamp without time zone DEFAULT getdate() ENCODE az64,
    inserted_at timestamp without time zone DEFAULT getdate() ENCODE az64,
    updated_at timestamp without time zone ENCODE az64,
    row_hash_md5 character(32) ENCODE lzo,
    UNIQUE (campgn_cd),
    UNIQUE (campgn_cd)
)
DISTSTYLE AUTO
SORTKEY ( campgn_cd, dw_trans_ts );