CREATE TABLE mktg_ops_tbls.dim_region_rsmo (
    region_key integer ENCODE az64,
    division_cd character varying(10) ENCODE lzo,
    division_dsc character varying(100) ENCODE lzo,
    merge_region_nm character varying(150) ENCODE lzo,
    region_nm character varying(100) ENCODE lzo,
    nk_region_id character varying(10) ENCODE lzo,
    acct_nm character varying(150) ENCODE lzo,
    acct_ext_id character varying(20) ENCODE lzo,
    site_bldg character varying(150) ENCODE lzo,
    site_ext_id character varying(20) ENCODE lzo,
    site_addr1 character varying(200) ENCODE lzo,
    site_addr2 character varying(200) ENCODE lzo,
    site_city character varying(100) ENCODE lzo,
    site_state character varying(10) ENCODE lzo,
    site_zip character varying(20) ENCODE lzo,
    rsmo_dsc character varying(100) ENCODE lzo,
    rsmo_mnthly_dsc character varying(100) ENCODE lzo,
    rsmo_detail_dsc character varying(100) ENCODE lzo,
    rsmo_ind integer ENCODE az64,
    rsmo_typb_ind integer ENCODE az64,
    type_op_mfr character varying(50) ENCODE lzo,
    rbc_prod_proj_cnt integer ENCODE az64,
    rbc_prod_coll_cnt integer ENCODE az64,
    drive_cnt integer ENCODE az64,
    row_stat_cd character varying(5) ENCODE lzo,
    dw_trans_ts timestamp without time zone ENCODE az64,
    appl_src_cd character varying(10) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE AUTO;