CREATE TABLE mktg_ops_tbls.dim_odr (
    odr_key bigint NOT NULL ENCODE az64,
    ssi_odr_id character varying(20) NOT NULL ENCODE lzo,
    ship_to_prsn_key bigint NOT NULL ENCODE az64 distkey,
    billing_prsn_key bigint NOT NULL ENCODE az64,
    cntct_prsn_key bigint NOT NULL ENCODE az64,
    ship_to_org_key bigint ENCODE az64,
    billing_org_key bigint ENCODE az64,
    cntct_org_key bigint ENCODE az64,
    user_prfl_key bigint ENCODE az64,
    cart_key bigint ENCODE az64,
    odr_num character varying(30) ENCODE lzo,
    str_frnt_id integer ENCODE az64,
    str_frnt_nm character varying(50) ENCODE lzo,
    supplier_id integer ENCODE az64,
    pmt_mthd character varying(30) ENCODE lzo,
    requested_shipping_mthd character varying(255) ENCODE lzo,
    sub_totl_amt numeric(10,2) ENCODE az64,
    promotion_discount_amt numeric(10,2) ENCODE az64,
    tax_amt numeric(10,2) ENCODE az64,
    shipping_chrg_amt numeric(10,2) ENCODE az64,
    handling_chrg_amt numeric(10,2) ENCODE az64,
    odr_totl_amt numeric(10,2) ENCODE az64,
    rffrrl_user_id character varying(20) ENCODE lzo,
    rffrrl_user_key bigint ENCODE az64,
    guest_ind smallint ENCODE az64,
    ip_addr character varying(20) ENCODE lzo,
    user_agent character varying(1000) ENCODE lzo,
    cart_token character varying(50) ENCODE lzo,
    odr_create_ts timestamp without time zone NOT NULL ENCODE az64,
    odr_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    odr_create_dt_key bigint NOT NULL ENCODE az64,
    odr_update_dt_key bigint NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    appl_src_cd character(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY;