CREATE TABLE mktg_ops_tbls.dm_campaign_hist (
    cnst_mstr_id bigint NOT NULL ENCODE az64 distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE az64,
    fr_last_ta_acct_id bigint NOT NULL ENCODE az64,
    finder_number character varying(45) NOT NULL ENCODE lzo,
    chapt_id character varying(5) ENCODE lzo,
    greeting character varying(100) ENCODE lzo,
    personalization character varying(100) ENCODE lzo,
    ttl character varying(20) ENCODE lzo,
    first_nm character varying(30) ENCODE lzo,
    middle_nm character varying(30) ENCODE lzo,
    last_nm character varying(50) ENCODE lzo,
    suffix character varying(20) ENCODE lzo,
    full_nm character varying(100) ENCODE lzo,
    secondary_contact_nm character varying(100) ENCODE lzo,
    company_nm character varying(100) ENCODE lzo,
    addr_line1 character varying(50) ENCODE lzo,
    addr_line2 character varying(50) ENCODE lzo,
    city character varying(30) ENCODE lzo,
    state character varying(2) ENCODE lzo,
    zip_cd character varying(9) ENCODE lzo,
    delivery_pt character varying(2) ENCODE lzo,
    check_digit character varying(1) ENCODE lzo,
    carrier_rt character varying(4) ENCODE lzo,
    line_of_travel character varying(5) ENCODE lzo,
    combo_src_cd character varying(50) ENCODE lzo,
    country character varying(25) ENCODE lzo,
    largest_gift_dt_src character varying(256) ENCODE lzo,
    largest_gift_dt date ENCODE az64,
    largest_gift_amt numeric(13,2) ENCODE az64,
    last_gift_dt_src character varying(256) ENCODE lzo,
    last_gift_dt date ENCODE az64,
    last_gift_amt numeric(13,2) ENCODE az64,
    first_gift_dt_src character varying(256) ENCODE lzo,
    first_gift_dt date ENCODE az64,
    first_gift_amt numeric(13,2) ENCODE az64,
    lifetime_no_of_gifts integer ENCODE az64,
    motivtn_cd character varying(20) ENCODE lzo,
    kit character varying(2) ENCODE lzo,
    vrsn character varying(2) ENCODE lzo,
    ask1 character varying(9) ENCODE lzo,
    ask2 character varying(9) ENCODE lzo,
    ask3 character varying(9) ENCODE lzo,
    ask4 character varying(9) ENCODE lzo,
    ask5 character varying(9) ENCODE lzo,
    ask6 character varying(9) ENCODE lzo,
    provide1 character varying(30) ENCODE lzo,
    provide2 character varying(30) ENCODE lzo,
    provide3 character varying(30) ENCODE lzo,
    provide4 character varying(30) ENCODE lzo,
    provide5 character varying(30) ENCODE lzo,
    provide6 character varying(30) ENCODE lzo,
    cell_subsrc_cd character varying(40) ENCODE lzo,
    email_addr character varying(100) ENCODE lzo,
    treatmnt_dsc character varying(100) ENCODE lzo,
    segment_cd character varying(30) ENCODE lzo,
    treatment_cd_src character varying(30) ENCODE lzo,
    treatmnt_cd character varying(2) ENCODE lzo,
    aprm_src_cd character varying(55) ENCODE lzo,
    scanline_cd character varying(60) ENCODE lzo,
    drop_date_src character varying(256) ENCODE lzo,
    drop_dt date ENCODE raw,
    target_tag_scr character varying(20) ENCODE lzo,
    vigintile smallint ENCODE az64,
    mods_fr_scr numeric(13,4) ENCODE az64,
    csreg_code character varying(5) ENCODE lzo,
    file_cd character(4) ENCODE lzo,
    trans_typ_cd character varying(4) ENCODE lzo,
    vendor_src_cd character varying(4) ENCODE lzo,
    curr_prcsd_file_nm character varying(255) ENCODE lzo,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( drop_dt );