CREATE TABLE mktg_ops_tbls.dv_channel_accessibility_1 (
    cnst_arc_best_state character varying(50) ENCODE lzo,
    cnst_arc_best_gender character varying(15) ENCODE lzo,
    cnst_age_band character varying(11) ENCODE lzo,
    email_assessmnt_ctg character varying(20) ENCODE lzo,
    addr_assessmnt_ctg character varying(20) ENCODE lzo,
    phone_assessmnt_ctg character varying(20) ENCODE lzo,
    last_patrng_los character varying(20) ENCODE lzo,
    last_arc_patrng_yr integer ENCODE az64,
    last_bio_patrng_yr integer ENCODE az64,
    last_fr_patrng_yr integer ENCODE az64,
    last_phss_patrng_yr integer ENCODE az64,
    last_volntr_patrng_yr integer ENCODE az64,
    arc_patrng_life_stg character varying(30) ENCODE lzo,
    bio_patrng_life_stg character varying(30) ENCODE lzo,
    fr_patrng_life_stg character varying(30) ENCODE lzo,
    phss_patrng_life_stg character varying(30) ENCODE lzo,
    volntr_patrng_life_stg character varying(30) ENCODE lzo,
    bio_patrng_ind smallint ENCODE az64,
    fr_patrng_ind smallint ENCODE az64,
    phss_patrng_ind smallint ENCODE az64,
    volntr_patrng_ind smallint ENCODE az64,
    no_patrng_ind smallint ENCODE az64,
    active_bio_patrng_ind smallint ENCODE az64,
    active_fr_patrng_ind smallint ENCODE az64,
    active_phss_patrng_ind smallint ENCODE az64,
    active_volntr_patrng_ind smallint ENCODE az64,
    patrng_cnt integer ENCODE az64,
    active_patrng_cnt integer ENCODE az64,
    income_val_dsc character varying(30) ENCODE lzo,
    income_val_cd integer ENCODE az64,
    ln_verfd_ind smallint ENCODE az64,
    bz_app_chan_accessible_flg character varying(1) ENCODE lzo,
    bz_app_chan_accessible_ind smallint ENCODE az64,
    ext_email_valid_flg character varying(1) ENCODE lzo,
    ext_email_last_yr_valid_flg character varying(1) ENCODE lzo,
    in_blood_region_flg character varying(1) ENCODE lzo,
    do_not_phone_ind smallint ENCODE az64,
    do_not_email_ind smallint ENCODE az64,
    do_not_mail_ind smallint ENCODE az64,
    do_not_txt_ind smallint ENCODE az64,
    fr_ok_to_email_flg character varying(1) ENCODE lzo,
    phss_ok_to_email_flg character varying(1) ENCODE lzo,
    cnst_mstr_id bigint ENCODE raw distkey
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );