CREATE TABLE mktg_ops_tbls.dv_channel_accessibility (
    cnst_arc_best_state character varying(50) ENCODE bytedict,
    cnst_arc_best_gender character varying(14) ENCODE bytedict,
    cnst_age_band character varying(11) ENCODE bytedict,
    email_assessmnt_ctg character varying(128) ENCODE bytedict,
    addr_assessmnt_ctg character varying(128) ENCODE bytedict,
    phone_assessmnt_ctg character varying(128) ENCODE bytedict,
    last_patrng_los character varying(40) ENCODE bytedict,
    last_arc_patrng_yr integer ENCODE az64,
    last_bio_patrng_yr integer ENCODE az64,
    last_fr_patrng_yr integer ENCODE az64,
    last_phss_patrng_yr integer ENCODE az64,
    last_volntr_patrng_yr integer ENCODE az64,
    arc_patrng_life_stg character varying(17) ENCODE bytedict,
    bio_patrng_life_stg character varying(17) ENCODE bytedict,
    fr_patrng_life_stg character varying(17) ENCODE bytedict,
    phss_patrng_life_stg character varying(17) ENCODE lzo,
    vol_patrng_life_stg character varying(17) ENCODE lzo,
    bio_patrng_ind integer ENCODE az64,
    fr_patrng_ind integer ENCODE az64,
    phss_patrng_ind integer ENCODE az64,
    volntr_patrng_ind integer ENCODE az64,
    no_patrng_ind integer ENCODE az64,
    active_bio_patrng_ind integer ENCODE az64,
    active_fr_patrng_ind integer ENCODE az64,
    active_phss_patrng_ind integer ENCODE az64,
    active_volntr_patrng_ind integer ENCODE az64,
    patrng_cnt integer ENCODE az64,
    active_patrng_cnt integer ENCODE az64,
    ln_verfd_ind integer ENCODE az64,
    bz_app_chan_accessible_flg character varying(1) ENCODE lzo,
    bz_app_chan_accessible_ind integer ENCODE az64,
    ext_email_valid_flg character varying(1) ENCODE lzo,
    ext_email_last_yr_valid_flg character varying(1) ENCODE lzo,
    in_blood_region_flg character varying(1) ENCODE lzo,
    do_not_phone_ind integer ENCODE az64,
    do_not_email_ind integer ENCODE az64,
    do_not_mail_ind integer ENCODE az64,
    do_not_txt_ind integer ENCODE az64,
    fr_ok_to_email_flg character varying(1) ENCODE lzo,
    phss_ok_to_email_flg character varying(1) ENCODE lzo,
    cnst_mstr_id bigint ENCODE az64 distkey
)
DISTSTYLE AUTO;