CREATE TABLE mktg_ops_tbls.fact_email_interaction (
    cnst_mstr_id bigint ENCODE zstd,
    orig_cnst_mstr_id bigint ENCODE zstd,
    recipient_key integer ENCODE zstd,
    nk_recipient_id integer ENCODE zstd,
    recipient_zip_cd character(5) ENCODE zstd,
    cnst_hsld_id character varying(18) ENCODE zstd,
    nk_intrctn_id integer NOT NULL ENCODE zstd distkey,
    delivery_key integer ENCODE zstd,
    nk_delivery_id integer ENCODE zstd,
    campaign_key integer ENCODE zstd,
    nk_operation_id integer ENCODE zstd,
    comnictn_src_key bigint ENCODE zstd,
    comnictn_typ_key bigint ENCODE zstd,
    chan_typ_key bigint ENCODE zstd,
    chan_typ_dsc character varying(100) ENCODE zstd,
    unit_key integer ENCODE zstd,
    nk_ecode character varying(5) ENCODE zstd,
    mktg_unit_key integer ENCODE zstd,
    mktg_nk_ecode character varying(5) ENCODE zstd,
    intrctn_status_key integer ENCODE zstd,
    nk_intrctn_status_dsc character varying(200) ENCODE zstd,
    src_cd character varying(20) ENCODE zstd,
    subsrc_cd character varying(40) ENCODE zstd,
    intrctn_dt_key integer ENCODE zstd,
    intrctn_dt date ENCODE zstd,
    list_run_dt_key integer ENCODE zstd,
    list_run_dt date ENCODE zstd,
    segmnt_key integer ENCODE zstd,
    nk_segmnt_cd character varying(50) ENCODE zstd,
    gen_segmnt_key integer ENCODE zstd,
    fr_last_ta_acct_id integer ENCODE zstd,
    offer_key integer ENCODE zstd,
    email_id integer ENCODE zstd,
    email_addr character varying(128) ENCODE zstd,
    email_to_domain character varying(175) ENCODE zstd,
    last_dntn_dt date ENCODE zstd,
    last_dntn_amt numeric(13,2) ENCODE zstd,
    email_intrctn_ind smallint ENCODE zstd,
    srcsys_trans_ts timestamp without time zone ENCODE zstd,
    dw_trans_ts timestamp without time zone ENCODE zstd,
    row_stat_cd character(1) ENCODE zstd,
    appl_src_cd character varying(4) ENCODE zstd,
    load_id integer ENCODE zstd,
    PRIMARY KEY (nk_intrctn_id)
)
DISTSTYLE KEY
SORTKEY ( nk_intrctn_id );