CREATE TABLE mktg_ops_tbls.fact_vs_surv_resp (
    collector_key integer NOT NULL ENCODE az64,
    qstn_key integer NOT NULL ENCODE az64,
    respondent_key integer NOT NULL ENCODE az64,
    qstn_resp_ctgy_key integer NOT NULL ENCODE az64,
    survey_key integer NOT NULL ENCODE az64,
    survey_start_dt_key integer NOT NULL ENCODE az64,
    survey_end_dt_key integer NOT NULL ENCODE az64,
    unit_key integer NOT NULL ENCODE az64,
    vol_key integer NOT NULL ENCODE az64,
    cnst_mstr_id bigint NOT NULL ENCODE az64,
    orig_cnst_mstr_id bigint ENCODE az64,
    nk_collector_id character(10) ENCODE lzo,
    nk_ecode character(5) ENCODE lzo,
    nk_qstn_id numeric(10,2) ENCODE az64,
    nk_respondent_id character(10) ENCODE lzo,
    nk_resp_id smallint ENCODE az64,
    nk_qstn_ctgy_cd character(2) ENCODE lzo,
    nk_resp_ctgy_cd character(2) ENCODE lzo,
    nk_survey_id character(2) ENCODE lzo,
    nk_survey_start_ts timestamp without time zone ENCODE az64,
    nk_survey_end_ts timestamp without time zone ENCODE az64,
    nk_survey_start_dt date ENCODE az64,
    nk_survey_end_dt date ENCODE az64,
    zip_cd character varying(10) ENCODE lzo,
    cell_value_txt character varying(4000) ENCODE lzo,
    cell_value_txt_ff character varying(4000) ENCODE lzo,
    cell_value_num integer ENCODE az64,
    cell_value_ind smallint DEFAULT 0 ENCODE az64,
    er0_ind smallint DEFAULT 0 ENCODE az64,
    er1_ind smallint DEFAULT 0 ENCODE az64,
    er2_ind smallint DEFAULT 0 ENCODE az64,
    er3_ind smallint DEFAULT 0 ENCODE az64,
    er4_ind smallint DEFAULT 0 ENCODE az64,
    er5_ind smallint DEFAULT 0 ENCODE az64,
    er6_ind smallint DEFAULT 0 ENCODE az64,
    np0_ind smallint DEFAULT 0 ENCODE az64,
    np1_ind smallint DEFAULT 0 ENCODE az64,
    np2_ind smallint DEFAULT 0 ENCODE az64,
    np3_ind smallint DEFAULT 0 ENCODE az64,
    np4_ind smallint DEFAULT 0 ENCODE az64,
    np5_ind smallint DEFAULT 0 ENCODE az64,
    np6_ind smallint DEFAULT 0 ENCODE az64,
    np7_ind smallint DEFAULT 0 ENCODE az64,
    np8_ind smallint DEFAULT 0 ENCODE az64,
    np9_ind smallint DEFAULT 0 ENCODE az64,
    np10_ind smallint DEFAULT 0 ENCODE az64,
    ad1_0_ind smallint DEFAULT 0 ENCODE az64,
    ad1_1_ind smallint DEFAULT 0 ENCODE az64,
    ad1_2_ind smallint DEFAULT 0 ENCODE az64,
    ad1_3_ind smallint DEFAULT 0 ENCODE az64,
    ad1_4_ind smallint DEFAULT 0 ENCODE az64,
    ad1_5_ind smallint DEFAULT 0 ENCODE az64,
    ad1_6_ind smallint DEFAULT 0 ENCODE az64,
    nr_ind smallint DEFAULT 0 ENCODE az64,
    src_cell_value integer ENCODE az64,
    surv_inst_id integer ENCODE az64,
    surv_src_cd character(2) NOT NULL ENCODE lzo,
    srcsys_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_create_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo,
    appl_src_cd character(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE AUTO;