CREATE TABLE mktg_ops_tbls.gms_bzfc_adb_fact_donation (
    cnst_mstr_id bigint ENCODE az64 distkey,
    unf_fr_cnst_key bigint ENCODE az64,
    recipient_key integer ENCODE az64,
    giftran_key bigint ENCODE az64,
    arc_fr_txn_seq_num integer ENCODE az64,
    alt_trans_id character varying(40) ENCODE lzo,
    gift_src_key bigint ENCODE az64,
    gift_src_cd character varying(40) ENCODE lzo,
    campgn_src_key bigint ENCODE az64,
    campgn_src_cd character varying(40) ENCODE lzo,
    gift_subsrc_cd character varying(50) ENCODE lzo,
    channel_typ_key bigint ENCODE az64,
    nk_ta_nm_id integer ENCODE az64,
    fr_affl_unit_key integer ENCODE az64,
    gen_segmnt_key integer ENCODE az64,
    non_tgt_gift_ind smallint ENCODE az64,
    non_tgt_gift_amt numeric(13,2) ENCODE az64,
    non_tgt_dm_gift_ind smallint ENCODE az64,
    non_tgt_dm_gift_amt numeric(13,2) ENCODE az64,
    non_tgt_em_gift_ind smallint ENCODE az64,
    non_tgt_em_gift_amt numeric(13,2) ENCODE az64,
    non_tgt_delivery_key integer ENCODE az64,
    non_tgt_campaign_key integer ENCODE az64,
    non_tgt_treatment_key integer ENCODE az64,
    non_tgt_fund_key bigint ENCODE az64,
    non_tgt_src_cd character varying(20) ENCODE lzo,
    non_tgt_subsrc_cd character varying(40) ENCODE lzo,
    non_tgt_intrctn_dt date ENCODE az64,
    non_tgt_intrctn_dt_key integer ENCODE az64,
    non_tgt_drop_dt date ENCODE az64,
    non_tgt_drop_dt_key integer ENCODE az64,
    non_tgt_mail_drop_num integer ENCODE az64,
    tgt_dm_delivery_key integer ENCODE az64,
    tgt_dm_campaign_key integer ENCODE az64,
    tgt_dm_treatment_key integer ENCODE az64,
    tgt_dm_fund_key bigint ENCODE az64,
    tgt_dm_src_cd character varying(20) ENCODE lzo,
    tgt_dm_subsrc_cd character varying(40) ENCODE lzo,
    tgt_dm_file_cd character varying(10) ENCODE lzo,
    tgt_dm_motivtn_cd character varying(20) ENCODE lzo,
    tgt_dm_rpt_cell_cd_key integer ENCODE az64,
    tgt_dm_gift_ind smallint ENCODE az64,
    tgt_dm_gift_amt numeric(13,2) ENCODE az64,
    tgt_dm_intrctn_dt date ENCODE az64,
    tgt_dm_intrctn_dt_key integer ENCODE az64,
    tgt_dm_drop_dt date ENCODE az64,
    tgt_dm_drop_dt_key integer ENCODE az64,
    tgt_dm_mail_drop_num integer ENCODE az64,
    tgt_em_delivery_key integer ENCODE az64,
    tgt_em_campaign_key integer ENCODE az64,
    tgt_em_treatment_key integer ENCODE az64,
    tgt_em_fund_key bigint ENCODE az64,
    tgt_em_src_cd character varying(20) ENCODE lzo,
    tgt_em_subsrc_cd character varying(40) ENCODE lzo,
    tgt_em_email_launch_dt date ENCODE az64,
    tgt_em_email_segmnt_key integer ENCODE az64,
    tgt_em_active_email_segment_ind smallint ENCODE az64,
    tgt_em_gift_ind smallint ENCODE az64,
    tgt_em_gift_amt numeric(13,2) ENCODE az64,
    tgt_em_intrctn_dt date ENCODE az64,
    tgt_em_intrctn_dt_key integer ENCODE az64,
    indrct_em_delivery_key integer ENCODE az64,
    indrct_em_campaign_key integer ENCODE az64,
    indrct_em_treatment_key integer ENCODE az64,
    indrct_em_fund_key bigint ENCODE az64,
    indrct_em_donat_ind smallint ENCODE az64,
    indrct_em_src_cd character varying(20) ENCODE lzo,
    indrct_em_subsrc_cd character varying(40) ENCODE lzo,
    indrct_em_sent_dt date ENCODE az64,
    indrct_em_email_launch_dt date ENCODE az64,
    indrct_em_email_segmnt_key integer ENCODE az64,
    indrct_em_dt_key integer ENCODE az64,
    indrct_em_attrbtn_cnt smallint ENCODE az64,
    indrct_dm_delivery_key integer ENCODE az64,
    indrct_dm_campaign_key integer ENCODE az64,
    indrct_dm_treatment_key integer ENCODE az64,
    indrct_dm_fund_key bigint ENCODE az64,
    indrct_dm_donat_ind smallint ENCODE az64,
    indrct_attrbtn_ind smallint ENCODE az64,
    indrct_dm_src_cd character varying(20) ENCODE bytedict,
    indrct_dm_subsrc_cd character varying(40) ENCODE lzo,
    indrct_dm_file_cd character varying(10) ENCODE lzo,
    indrct_dm_motivtn_cd character varying(20) ENCODE lzo,
    indrct_dm_rpt_cell_cd_key integer ENCODE az64,
    indrct_dm_mailed_dt date ENCODE az64,
    indrct_dm_mailed_dt_key integer ENCODE az64,
    indrct_dm_drop_dt date ENCODE az64,
    indrct_dm_drop_dt_key integer ENCODE az64,
    indrct_mail_drop_num integer ENCODE az64,
    indrct_dm_attrbtn_cnt integer ENCODE az64,
    acqstn_typ_cd character varying(3) ENCODE lzo,
    multi_indrct_attrib_ind smallint ENCODE az64,
    intrctn_dt date ENCODE az64,
    intrctn_atrbtn_typ_cd character varying(4) ENCODE lzo,
    intrctn_dt_key integer ENCODE az64,
    intrctn_delivery_key integer ENCODE az64,
    intrctn_campaign_key integer ENCODE az64,
    intrctn_treatment_key integer ENCODE az64,
    intrctn_fund_key bigint ENCODE az64,
    intrctn_attrbtn_ind smallint ENCODE az64,
    intrctn_src_key bigint ENCODE az64,
    intrctn_src_cd character varying(20) ENCODE lzo,
    intrctn_subsrc_cd character varying(50) ENCODE lzo,
    intrctn_file_cd character varying(10) ENCODE lzo,
    intrctn_motivtn_cd character varying(20) ENCODE lzo,
    intrctn_rpt_cell_cd_key integer ENCODE az64,
    intrctn_email_launch_dt date ENCODE az64,
    intrctn_email_segmnt_key integer ENCODE az64,
    intrctn_drop_dt date ENCODE az64,
    intrctn_drop_dt_key integer ENCODE az64,
    intrctn_mail_drop_num integer ENCODE az64,
    dntn_fr_pmt_amt numeric(13,2) ENCODE az64,
    dntn_gift_dt date ENCODE az64,
    dntn_gift_dt_key integer ENCODE az64,
    orig_deposit_dt date ENCODE az64,
    orig_deposit_dt_key integer ENCODE az64,
    deposit_dt date ENCODE az64,
    deposit_dt_key integer ENCODE az64,
    recurring_ind integer ENCODE az64,
    recurng_start_dt timestamp without time zone ENCODE az64,
    online_channel_cd character varying(40) ENCODE lzo,
    soft_credit_ind smallint ENCODE az64,
    fr_trans_cnst_zip_cd character varying(5) ENCODE lzo,
    trans_fund_key integer ENCODE az64,
    trans_fund_cd character varying(40) ENCODE lzo,
    trans_fund_dsc character varying(150) ENCODE lzo,
    trans_email_segmnt_key integer ENCODE az64,
    days_btwn_intrctn_txn_num integer ENCODE az64,
    first_dntn_ind integer ENCODE az64,
    referral_source character varying(100) ENCODE lzo,
    referral_medium character varying(300) ENCODE lzo,
    referral_campaign character varying(100) ENCODE lzo,
    referral_device character varying(25) ENCODE lzo,
    referral_lst_touch_chnl character varying(25) ENCODE lzo
)
DISTSTYLE KEY
SORTKEY ( dntn_gift_dt );