CREATE TABLE mktg_ops_tbls.gms_arc_fr_txn (
    cnst_mstr_id bigint NOT NULL ENCODE az64,
    giftran_key bigint NOT NULL ENCODE az64,
    gift_cnst_grp_key bigint NOT NULL ENCODE az64,
    nk_gift_id character varying(20) ENCODE lzo,
    dim_giftran_key bigint ENCODE az64,
    alt_trans_id character varying(40) ENCODE lzo,
    bzd_unique_trans_id character varying(100) ENCODE lzo,
    ta_acct_id bigint ENCODE az64,
    nk_ta_gift_seq integer ENCODE az64,
    nk_sf_gift_id character varying(20) ENCODE lzo,
    gift_versn numeric(6,4) ENCODE az64,
    gift_num character varying(20) ENCODE lzo,
    gift_tran_typ_key integer ENCODE az64,
    pmt_mthd_key bigint ENCODE az64,
    dntn_chan_key bigint ENCODE az64,
    sustnr_typ_key integer ENCODE az64,
    gift_rec_dt_key integer ENCODE az64,
    gift_rec_dt date ENCODE az64,
    dntn_gift_dt_key integer ENCODE az64,
    dntn_gift_dt date ENCODE az64,
    released_dt_key integer ENCODE az64,
    released_dt date ENCODE az64,
    orig_released_dt_key integer ENCODE az64,
    orig_released_dt date ENCODE az64,
    deposit_dt_key integer ENCODE az64,
    deposit_dt date ENCODE az64,
    orig_deposit_dt_key integer ENCODE az64,
    orig_deposit_dt date ENCODE az64,
    gift_appl_src_cd character varying(10) ENCODE lzo,
    pmt_typ_key bigint ENCODE az64,
    email_segmnt_key integer ENCODE az64,
    channel_typ_key bigint ENCODE az64,
    online_channel_key integer ENCODE az64,
    online_channel_cd character varying(40) ENCODE lzo,
    txn_channel character varying(255) ENCODE lzo,
    gl_debit_acct_key bigint ENCODE az64,
    gl_credit_acct_key bigint ENCODE az64,
    trans_fund_key integer ENCODE az64,
    trans_fund_cd character varying(40) ENCODE lzo,
    trans_fund_dsc character varying(150) ENCODE lzo,
    giftran_src_key integer ENCODE az64,
    gift_src_key integer ENCODE az64,
    orig_gift_src_key integer ENCODE az64,
    gift_src_cd character varying(20) ENCODE lzo,
    gift_sub_src_cd character varying(100) ENCODE lzo,
    campgn_src_key integer ENCODE az64,
    orig_campgn_src_key integer ENCODE az64,
    campgn_src_cd character varying(20) ENCODE lzo,
    gift_src_dsc character varying(100) ENCODE lzo,
    treatmnt_key integer ENCODE az64,
    treatmnt_cd character varying(50) ENCODE lzo,
    fr_affl_unit_key integer ENCODE az64,
    gift_amt_tier_key integer ENCODE az64,
    fr_affl_cd character varying(5) ENCODE lzo,
    gift_trbt_key bigint DEFAULT 0 ENCODE az64,
    gift_trbt_typ_cd character varying(20) ENCODE lzo,
    gift_trbt_typ_dsc character varying(100) ENCODE lzo,
    gift_trbt_nm character varying(300) ENCODE lzo,
    gift_trbt_from character varying(300) ENCODE lzo,
    giftran_typ_dsc character varying(150) ENCODE lzo,
    vendor_key integer ENCODE az64,
    merchant_key integer ENCODE az64,
    sc_affl_unit_key integer ENCODE az64,
    sc_affl_unit_cd character varying(5) ENCODE lzo,
    dim_gift_sku_key bigint DEFAULT 0 ENCODE az64 distkey,
    dim_gift_premium_key bigint DEFAULT 0 ENCODE az64,
    cnvo_cnst_id character varying(20) ENCODE lzo,
    fr_merchant_id character varying(100) ENCODE lzo,
    fcc_key bigint ENCODE az64,
    prog_key bigint ENCODE az64,
    derived_channel character varying(30) ENCODE lzo,
    cnst_typ_cd character varying(4) ENCODE lzo,
    rco_dntn_id character varying(765) ENCODE lzo,
    rco_subscription_id character varying(765) ENCODE lzo,
    subscription_id character varying(765) ENCODE lzo,
    gift_grp_id character varying(20) ENCODE lzo,
    recurng_start_dt timestamp without time zone ENCODE az64,
    recurring_ind integer ENCODE az64,
    fr_distr_dntn_ind smallint ENCODE az64,
    fr_impctd_area_dntn_ind smallint ENCODE az64,
    active_ind smallint ENCODE az64,
    ack_ind smallint ENCODE az64,
    thankyou_ind smallint ENCODE az64,
    soft_credit_ind smallint ENCODE az64,
    gift_anon_ind smallint ENCODE az64,
    split_gift_ind smallint ENCODE az64,
    trbt_gift_ind smallint ENCODE az64,
    installment_ind smallint ENCODE az64,
    confidence_ind smallint ENCODE az64,
    gift_ask_mult_lnk_ind smallint DEFAULT 0 ENCODE az64,
    dnr_geogrphc_intrst_local_ind smallint ENCODE az64,
    gift_in_care_of_ind smallint ENCODE az64,
    evnt_benefit_ind smallint ENCODE az64,
    conv_trans_ind smallint ENCODE az64,
    ta_trans_ind smallint ENCODE az64,
    do_not_feed_gl_ind smallint ENCODE az64,
    adj_ind smallint ENCODE az64,
    bdgt_rlvng_ind smallint ENCODE az64,
    released_ind smallint ENCODE az64,
    manual_entry_ind smallint ENCODE az64,
    reject_ind smallint ENCODE az64,
    misdirected_ind smallint ENCODE az64,
    vsblty_ind smallint ENCODE az64,
    fr_credit_ind smallint ENCODE az64,
    prior_prd_ind smallint ENCODE az64,
    gl_override_ind smallint ENCODE az64,
    stock_gift_ind smallint ENCODE az64,
    inkind_gift_ind smallint ENCODE az64,
    dnr_adv_gift_ind smallint ENCODE az64,
    episodic_gift_ind smallint ENCODE az64,
    fmd_txn_ind smallint ENCODE az64,
    prvt_ind smallint ENCODE az64,
    fr_pmt_amt numeric(13,2) ENCODE az64,
    totl_gift_amt numeric(13,2) ENCODE az64,
    gift_exps_amt numeric(13,2) ENCODE az64,
    arc_fr_txn_seq_num integer ENCODE az64,
    dntn_entity_url character varying(765) ENCODE lzo,
    srcsys_create_ts timestamp without time zone ENCODE az64,
    srcsys_update_ts timestamp without time zone ENCODE az64,
    trans_update_dt date ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY;