CREATE TABLE mktg_ops_tbls.gms_bzfc_fact_email_intrctn_smry (
    cnst_mstr_id bigint ENCODE az64 distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    nk_recipient_id integer ENCODE az64,
    recipient_zip_cd character(5) ENCODE lzo,
    nk_intrctn_id integer ENCODE az64,
    delivery_key integer ENCODE az64,
    campaign_key integer ENCODE az64,
    src_key bigint ENCODE az64,
    comnictn_src_key bigint ENCODE az64,
    chan_typ_key bigint ENCODE az64,
    gen_segmnt_key integer ENCODE az64,
    unit_key integer ENCODE az64,
    nk_ecode character varying(5) ENCODE lzo,
    intrctn_status_key integer ENCODE az64,
    src_cd character varying(20) ENCODE bytedict,
    subsrc_cd character varying(40) ENCODE lzo,
    intrctn_dt_key integer ENCODE az64,
    intrctn_dt date ENCODE az64,
    email_addr character varying(128) ENCODE lzo,
    email_to_domain character varying(175) ENCODE lzo,
    email_launch_dt date ENCODE az64,
    email_sent_ind smallint ENCODE az64,
    email_failed_ind smallint ENCODE az64,
    email_pending_ind smallint ENCODE az64,
    email_sent_cnt integer ENCODE az64,
    email_failed_cnt integer ENCODE az64,
    email_pending_cnt integer ENCODE az64,
    email_total_cnt integer ENCODE az64,
    email_open_ind smallint ENCODE az64,
    email_open_cnt integer ENCODE az64,
    first_email_open_dt timestamp without time zone ENCODE az64,
    last_email_open_dt timestamp without time zone ENCODE az64,
    email_link_click_ind smallint ENCODE az64,
    distinct_url_click_ind smallint ENCODE az64,
    email_link_click_cnt integer ENCODE az64,
    distinct_url_click_cnt integer ENCODE az64,
    first_link_click_dt timestamp without time zone ENCODE az64,
    last_link_click_dt timestamp without time zone ENCODE az64,
    unsbscrb_ind smallint ENCODE az64,
    unsbscrb_click_cnt integer ENCODE az64,
    first_unsbscrb_dt timestamp without time zone ENCODE az64,
    last_unsbscrb_dt timestamp without time zone ENCODE az64,
    mirror_page_click_cnt integer ENCODE az64,
    mirror_page_click_ind smallint ENCODE az64,
    email_bounce_ind smallint ENCODE az64,
    fbl_ind smallint ENCODE az64,
    hard_bounce_ind smallint ENCODE az64,
    soft_bounce_ind smallint ENCODE az64,
    fbl_cnt integer ENCODE az64,
    hard_bounce_cnt integer ENCODE az64,
    soft_bounce_cnt integer ENCODE az64,
    total_bounce_cnt integer ENCODE az64,
    first_bounce_dt timestamp without time zone ENCODE az64,
    last_bounce_dt timestamp without time zone ENCODE az64,
    last_dntn_gift_dt date ENCODE az64,
    email_segmnt_key smallint ENCODE az64,
    email_segmnt_dsc character varying(21) ENCODE lzo,
    active_email_segment_ind smallint ENCODE az64
)
DISTSTYLE AUTO;