CREATE TABLE mktg_ops_tbls.gms_arc_fr_smry_sustnr (
    cnst_mstr_id bigint ENCODE az64 distkey,
    cy0_year_dsc integer ENCODE az64,
    cy0_first_offline_sustnr_gift_dt date ENCODE az64,
    cy0_last_offline_sustnr_gift_dt date ENCODE az64,
    cy0_offline_sustnr_gift_cnt integer ENCODE az64,
    cy0_offline_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy1_year_dsc integer ENCODE az64,
    cy1_first_offline_sustnr_gift_dt date ENCODE az64,
    cy1_last_offline_sustnr_gift_dt date ENCODE az64,
    cy1_offline_sustnr_gift_cnt integer ENCODE az64,
    cy1_offline_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy2_year_dsc integer ENCODE az64,
    cy2_first_offline_sustnr_gift_dt date ENCODE az64,
    cy2_last_offline_sustnr_gift_dt date ENCODE az64,
    cy2_offline_sustnr_gift_cnt integer ENCODE az64,
    cy2_offline_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy0_first_online_sustnr_gift_dt date ENCODE az64,
    cy0_last_online_sustnr_gift_dt date ENCODE az64,
    cy0_online_sustnr_gift_cnt integer ENCODE az64,
    cy0_online_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy1_first_online_sustnr_gift_dt date ENCODE az64,
    cy1_last_online_sustnr_gift_dt date ENCODE az64,
    cy1_online_sustnr_gift_cnt integer ENCODE az64,
    cy1_online_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy2_first_online_sustnr_gift_dt date ENCODE az64,
    cy2_last_online_sustnr_gift_dt date ENCODE az64,
    cy2_online_sustnr_gift_cnt integer ENCODE az64,
    cy2_online_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy0_first_phone_sustnr_gift_dt date ENCODE az64,
    cy0_last_phone_sustnr_gift_dt date ENCODE az64,
    cy0_phone_sustnr_gift_cnt integer ENCODE az64,
    cy0_phone_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy1_first_phone_sustnr_gift_dt date ENCODE az64,
    cy1_last_phone_sustnr_gift_dt date ENCODE az64,
    cy1_phone_sustnr_gift_cnt integer ENCODE az64,
    cy1_phone_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy2_first_phone_sustnr_gift_dt date ENCODE az64,
    cy2_last_phone_sustnr_gift_dt date ENCODE az64,
    cy2_phone_sustnr_gift_cnt integer ENCODE az64,
    cy2_phone_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy0_first_othr_sustnr_gift_dt date ENCODE az64,
    cy0_last_othr_sustnr_gift_dt date ENCODE az64,
    cy0_othr_sustnr_gift_cnt integer ENCODE az64,
    cy0_othr_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy1_first_othr_sustnr_gift_dt date ENCODE az64,
    cy1_last_othr_sustnr_gift_dt date ENCODE az64,
    cy1_othr_sustnr_gift_cnt integer ENCODE az64,
    cy1_othr_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy2_first_othr_sustnr_gift_dt date ENCODE az64,
    cy2_last_othr_sustnr_gift_dt date ENCODE az64,
    cy2_othr_sustnr_gift_cnt integer ENCODE az64,
    cy2_othr_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy0_first_f2f_sustnr_gift_dt date ENCODE az64,
    cy0_last_f2f_sustnr_gift_dt date ENCODE az64,
    cy0_f2f_sustnr_gift_cnt integer ENCODE az64,
    cy0_f2f_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy1_first_f2f_sustnr_gift_dt date ENCODE az64,
    cy1_last_f2f_sustnr_gift_dt date ENCODE az64,
    cy1_f2f_sustnr_gift_cnt integer ENCODE az64,
    cy1_f2f_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy2_first_f2f_sustnr_gift_dt date ENCODE az64,
    cy2_last_f2f_sustnr_gift_dt date ENCODE az64,
    cy2_f2f_sustnr_gift_cnt integer ENCODE az64,
    cy2_f2f_sustnr_gift_amt numeric(15,2) ENCODE az64,
    cy0_offline_sustainer_ind smallint ENCODE az64,
    cy0_offline_sustainer_flg character varying(1) ENCODE lzo,
    cy1_offline_sustainer_ind smallint ENCODE az64,
    cy1_offline_sustainer_flg character varying(1) ENCODE lzo,
    cy2_offline_sustainer_ind smallint ENCODE az64,
    cy2_offline_sustainer_flg character varying(1) ENCODE lzo,
    cy0_online_sustainer_ind smallint ENCODE az64,
    cy0_online_sustainer_flg character varying(1) ENCODE lzo,
    cy1_online_sustainer_ind smallint ENCODE az64,
    cy1_online_sustainer_flg character varying(1) ENCODE lzo,
    cy2_online_sustainer_ind smallint ENCODE az64,
    cy2_online_sustainer_flg character varying(1) ENCODE lzo,
    cy0_phone_sustainer_ind smallint ENCODE az64,
    cy0_phone_sustainer_flg character varying(1) ENCODE lzo,
    cy1_phone_sustainer_ind smallint ENCODE az64,
    cy1_phone_sustainer_flg character varying(1) ENCODE lzo,
    cy2_phone_sustainer_ind smallint ENCODE az64,
    cy2_phone_sustainer_flg character varying(1) ENCODE lzo,
    cy0_othr_sustainer_ind smallint ENCODE az64,
    cy0_othr_sustainer_flg character varying(1) ENCODE lzo,
    cy1_othr_sustainer_ind smallint ENCODE az64,
    cy1_othr_sustainer_flg character varying(1) ENCODE lzo,
    cy2_othr_sustainer_ind smallint ENCODE az64,
    cy2_othr_sustainer_flg character varying(1) ENCODE lzo,
    cy0_f2f_sustainer_ind smallint ENCODE az64,
    cy0_f2f_sustainer_flg character varying(1) ENCODE lzo,
    cy1_f2f_sustainer_ind smallint ENCODE az64,
    cy1_f2f_sustainer_flg character varying(1) ENCODE lzo,
    cy2_f2f_sustainer_ind smallint ENCODE az64,
    cy2_f2f_sustainer_flg character varying(1) ENCODE lzo,
    current_sustnr_ind smallint ENCODE az64,
    cy0_sustainer_ind smallint ENCODE az64,
    cy1_sustainer_ind smallint ENCODE az64,
    cy2_sustainer_ind smallint ENCODE az64,
    first_sustnr_dt date ENCODE az64,
    first_sustnr_gift_amt numeric(13,2) ENCODE az64,
    last_sustnr_dt date ENCODE az64,
    last_sustnr_gift_amt numeric(13,2) ENCODE az64
)
DISTSTYLE KEY;