CREATE TABLE mktg_ops_tbls.gms_cnst_cdi_smry_fr_prfr_stg (
    cnst_mstr_id bigint ENCODE zstd distkey,
    cnst_hsld_id character varying(18) ENCODE zstd,
    cnst_arc_deceased_cd character(1) ENCODE zstd,
    dm_prsn_nm_src_cd character varying(10) ENCODE zstd,
    dm_cnst_data_src_cd character varying(10) ENCODE zstd,
    dm_locator_prsn_nm_key bigint ENCODE zstd,
    dm_cnst_prsn_nm_assessmnt_ctg character varying(40) ENCODE zstd,
    dm_cnst_prsn_prfx_nm character varying(50) ENCODE zstd,
    dm_cnst_prsn_f_nm character varying(50) ENCODE zstd,
    dm_cnst_prsn_m_nm character varying(50) ENCODE zstd,
    dm_cnst_prsn_l_nm character varying(50) ENCODE zstd,
    dm_cnst_prsn_sfx_nm character varying(50) ENCODE zstd,
    dm_cnst_prsn_full_nm character varying(100) ENCODE zstd,
    dm_cnst_alias_in_saltn_nm character varying(120) ENCODE zstd,
    dm_cnst_alias_out_saltn_nm character varying(120) ENCODE zstd,
    dm_locator_addr_key bigint ENCODE zstd,
    dm_cnst_addr_assessmnt_ctg character varying(40) ENCODE zstd,
    dpv_cd character varying(1) ENCODE zstd,
    dm_cnst_line_1_addr character varying(100) ENCODE zstd,
    dm_cnst_line_2_addr character varying(100) ENCODE zstd,
    dm_cnst_city_nm character varying(100) ENCODE zstd,
    dm_cnst_st_cd character(2) ENCODE zstd,
    dm_cnst_zip_5_cd character(5) ENCODE zstd,
    dm_cnst_zip_4_cd character(4) ENCODE zstd,
    dm_cnst_addr_county_nm character varying(100) ENCODE zstd,
    cem_all_mail_override_flg character varying(1) ENCODE zstd,
    cem_fr_mail_override_flg character varying(1) ENCODE zstd,
    cem_all_mail_override_ind smallint ENCODE zstd,
    cem_fr_mail_override_ind smallint ENCODE zstd,
    ncoa_mail_override_flg character varying(1) ENCODE zstd,
    ncoa_mail_override_ind smallint ENCODE zstd,
    dm_cnst_email character varying(100) ENCODE zstd,
    dm_cnst_org_nm character varying(150) ENCODE zstd,
    dm_cnst_typ_dsc character varying(50) ENCODE zstd,
    dm_cnst_prsn_prfx_nm2 character varying(50) ENCODE zstd,
    dm_cnst_prsn_f_nm2 character varying(50) ENCODE zstd,
    dm_cnst_prsn_m_nm2 character varying(50) ENCODE zstd,
    dm_cnst_prsn_l_nm2 character varying(50) ENCODE zstd,
    dm_cnst_prsn_sfx_nm2 character varying(50) ENCODE zstd,
    dm_cnst_prsn_full_nm2 character varying(100) ENCODE zstd,
    em_prsn_nm_src_cd character varying(10) ENCODE zstd,
    em_cnst_data_src_cd character varying(10) ENCODE zstd,
    em_locator_prsn_nm_key bigint ENCODE zstd,
    em_cnst_prsn_nm_assessmnt_ctg character varying(40) ENCODE zstd,
    em_cnst_prsn_prfx_nm character varying(50) ENCODE zstd,
    em_cnst_prsn_f_nm character varying(200) ENCODE zstd,
    em_cnst_prsn_m_nm character varying(50) ENCODE zstd,
    em_cnst_prsn_l_nm character varying(50) ENCODE zstd,
    em_cnst_prsn_sfx_nm character varying(50) ENCODE zstd,
    em_cnst_prsn_full_nm character varying(100) ENCODE zstd,
    em_cnst_alias_in_saltn_nm character varying(120) ENCODE zstd,
    em_cnst_alias_out_saltn_nm character varying(120) ENCODE zstd,
    em_locator_addr_key bigint ENCODE zstd,
    em_cnst_line_1_addr character varying(200) ENCODE zstd,
    em_cnst_line_2_addr character varying(200) ENCODE zstd,
    em_cnst_city_nm character varying(200) ENCODE zstd,
    em_cnst_st_cd character varying(200) ENCODE zstd,
    em_cnst_zip_5_cd character varying(5) ENCODE zstd,
    em_cnst_zip_4_cd character varying(4) ENCODE zstd,
    em_cnst_addr_county_nm character varying(100) ENCODE zstd,
    em_cnst_email character varying(200) ENCODE zstd,
    em_email_key bigint ENCODE zstd,
    em_cnst_email_assessmnt_ctg character varying(40) ENCODE zstd,
    em_cnst_org_nm character varying(150) ENCODE zstd,
    em_cnst_typ_dsc character varying(50) ENCODE zstd,
    em_cnst_prsn_prfx_nm2 character varying(50) ENCODE zstd,
    em_cnst_prsn_f_nm2 character varying(50) ENCODE zstd,
    em_cnst_prsn_m_nm2 character varying(50) ENCODE zstd,
    em_cnst_prsn_l_nm2 character varying(50) ENCODE zstd,
    em_cnst_prsn_sfx_nm2 character varying(50) ENCODE zstd,
    em_cnst_prsn_full_nm2 character varying(100) ENCODE zstd,
    email_dlvrbl_ind smallint ENCODE zstd,
    prim_cnst_phn character varying(25) ENCODE zstd,
    prim_cnst_phn_source character varying(10) ENCODE zstd,
    prim_cnst_phn_typ_dsc character varying(20) ENCODE zstd,
    cnst_work_phn character varying(25) ENCODE zstd,
    cnst_work_phn_source character varying(10) ENCODE zstd,
    cnst_work_phn_typ_dsc character varying(20) ENCODE zstd,
    cnst_mbl_phn character varying(25) ENCODE zstd,
    cnst_mbl_phn_source character varying(10) ENCODE zstd,
    cnst_mbl_phn_typ_dsc character varying(20) ENCODE zstd,
    do_not_call_hm_phn_ind smallint ENCODE zstd,
    do_not_call_mbl_phn_ind smallint ENCODE zstd,
    do_not_call_work_phn_ind smallint ENCODE zstd,
    do_not_email_ind smallint ENCODE zstd,
    do_not_mail_ind smallint ENCODE zstd,
    do_not_txt_ind smallint ENCODE zstd,
    cnst_3rd_prty_segmtn_group_nm character varying(4) ENCODE zstd,
    unit_key integer ENCODE zstd,
    affl_lock_ind smallint ENCODE zstd,
    sf_acct_fmd_ind smallint ENCODE zstd,
    frf_status_cd character varying(20) ENCODE zstd,
    portfolio_category character varying(100) ENCODE zstd,
    rlshp_mgr_ownr_key bigint ENCODE zstd,
    rlshp_mgr_nm character varying(100) ENCODE zstd,
    rlshp_mgr_prefd_email_addr character varying(100) ENCODE zstd,
    acct_in_salutn_nm character varying(100) ENCODE zstd,
    acct_out_salutn_nm character varying(100) ENCODE zstd,
    dm_pa_addr_check character varying(10) ENCODE zstd,
    unit_key_src character varying(20) ENCODE zstd,
    mktg_unit_key integer ENCODE zstd,
    cnst_typ_cd character varying(2) ENCODE zstd,
    org_typ_cd character varying(5) ENCODE zstd,
    has_smry_profile_ind smallint ENCODE zstd,
    inactvn_unf_fr_cnst_key integer ENCODE zstd,
    inactvtn_reason_cd character varying(25) ENCODE zstd,
    inactvtn_reason_dsc character varying(100) ENCODE zstd,
    inactvtn_dt date ENCODE zstd,
    inactvtn_reason_txt character varying(255) ENCODE zstd,
    ag_bzd_sfid character varying(20) ENCODE zstd,
    cntct_bzd_sfid character varying(20) ENCODE zstd,
    mult_sf_cnst_ind smallint ENCODE zstd
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );