CREATE TABLE mktg_ops_tbls.mobile_commons_active (
    id integer ENCODE raw distkey,
    phone_num character varying(20) ENCODE lzo,
    email character varying(34) ENCODE lzo,
    first_nm character varying(16) ENCODE lzo,
    last_nm character varying(18) ENCODE lzo,
    status character varying(17) ENCODE lzo,
    description smallint ENCODE az64,
    street1 character varying(43) ENCODE lzo,
    street2 character varying(61) ENCODE lzo,
    city character varying(23) ENCODE lzo,
    state character varying(2) ENCODE lzo,
    postal_cd integer ENCODE az64,
    country character varying(2) ENCODE lzo,
    congressional_district character varying(5) ENCODE lzo,
    state_upper_district character varying(5) ENCODE lzo,
    state_lower_district character varying(6) ENCODE lzo,
    split_district character varying(2) ENCODE lzo,
    latitude numeric(8,6) ENCODE az64,
    longitude numeric(10,6) ENCODE az64,
    precision1 character varying(21) ENCODE lzo,
    geocoded_city character varying(18) ENCODE lzo,
    geocoded_state character varying(2) ENCODE lzo,
    geocoded_postal_cd integer ENCODE az64,
    geocoded_country character varying(2) ENCODE lzo,
    carrier_nm character varying(34) ENCODE lzo,
    created_ts timestamp without time zone ENCODE az64,
    source_typ character varying(14) ENCODE lzo,
    source_nm character varying(26) ENCODE lzo,
    opted_out_at smallint ENCODE az64,
    opt_out_source smallint ENCODE az64,
    opt_in_2010_2015_disaster character varying(3) ENCODE lzo,
    opt_in_fy15_disaster character varying(3) ENCODE lzo,
    opt_in_fy16_disaster smallint ENCODE az64,
    opt_in_fy17_disaster character varying(8) ENCODE lzo,
    opt_in_redcross character varying(3) ENCODE lzo,
    opt_in_assist character varying(3) ENCODE lzo,
    opt_in_donate character varying(3) ENCODE lzo,
    opt_in_file smallint ENCODE az64,
    opt_in_prevent character varying(3) ENCODE lzo,
    opt_in_app_download character varying(12) ENCODE lzo,
    opt_in_engagement character varying(3) ENCODE lzo,
    opt_in_test smallint ENCODE az64,
    opt_in_online character varying(3) ENCODE lzo,
    donation_amt smallint ENCODE az64,
    opt_out_blood_ask smallint ENCODE az64,
    active_fundraiser character varying(3) ENCODE lzo
)
DISTSTYLE KEY
SORTKEY ( id );