CREATE TABLE mktg_ops_tbls.phone_interaction_eoc (
    unq_id character varying(30) ENCODE zstd,
    cmpgn_cd character varying(30) ENCODE zstd,
    pgm_type character varying(10) ENCODE zstd,
    sgmnt_dsc character varying(50) ENCODE zstd,
    fiscal_yr smallint ENCODE zstd,
    qtr character(2) ENCODE zstd,
    sf_acct_id character varying(9) ENCODE zstd,
    cnst_mstr_id bigint ENCODE zstd distkey,
    orig_cnst_mstr_id bigint ENCODE zstd,
    src_cd character varying(20) ENCODE zstd,
    appeal_cd smallint ENCODE zstd,
    dsgntn_cd character varying(23) ENCODE zstd,
    chnl_cd smallint ENCODE zstd,
    sf_contact_id character varying(6) ENCODE zstd,
    acct_nm character varying(256) ENCODE zstd,
    nk_ecode character varying(256) ENCODE zstd,
    region_nm character varying(256) ENCODE zstd,
    first_nm character varying(30) ENCODE zstd,
    last_nm character varying(50) ENCODE zstd,
    addr_line1 character varying(50) ENCODE zstd,
    addr_line2 character varying(50) ENCODE zstd,
    city character varying(30) ENCODE zstd,
    state character(2) ENCODE zstd,
    zip_cd character varying(9) ENCODE zstd,
    home_phn_num character varying(256) ENCODE zstd,
    home_phn_num_cln character varying(256) ENCODE zstd,
    mbl_phn_num character varying(256) ENCODE zstd,
    mbl_phn_num_cln character varying(256) ENCODE zstd,
    call_dt_src character varying(256) ENCODE zstd,
    call_dt date ENCODE zstd,
    call_start_ts_src character varying(256) ENCODE zstd,
    call_start_ts timestamp without time zone ENCODE zstd,
    call_end_ts_src character varying(256) ENCODE zstd,
    call_end_ts timestamp without time zone ENCODE zstd,
    elapsed_call_tm character varying(256) ENCODE zstd,
    cmpgn_call_atmpt_cnt smallint ENCODE zstd,
    phn_chng_type character varying(8) ENCODE zstd,
    scrpt_num smallint ENCODE zstd,
    afltn_cd smallint ENCODE zstd,
    gift_amt numeric(15,2) ENCODE zstd,
    pledge_amt numeric(15,2) ENCODE zstd,
    addr_id smallint ENCODE zstd,
    email_id smallint ENCODE zstd,
    name_id smallint ENCODE zstd,
    phn_id smallint ENCODE zstd,
    pfx character varying(256) ENCODE zstd,
    slttn character varying(256) ENCODE zstd,
    mi character(1) ENCODE zstd,
    sfx character varying(256) ENCODE zstd,
    dspstn_id integer ENCODE zstd,
    dspstn1 character(2) ENCODE zstd,
    dspstn2 character(2) ENCODE zstd,
    addi_rqst smallint ENCODE zstd,
    phn_chng_flg character(1) ENCODE zstd,
    addr_chng_flg character(1) ENCODE zstd,
    nm_chng_flg character(1) ENCODE zstd,
    email_chng_flg character(1) ENCODE zstd,
    email_addr character varying(256) ENCODE zstd,
    is_cell_flg character(1) ENCODE zstd,
    scr1_id integer ENCODE zstd,
    scr1_val integer ENCODE zstd,
    scr2_id integer ENCODE zstd,
    scr2_val integer ENCODE zstd,
    scr3_id integer ENCODE zstd,
    scr3_val integer ENCODE zstd,
    decile smallint ENCODE zstd,
    cmnt character varying(40) ENCODE zstd,
    curr_prcsd_file_nm character varying(255) ENCODE zstd,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE zstd,
    row_stat_cd character(1) NOT NULL ENCODE zstd,
    appl_src_cd character varying(4) NOT NULL ENCODE zstd,
    load_id integer NOT NULL ENCODE zstd
)
DISTSTYLE KEY
SORTKEY ( dw_trans_ts );