CREATE TABLE mktg_ops_tbls.pref_cnst_mstr (
    id integer NOT NULL identity(1,1) ENCODE az64,
    cnst_mstr_id numeric(20,0) DEFAULT 0 ENCODE az64 distkey,
    created_by numeric(20,0) DEFAULT 0 ENCODE az64,
    last_updated_by numeric(20,0) DEFAULT 0 ENCODE az64,
    created_date timestamp without time zone ENCODE az64,
    last_updated_date timestamp without time zone ENCODE az64,
    fr_email_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_text_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_phone_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_dm_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_email_opt_out_old smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_text_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_phone_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_dm_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_email_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_text_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_phone_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_dm_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_email_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_text_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_phone_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_dm_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    global_opt_out smallint NOT NULL DEFAULT 0 ENCODE az64,
    sftp character varying(25) DEFAULT 'N'::character varying ENCODE lzo,
    bio_email_opt_out character(1) DEFAULT 'N'::bpchar ENCODE lzo,
    fr_email_opt_in_newsletters smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_email_opt_in_disaster smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_email_opt_in_localnews smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_fd_1 smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_fd_2 smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_fd_3 smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_fd_4 smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_fd_5 smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_fd_6 smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_fd_7 smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_fd_1 smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_fd_2 smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_fd_3 smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_fd_4 smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_fd_5 smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_fd_6 smallint NOT NULL DEFAULT 0 ENCODE az64,
    bio_fd_7 smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_fd_1 smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_fd_2 smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_fd_3 smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_fd_4 smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_fd_5 smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_fd_6 smallint NOT NULL DEFAULT 0 ENCODE az64,
    ts_fd_7 smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_fd_1 smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_fd_2 smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_fd_3 smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_fd_4 smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_fd_5 smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_fd_6 smallint NOT NULL DEFAULT 0 ENCODE az64,
    vms_fd_7 smallint NOT NULL DEFAULT 0 ENCODE az64,
    fr_last_upd_date timestamp without time zone ENCODE az64,
    bio_last_upd_date timestamp without time zone ENCODE az64
)
DISTSTYLE KEY;