CREATE TABLE mktg_ops_tbls.rr_rqq_rql_file_xref (
    src_cd character varying(20) ENCODE raw distkey,
    drop_dt_src character varying(20) ENCODE lzo,
    drop_dt date ENCODE az64,
    motivtn_cd character varying(20) ENCODE lzo,
    qty integer ENCODE az64,
    kit_cd character varying(2) ENCODE lzo,
    kit_cd_dsc character varying(100) ENCODE lzo,
    segmnt_cd character varying(3) ENCODE raw,
    segmnt_dsc character varying(100) ENCODE lzo,
    file_cd character varying(4) ENCODE lzo,
    file_cd_dsc character varying(100) ENCODE lzo,
    select_grp_dsc character varying(100) ENCODE lzo,
    superdupe_ind smallint ENCODE az64,
    list_typ character varying(20) ENCODE lzo,
    list_cost_est_amt numeric(13,2) ENCODE az64,
    ppp_cost_est_amt numeric(13,2) ENCODE az64,
    list_cost_act_amt numeric(13,2) ENCODE az64,
    ppp_cost_act_amt numeric(13,2) ENCODE az64,
    cpp numeric(8,5) ENCODE az64,
    cpm numeric(13,2) ENCODE az64,
    recency character varying(48) ENCODE lzo,
    gift_size character varying(42) ENCODE lzo,
    tier character varying(47) ENCODE lzo,
    curr_prcsd_file_nm character varying(256) ENCODE lzo,
    dw_trans_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character varying(4) ENCODE lzo,
    load_id integer ENCODE az64,
    src_unq_row_id bigint ENCODE az64,
    src_txn_id bigint ENCODE az64,
    src_txn_seq bigint ENCODE az64,
    ingest_ts timestamp without time zone DEFAULT getdate() ENCODE az64,
    unq_row_id bigint NOT NULL identity(1,1) ENCODE az64,
    PRIMARY KEY (unq_row_id)
)
DISTSTYLE KEY
SORTKEY ( src_cd, segmnt_cd );