CREATE TABLE mktg_ops_tbls.srvy_rgnl_ldrshp_hst (
    snapshot_ts timestamp without time zone ENCODE az64,
    history_record_ts timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    adnc_mbr_id integer ENCODE az64,
    cnst_mstr_id bigint ENCODE az64,
    orig_cnst_mstr_id bigint ENCODE az64,
    last_nm character varying(255) ENCODE lzo,
    email character varying(255) ENCODE lzo,
    survey_nm character varying(255) ENCODE lzo,
    survey_period character(4) ENCODE lzo,
    edrtl_respns_period_key smallint ENCODE az64,
    edrtl_respns_period character varying(7) ENCODE lzo,
    division_cd character(5) ENCODE lzo,
    division_dsc character varying(40) ENCODE lzo,
    division_dsc_abbr character varying(40) ENCODE lzo,
    nk_ecode character(5) ENCODE lzo,
    cs_region_nm character varying(250) ENCODE lzo,
    cs_region_nm_abbr character varying(250) ENCODE lzo,
    vol_position character varying(30) ENCODE lzo,
    position_category character varying(15) ENCODE lzo,
    tmwrk_lvl_rtng smallint ENCODE az64,
    tmwrk_lvl_rtng_dsc character varying(10) ENCODE lzo,
    embrcd_ldr_rtng_composite smallint ENCODE az64,
    embrcd_ldr_rtng_composite_dsc character varying(15) ENCODE lzo,
    ed_focus_five_key_rsp_rtng smallint ENCODE az64,
    ed_focus_five_key_rsp_rtng_dsc character varying(54) ENCODE lzo,
    ed_have_sprt_rtng smallint ENCODE az64,
    ed_have_sprt_rtng_dsc character varying(15) ENCODE lzo,
    mutual_rspct_rtng smallint ENCODE az64,
    mutual_rspct_rtng_dsc character varying(15) ENCODE lzo,
    team_cmtmnt_rtng smallint ENCODE az64,
    team_cmtmnt_rtng_dsc character varying(15) ENCODE lzo,
    held_accntbl_rtng smallint ENCODE az64,
    held_accntbl_rtng_dsc character varying(15) ENCODE lzo,
    lead_by_exmpl_lob_rtng smallint ENCODE az64,
    lead_by_exmpl_lob_rtng_dsc character varying(15) ENCODE lzo,
    ed_aware_ind smallint ENCODE az64,
    arc_face_srvg_composite smallint ENCODE az64,
    arc_face_srvg_composite_dsc character varying(35) ENCODE lzo,
    rltnshp_bldg_cpcty_composite smallint ENCODE az64,
    rltnshp_bldg_cpcty_composite_dsc character varying(35) ENCODE lzo,
    chptr_board_dvlpmnt_composite smallint ENCODE az64,
    chptr_board_dvlpmnt_composite_dsc character varying(35) ENCODE lzo,
    cmmnty_ldr_dvlpmnt_composite smallint ENCODE az64,
    cmmnty_ldr_dvlpmnt_composite_dsc character varying(35) ENCODE lzo,
    tmwrk_inclsn_envrnmnt_composite smallint ENCODE az64,
    tmwrk_inclsn_envrnmnt_composite_dsc character varying(35) ENCODE lzo,
    ed_mng_evnt_ind smallint ENCODE az64,
    ed_lcl_bldg_mntnc_ind smallint ENCODE az64,
    ed_frnt_dsk_ind smallint ENCODE az64,
    ed_offc_mngmnt_ind smallint ENCODE az64,
    ed_vlntr_cmplnt_ind smallint ENCODE az64,
    ed_clnt_srvc_dlvry_ind smallint ENCODE az64,
    ed_other_ind smallint ENCODE az64,
    ed_other_txt_dsc character varying(765) ENCODE lzo,
    ed_focus_area_total integer ENCODE az64,
    ed_focus_outside_top5_ind smallint ENCODE az64,
    rlt_addtnl_cmt character varying(12000) ENCODE lzo,
    ed_addtnl_cmt character varying(12000) ENCODE lzo,
    ed_addtnl_sprt_cmt character varying(12000) ENCODE lzo,
    srcsys_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character(4) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE AUTO;