CREATE TABLE mktg_ops_tbls.srvy_gplg_rspns (
    snapshot_ts timestamp without time zone ENCODE az64,
    history_record_ts timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    iwebappid integer ENCODE az64,
    src_cd character varying(20) ENCODE lzo,
    adnc_mbr_id integer ENCODE az64,
    survey_nm character varying(255) ENCODE lzo,
    cnst_mstr_id bigint ENCODE az64 distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    first_nm character varying(255) ENCODE lzo,
    last_nm character varying(255) ENCODE lzo,
    addr1 character varying(255) ENCODE lzo,
    city character varying(255) ENCODE lzo,
    state character varying(255) ENCODE lzo,
    zip_cd character varying(255) ENCODE lzo,
    email character varying(255) ENCODE lzo,
    phone character varying(15) ENCODE lzo,
    age_band character varying(12) ENCODE lzo,
    marital_status character varying(25) ENCODE lzo,
    unit_key integer ENCODE az64,
    nk_ecode character varying(5) ENCODE lzo,
    suprt_imprtnc character varying(25) ENCODE lzo,
    gift_plan_status character varying(60) ENCODE lzo,
    a1_there_for_me_suprt_ind smallint ENCODE az64,
    b1_gen_suprt_ind smallint ENCODE az64,
    c1_dstr_suprt_ind smallint ENCODE az64,
    d1_tax_suprt_ind smallint ENCODE az64,
    e1_mission_suprt_ind smallint ENCODE az64,
    a2_inflncl_persn_ind smallint ENCODE az64,
    a3_pgm_safety_ind smallint ENCODE az64,
    b3_pgm_afes_ind smallint ENCODE az64,
    c3_pgm_biomed_ind smallint ENCODE az64,
    d3_pgm_domestic_dstr_ind smallint ENCODE az64,
    e3_pgm_intl_dstr_ind smallint ENCODE az64,
    a4_extrmly_imprtnt_ind smallint ENCODE az64,
    b4_very_imprtnt_ind smallint ENCODE az64,
    c4_somewhat_imprtnt_ind smallint ENCODE az64,
    d4_not_very_imprtnt_ind smallint ENCODE az64,
    e4_no_opinion_ind smallint ENCODE az64,
    a5_arc_in_will_ind smallint ENCODE az64,
    b5_other_charity_in_will_ind smallint ENCODE az64,
    c5_no_charity_in_will_ind smallint ENCODE az64,
    a6_consider_arc_in_will_ind smallint ENCODE az64,
    a7_cga_interest_ind smallint ENCODE az64,
    b8_children_ind smallint ENCODE az64,
    c8_grand_children_ind smallint ENCODE az64,
    f8_arc_story character varying(4000) ENCODE lzo,
    dw_create_ts timestamp without time zone ENCODE az64,
    dw_updt_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character(4) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE KEY;