CREATE TABLE mktg_ops_tbls.srvy_new_vlntr_rspns_fy22 (
    snapshot_ts timestamp without time zone ENCODE az64,
    history_record_ts timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    adnc_mbr_id integer ENCODE az64,
    cnst_mstr_id bigint ENCODE az64 distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    last_nm character varying(255) ENCODE lzo,
    email character varying(255) ENCODE lzo,
    survey_nm character varying(255) ENCODE lzo,
    vlntr_rsn character varying(5) ENCODE lzo,
    vlntr_rsn_dsc character varying(75) ENCODE lzo,
    rcmnd_frnd_vlntr character varying(5) ENCODE lzo,
    why_scr_cmt character varying(4000) ENCODE lzo,
    a4_acctg_fnc_ind smallint ENCODE az64,
    b4_blood_svc_ind smallint ENCODE az64,
    c4_gen_admin_sprt_srvc_ind smallint ENCODE az64,
    d4_saf_srvc_ind smallint ENCODE az64,
    e4_comnty_srvc_ind smallint ENCODE az64,
    f4_trng_srvc_ind smallint ENCODE az64,
    g4_vlntr_srvc_ind smallint ENCODE az64,
    h4_dstr_srvc_ind smallint ENCODE az64,
    i4_intl_srvc_ind smallint ENCODE az64,
    j4_youth_prgrm_srvc_ind smallint ENCODE az64,
    k4_fr_srvc_ind smallint ENCODE az64,
    l4_ldrshp_ind smallint ENCODE az64,
    m4_nt_vlntr_ind smallint ENCODE az64,
    n4_unsure_ind smallint ENCODE az64,
    o4_other_ind smallint ENCODE az64,
    o4_oth_cmt character varying(4000) ENCODE lzo,
    p4_mktg_cmnctn_ind smallint ENCODE az64,
    wn_vlntr_num smallint ENCODE az64,
    wn_vlntr_dsc character varying(100) ENCODE lzo,
    ol_ez_undrstnd character varying(5) ENCODE lzo,
    stsfy_vlntr_optnty character varying(5) ENCODE lzo,
    adqt_rsltn character varying(5) ENCODE lzo,
    rl_rspnsblt character varying(5) ENCODE lzo,
    tl_rsrc character varying(5) ENCODE lzo,
    trng_adqt_prprd character varying(5) ENCODE lzo,
    a7_dntd_bld_arc_ind smallint ENCODE az64,
    b7_dntd_mny_arc_ind smallint ENCODE az64,
    c7_dwnld_arc_prp_app_ind smallint ENCODE az64,
    d7_tkn_hs_crs_ind smallint ENCODE az64,
    e7_rfrd_fmly_mbr_ind smallint ENCODE az64,
    f7_none_ind smallint ENCODE az64,
    vlntr_cnctn_ez character varying(5) ENCODE lzo,
    vlntr_cnctn_usfl character varying(5) ENCODE lzo,
    vlntr_cnctn_ovrl character varying(5) ENCODE lzo,
    vlntr_actvty_sprt character varying(5) ENCODE lzo,
    vlntr_actvty_expctd character varying(5) ENCODE lzo,
    vlntr_gd_tmwrk character varying(5) ENCODE lzo,
    vlntr_vlbl_mmbr character varying(5) ENCODE lzo,
    vlntr_sprvsr_rspct character varying(5) ENCODE lzo,
    nv_exp_cmt character varying(4000) ENCODE lzo,
    exp_rtng_num smallint ENCODE az64,
    exp_rtng_dsc character varying(60) ENCODE lzo,
    dw_create_ts timestamp without time zone ENCODE az64,
    dw_updt_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character(4) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE KEY;