CREATE TABLE mktg_ops_tbls.srvy_anvrsy_vlntr_rspns_fy22 (
    snapshot_ts timestamp without time zone ENCODE az64,
    history_record_ts timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    adnc_mbr_id integer ENCODE az64,
    cnst_mstr_id bigint ENCODE az64 distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    last_nm character varying(255) ENCODE lzo,
    email character varying(255) ENCODE lzo,
    survey_nm character varying(255) ENCODE lzo,
    vlntr_length character varying(25) ENCODE lzo,
    vlntr_xprnc_rtng smallint ENCODE az64,
    vlntr_xprnc_rtng_dsc character varying(25) ENCODE lzo,
    tmwrk_good_rtng smallint ENCODE az64,
    tmwrk_good_rtng_dsc character varying(20) ENCODE lzo,
    why_scr_tmwrk_cmt character varying(4000) ENCODE lzo,
    rcmnd_frnd_vlntr_rtng smallint ENCODE az64,
    rcmnd_frnd_vlntr_rtng_dsc character varying(25) ENCODE lzo,
    why_scr_cmt character varying(4000) ENCODE lzo,
    a5_acctg_fnc_ind smallint ENCODE az64,
    b5_blood_svc_ind smallint ENCODE az64,
    c5_gen_admin_sprt_srvc_ind smallint ENCODE az64,
    d5_saf_srvc_ind smallint ENCODE az64,
    e5_comnty_srvc_ind smallint ENCODE az64,
    f5_trng_srvc_ind smallint ENCODE az64,
    g5_vlntr_srvc_ind smallint ENCODE az64,
    h5_dstr_srvc_ind smallint ENCODE az64,
    i5_intl_srvc_ind smallint ENCODE az64,
    j5_youth_prgrm_srvc_ind smallint ENCODE az64,
    k5_fr_srvc_ind smallint ENCODE az64,
    l5_ldrshp_ind smallint ENCODE az64,
    m5_mrktg_ind smallint ENCODE az64,
    n5_other_ind smallint ENCODE az64,
    n5_other_dsc character varying(60) ENCODE lzo,
    a5_exp_rtng_num smallint ENCODE az64,
    a5_exp_rtng_dsc character varying(15) ENCODE lzo,
    b5_exp_rtng_num smallint ENCODE az64,
    b5_exp_rtng_dsc character varying(15) ENCODE lzo,
    c5_exp_rtng_num smallint ENCODE az64,
    c5_exp_rtng_dsc character varying(15) ENCODE lzo,
    d5_exp_rtng_num smallint ENCODE az64,
    d5_exp_rtng_dsc character varying(15) ENCODE lzo,
    e5_exp_rtng_num smallint ENCODE az64,
    e5_exp_rtng_dsc character varying(15) ENCODE lzo,
    f5_exp_rtng_num smallint ENCODE az64,
    f5_exp_rtng_dsc character varying(15) ENCODE lzo,
    g5_exp_rtng_num smallint ENCODE az64,
    g5_exp_rtng_dsc character varying(15) ENCODE lzo,
    h5_exp_rtng_num smallint ENCODE az64,
    h5_exp_rtng_dsc character varying(15) ENCODE lzo,
    h5_in_rgn_dro_dplymnt_ind smallint ENCODE az64,
    h5_out_rgn_dro_dplymnt_ind smallint ENCODE az64,
    h5_both_rgn_dro_dplymnt_ind smallint ENCODE az64,
    h5_no_rgn_dro_dplymnt_ind smallint ENCODE az64,
    i5_exp_rtng_num smallint ENCODE az64,
    i5_exp_rtng_dsc character varying(15) ENCODE lzo,
    j5_exp_rtng_num smallint ENCODE az64,
    j5_exp_rtng_dsc character varying(15) ENCODE lzo,
    k5_exp_rtng_num smallint ENCODE az64,
    k5_exp_rtng_dsc character varying(15) ENCODE lzo,
    l5_exp_rtng_num smallint ENCODE az64,
    l5_exp_rtng_dsc character varying(15) ENCODE lzo,
    m5_exp_rtng_num smallint ENCODE az64,
    m5_exp_rtng_dsc character varying(15) ENCODE lzo,
    a6_vlntr_sprt_rtng smallint ENCODE az64,
    a6_vlntr_sprt_rtng_dsc character varying(20) ENCODE lzo,
    b6_expctn_rtng smallint ENCODE az64,
    b6_expctn_rtng_dsc character varying(20) ENCODE lzo,
    c6_trng_mtrl_rtng smallint ENCODE az64,
    c6_trng_mtrl_rtng_dsc character varying(20) ENCODE lzo,
    d6_tmwrk_good_rtng smallint ENCODE az64,
    d6_tmwrk_good_rtng_dsc character varying(20) ENCODE lzo,
    e6_team_value_rtng smallint ENCODE az64,
    e6_team_value_rtng_dsc character varying(20) ENCODE lzo,
    f6_rspct_sprvsr_rtng smallint ENCODE az64,
    f6_rspct_sprvsr_rtng_dsc character varying(20) ENCODE lzo,
    g6_bhvr_cnstnt_rtng smallint ENCODE az64,
    g6_bhvr_cnstnt_rtng_dsc character varying(20) ENCODE lzo,
    h6_prspctv_value_rtng smallint ENCODE az64,
    h6_prspctv_value_rtng_dsc character varying(20) ENCODE lzo,
    i6_vlntr_cont_rtng smallint ENCODE az64,
    i6_vlntr_cont_rtng_dsc character varying(20) ENCODE lzo,
    j6_bkgrnd_rspctd_rtng smallint ENCODE az64,
    j6_bkgrnd_rspctd_rtng_dsc character varying(20) ENCODE lzo,
    vlntr_exp_cmt character varying(4000) ENCODE lzo,
    vlntr_hrs_value smallint ENCODE az64,
    vlntr_hrs_dsc character varying(50) ENCODE lzo,
    a9_dntd_bld_ind smallint ENCODE az64,
    b9_dntd_mny_ind smallint ENCODE az64,
    c9_prprdns_app_ind smallint ENCODE az64,
    d9_hs_crs_ind smallint ENCODE az64,
    e9_ref_fmly_ind smallint ENCODE az64,
    f9_none_ind smallint ENCODE az64,
    a10_vlntr_exprnc_easy_rtng smallint ENCODE az64,
    a10_vlntr_exprnc_easy_rtng_dsc character varying(20) ENCODE lzo,
    b10_vlntr_cnctn_usfl_rtng smallint ENCODE az64,
    b10_vlntr_cnctn_usfl_rtng_dsc character varying(20) ENCODE lzo,
    c10_vlntr_cnctn_easy_rtng smallint ENCODE az64,
    c10_vlntr_cnctn_easy_rtng_dsc character varying(20) ENCODE lzo,
    dw_create_ts timestamp without time zone ENCODE az64,
    dw_updt_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character(4) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE KEY;