CREATE TABLE mktg_ops_tbls.srvy_new_vlntr_rspns (
    snapshot_ts timestamp without time zone ENCODE az64,
    history_record_ts timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    adnc_mbr_id integer ENCODE az64 distkey,
    cnst_mstr_id bigint ENCODE az64,
    orig_cnst_mstr_id bigint ENCODE az64,
    last_nm character varying(255) ENCODE lzo,
    email character varying(255) ENCODE lzo,
    survey_nm character varying(255) ENCODE lzo,
    vlntr_lrn character varying(5) ENCODE lzo,
    vlntr_lrn_oth_cmt character varying(12000) ENCODE lzo,
    vlntr_rsn character varying(5) ENCODE lzo,
    rcmnd_frnd_vlntr character varying(5) ENCODE lzo,
    why_scr_cmt character varying(12000) ENCODE lzo,
    a5_prvd_asst_ind smallint ENCODE az64,
    b5_trng_oth_ind smallint ENCODE az64,
    c5_miltry_asst_ind smallint ENCODE az64,
    d5_cmnty_evt_ind smallint ENCODE az64,
    e5_busn_oprtn_ind smallint ENCODE az64,
    f5_trng_new_vlntr_ind smallint ENCODE az64,
    g5_lcl_evt_ind smallint ENCODE az64,
    h5_brd_mbr_ind smallint ENCODE az64,
    i5_dstr_evt_ind smallint ENCODE az64,
    j5_intl_svc_ind smallint ENCODE az64,
    k5_arc_club_ind smallint ENCODE az64,
    l5_nt_actv_vlntr_ind smallint ENCODE az64,
    m5_oth_ind smallint ENCODE az64,
    wn_vlntr_cmt character varying(12000) ENCODE lzo,
    ol_ez_undrstnd character varying(5) ENCODE lzo,
    adqt_rsltn character varying(5) ENCODE lzo,
    timlns_aplctn_acptbl character varying(5) ENCODE lzo,
    timlns_ntfy_acptbl character varying(5) ENCODE lzo,
    rl_rspnsblt character varying(5) ENCODE lzo,
    tl_rsrc character varying(5) ENCODE lzo,
    trng_adqt_prprd character varying(5) ENCODE lzo,
    a13_attnd_class_ind smallint ENCODE az64,
    b13_ono_trng_ind smallint ENCODE az64,
    c13_ol_trng_ind smallint ENCODE az64,
    d13_awr_trng_ind smallint ENCODE az64,
    e13_nt_awr_trng_ind smallint ENCODE az64,
    a14_mltry_svc_ind smallint ENCODE az64,
    b14_dnt_bld_ind smallint ENCODE az64,
    c14_fin_dntn_ind smallint ENCODE az64,
    d14_dstr_astnc_ind smallint ENCODE az64,
    e14_arc_class_ind smallint ENCODE az64,
    f14_sm_ambsdr_ind smallint ENCODE az64,
    g14_oth_ind smallint ENCODE az64,
    h14_oth_cmt character varying(4000) ENCODE lzo,
    vlntr_exp_cmt character varying(12000) ENCODE lzo,
    a15_new_chlng_ind smallint ENCODE az64,
    b15_skl_edctn_ind smallint ENCODE az64,
    c15_mkg_frnd_ind smallint ENCODE az64,
    d15_hlpg_need_ind smallint ENCODE az64,
    e15_smtng_do_ind smallint ENCODE az64,
    f15_cmnty_gv_bck_ind smallint ENCODE az64,
    g15_hlpg_fmly_ind smallint ENCODE az64,
    h15_oth_ind smallint ENCODE az64,
    i15_oth_cmt character varying(4000) ENCODE lzo,
    nv_chng_cmt character varying(12000) ENCODE lzo,
    ocptn_ctgy character varying(5) ENCODE lzo,
    dw_create_ts timestamp without time zone ENCODE az64,
    dw_updt_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character(4) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE AUTO
SORTKEY ( snapshot_ts );