CREATE TABLE mktg_ops_tbls.srvy_rgnl_ldrshp_fy21 (
    snapshot_ts timestamp without time zone ENCODE az64,
    history_record_ts timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    adnc_mbr_id integer ENCODE az64,
    cnst_mstr_id bigint ENCODE az64 distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    last_nm character varying(255) ENCODE lzo,
    full_nm character varying(255) ENCODE lzo,
    email character varying(255) ENCODE lzo,
    survey_nm character varying(255) ENCODE lzo,
    survey_period character(4) ENCODE lzo,
    division_cd character(5) ENCODE lzo,
    nk_ecode character(5) ENCODE lzo,
    vol_position character varying(30) ENCODE lzo,
    a1_mutual_rspct_rtng smallint ENCODE az64,
    a1_mutual_rspct_rtng_dsc character varying(15) ENCODE lzo,
    b1_team_cmtmnt_rtng smallint ENCODE az64,
    b1_team_cmtmnt_rtng_dsc character varying(15) ENCODE lzo,
    c1_held_accntbl_rtng smallint ENCODE az64,
    c1_held_accntbl_rtng_dsc character varying(15) ENCODE lzo,
    d1_lead_by_exmpl_lob_rtng smallint ENCODE az64,
    d1_lead_by_exmpl_lob_rtng_dsc character varying(15) ENCODE lzo,
    a2_tmwrk_lvl_rtng smallint ENCODE az64,
    a2_tmwrk_lvl_rtng_dsc character varying(10) ENCODE lzo,
    a4_arc_face_srvg_rtng smallint ENCODE az64,
    a4_arc_face_srvg_rtng_dsc character varying(35) ENCODE lzo,
    b4_rltnshp_bldg_cpcty_rtng smallint ENCODE az64,
    b4_rltnshp_bldg_cpcty_rtng_dsc character varying(35) ENCODE lzo,
    c4_chptr_board_dvlpmnt_rtng smallint ENCODE az64,
    c4_chptr_board_dvlpmnt_rtng_dsc character varying(35) ENCODE lzo,
    d4_cmmnty_ldr_dvlpmnt_rtng smallint ENCODE az64,
    d4_cmmnty_ldr_dvlpmnt_rtng_dsc character varying(35) ENCODE lzo,
    e4_tmwrk_inclsn_envrnmnt_rtng smallint ENCODE az64,
    e4_tmwrk_inclsn_envrnmnt_rtng_dsc character varying(35) ENCODE lzo,
    a4_ed_embrcd_ldr_rtng smallint ENCODE az64,
    a4_ed_embrcd_ldr_rtng_dsc character varying(15) ENCODE lzo,
    a5_ed_aware_ind smallint ENCODE az64,
    a6_eda_arc_face_srvg_rtng smallint ENCODE az64,
    a6_eda_arc_face_srvg_rtng_dsc character varying(35) ENCODE lzo,
    b6_eda_rltnshp_bldg_cpcty_rtng smallint ENCODE az64,
    b6_eda_rltnshp_bldg_cpcty_rtng_dsc character varying(35) ENCODE lzo,
    c6_eda_chptr_board_dvlpmnt_rtng smallint ENCODE az64,
    c6_eda_chptr_board_dvlpmnt_rtng_dsc character varying(35) ENCODE lzo,
    d6_eda_cmmnty_ldr_dvlpmnt_rtng smallint ENCODE az64,
    d6_eda_cmmnty_ldr_dvlpmnt_rtng_dsc character varying(35) ENCODE lzo,
    e6_eda_tmwrk_inclsn_envrnmnt_rtng smallint ENCODE az64,
    e6_eda_tmwrk_inclsn_envrnmnt_rtng_dsc character varying(35) ENCODE lzo,
    a6_edna_arc_face_srvg_rtng smallint ENCODE az64,
    a6_edna_arc_face_srvg_rtng_dsc character varying(35) ENCODE lzo,
    b6_edna_rltnshp_bldg_cpcty_rtng smallint ENCODE az64,
    b6_edna_rltnshp_bldg_cpcty_rtng_dsc character varying(35) ENCODE lzo,
    c6_edna_chptr_board_dvlpmnt_rtng smallint ENCODE az64,
    c6_edna_chptr_board_dvlpmnt_rtng_dsc character varying(35) ENCODE lzo,
    d6_edna_cmmnty_ldr_dvlpmnt_rtng smallint ENCODE az64,
    d6_edna_cmmnty_ldr_dvlpmnt_rtng_dsc character varying(35) ENCODE lzo,
    e6_edna_tmwrk_inclsn_envrnmnt_rtng smallint ENCODE az64,
    e6_edna_tmwrk_inclsn_envrnmnt_rtng_dsc character varying(35) ENCODE lzo,
    a7_ed_have_sprt_rtng smallint ENCODE az64,
    a7_ed_have_sprt_rtng_dsc character varying(15) ENCODE lzo,
    a8_ed_focus_five_key_rsp_rtng smallint ENCODE az64,
    a8_ed_focus_five_key_rsp_rtng_dsc character varying(15) ENCODE lzo,
    a9_ed_mng_evnt_ind smallint ENCODE az64,
    b9_ed_lcl_bldg_mntnc_ind smallint ENCODE az64,
    c9_ed_frnt_dsk_ind smallint ENCODE az64,
    d9_ed_offc_mngmnt_ind smallint ENCODE az64,
    e9_ed_vlntr_cmplnt_ind smallint ENCODE az64,
    f9_ed_clnt_srvc_dlvry_ind smallint ENCODE az64,
    g9_ed_other_ind smallint ENCODE az64,
    g9_ed_other_txt_dsc character varying(255) ENCODE lzo,
    rlt_addtnl_cmt character varying(4000) ENCODE lzo,
    ed_addtnl_cmt character varying(4000) ENCODE lzo,
    ed_addtnl_sprt_cmt character varying(4000) ENCODE lzo,
    dw_create_ts timestamp without time zone ENCODE az64,
    dw_updt_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character(4) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE KEY;