CREATE TABLE mktg_ops_tbls.srvy_anvrsy_vlntr_rspns (
    snapshot_ts timestamp without time zone ENCODE az64,
    history_record_ts timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    adnc_mbr_id integer ENCODE az64,
    cnst_mstr_id bigint ENCODE az64,
    orig_cnst_mstr_id bigint ENCODE az64,
    last_nm character varying(255) ENCODE lzo,
    email character varying(255) ENCODE lzo,
    survey_nm character varying(255) ENCODE lzo,
    vlntr_length character varying(75) ENCODE lzo,
    a2_blood_svc_ind smallint ENCODE az64,
    b2_gen_admin_sprt_srvc_ind smallint ENCODE az64,
    c2_saf_srvc_ind smallint ENCODE az64,
    d2_comnty_srvc_ind smallint ENCODE az64,
    e2_health_safety_srvc_ind smallint ENCODE az64,
    f2_vlntr_srvc_ind smallint ENCODE az64,
    g2_dstr_srvc_ind smallint ENCODE az64,
    h2_intl_srvc_ind smallint ENCODE az64,
    i2_youth_prgrm_srvc_ind smallint ENCODE az64,
    j2_fr_srvc_ind smallint ENCODE az64,
    k2_ldrshp_ind smallint ENCODE az64,
    l2_other_srvc_ind smallint ENCODE az64,
    vlntr_area_cmt character varying(12000) ENCODE lzo,
    vlntr_xprnc_rtng smallint ENCODE az64,
    vlntr_xprnc_rtng_dsc character varying(25) ENCODE lzo,
    rcmnd_frnd_vlntr_rtng smallint ENCODE az64,
    rcmnd_frnd_vlntr_rtng_dsc character varying(25) ENCODE lzo,
    why_scr_cmt character varying(12000) ENCODE lzo,
    a6_vlntr_sprt_rtng smallint ENCODE az64,
    a6_vlntr_sprt_rtng_dsc character varying(25) ENCODE lzo,
    b6_expctn_rtng smallint ENCODE az64,
    b6_expctn_rtng_dsc character varying(25) ENCODE lzo,
    c6_trng_mtrl_rtng smallint ENCODE az64,
    c6_trng_mtrl_rtng_dsc character varying(25) ENCODE lzo,
    d6_tmwrk_good_rtng smallint ENCODE az64,
    d6_tmwrk_good_rtng_dsc character varying(25) ENCODE lzo,
    e6_team_value_rtng smallint ENCODE az64,
    e6_team_value_rtng_dsc character varying(25) ENCODE lzo,
    f6_rspct_sprvsr_rtng smallint ENCODE az64,
    f6_rspct_sprvsr_rtng_dsc character varying(25) ENCODE lzo,
    g6_bhvr_cnstnt_rtng smallint ENCODE az64,
    g6_bhvr_cnstnt_rtng_dsc character varying(25) ENCODE lzo,
    h6_prspctv_value_rtng smallint ENCODE az64,
    h6_prspctv_value_rtng_dsc character varying(20) ENCODE lzo,
    i6_vlntr_cont_rtng smallint ENCODE az64,
    i6_vlntr_cont_rtng_dsc character varying(20) ENCODE lzo,
    vlntr_exp_cmt character varying(12000) ENCODE lzo,
    vlntr_hrs_value smallint ENCODE az64,
    vlntr_hrs_dsc character varying(50) ENCODE lzo,
    a9_dntd_bld_ind smallint ENCODE az64,
    b9_dntd_mny_ind smallint ENCODE az64,
    c9_prprdns_app_ind smallint ENCODE az64,
    d9_hs_crs_ind smallint ENCODE az64,
    e9_ref_fmly_ind smallint ENCODE az64,
    f9_none_ind smallint ENCODE az64,
    a10_vlntr_exprnc_easy_rtng smallint ENCODE az64,
    a10_vlntr_exprnc_easy_rtng_dsc character varying(25) ENCODE lzo,
    b10_vlntr_cnctn_usfl_rtng smallint ENCODE az64,
    b10_vlntr_cnctn_usfl_rtng_dsc character varying(25) ENCODE lzo,
    c10_vlntr_cnctn_easy_rtng smallint ENCODE az64,
    c10_vlntr_cnctn_easy_rtng_dsc character varying(25) ENCODE lzo,
    a11_arc_cmptr_rtng smallint ENCODE az64,
    a11_arc_cmptr_rtng_dsc character varying(25) ENCODE lzo,
    b11_arc_email_rtng smallint ENCODE az64,
    b11_arc_email_rtng_dsc character varying(25) ENCODE lzo,
    c11_arc_xchng_rtng smallint ENCODE az64,
    c11_arc_xchng_rtng_dsc character varying(25) ENCODE lzo,
    d11_arc_edge_rtng smallint ENCODE az64,
    d11_arc_edge_rtng_dsc character varying(25) ENCODE lzo,
    arc_edctn_lvl_value smallint ENCODE az64,
    arc_edctn_lvl_dsc character varying(50) ENCODE lzo,
    vlntr_dscrptn_value smallint ENCODE az64,
    vlntr_dscrptn_dsc character varying(50) ENCODE lzo,
    dw_create_ts timestamp without time zone ENCODE az64,
    dw_updt_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo,
    appl_src_cd character(4) ENCODE lzo,
    load_id integer ENCODE az64
)
DISTSTYLE AUTO
SORTKEY ( snapshot_ts );