CREATE TABLE mktg_ops_tbls.adb_bio_dnr_stsfctn_srvy (
    snapshot_ts timestamp without time zone ENCODE az64,
    cnst_mstr_id integer ENCODE az64,
    orig_cnst_mstr_id integer ENCODE az64,
    donat_key integer ENCODE az64,
    age_band_key integer ENCODE az64,
    blood_type_key integer ENCODE az64,
    donat_dt_key integer ENCODE az64,
    donor_key integer ENCODE az64,
    drive_key integer ENCODE az64,
    drive_site_key integer ENCODE az64,
    phleb_key integer ENCODE az64,
    race_key integer ENCODE az64,
    region_key integer ENCODE az64,
    sponsor_key integer ENCODE az64,
    nk_donat_dt date ENCODE az64,
    first_donat_ind smallint DEFAULT 0 ENCODE az64,
    em_cnst_email character varying(100) ENCODE lzo COLLATE case_sensitive,
    last_nm character varying(50) ENCODE lzo COLLATE case_sensitive,
    audnc_mbr_id integer ENCODE az64,
    hstry_rcrd_id integer ENCODE az64,
    hstry_rcrd_ts timestamp without time zone ENCODE az64,
    abstract character varying(255) ENCODE lzo COLLATE case_sensitive,
    cnst_mbl_phn character varying(20) ENCODE lzo COLLATE case_sensitive,
    donatn_in_6mth character varying(10) ENCODE lzo COLLATE case_sensitive,
    feel_welcmd character varying(10) ENCODE lzo COLLATE case_sensitive,
    hh_mnr_ad_rtng character varying(1) ENCODE lzo COLLATE case_sensitive,
    hh_thanked_ad_rtng character varying(1) ENCODE lzo COLLATE case_sensitive,
    phleb_crts_ad_rtng character varying(1) ENCODE lzo COLLATE case_sensitive,
    phleb_thanked_ad_rtng character varying(1) ENCODE lzo COLLATE case_sensitive,
    wait_tm_after_chkin_ad_rtng character varying(1) ENCODE lzo COLLATE case_sensitive,
    wait_tm_after_exam_ad_rtng character varying(1) ENCODE lzo COLLATE case_sensitive,
    donatn_tm_ad_rtng character varying(1) ENCODE lzo COLLATE case_sensitive,
    donatn_exprnc_ad_rtng character varying(1) ENCODE lzo COLLATE case_sensitive,
    phleb_skl_ad_rtng character varying(1) ENCODE lzo COLLATE case_sensitive,
    ok_arc_2_cntct_flg character varying(10) ENCODE lzo COLLATE case_sensitive,
    ok_arc_2_txt_flg character varying(10) ENCODE lzo COLLATE case_sensitive,
    rcmnd_frnd_dntng_bld_src smallint ENCODE az64,
    rcmnd_frnd_dntng_bld character varying(5) ENCODE lzo COLLATE case_sensitive,
    thanked_for_donation character varying(10) ENCODE lzo COLLATE case_sensitive,
    prmptd_comnictn_chan character varying(50) ENCODE lzo COLLATE case_sensitive,
    sckl_cell_trt_tstg_ntrst smallint ENCODE az64,
    cvd_antbdy_tstg_ntrst smallint ENCODE az64,
    nvlvd_with_org_hstng_drv smallint ENCODE az64,
    frnd_or_fmly_rqst_to_dnt smallint ENCODE az64,
    hlp_othrs_by_gvng_bld smallint ENCODE az64,
    sckl_cell_ptnts_need_dntns smallint ENCODE az64,
    bld_drv_in_my_cmnty smallint ENCODE az64,
    miniphys smallint ENCODE az64,
    type_o_bld smallint ENCODE az64,
    none_of_abv smallint ENCODE az64,
    race_cd character varying(40) ENCODE lzo COLLATE case_sensitive,
    race_desc character varying(40) ENCODE lzo COLLATE case_sensitive,
    interest_lvl_src smallint ENCODE az64,
    interest_lvl character varying(5) ENCODE lzo COLLATE case_sensitive,
    sckl_trait_stat_cd smallint ENCODE az64,
    slanguage character varying(12) ENCODE lzo COLLATE case_sensitive,
    invlvd_with_org_hstng_drv_lat smallint ENCODE az64,
    asked_to_dnt_lat smallint ENCODE az64,
    hlp_othrs_by_gvng_bld_lat smallint ENCODE az64,
    bld_drv_in_my_cmnty_lat smallint ENCODE az64,
    miniphys_lat smallint ENCODE az64,
    type_o_bld_lat smallint ENCODE az64,
    none_of_abv_lat smallint ENCODE az64,
    interest_lvl_lat character varying(5) ENCODE lzo COLLATE case_sensitive,
    srvy_vrsn character varying(2) ENCODE lzo COLLATE case_sensitive,
    dw_create_ts timestamp without time zone ENCODE az64,
    dw_updt_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character(4) ENCODE lzo COLLATE case_sensitive,
    load_id integer ENCODE az64
)
DISTSTYLE ALL;