CREATE TABLE mktg_ops_tbls.adb_xtkfolder_b401072026 (
    dcomputedcost double precision NOT NULL ENCODE raw,
    destimatedcost double precision NOT NULL ENCODE raw,
    drealcost double precision NOT NULL ENCODE raw,
    ibudgetid integer NOT NULL ENCODE az64,
    ibuiltin smallint NOT NULL ENCODE az64,
    ichildcount smallint NOT NULL ENCODE az64,
    icommitmentlevel smallint NOT NULL ENCODE az64,
    icomputationstate smallint NOT NULL ENCODE az64,
    icreatedbyid integer NOT NULL ENCODE az64,
    ienvid integer NOT NULL ENCODE az64,
    ifolderid integer NOT NULL ENCODE az64,
    igolive smallint NOT NULL ENCODE az64,
    iisview smallint NOT NULL ENCODE az64,
    ilive smallint NOT NULL ENCODE az64,
    imodifiedbyid integer NOT NULL ENCODE az64,
    iorder smallint NOT NULL ENCODE az64,
    iorgunitid integer NOT NULL ENCODE az64,
    iparentid integer NOT NULL ENCODE az64,
    iprodenvid integer NOT NULL ENCODE az64,
    isystem smallint NOT NULL ENCODE az64,
    iunselected smallint NOT NULL ENCODE az64,
    mdata character varying(4000) ENCODE lzo COLLATE case_insensitive,
    sentity character varying(64) ENCODE lzo COLLATE case_insensitive,
    sfullname character varying(255) ENCODE lzo COLLATE case_insensitive,
    simagename character varying(80) ENCODE lzo COLLATE case_insensitive,
    simagenamespace character varying(16) ENCODE lzo COLLATE case_insensitive,
    sinputschema character varying(64) ENCODE lzo COLLATE case_insensitive,
    slabel character varying(128) ENCODE lzo COLLATE case_insensitive,
    smodel character varying(64) ENCODE lzo COLLATE case_insensitive,
    sname character varying(64) ENCODE lzo COLLATE case_insensitive,
    snature character varying(64) ENCODE lzo COLLATE case_insensitive,
    tscreated timestamp without time zone ENCODE az64,
    tsend timestamp without time zone ENCODE az64,
    tslastcomputed timestamp without time zone ENCODE az64,
    tslastmodified timestamp without time zone ENCODE az64,
    tsproduction timestamp without time zone ENCODE az64,
    tsstart timestamp without time zone ENCODE az64,
    ianonymous smallint NOT NULL ENCODE az64,
    ideliverymappingid integer NOT NULL ENCODE az64,
    ivisitorfolderid integer NOT NULL ENCODE az64,
    tsweightend timestamp without time zone ENCODE az64,
    tsweightstart timestamp without time zone ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_insensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_insensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;