CREATE TABLE mktg_ops_tbls.adb_anlytc_hit (
    hit_id_high_low numeric(38,0) ENCODE az64,
    hit_id_high_low_fmt character varying(256) ENCODE lzo COLLATE case_sensitive,
    hit_time_gmt integer ENCODE az64,
    hit_tm_ts timestamp without time zone ENCODE az64,
    hit_tm_ts_str character varying(29) ENCODE lzo COLLATE case_sensitive,
    hit_id_high bigint ENCODE az64,
    hit_id_low bigint ENCODE az64,
    va_clsr_id integer ENCODE az64,
    visit_pg_num integer ENCODE az64,
    visit_ref_dmn character varying(50) ENCODE lzo COLLATE case_sensitive,
    va_nstnc_evnt integer ENCODE az64,
    evar48 character varying(30) ENCODE lzo COLLATE case_sensitive,
    evar49 character varying(50) ENCODE lzo COLLATE case_sensitive,
    vis_id_low bigint ENCODE az64,
    vis_id_high bigint ENCODE az64,
    vis_id_high_low numeric(38,0) ENCODE az64,
    vis_id_high_low_fmt character varying(256) ENCODE lzo COLLATE case_sensitive,
    mc_vis_id double precision ENCODE raw,
    rco_dntn_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    channel character varying(50) ENCODE lzo COLLATE case_sensitive,
    frst_prty_id character varying(50) ENCODE lzo COLLATE case_sensitive,
    curr_prcsd_file_nm character varying(256) ENCODE lzo COLLATE case_insensitive,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_insensitive,
    appl_src_cd character(4) NOT NULL ENCODE lzo COLLATE case_insensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;