CREATE TABLE mktg_ops_tbls.adb_nmswebapplogrcpdata_b401072026 (
    iwebapplogid integer NOT NULL ENCODE az64,
    byte0 smallint ENCODE az64,
    byte1 smallint ENCODE az64,
    byte2 smallint ENCODE az64,
    byte3 smallint ENCODE az64,
    byte4 smallint ENCODE az64,
    byte5 smallint ENCODE az64,
    byte6 smallint ENCODE az64,
    byte7 smallint ENCODE az64,
    byte8 smallint ENCODE az64,
    byte9 smallint ENCODE az64,
    byte10 smallint ENCODE az64,
    byte11 smallint ENCODE az64,
    byte12 smallint ENCODE az64,
    byte13 smallint ENCODE az64,
    byte14 smallint ENCODE az64,
    byte15 smallint ENCODE az64,
    byte16 smallint ENCODE az64,
    byte17 smallint ENCODE az64,
    byte18 smallint ENCODE az64,
    byte19 smallint ENCODE az64,
    byte20 smallint ENCODE az64,
    byte21 smallint ENCODE az64,
    byte22 smallint ENCODE az64,
    byte23 smallint ENCODE az64,
    boolean0 smallint ENCODE az64,
    boolean1 smallint ENCODE az64,
    boolean2 smallint ENCODE az64,
    boolean3 smallint ENCODE az64,
    boolean4 smallint ENCODE az64,
    boolean5 smallint ENCODE az64,
    boolean6 smallint ENCODE az64,
    boolean7 smallint ENCODE az64,
    boolean8 smallint ENCODE az64,
    boolean9 smallint ENCODE az64,
    boolean10 smallint ENCODE az64,
    boolean11 smallint ENCODE az64,
    boolean12 smallint ENCODE az64,
    boolean13 smallint ENCODE az64,
    boolean14 smallint ENCODE az64,
    boolean15 smallint ENCODE az64,
    boolean16 smallint ENCODE az64,
    boolean17 smallint ENCODE az64,
    boolean18 smallint ENCODE az64,
    boolean19 smallint ENCODE az64,
    boolean20 smallint ENCODE az64,
    boolean21 smallint ENCODE az64,
    boolean22 smallint ENCODE az64,
    boolean23 smallint ENCODE az64,
    boolean24 smallint ENCODE az64,
    boolean25 smallint ENCODE az64,
    boolean26 smallint ENCODE az64,
    boolean27 smallint ENCODE az64,
    boolean28 smallint ENCODE az64,
    boolean29 smallint ENCODE az64,
    boolean30 smallint ENCODE az64,
    boolean31 smallint ENCODE az64,
    boolean32 smallint ENCODE az64,
    boolean33 smallint ENCODE az64,
    string0 character varying(300) ENCODE lzo COLLATE case_sensitive,
    string1 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string10 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string11 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string12 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string13 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string14 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string15 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string16 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string2 character varying(300) ENCODE lzo COLLATE case_sensitive,
    string3 character varying(300) ENCODE lzo COLLATE case_sensitive,
    string4 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string5 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string6 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string7 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string8 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string9 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string17 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string18 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string19 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string20 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string21 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string22 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string23 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string24 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string25 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string26 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string27 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string28 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string29 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string30 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string31 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string32 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string33 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string34 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string35 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string36 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string37 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string38 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string39 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string40 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string41 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string42 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string43 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string44 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string45 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string46 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string47 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string48 character varying(255) ENCODE lzo COLLATE case_sensitive,
    int641 bigint ENCODE az64,
    long0 integer ENCODE az64,
    string50 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string51 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string52 character varying(255) ENCODE lzo COLLATE case_sensitive,
    mdata character varying(10000) ENCODE lzo COLLATE case_sensitive,
    datetime0 timestamp without time zone ENCODE az64,
    string49 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string53 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string54 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string55 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string56 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string57 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string58 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string59 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string60 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string61 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string62 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string63 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string64 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string65 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string71 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string72 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string73 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string74 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string76 character varying(255) ENCODE lzo COLLATE case_sensitive,
    string66 character varying(255) ENCODE lzo COLLATE case_sensitive,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;