CREATE TABLE mktg_ops_tbls.bzf_cnst_scr_simio (
    cnst_mstr_id bigint NOT NULL ENCODE raw distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE raw,
    sm_scrts timestamp without time zone ENCODE az64,
    sm_arc_disaster_scrval smallint ENCODE az64,
    sm_arc_active_scrval smallint ENCODE az64,
    sm_arc_lapsed_scrval smallint ENCODE az64,
    sm_arc_non_fr_scrval smallint ENCODE az64,
    sm_political_left_dnr_scrval smallint ENCODE az64,
    sm_political_right_dnr_scrval smallint ENCODE az64,
    sm_envirnmnt_dnr_scrval smallint ENCODE az64,
    sm_veteran_dnr_scrval smallint ENCODE az64,
    sm_health_dnr_scrval smallint ENCODE az64,
    sm_children_dnr_scrval smallint ENCODE az64,
    sm_religious_dnr_scrval smallint ENCODE az64,
    sm_humanitarian_dnr_scrval smallint ENCODE az64,
    sm_animal_dnr_scrval smallint ENCODE az64,
    sm_new_dnr_act_propnsty_scrval smallint ENCODE az64,
    sm_mid_level_upgrd_propnsty_scrval smallint ENCODE az64,
    sm_mnthly_sust_propnsty_scrval smallint ENCODE az64,
    sm_mjr_gift_propnsty_scrval smallint ENCODE az64,
    sm_pg_propnsty_scrval smallint ENCODE az64,
    sm_dnr_advsd_fund_propnsty_scrval smallint ENCODE az64,
    sm_rfm_dm_chanl_scrval numeric(20,10) ENCODE az64,
    sm_rfm_oln_chanl_scrval numeric(20,10) ENCODE az64,
    sm_rfm_tm_chanl_scrval numeric(20,10) ENCODE az64,
    sm_rfm_othr_chanl_scrval numeric(20,10) ENCODE az64,
    sm_rfm_lst_dntn_dt_scrval numeric(20,10) ENCODE az64,
    sm_rfm_lftm_dntn_cnt_scrval numeric(20,10) ENCODE az64,
    sm_rfm_lftm_dntn_amt_scrval numeric(20,10) ENCODE az64,
    sm_rfm_max_dntn_amt_scrval numeric(20,10) ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id, orig_cnst_mstr_id );