CREATE TABLE mktg_ops_tbls.bzfc_fact_phone_interaction_b401072026 (
    cnst_mstr_id bigint ENCODE zstd,
    orig_cnst_mstr_id bigint ENCODE zstd,
    campgn_key integer ENCODE zstd,
    script_key integer ENCODE zstd,
    dspstn_key integer ENCODE zstd,
    adtnl_reqst_key integer ENCODE zstd,
    unit_key integer ENCODE zstd,
    orig_unit_key integer ENCODE zstd,
    call_trans_key integer ENCODE zstd,
    unq_id character varying(30) ENCODE zstd COLLATE case_sensitive distkey,
    cmpgn_cd character varying(30) ENCODE zstd COLLATE case_sensitive,
    scrpt_num smallint ENCODE zstd,
    dspstn_id integer ENCODE zstd,
    dspstn1_cd character(2) ENCODE zstd COLLATE case_sensitive,
    dspstn2_cd character(2) ENCODE zstd COLLATE case_sensitive,
    addi_rqst_cd character(2) ENCODE zstd COLLATE case_sensitive,
    nk_ecode character varying(256) ENCODE zstd COLLATE case_sensitive,
    pgm_type character varying(10) ENCODE zstd COLLATE case_sensitive,
    sgmnt_dsc character varying(50) ENCODE zstd COLLATE case_sensitive,
    fiscal_yr smallint ENCODE zstd,
    qtr character(2) ENCODE zstd COLLATE case_sensitive,
    src_cd character varying(20) ENCODE zstd COLLATE case_sensitive,
    home_phn_num_cln character varying(256) ENCODE zstd COLLATE case_sensitive,
    mbl_phn_num_cln character varying(256) ENCODE zstd COLLATE case_sensitive,
    phn_line_typ character varying(8) ENCODE zstd COLLATE case_sensitive,
    call_dt date ENCODE zstd,
    call_start_ts timestamp without time zone ENCODE zstd,
    call_end_ts timestamp without time zone ENCODE zstd,
    elapsed_call_tm character varying(50) ENCODE zstd COLLATE case_sensitive,
    cmpgn_call_atmpt_cnt smallint ENCODE zstd,
    gift_amt numeric(15,2) ENCODE zstd,
    pledge_amt numeric(15,2) ENCODE zstd,
    phone_change_ind smallint ENCODE zstd,
    addr_change_ind smallint ENCODE zstd,
    name_change_ind smallint ENCODE zstd,
    email_change_ind smallint ENCODE zstd,
    is_cell_ind smallint ENCODE zstd,
    call_seqnc_num integer ENCODE zstd,
    scr1_id integer ENCODE zstd,
    scr1_val integer ENCODE zstd,
    scr2_id integer ENCODE zstd,
    scr2_val integer ENCODE zstd,
    scr3_id integer ENCODE zstd,
    scr3_val integer ENCODE zstd,
    decile smallint ENCODE zstd,
    cmnt character varying(40) ENCODE zstd COLLATE case_sensitive,
    curr_prcsd_file_nm character varying(255) ENCODE zstd COLLATE case_sensitive,
    dw_trans_ts timestamp without time zone ENCODE zstd,
    row_stat_cd character varying(1) ENCODE zstd COLLATE case_sensitive,
    appl_src_cd character varying(4) ENCODE zstd COLLATE case_sensitive,
    load_id smallint ENCODE zstd
)
DISTSTYLE KEY
SORTKEY ( dw_trans_ts );