CREATE TABLE mktg_ops_tbls.bzfc_pg_response_log (
    clnsd_first_nm character varying(20) ENCODE raw COLLATE case_sensitive,
    clnsd_last_nm character varying(80) ENCODE raw COLLATE case_sensitive,
    clnsd_email_addr character varying(100) ENCODE raw COLLATE case_sensitive,
    derived_campaign character varying(50) ENCODE raw COLLATE case_sensitive,
    first_response_dt date ENCODE az64,
    response_group_dsc character varying(10) ENCODE raw COLLATE case_sensitive,
    response_cnt smallint ENCODE az64,
    first_response_ts date ENCODE az64,
    match_lob_src character varying(4) ENCODE lzo COLLATE case_sensitive,
    match_typ character varying(50) ENCODE lzo COLLATE case_sensitive,
    cds_batch_number character varying(100) ENCODE lzo COLLATE case_sensitive,
    cds_sequence_number character varying(50) ENCODE lzo COLLATE case_sensitive,
    response_ts_src character varying(25) ENCODE lzo COLLATE case_sensitive,
    response_ts timestamp without time zone ENCODE az64,
    response_dt date ENCODE raw,
    site_url character varying(256) ENCODE lzo COLLATE case_sensitive,
    lander_type character varying(100) ENCODE lzo COLLATE case_sensitive,
    nk_ecode character varying(10) ENCODE lzo COLLATE case_sensitive,
    src_cd_src character varying(20) ENCODE lzo COLLATE case_sensitive,
    scr_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    cnst_mstr_id_src character varying(19) ENCODE lzo COLLATE case_sensitive,
    cnst_mstr_id bigint ENCODE az64,
    orig_cnst_mstr_id bigint ENCODE az64,
    ttl character varying(20) ENCODE lzo COLLATE case_sensitive,
    first_nm character varying(20) ENCODE lzo COLLATE case_sensitive,
    middle_nm character varying(40) ENCODE lzo COLLATE case_sensitive,
    last_nm character varying(80) ENCODE lzo COLLATE case_sensitive,
    sfx character varying(30) ENCODE lzo COLLATE case_sensitive,
    prf_ttl character varying(200) ENCODE lzo COLLATE case_sensitive,
    cmpny_nm character varying(200) ENCODE lzo COLLATE case_sensitive,
    birth_dt_src character varying(10) ENCODE lzo COLLATE case_sensitive,
    birth_dt date ENCODE az64,
    spouse_birth_dt_src character varying(10) ENCODE lzo COLLATE case_sensitive,
    spouse_birth_dt date ENCODE az64,
    addr_ln1 character varying(100) ENCODE lzo COLLATE case_sensitive,
    addr_ln2 character varying(100) ENCODE lzo COLLATE case_sensitive,
    addr_ln3 character varying(100) ENCODE lzo COLLATE case_sensitive,
    city character varying(25) ENCODE lzo COLLATE case_sensitive,
    state character varying(2) ENCODE lzo COLLATE case_sensitive,
    zip_cd character varying(10) ENCODE lzo COLLATE case_sensitive,
    phone_num character varying(20) ENCODE lzo COLLATE case_sensitive,
    phone_mobile_ind smallint ENCODE az64,
    phone_home_ind smallint ENCODE az64,
    email_addr character varying(100) ENCODE lzo COLLATE case_sensitive,
    cntct_prfrnc character varying(25) ENCODE lzo COLLATE case_sensitive,
    cntct_prfrnc_phone_ind smallint ENCODE az64,
    cntct_prfrnc_text_ind smallint ENCODE az64,
    cntct_prfrnc_email_ind smallint ENCODE az64,
    cdrp_pg_info_request_pg_information character varying(5) ENCODE lzo COLLATE case_sensitive,
    cdrp_pg_confirm_arc_in_will character varying(5) ENCODE lzo COLLATE case_sensitive,
    cga_age_payments_begin character varying(100) ENCODE lzo COLLATE case_sensitive,
    cga_5000 character varying(5) ENCODE lzo COLLATE case_sensitive,
    cga_10000 character varying(5) ENCODE lzo COLLATE case_sensitive,
    cga_50000 character varying(5) ENCODE lzo COLLATE case_sensitive,
    cga_100000 character varying(5) ENCODE lzo COLLATE case_sensitive,
    cga_other character varying(132) ENCODE lzo COLLATE case_sensitive,
    cga_fdbk character varying(256) ENCODE lzo COLLATE case_sensitive,
    wg_rqst character varying(5) ENCODE lzo COLLATE case_sensitive,
    wg_arc_in_will character varying(5) ENCODE lzo COLLATE case_sensitive,
    wg_intend_arc_in_will character varying(5) ENCODE lzo COLLATE case_sensitive,
    wg_consider_arc_in_will character varying(5) ENCODE lzo COLLATE case_sensitive,
    wg_fdbk character varying(256) ENCODE lzo COLLATE case_sensitive,
    interest_in_life_income_gift_w_stock character varying(5) ENCODE lzo COLLATE case_sensitive,
    interest_in_life_income_gift_w_real_estate character varying(5) ENCODE lzo COLLATE case_sensitive,
    interest_in_life_income_gift_w_ira character varying(5) ENCODE lzo COLLATE case_sensitive,
    interest_in_gift_in_will character varying(5) ENCODE lzo COLLATE case_sensitive,
    interest_in_gift_outside_will character varying(5) ENCODE lzo COLLATE case_sensitive,
    interest_in_life_income_gifts character varying(5) ENCODE lzo COLLATE case_sensitive,
    interest_in_ira_qcd_gifts character varying(5) ENCODE lzo COLLATE case_sensitive,
    consider_charity_in_will character varying(5) ENCODE lzo COLLATE case_sensitive,
    email_opt_in character varying(5) ENCODE lzo COLLATE case_sensitive,
    giving_reason_arc_was_there_for_me character varying(5) ENCODE lzo COLLATE case_sensitive,
    giving_reason_provide_general_support character varying(5) ENCODE lzo COLLATE case_sensitive,
    giving_reason_respond_to_local_or_national_disasters_or_emergencies character varying(5) ENCODE lzo COLLATE case_sensitive,
    giving_reason_tax_purposes character varying(5) ENCODE lzo COLLATE case_sensitive,
    giving_reason_believe_in_arc_mission character varying(5) ENCODE lzo COLLATE case_sensitive,
    giving_reason_frnd_fmly_mbr_suprtr character varying(5) ENCODE lzo COLLATE case_sensitive,
    influential_person_in_your_life character varying(5) ENCODE lzo COLLATE case_sensitive,
    has_the_arc_brought_hope_and_help_to_your_family_or_community character varying(5) ENCODE lzo COLLATE case_sensitive,
    arc_programs_health_safety_education character varying(5) ENCODE lzo COLLATE case_sensitive,
    arc_programs_support_for_armed_forces character varying(5) ENCODE lzo COLLATE case_sensitive,
    arc_programs_blood_services character varying(5) ENCODE lzo COLLATE case_sensitive,
    arc_programs_domestic_disaster_relief character varying(5) ENCODE lzo COLLATE case_sensitive,
    arc_programs_international_relief character varying(5) ENCODE lzo COLLATE case_sensitive,
    arc_programs_important_to_provide_arc_services_in_future character varying(50) ENCODE lzo COLLATE case_sensitive,
    means_of_support_check_credit_card character varying(50) ENCODE lzo COLLATE case_sensitive,
    means_of_support_volunteering character varying(50) ENCODE lzo COLLATE case_sensitive,
    means_of_support_gift_in_your_will character varying(50) ENCODE lzo COLLATE case_sensitive,
    means_of_support_gift_in_your_will_honoring_a_loved_one character varying(50) ENCODE lzo COLLATE case_sensitive,
    means_of_support_beneficiary_designation character varying(50) ENCODE lzo COLLATE case_sensitive,
    means_of_support_gift_ira_chrtbl_dstrbtn character varying(50) ENCODE lzo COLLATE case_sensitive,
    means_of_support_blood_donation character varying(50) ENCODE lzo COLLATE case_sensitive,
    means_of_support_gifts_that_pay_you_income_for_life character varying(50) ENCODE lzo COLLATE case_sensitive,
    means_of_support_gifts_of_other_assets_stock_real_estate_bank_acct character varying(50) ENCODE lzo COLLATE case_sensitive,
    marital_status character varying(50) ENCODE lzo COLLATE case_sensitive,
    chldrn character varying(5) ENCODE lzo COLLATE case_sensitive,
    grndchldrn character varying(5) ENCODE lzo COLLATE case_sensitive,
    arc_story character varying(4000) ENCODE lzo COLLATE case_sensitive,
    age character varying(20) ENCODE lzo COLLATE case_sensitive,
    cds_image_id character varying(50) ENCODE raw COLLATE case_sensitive,
    gift_typ character varying(50) ENCODE lzo COLLATE case_sensitive,
    gift_created_dt_src character varying(10) ENCODE lzo COLLATE case_sensitive,
    gift_created_dt date ENCODE az64,
    dcmnt_created_dt_src character varying(10) ENCODE lzo COLLATE case_sensitive,
    dcmnt_created_dt date ENCODE az64,
    est_gift_value_amt numeric(15,2) ENCODE az64,
    gift_value_typ character varying(5) ENCODE lzo COLLATE case_sensitive,
    plan_typ character varying(20) ENCODE lzo COLLATE case_sensitive,
    contigent_lvl character varying(5) ENCODE lzo COLLATE case_sensitive,
    message character varying(1500) ENCODE lzo COLLATE case_sensitive,
    don_ext_id character varying(30) ENCODE lzo COLLATE case_sensitive,
    frwl_gift_id character varying(30) ENCODE raw COLLATE case_sensitive,
    asset_type character varying(100) ENCODE lzo COLLATE case_sensitive,
    fincl_inst character varying(100) ENCODE lzo COLLATE case_sensitive,
    prfrd_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    chng_made_dt_src character varying(10) ENCODE lzo COLLATE case_sensitive,
    chng_made_dt date ENCODE az64,
    old_gift_value_amt numeric(15,2) ENCODE az64,
    new_gift_value_amt numeric(15,2) ENCODE az64,
    jnt_gft_ind smallint ENCODE az64,
    addtnl_nm character varying(50) ENCODE lzo COLLATE case_sensitive,
    anmty_ind smallint ENCODE az64,
    gft_vhcl_dsc character varying(50) ENCODE lzo COLLATE case_sensitive,
    dsgntn_dsc character varying(30) ENCODE lzo COLLATE case_sensitive,
    gft_cmnts character varying(256) ENCODE lzo COLLATE case_sensitive,
    mds_pg_response_typ character varying(30) ENCODE lzo COLLATE case_sensitive,
    hist_seqnum bigint ENCODE raw distkey,
    history_record_id integer ENCODE raw,
    pgc_response_id integer ENCODE raw,
    mds_unq_id character varying(30) ENCODE raw COLLATE case_sensitive,
    rcrdg_file_nm character varying(25) ENCODE lzo COLLATE case_sensitive,
    curr_prcsd_file_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    last_match_proc_dt date ENCODE az64,
    stuart_list_proc_dt date ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( clnsd_first_nm, clnsd_last_nm, clnsd_email_addr, derived_campaign, response_group_dsc, response_dt, cds_image_id, frwl_gift_id, hist_seqnum, history_record_id, pgc_response_id, mds_unq_id );