CREATE TABLE mktg_ops_tbls.bzfc_fact_sms_interaction (
    cnst_mstr_id bigint ENCODE az64,
    irecipientid integer ENCODE az64,
    recipient_cnst_mstr_id bigint ENCODE az64,
    mobile_num character varying(20) ENCODE lzo COLLATE case_sensitive,
    unit_key integer ENCODE az64,
    nk_intrctn_id integer ENCODE az64,
    delivery_key integer ENCODE az64,
    campgn_key integer ENCODE az64,
    channel_key integer ENCODE az64,
    intrctn_status_key integer ENCODE az64,
    src_key bigint ENCODE az64,
    src_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    subsrc_cd character varying(50) ENCODE lzo COLLATE case_sensitive,
    delivery_status_cd character varying(50) ENCODE lzo COLLATE case_sensitive,
    delivery_status_dsc character varying(200) ENCODE lzo COLLATE case_sensitive,
    intrctn_status_id smallint ENCODE az64,
    intrctn_status_dsc character varying(200) ENCODE lzo COLLATE case_sensitive,
    channel_dsc character varying(19) ENCODE lzo COLLATE case_sensitive,
    intrctn_ts timestamp without time zone ENCODE az64,
    intrctn_dt date ENCODE az64,
    sms_intrctn_ind smallint ENCODE az64,
    srcsys_trans_ts timestamp without time zone ENCODE az64,
    dw_trans_ts timestamp without time zone ENCODE az64,
    row_stat_cd character varying(1) ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) ENCODE lzo COLLATE case_sensitive,
    load_id smallint ENCODE az64
)
DISTSTYLE AUTO;