CREATE TABLE mktg_ops_tbls.dm_campaign_hist (
    cnst_mstr_id bigint NOT NULL ENCODE az64 distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE az64,
    fr_last_ta_acct_id bigint NOT NULL ENCODE az64,
    finder_number character varying(45) NOT NULL ENCODE lzo COLLATE case_sensitive,
    chapt_id character varying(5) ENCODE lzo COLLATE case_sensitive,
    greeting character varying(100) ENCODE lzo COLLATE case_sensitive,
    personalization character varying(100) ENCODE lzo COLLATE case_sensitive,
    ttl character varying(20) ENCODE lzo COLLATE case_sensitive,
    first_nm character varying(30) ENCODE lzo COLLATE case_sensitive,
    middle_nm character varying(30) ENCODE lzo COLLATE case_sensitive,
    last_nm character varying(50) ENCODE lzo COLLATE case_sensitive,
    suffix character varying(20) ENCODE lzo COLLATE case_sensitive,
    full_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    secondary_contact_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    company_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    addr_line1 character varying(50) ENCODE lzo COLLATE case_sensitive,
    addr_line2 character varying(50) ENCODE lzo COLLATE case_sensitive,
    city character varying(30) ENCODE lzo COLLATE case_sensitive,
    state character varying(2) ENCODE lzo COLLATE case_sensitive,
    zip_cd character varying(9) ENCODE lzo COLLATE case_sensitive,
    delivery_pt character varying(2) ENCODE lzo COLLATE case_sensitive,
    check_digit character varying(1) ENCODE lzo COLLATE case_sensitive,
    carrier_rt character varying(4) ENCODE lzo COLLATE case_sensitive,
    line_of_travel character varying(5) ENCODE lzo COLLATE case_sensitive,
    combo_src_cd character varying(50) ENCODE lzo COLLATE case_sensitive,
    country character varying(25) ENCODE lzo COLLATE case_sensitive,
    largest_gift_dt_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    largest_gift_dt date ENCODE az64,
    largest_gift_amt numeric(13,2) ENCODE az64,
    last_gift_dt_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    last_gift_dt date ENCODE az64,
    last_gift_amt numeric(13,2) ENCODE az64,
    first_gift_dt_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    first_gift_dt date ENCODE az64,
    first_gift_amt numeric(13,2) ENCODE az64,
    lifetime_no_of_gifts integer ENCODE az64,
    motivtn_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    kit character varying(2) ENCODE lzo COLLATE case_sensitive,
    vrsn character varying(2) ENCODE lzo COLLATE case_sensitive,
    ask1 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask2 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask3 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask4 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask5 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask6 character varying(9) ENCODE lzo COLLATE case_sensitive,
    provide1 character varying(30) ENCODE lzo COLLATE case_sensitive,
    provide2 character varying(30) ENCODE lzo COLLATE case_sensitive,
    provide3 character varying(30) ENCODE lzo COLLATE case_sensitive,
    provide4 character varying(30) ENCODE lzo COLLATE case_sensitive,
    provide5 character varying(30) ENCODE lzo COLLATE case_sensitive,
    provide6 character varying(30) ENCODE lzo COLLATE case_sensitive,
    cell_subsrc_cd character varying(40) ENCODE lzo COLLATE case_sensitive,
    email_addr character varying(100) ENCODE lzo COLLATE case_sensitive,
    treatmnt_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    segment_cd character varying(30) ENCODE lzo COLLATE case_sensitive,
    treatment_cd_src character varying(30) ENCODE lzo COLLATE case_sensitive,
    treatmnt_cd character varying(2) ENCODE lzo COLLATE case_sensitive,
    aprm_src_cd character varying(55) ENCODE lzo COLLATE case_sensitive,
    scanline_cd character varying(60) ENCODE lzo COLLATE case_sensitive,
    drop_date_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    drop_dt date ENCODE raw,
    target_tag_scr character varying(20) ENCODE lzo COLLATE case_sensitive,
    vigintile smallint ENCODE az64,
    mods_fr_scr numeric(13,4) ENCODE az64,
    csreg_code character varying(5) ENCODE lzo COLLATE case_sensitive,
    file_cd character(4) ENCODE lzo COLLATE case_sensitive,
    trans_typ_cd character varying(4) ENCODE lzo COLLATE case_sensitive,
    vendor_src_cd character varying(4) ENCODE lzo COLLATE case_sensitive,
    curr_prcsd_file_nm character varying(255) ENCODE lzo COLLATE case_sensitive,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( drop_dt );