CREATE TABLE mktg_ops_tbls.fact_interaction_ff_b401072026 (
    cnst_mstr_id bigint ENCODE az64 distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    cnst_hsld_id character varying(18) ENCODE lzo COLLATE case_sensitive,
    cell_id integer ENCODE az64,
    cell_src_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    cell_subsrc_cd character varying(40) ENCODE lzo COLLATE case_sensitive,
    motivtn_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    fr_last_ta_acct_id integer ENCODE az64,
    finder_number character varying(45) NOT NULL ENCODE lzo COLLATE case_sensitive,
    offer_id integer ENCODE az64,
    treatment_id integer ENCODE az64,
    activity_id integer ENCODE az64,
    segementation_id integer ENCODE az64,
    segment_id integer ENCODE az64,
    segmnt_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    outbnd_id integer ENCODE az64,
    email_id integer ENCODE az64,
    email_sent_dt date ENCODE az64,
    to_domain character varying(175) ENCODE lzo COLLATE case_sensitive,
    drop_dt date ENCODE raw,
    update_dt date ENCODE az64,
    last_dntn_dt date ENCODE az64,
    last_dntn_amt numeric(13,2) ENCODE az64,
    chpt_affl character varying(150) ENCODE lzo COLLATE case_sensitive,
    submitter_nm character varying(150) ENCODE lzo COLLATE case_sensitive,
    chpt_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    cntct_dt date ENCODE az64,
    run_dt date ENCODE az64,
    run_id integer ENCODE az64,
    mailed_ind smallint DEFAULT 0 ENCODE az64,
    supressed_ind smallint DEFAULT 0 ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE raw
)
DISTSTYLE KEY;