CREATE TABLE mktg_ops_tbls.fact_interaction_aprm (
    cnst_mstr_id bigint NOT NULL ENCODE raw distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE az64,
    cnst_hsld_id character varying(18) ENCODE lzo COLLATE case_sensitive,
    finder_number character varying(45) ENCODE lzo COLLATE case_sensitive,
    cell_src_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    cell_subsrc_cd character varying(40) ENCODE lzo COLLATE case_sensitive,
    motivtn_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    fr_last_ta_acct_id integer ENCODE az64,
    offer_id integer ENCODE az64,
    treatment_id integer ENCODE az64,
    activity_id integer ENCODE az64,
    segmentation_id integer ENCODE az64,
    segment_id integer ENCODE az64,
    segmnt_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    outbnd_id integer ENCODE az64,
    email_id integer ENCODE az64,
    email_sent_dt date ENCODE az64,
    to_domain character varying(175) ENCODE lzo COLLATE case_sensitive,
    drop_dt date ENCODE az64,
    update_dt date ENCODE az64,
    last_dntn_dt date ENCODE az64,
    last_dntn_amt numeric(13,2) ENCODE az64,
    chpt_affl character varying(150) ENCODE lzo COLLATE case_sensitive,
    submitter_nm character varying(150) ENCODE lzo COLLATE case_sensitive,
    chpt_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    cntct_dt date ENCODE az64,
    run_dt date ENCODE az64,
    run_id integer ENCODE az64,
    mailed_ind boolean DEFAULT 0 ENCODE raw,
    supressed_ind boolean DEFAULT 0 ENCODE raw,
    call_ind boolean DEFAULT 0 ENCODE raw,
    call_result character varying(20) ENCODE lzo COLLATE case_sensitive,
    do_not_call_ind boolean DEFAULT 0 ENCODE raw,
    target_tag_scr character varying(20) ENCODE lzo COLLATE case_sensitive,
    vigintile smallint ENCODE az64,
    mods_fr_scr numeric(13,4) ENCODE az64,
    ask1 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask2 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask3 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask4 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask5 character varying(9) ENCODE lzo COLLATE case_sensitive,
    ask6 character varying(9) ENCODE lzo COLLATE case_sensitive,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE bytedict COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( dw_trans_ts, cnst_mstr_id );