CREATE TABLE mktg_ops_tbls.gofundraise_donor (
    chapter_cd character varying(5) ENCODE lzo COLLATE case_sensitive,
    cnst_mstr_id bigint ENCODE az64,
    cnst_prefix smallint ENCODE az64,
    cnst_first_nm character varying(50) ENCODE lzo COLLATE case_sensitive,
    cnst_middle_nm character varying(50) ENCODE lzo COLLATE case_sensitive,
    cnst_last_nm character varying(50) ENCODE lzo COLLATE case_sensitive,
    address_line1a character varying(256) ENCODE lzo COLLATE case_sensitive,
    address_line2_a character varying(256) ENCODE lzo COLLATE case_sensitive,
    city_a character varying(100) ENCODE lzo COLLATE case_sensitive,
    state_a character varying(30) ENCODE lzo COLLATE case_sensitive,
    zip_a character varying(10) ENCODE lzo COLLATE case_sensitive,
    address_line1_b character varying(256) ENCODE lzo COLLATE case_sensitive,
    address_line2_b character varying(256) ENCODE lzo COLLATE case_sensitive,
    city_b character varying(100) ENCODE lzo COLLATE case_sensitive,
    state_b character varying(30) ENCODE lzo COLLATE case_sensitive,
    zip_b character varying(10) ENCODE lzo COLLATE case_sensitive,
    phone_a character varying(15) ENCODE lzo COLLATE case_sensitive,
    phone_b character varying(15) ENCODE lzo COLLATE case_sensitive,
    phone_c character varying(15) ENCODE lzo COLLATE case_sensitive,
    email_a character varying(100) ENCODE lzo COLLATE case_sensitive,
    email_b character varying(100) ENCODE lzo COLLATE case_sensitive,
    job_title character varying(100) ENCODE lzo COLLATE case_sensitive,
    company_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    remove_flg character varying(1) ENCODE lzo COLLATE case_sensitive,
    notes character varying(256) ENCODE lzo COLLATE case_sensitive,
    processed_file_nm character varying(256) ENCODE lzo COLLATE case_sensitive,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64
)
DISTSTYLE AUTO;