CREATE TABLE mktg_ops_tbls.mobile_commons_active (
    id integer ENCODE raw distkey,
    phone_num character varying(20) ENCODE lzo COLLATE case_sensitive,
    email character varying(34) ENCODE lzo COLLATE case_sensitive,
    first_nm character varying(16) ENCODE lzo COLLATE case_sensitive,
    last_nm character varying(18) ENCODE lzo COLLATE case_sensitive,
    status character varying(17) ENCODE lzo COLLATE case_sensitive,
    description smallint ENCODE az64,
    street1 character varying(43) ENCODE lzo COLLATE case_sensitive,
    street2 character varying(61) ENCODE lzo COLLATE case_sensitive,
    city character varying(23) ENCODE lzo COLLATE case_sensitive,
    state character varying(2) ENCODE lzo COLLATE case_sensitive,
    postal_cd integer ENCODE az64,
    country character varying(2) ENCODE lzo COLLATE case_sensitive,
    congressional_district character varying(5) ENCODE lzo COLLATE case_sensitive,
    state_upper_district character varying(5) ENCODE lzo COLLATE case_sensitive,
    state_lower_district character varying(6) ENCODE lzo COLLATE case_sensitive,
    split_district character varying(2) ENCODE lzo COLLATE case_sensitive,
    latitude numeric(8,6) ENCODE az64,
    longitude numeric(10,6) ENCODE az64,
    precision1 character varying(21) ENCODE lzo COLLATE case_sensitive,
    geocoded_city character varying(18) ENCODE lzo COLLATE case_sensitive,
    geocoded_state character varying(2) ENCODE lzo COLLATE case_sensitive,
    geocoded_postal_cd integer ENCODE az64,
    geocoded_country character varying(2) ENCODE lzo COLLATE case_sensitive,
    carrier_nm character varying(34) ENCODE lzo COLLATE case_sensitive,
    created_ts timestamp without time zone ENCODE az64,
    source_typ character varying(14) ENCODE lzo COLLATE case_sensitive,
    source_nm character varying(26) ENCODE lzo COLLATE case_sensitive,
    opted_out_at smallint ENCODE az64,
    opt_out_source smallint ENCODE az64,
    opt_in_2010_2015_disaster character varying(3) ENCODE lzo COLLATE case_sensitive,
    opt_in_fy15_disaster character varying(3) ENCODE lzo COLLATE case_sensitive,
    opt_in_fy16_disaster smallint ENCODE az64,
    opt_in_fy17_disaster character varying(8) ENCODE lzo COLLATE case_sensitive,
    opt_in_redcross character varying(3) ENCODE lzo COLLATE case_sensitive,
    opt_in_assist character varying(3) ENCODE lzo COLLATE case_sensitive,
    opt_in_donate character varying(3) ENCODE lzo COLLATE case_sensitive,
    opt_in_file smallint ENCODE az64,
    opt_in_prevent character varying(3) ENCODE lzo COLLATE case_sensitive,
    opt_in_app_download character varying(12) ENCODE lzo COLLATE case_sensitive,
    opt_in_engagement character varying(3) ENCODE lzo COLLATE case_sensitive,
    opt_in_test smallint ENCODE az64,
    opt_in_online character varying(3) ENCODE lzo COLLATE case_sensitive,
    donation_amt smallint ENCODE az64,
    opt_out_blood_ask smallint ENCODE az64,
    active_fundraiser character varying(3) ENCODE lzo COLLATE case_sensitive
)
DISTSTYLE KEY
SORTKEY ( id );