CREATE TABLE mktg_ops_tbls.phone_interaction_sustnr_upgr (
    cnst_mstr_id bigint NOT NULL ENCODE az64 distkey,
    orig_cnst_mstr_id bigint ENCODE az64,
    cmpgn_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    first_nm character varying(20) ENCODE lzo COLLATE case_sensitive,
    last_nm character varying(20) ENCODE lzo COLLATE case_sensitive,
    addr_ln1 character varying(50) ENCODE lzo COLLATE case_sensitive,
    addr_ln2 character varying(50) ENCODE lzo COLLATE case_sensitive,
    city character varying(30) ENCODE lzo COLLATE case_sensitive,
    state character(2) ENCODE lzo COLLATE case_sensitive,
    zip_cd character varying(5) ENCODE lzo COLLATE case_sensitive,
    phn_num character varying(20) ENCODE lzo COLLATE case_sensitive,
    email_addr character varying(50) ENCODE lzo COLLATE case_sensitive,
    last_sstnr_dt date ENCODE az64,
    last_sstnr_amt numeric(13,2) ENCODE az64,
    upgrd_amt numeric(13,2) ENCODE az64,
    new_tot_amt numeric(13,2) ENCODE az64,
    dsgntn character varying(30) ENCODE lzo COLLATE case_sensitive,
    subscrptn_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    rco_subscrptn_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    pmt_typ character varying(20) ENCODE lzo COLLATE case_sensitive,
    sustnr_match_ind smallint ENCODE az64,
    curr_prcsd_file_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE raw,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( dw_trans_ts );