CREATE TABLE mktg_ops_tbls.rr_rqq_rql_file_xref (
    src_cd character varying(20) ENCODE raw COLLATE case_sensitive distkey,
    drop_dt_src character varying(20) ENCODE lzo COLLATE case_sensitive,
    drop_dt date ENCODE az64,
    motivtn_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    qty integer ENCODE az64,
    kit_cd character varying(2) ENCODE lzo COLLATE case_sensitive,
    kit_cd_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    segmnt_cd character varying(3) ENCODE raw COLLATE case_sensitive,
    segmnt_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    file_cd character varying(4) ENCODE lzo COLLATE case_sensitive,
    file_cd_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    select_grp_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    superdupe_ind smallint ENCODE az64,
    list_typ character varying(20) ENCODE lzo COLLATE case_sensitive,
    list_cost_est_amt numeric(13,2) ENCODE az64,
    ppp_cost_est_amt numeric(13,2) ENCODE az64,
    list_cost_act_amt numeric(13,2) ENCODE az64,
    ppp_cost_act_amt numeric(13,2) ENCODE az64,
    cpp numeric(8,5) ENCODE az64,
    cpm numeric(13,2) ENCODE az64,
    recency character varying(48) ENCODE lzo COLLATE case_sensitive,
    gift_size character varying(42) ENCODE lzo COLLATE case_sensitive,
    tier character varying(47) ENCODE lzo COLLATE case_sensitive,
    curr_prcsd_file_nm character varying(256) ENCODE lzo COLLATE case_sensitive,
    dw_trans_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) ENCODE lzo COLLATE case_sensitive,
    load_id integer ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( src_cd, segmnt_cd );