CREATE TABLE mktg_ops_tbls.srvy_rgnl_ldrshp (
    snapshot_ts timestamp without time zone ENCODE az64,
    history_record_ts timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    adnc_mbr_id integer ENCODE az64,
    cnst_mstr_id integer ENCODE az64,
    orig_cnst_mstr_id integer ENCODE az64,
    last_nm character varying(30) ENCODE lzo COLLATE case_sensitive,
    email character varying(30) ENCODE lzo COLLATE case_sensitive,
    survey_nm character varying(128) ENCODE lzo COLLATE case_sensitive,
    survey_period character varying(16) ENCODE lzo COLLATE case_sensitive,
    edrtl_respns_period_key integer ENCODE az64,
    edrtl_respns_period character varying(50) ENCODE lzo COLLATE case_sensitive,
    division_cd character(4) ENCODE lzo COLLATE case_sensitive,
    division_dsc character varying(40) ENCODE lzo COLLATE case_sensitive,
    division_dsc_abbr character varying(40) ENCODE lzo COLLATE case_sensitive,
    nk_ecode character varying(255) ENCODE lzo COLLATE case_sensitive,
    cs_region_nm character varying(250) ENCODE lzo COLLATE case_sensitive,
    cs_region_nm_abbr character varying(250) ENCODE lzo COLLATE case_sensitive,
    vol_position character varying(382) ENCODE lzo COLLATE case_sensitive,
    position_category character varying(5) ENCODE lzo COLLATE case_sensitive,
    tmwrk_lvl_rtng1 smallint ENCODE az64,
    tmwrk_lvl_rtng_dsc character varying(9) ENCODE lzo COLLATE case_sensitive,
    embrcd_ldr_rtng_composite smallint ENCODE az64,
    embrcd_ldr_rtng_composite_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    ed_focus_five_key_rsp_rtng smallint ENCODE az64,
    ed_focus_five_key_rsp_rtng_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    ed_have_sprt_rtng smallint ENCODE az64,
    ed_have_sprt_rtng_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    mutual_rspct_rtng smallint ENCODE az64,
    mutual_rspct_rtng_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    team_cmtmnt_rtng smallint ENCODE az64,
    team_cmtmnt_rtng_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    held_accntbl_rtng smallint ENCODE az64,
    held_accntbl_rtng_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    lead_by_exmpl_lob_rtng smallint ENCODE az64,
    lead_by_exmpl_lob_rtng_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    ed_aware_ind integer ENCODE az64,
    arc_face_srvg_composite integer ENCODE az64,
    arc_face_srvg_composite_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    rltnshp_bldg_cpcty_composite integer ENCODE az64,
    rltnshp_bldg_cpcty_composite_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    chptr_board_dvlpmnt_composite integer ENCODE az64,
    chptr_board_dvlpmnt_composite_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    cmmnty_ldr_dvlpmnt_composite integer ENCODE az64,
    cmmnty_ldr_dvlpmnt_composite_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    tmwrk_inclsn_envrnmnt_composite integer ENCODE az64,
    tmwrk_inclsn_envrnmnt_composite_dsc character varying(13) ENCODE lzo COLLATE case_sensitive,
    ed_mng_evnt_ind smallint ENCODE az64,
    ed_lcl_bldg_mntnc_ind smallint ENCODE az64,
    ed_frnt_dsk_ind smallint ENCODE az64,
    ed_offc_mngmnt_ind smallint ENCODE az64,
    ed_vlntr_cmplnt_ind smallint ENCODE az64,
    ed_clnt_srvc_dlvry_ind smallint ENCODE az64,
    ed_other_ind smallint ENCODE az64,
    ed_other_txt_dsc character varying(255) ENCODE lzo COLLATE case_sensitive,
    ed_focus_area_total smallint ENCODE az64,
    ed_focus_outside_top5_ind integer ENCODE az64,
    rlt_addtnl_cmt character varying(10000) ENCODE lzo COLLATE case_sensitive,
    ed_addtnl_cmt character varying(10000) ENCODE lzo COLLATE case_sensitive,
    ed_addtnl_sprt_cmt character varying(10000) ENCODE lzo COLLATE case_sensitive,
    srcsys_trans_ts timestamp without time zone ENCODE az64,
    dw_trans_ts timestamp with time zone ENCODE az64,
    row_stat_cd character varying(1) ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) ENCODE lzo COLLATE case_sensitive,
    load_id integer ENCODE az64
)
DISTSTYLE AUTO
SORTKEY ( snapshot_ts );