CREATE TABLE mktg_ops_tbls.srvy_new_anvrsy_vlntr_rspns (
    snapshot_ts timestamp without time zone ENCODE az64,
    history_record_ts timestamp without time zone ENCODE az64,
    history_record_id integer ENCODE az64,
    adnc_mbr_id integer ENCODE az64,
    cnst_mstr_id bigint ENCODE az64,
    orig_cnst_mstr_id bigint ENCODE az64,
    last_nm character varying(255) ENCODE lzo COLLATE case_insensitive,
    email character varying(255) ENCODE lzo COLLATE case_insensitive,
    survey_nm character varying(255) ENCODE lzo COLLATE case_insensitive,
    vlntr_length character varying(75) ENCODE lzo COLLATE case_insensitive,
    a2_blood_svc_ind smallint ENCODE az64,
    b2_gen_admin_sprt_srvc_ind smallint ENCODE az64,
    c2_saf_srvc_ind smallint ENCODE az64,
    d2_comnty_srvc_ind smallint ENCODE az64,
    e2_health_safety_srvc_ind smallint ENCODE az64,
    f2_vlntr_srvc_ind smallint ENCODE az64,
    g2_dstr_srvc_ind smallint ENCODE az64,
    h2_intl_srvc_ind smallint ENCODE az64,
    i2_youth_prgrm_srvc_ind smallint ENCODE az64,
    j2_fr_srvc_ind smallint ENCODE az64,
    k2_ldrshp_ind smallint ENCODE az64,
    l2_other_srvc_ind smallint ENCODE az64,
    vol_area_no_answer character varying(3) ENCODE lzo COLLATE case_sensitive,
    other_srvc_cmt character varying(12000) ENCODE lzo COLLATE case_insensitive,
    vlntr_xprnc_rtng smallint ENCODE az64,
    vlntr_xprnc_rtng_dsc character varying(50) ENCODE lzo COLLATE case_insensitive,
    rcmnd_frnd_vlntr_rtng smallint ENCODE az64,
    rcmnd_frnd_vlntr_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    why_scr_cmt character varying(12000) ENCODE lzo COLLATE case_insensitive,
    a6_vlntr_sprt_rtng smallint ENCODE az64,
    a6_vlntr_sprt_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    b6_expctn_rtng smallint ENCODE az64,
    b6_expctn_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    c6_trng_mtrl_rtng smallint ENCODE az64,
    c6_trng_mtrl_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    d6_tmwrk_good_rtng smallint ENCODE az64,
    d6_tmwrk_good_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    e6_team_value_rtng smallint ENCODE az64,
    e6_team_value_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    f6_rspct_sprvsr_rtng smallint ENCODE az64,
    f6_rspct_sprvsr_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    g6_bhvr_cnstnt_rtng smallint ENCODE az64,
    g6_bhvr_cnstnt_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    h6_prspctv_value_rtng smallint ENCODE az64,
    h6_prspctv_value_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    i6_vlntr_cont_rtng smallint ENCODE az64,
    i6_vlntr_cont_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    vlntr_exp_cmt character varying(12000) ENCODE lzo COLLATE case_insensitive,
    vlntr_hrs_value smallint ENCODE az64,
    vlntr_hrs_dsc character varying(50) ENCODE lzo COLLATE case_insensitive,
    a9_dntd_bld_ind smallint ENCODE az64,
    b9_dntd_mny_ind smallint ENCODE az64,
    c9_prprdns_app_ind smallint ENCODE az64,
    d9_hs_crs_ind smallint ENCODE az64,
    e9_ref_fmly_ind smallint ENCODE az64,
    f9_none_ind smallint ENCODE az64,
    l12mo_have_you_no_answer smallint ENCODE az64,
    a10_vlntr_exprnc_easy_rtng smallint ENCODE az64,
    a10_vlntr_exprnc_easy_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    b10_vlntr_cnctn_usfl_rtng smallint ENCODE az64,
    b10_vlntr_cnctn_usfl_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    c10_vlntr_cnctn_easy_rtng smallint ENCODE az64,
    c10_vlntr_cnctn_easy_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    a11_arc_cmptr_rtng smallint ENCODE az64,
    a11_arc_cmptr_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    b11_arc_email_rtng smallint ENCODE az64,
    b11_arc_email_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    c11_arc_xchng_rtng smallint ENCODE az64,
    c11_arc_xchng_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    d11_arc_edge_rtng smallint ENCODE az64,
    d11_arc_edge_rtng_dsc character varying(25) ENCODE lzo COLLATE case_insensitive,
    arc_edctn_lvl_value smallint ENCODE az64,
    arc_edctn_lvl_dsc character varying(50) ENCODE lzo COLLATE case_insensitive,
    vlntr_dscrptn_value smallint ENCODE az64,
    vlntr_dscrptn_dsc character varying(50) ENCODE lzo COLLATE case_insensitive,
    dw_create_ts timestamp without time zone ENCODE az64,
    dw_updt_ts timestamp without time zone ENCODE az64,
    row_stat_cd character(1) ENCODE lzo COLLATE case_insensitive,
    appl_src_cd character(4) ENCODE lzo COLLATE case_insensitive,
    load_id integer ENCODE az64,
    dm_cnst_zip_5_cd character(5) ENCODE lzo COLLATE case_sensitive,
    attribtn_zip_5_cd character(5) ENCODE lzo COLLATE case_sensitive,
    unit_key integer ENCODE az64,
    mktg_unit_key integer ENCODE az64,
    mktg_unit_cd character(20) ENCODE lzo COLLATE case_sensitive,
    unit_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    cs_region_cd character(5) ENCODE lzo COLLATE case_sensitive,
    region_nm character varying(250) ENCODE lzo COLLATE case_sensitive,
    division_cd character(4) ENCODE lzo COLLATE case_sensitive,
    division_dsc character varying(40) ENCODE lzo COLLATE case_sensitive,
    district_cd character varying(15) ENCODE lzo COLLATE case_sensitive,
    district_nm character varying(150) ENCODE lzo COLLATE case_sensitive,
    unit_zip character varying(5) ENCODE lzo COLLATE case_sensitive,
    orc_division_id character(5) ENCODE lzo COLLATE case_sensitive,
    orc_division_name character varying(40) ENCODE lzo COLLATE case_sensitive,
    ds_region_id character(5) ENCODE lzo COLLATE case_sensitive,
    ds_region_name character varying(40) ENCODE lzo COLLATE case_sensitive,
    geo_lat_lon_id character varying(150) ENCODE lzo COLLATE case_sensitive,
    geo_centriod_lat numeric(13,6) ENCODE az64,
    geo_centriod_lon numeric(13,6) ENCODE az64,
    bio_region_nm character varying(40) ENCODE lzo COLLATE case_sensitive,
    bio_division_dsc character varying(30) ENCODE lzo COLLATE case_sensitive,
    ldrshp_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    fiscal_yr smallint ENCODE az64
)
DISTSTYLE AUTO;