CREATE OR REPLACE VIEW mods_bi.ufds_vws.bzfc_dim_unf_fr_indv AS
/*
Created BY: Soumya P
Created Date:08/03/2019
Purpose :Too fetch 'IN' records

Modified by : Aman Kumar
modified date :6-june-2019
purpose :added the prefd_county_cd and prefd_county_nm  columns
*/
SELECT
unf_fr_cnst_key ,
nk_gmp_cnst_id,
nk_gpp_cnst_seq,
nk_sf_acct_guid,
nk_sf_cntct_guid,
nk_ta_acct_id,
nk_ta_nm_id,
nk_chpt_sys_id,
nk_hema_intrnl_acct_id,
nk_hema_intrnl_cntct_id,
frf_acct_id,
frf_cntct_id,
cnst_mstr_id,
cnst_alt_id,
cnst_typ_cd,
cnst_typ_dsc,
dnr_typ_cd,
dnr_typ_dsc,
prfx_cd,
prfx_dsc,
first_nm,
midl_nm,
last_nm,
sfx_cd,
sfx_dsc,
job_title_nm,
nm_line,
empl_num,
prefd_addr_locator_key,
prefd_addr_typ,
prefd_addr_line_1,
prefd_addr_line_2,
prefd_city_nm,
prefd_state_cd,
prefd_state_dsc,
prefd_zip_cd,
prefd_country_cd,
prefd_country_nm,
prefd_county_cd,
prefd_county_nm,
prefd_phn_locator_key,
prefd_phn_typ,
prefd_phn_num,
prefd_email_locator_key,
prefd_email_typ,
prefd_email_addr,
prefd_lang_cd,
prefd_lang_dsc,
strt_dt,
death_dt,
frf_spotlighted_dt,
birth_dy,
birth_mth,
birth_yr,
active_ind,
frf_active_ind,
prim_ind,
deceased_ind,
--affl_lock_ind,
anon_ind,
prvt_ind,
has_cdi_mstr_brg_ind,
frf_acct_key,
frf_anon_ind,
frf_gift_mngd_dnr_ind,
frf_cur_mngd_dnr_ind,
frf_prvt_ind,
frf_visit_in_pairs_ind,
frf_spotlight_dnr_ind,
frf_upld_txt,
sustnr_ind,
plnd_gvng_confirm_ind,
plnd_gvng_info_rqst_ind,
inactvtn_reason_cd,
inactvtn_reason_dsc,
inactvtn_dt,
inactvtn_reason_txt,
frf_status_cd,
frf_spotlight_note_txt,
frf_num_of_lctn,
frf_gift_portfolio_ctg,
frf_cur_portfolio_ctg,
frf_industry_nm,
frf_acct_ownr_asgnd_dt,
frf_acct_modified_key,
frf_prev_acct_ownr_key,
frf_acct_ownr_key,
frf_rev_credit_key,
rev_credit_key,
bio_acct_mngr_nm,
bio_acct_mngr_email,
bio_acct_mngr_phn,
bio_acct_ind,
bio_annual_collect_tgt,
bio_annual_drive_tgt,
bio_rgn_nm,
bio_cllctn_zipcode_dtl_key,
bio_maintain_strat_ind,
backed_out_ind,
back_out_reason_cd,
vendor_src_cd,
grp_active_cnst_cnt,
grp_cnst_1_key,
grp_cnst_2_key,
grp_cnst_1_spouse_key,
grp_cnst_2_spouse_key,
grp_org_cnst_key,
grp_cnst_1_mstr_id,
grp_cnst_2_mstr_id,
grp_cnst_1_spouse_mstr_id,
grp_cnst_2_spouse_mstr_id,
grp_org_mstr_id,
grp_cnst_rmng_mstr_id,
grp_cnst_rmng_cnst_nm,
related_org_1_key,
related_org_2_key,
related_org_3_key,
appl_src_cd,
buyerattributes
FROM mods_bi.ufds_vws.bzfc_dim_unf_fr_cnst
WHERE cnst_typ_cd IN ('IN', 'DW Unknown')
WITH NO SCHEMA BINDING;
GRANT ALL ON TABLE mods_bi.ufds_vws.bzfc_dim_unf_fr_indv TO role ds_mods_writer;
GRANT SELECT ON TABLE mods_bi.ufds_vws.bzfc_dim_unf_fr_indv TO role ds_mods_reader_vt;

CREATE OR REPLACE VIEW mods_bi.ufds_vws.gmpbzal_dim_fund AS
SELECT
fund_key,
row_eff_from_ts,
row_eff_to_ts,
fund_cd,
fund_dsc,
fund_long_dsc,
fund_catg_dsc,
gl_company_fund_cd,
gl_company_fund_dsc,
gl_action_prog_cd,
gl_action_prog_dsc,
gl_prog_srcv_cd,
gl_prog_srcv_dsc,
non_bdgt_rlvng_ind,
active_ind,
(CASE WHEN fund_cd IN ( '4905', '4904' , '3406' , '4900' , '4900-dm' , '4960' , '4900-DM' , '4999' , '2099' , '2947' , '2574-24' , '2575-24' , '4908' )
THEN 'Blue Sky' ELSE
(CASE WHEN gl_company_fund_cd IN ( '052' , '062' ) THEN 'Gray Sky' ELSE 'Blue Sky' END)END) AS fundraising_period,
srcsys_create_ts,
srcsys_update_ts,
srcsys_created_by,
srcsys_modified_by,
row_status_cd,
dw_trans_ts,
load_id,
appl_src_cd,
spanish_fund_dsc
FROM cdigms_rep.gms_tbls.dim_fund
WITH NO SCHEMA BINDING;
GRANT ALL ON TABLE mods_bi.ufds_vws.gmpbzal_dim_fund TO role ds_mods_writer;
GRANT SELECT ON TABLE mods_bi.ufds_vws.gmpbzal_dim_fund TO role ds_mods_reader_vt;

CREATE OR REPLACE VIEW mods_bi.ufds_vws.gmpbza_dim_src AS
SELECT
src_key,
row_eff_from_ts,
row_eff_to_ts,
src_cd,
src_dsc,
prog_cd,
prog_dsc,
rev_credit_cd,
rev_credit_nm,
dnr_specified_lctn_cd,
dnr_specified_lctn_nm,
gl_fcc_dsc,
gl_fcc_cd,
gl_ntrl_acct_cd,
gl_ntrl_acct_dsc,
fund_cd,
fund_dsc,
sub_src_cd,
evnt_benefit_ind,
active_ind,
srcsys_create_ts,
srcsys_update_ts,
srcsys_created_by,
srcsys_modified_by,
row_status_cd,
dw_trans_ts,
load_id,
appl_src_cd,
CASE WHEN row_eff_to_ts = TIMESTAMP '9999-12-31 00:00:00' OR row_eff_to_ts = TIMESTAMP '9999-12-31 00:00:00' THEN 1 ELSE 0 END AS bzd_curr_ind
FROM cdigms_rep.gms_tbls.dim_src
WHERE row_status_cd != 'L'
WITH NO SCHEMA BINDING;
GRANT ALL ON TABLE mods_bi.ufds_vws.gmpbza_dim_src TO role ds_mods_writer;
GRANT SELECT ON TABLE mods_bi.ufds_vws.gmpbza_dim_src TO role ds_mods_reader_vt;

CREATE OR REPLACE VIEW mods_bi.ufds_vws.gmpbza_gift_addr AS
SELECT
gift_addr_key,
giftran_key,
gift_cnst_grp_key,
row_eff_from_ts,
row_eff_to_ts,
nk_gmp_addr_id,
nk_gpp_addr_seq,
nk_ta_acct_id,
nk_ta_addr_id,
gift_in_care_of,
locator_addr_key,
addr_typ_cd,
addr_typ_dsc,
addr_line1,
addr_line2,
city,
state_cd,
state_dsc,
zipcode,
zipcode_extsn,
country_cd,
country_dsc,
cln_addr_line1,
cln_addr_line2,
cln_city,
cln_zipcode,
cln_state_cd,
cln_state_dsc,
cln_country_cd,
cln_country_dsc,
dpv_cd,
seasnl_ind,
seasnl_from_mth,
seasnl_to_mth,
seasnl_from_dt,
seasnl_to_dt,
addr_on_gift_ind,
prefd_ind,
active_ind,
backed_out_ind,
back_out_reason_cd,
vendor_src_cd,
srcsys_create_ts,
srcsys_update_ts,
srcsys_created_by,
srcsys_modified_by,
row_status_cd,
dw_trans_ts,
load_id,
appl_src_cd,
CASE WHEN row_eff_to_ts = TIMESTAMP '9999-12-31 00:00:00' OR row_eff_to_ts = TIMESTAMP '9999-12-31 00:00:00' THEN 1 ELSE 0 END AS bzd_curr_ind
FROM cdigms_rep.gms_tbls.gift_addr
WHERE row_status_cd != 'L'
WITH NO SCHEMA BINDING;
GRANT ALL ON TABLE mods_bi.ufds_vws.gmpbza_gift_addr TO role ds_mods_writer;
GRANT SELECT ON TABLE mods_bi.ufds_vws.gmpbza_gift_addr TO role ds_mods_reader_vt;
