CREATE OR REPLACE VIEW ufds_vws.bzfc_fact_giftran AS
/*------------------------------------------------------------------------------------------------------------------------------------
Created by: Aman Kumar
created date:23-Sep-2019
Purpose: BOSE VIEW

Updated by : Sumit Jha
Updated date : 03-Nov-2023
Purpose : Addition of new column 'gift_disaster_infl_ind' as part of GMS-36635

Updated by : Kshama Chaurasia
Updated date : 02-Aug-2024
Purpose: Adding 'fundraising_period_ctg' column to ufds_vws.bzfc_fact_giftran */
------------------------------------------------------------------------------------------------------------------------------------*/
SELECT
giftran.giftran_key,
giftran.gift_cnst_grp_key,
giftran.nk_giftran_id,
giftran.nk_gpp_id,
giftran.nk_batch_id,
giftran.nk_basket_id,
giftran.nk_gift_id,
giftran.nk_ta_acct_id,
giftran.nk_ta_gift_seq,
giftran.nk_ta_gift_adj_seq,
giftran.nk_ta_batch_num,
giftran.nk_ta_batch_seq,
giftran.nk_sf_gift_id,
giftran.gift_grp_id,
giftran.gift_disaster_infl_ind,
giftran.adj_seq,
giftran.gift_versn,
giftran.pledge_num,
giftran.gift_num,
giftran.gift_rec_dt ,
giftran.gift_rec_dt_key,
giftran.gift_dt ,
giftran.gift_dt_key,
giftran.released_dt ,
giftran.released_dt_key,
giftran.deposit_dt ,
giftran.deposit_dt_key,
giftran.adj_dt ,
giftran.adj_dt_key,
giftran.channel_key,
giftran.orig_released_dt ,
giftran.orig_released_dt_key,
giftran.orig_deposit_dt ,
giftran.orig_deposit_dt_key,
giftran.gift_amt,
giftran.totl_gift_amt,
giftran.gift_exps_amt,
giftran.intended_gift_amt,
giftran.split_gift_cnt,
giftran.active_ind,
giftran.ack_ind,
giftran.thankyou_ind,
giftran.do_not_feed_gl_ind,
giftran.gift_anon_ind,
giftran.sc_ind,
giftran.split_gift_ind,
giftran.trbt_gift_ind,
giftran.adj_ind,
giftran.installment_ind,
giftran.gift_in_care_of_ind,
giftran.dnr_geogrphc_intrst_local_ind,
giftran.bdgt_rlvng_ind,
giftran.released_ind,
giftran.manual_entry_ind,
giftran.reject_ind,
giftran.misdirected_ind,
giftran.evnt_benefit_ind,
giftran.vsblty_ind,
giftran.fr_credit_ind,
giftran.confidence_ind,
giftran.prior_prd_ind,
giftran.gl_override_ind,
giftran.conv_trans_ind,
giftran.ta_trans_ind,
giftran.stock_gift_ind,
giftran.inkind_gift_ind,
giftran.dnr_adv_gift_ind,
giftran.episodic_gift_ind,
giftran.frc_inctv_prd_clsd_ind,
giftran.gift_ask_mult_lnk_ind,
giftran.treatment_cd,
giftran.sub_src_cd,
giftran.rev_chan,
giftran.gl_credit_acct_string,
giftran.gl_debit_acct_string,
giftran.gmp_gift_locator_key,
giftran.dim_gift_trbt_key,
giftran.dim_gift_stock_key,
giftran.dim_gift_inkind_key,
giftran.dim_gift_sku_key,
giftran.dim_gift_premium_key,
giftran.dim_giftran_key,
giftran.rlse_key,
giftran.acctng_batch_key,
giftran.bypass_batch_key,
giftran.adj_typ_key,
giftran.gift_stg_key,
giftran.sustnr_typ_key,
giftran.pmt_mthd_key,
giftran.giftran_typ_key,
giftran.dntn_chan_key,
giftran.merchant_key,
giftran.vendor_key,
giftran.prog_key,
giftran.gl_fcc_key,
giftran.gl_credit_acct_key,
giftran.gl_debit_acct_key,
giftran.lnk_status,
giftran.ask_key,
giftran.fund_key,
giftran.gift_rev_credit_key,
giftran.gift_rev_credit_rpt_key,
giftran.sending_lctn_key,
giftran.dnr_specified_lctn_key,
giftran.sc_affl_key,
giftran.src_key,
giftran.qlty_assrnc_rslt_key,
giftran.pended_reason_key,
giftran.reject_reason_key,
giftran.gift_amt_tier_key,
giftran.back_out_batch_key,
giftran.tgt_typ_key,
giftran.frf_offer_key,
giftran.frf_service_key,
giftran.vendor_src_cd,
giftran.srcsys_create_ts ,
giftran.srcsys_update_ts ,
giftran.srcsys_created_by,
giftran.srcsys_modified_by,
giftran.row_status_cd,
giftran.dw_trans_ts ,
giftran.load_id,
giftran.appl_src_cd,
giftran.retrieved_trans_ind,
giftran.fin_released_dt ,
giftran.fin_released_dt_key,
giftran.prvt_ind,
CASE
WHEN giftran.gift_disaster_infl_ind = 1 THEN 'Gray Sky Influenced'
WHEN dim_fund.fundraising_period = 'Gray Sky' THEN 'Gray Sky Designated'
WHEN dim_fund.fundraising_period = 'Blue Sky' THEN 'Blue Sky' END AS fundraising_period_ctg
FROM cdigms_rep.ufds_tbls.bzfc_fact_giftran AS giftran
LEFT JOIN ufds_vws.gmpbzal_dim_fund AS dim_fund ON giftran.fund_key = dim_fund.fund_key
WHERE giftran.row_status_cd != 'L'
AND COALESCE(giftran.misdirected_ind,0) = 0
WITH NO SCHEMA BINDING;