CREATE OR REPLACE VIEW ufds_vws.gmpbz_dim_giftran AS
SELECT
dim_giftran_key,
nk_giftran_id,
nk_gift_id,
nk_gpp_id,
nk_batch_id,
nk_basket_id,
gift_grp_id,
adj_seq,
alt_trans_id,
gift_img_id,
gift_bundle_img_id,
merchant_id,
ask_id,
sf_case_id,
vendor_batch_id,
related_gift_id,
finder_num,
ask_src,
gift_org_facil_num,
third_prty,
dnr_adv_fund,
inkind_dro_lctn,
credit_card_num,
credit_card_exp_dt,
check_num,
shpmt_tracking_num,
gift_note_txt,
vendor_src_trans_ts,
backed_out_ind,
back_out_reason_cd,
vendor_src_cd,
srcsys_create_ts,
srcsys_update_ts,
srcsys_created_by,
srcsys_modified_by,
row_status_cd,
dw_trans_ts,
load_id,
appl_src_cd
FROM cdigms_rep.gms_tbls.dim_giftran
WHERE row_status_cd != 'L'
WITH NO SCHEMA BINDING;