CREATE OR REPLACE VIEW ufds_vws.gmpbza_gift_addr AS
SELECT
gift_addr_key,
giftran_key,
gift_cnst_grp_key,
row_eff_from_ts,
row_eff_to_ts,
nk_gmp_addr_id,
nk_gpp_addr_seq,
nk_ta_acct_id,
nk_ta_addr_id,
gift_in_care_of,
locator_addr_key,
addr_typ_cd,
addr_typ_dsc,
addr_line1,
addr_line2,
city,
state_cd,
state_dsc,
zipcode,
zipcode_extsn,
country_cd,
country_dsc,
cln_addr_line1,
cln_addr_line2,
cln_city,
cln_zipcode,
cln_state_cd,
cln_state_dsc,
cln_country_cd,
cln_country_dsc,
dpv_cd,
seasnl_ind,
seasnl_from_mth,
seasnl_to_mth,
seasnl_from_dt,
seasnl_to_dt,
addr_on_gift_ind,
prefd_ind,
active_ind,
backed_out_ind,
back_out_reason_cd,
vendor_src_cd,
srcsys_create_ts,
srcsys_update_ts,
srcsys_created_by,
srcsys_modified_by,
row_status_cd,
dw_trans_ts,
load_id,
appl_src_cd,
CASE WHEN row_eff_to_ts = TIMESTAMP '9999-12-31 00:00:00' OR row_eff_to_ts = TIMESTAMP '9999-12-31 00:00:00' THEN 1 ELSE 0 END AS bzd_curr_ind
FROM cdigms_rep.gms_tbls.gift_addr
WHERE row_status_cd != 'L'
WITH NO SCHEMA BINDING;