CREATE OR REPLACE VIEW ufds_vws.gmpbz_cnst_comnictn_email AS
SELECT
nk_cnst_comnictn_id,
nk_gift_id,
prse_cd,
comnictn_cd,
gift_dt,
gift_amt,
src_cd,
src_dsc,
dnr_advs_fnd_nm,
donormasterid1,
donormasterid2,
org_nm,
email_address,
salutn,
addressee,
addr_line1,
addr_line2,
city,
state_cd,
zipcode,
trbt_nm ,
trbt_typ_cd,
trbt_from ,
trbt_typ_dsc,
giftran_typ_dsc,
personalizationline,
trbt_card_typ_cd,
prem_cd,
prem_count,
comnictn_dw_extr_dt,
fund_dsc,
revenue_dsc,
ira,
cdrp_flg,
dlvry_mthd_cd,
lang_cd,
inkind_dsc,
totl_stock_gift_amt,
srcsys_created_by,
srcsys_modified_by,
srcsys_create_ts,
srcsys_update_ts,
row_status_cd,
dw_trans_ts
FROM cdigms_rep.gms_tbls.cnst_comnictn_email
WHERE row_status_cd != 'L'
WITH NO SCHEMA BINDING;