"""
Script Behavior Summary:

3. Database Credentials:
   - The database username and password for `create_objects.py` are provided at runtime
     through an interactive prompt.
   - The password input is masked and not displayed on the screen.
   - Credentials are used only for establishing the target database connection and
     are not stored after the connection is created.

4. Object Creation Workflow:
   - The script connects to the target database.
   - The object type(s) to be created are read from the YAML configuration file.
   - Based on the object type, the script executes the corresponding DDL scripts
     generated by the fetch process.

   - Before execution, the script displays the source folder containing the DDL scripts
     and asks for user confirmation (Y/N) to proceed with object creation.

5. Drop and Create Capability:
   - For tables, the script supports a DROP followed by CREATE operation.
   - This is implemented because `CREATE OR REPLACE TABLE` is not supported.
   - Existing tables are safely dropped before being recreated.
"""


import os
import psycopg2
import logging
import yaml
import csv
from datetime import datetime
from pathlib import Path
import pwinput


# Load configuration from YAML
def load_config(config_file="create_objects_parameters.yaml"):
    try:
        # Since .py file is now inside Create_Object_Input folder
        # base_path points to Create_Object_Input folder
        base_path = Path(__file__).parent

        # YAML file is in the same folder as the .py file
        yaml_path = base_path / config_file

        with open(yaml_path, "r") as file:
            config = yaml.safe_load(file)

        # Convert relative paths to absolute paths
        # Now we need to go UP one level (parent.parent) to get to project root
        if 'paths' in config:
            project_root = base_path.parent  # Go up to project root
            for key in ['ddl_base_path', 'log_directory', 'output_directory']:
                if key in config['paths']:
                    path_value = config['paths'][key]
                    # If path doesn't start with drive letter or /, treat as relative
                    if not (path_value.startswith('/') or (len(path_value) > 1 and path_value[1] == ':')):
                        config['paths'][key] = str(project_root / path_value)

        return config

    except Exception as e:
        print(f"Error loading configuration file: {e}")
        return None


# Find the latest timestamped folder for the schema
def find_latest_schema_folder(ddl_base_path, object_type, schema_name):
    """
    Dynamically finds the latest timestamped folder for the given schema and object type.
    Example: Fetch_Object_Output/View/mktg_ops_vws_20251212_1628/
    """
    try:
        # Construct the path to the object type folder
        object_type_path = os.path.join(ddl_base_path, object_type.capitalize())

        if not os.path.exists(object_type_path):
            logging.error(f"Object type path does not exist: {object_type_path}")
            return None, None

        # Find all folders that start with the schema_name
        matching_folders = [
            f for f in os.listdir(object_type_path)
            if os.path.isdir(os.path.join(object_type_path, f)) and f.startswith(schema_name + "_")
        ]

        if not matching_folders:
            logging.error(f"No folders found for schema '{schema_name}' in {object_type_path}")
            return None, None

        # Sort by folder name (timestamp is in the name, so this works)
        matching_folders.sort(reverse=True)
        latest_folder = matching_folders[0]

        full_path = os.path.join(object_type_path, latest_folder)

        logging.info("=" * 80)
        logging.info(f"DYNAMIC FOLDER RESOLUTION")
        logging.info("=" * 80)
        logging.info(f"Object Type: {object_type.upper()}")
        logging.info(f"Schema Name: {schema_name}")
        logging.info(f"Base Path: {object_type_path}")
        logging.info(f"Found {len(matching_folders)} matching folder(s)")
        logging.info(f"Latest Folder: {latest_folder}")
        logging.info(f"Full Path: {full_path}")
        logging.info("=" * 80)

        return full_path, latest_folder

    except Exception as e:
        logging.error(f"Error finding latest schema folder: {e}")
        return None, None


# Setup logging with dynamic file names and timestamps
def setup_logging(log_directory, run_identifier):
    try:
        os.makedirs(log_directory, exist_ok=True)

        # Add timestamp to log file name
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        log_file = os.path.join(log_directory, f"{run_identifier}_{timestamp}_log.log")

        # Clear any existing handlers
        for handler in logging.root.handlers[:]:
            logging.root.removeHandler(handler)

        logging.basicConfig(
            filename=log_file,
            level=logging.INFO,
            format="%(asctime)s - %(levelname)s - %(message)s",
            filemode='w'  # Each run creates a new file due to timestamp
        )

        # Also log to console
        console = logging.StreamHandler()
        console.setLevel(logging.INFO)
        formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
        console.setFormatter(formatter)
        logging.getLogger('').addHandler(console)

        logging.info("=" * 80)
        logging.info(f"Starting DDL Execution Script - {run_identifier}")
        logging.info(f"Timestamp: {timestamp}")
        logging.info("=" * 80)

        return log_file
    except Exception as e:
        print(f"Error setting up logging: {e}")
        return None


# Connect to Redshift
def connect_to_redshift(config):
    try:
        username = input("Enter Redshift username: ")
        password = pwinput.pwinput(prompt="Enter Redshift password: ", mask="*")
        connection = psycopg2.connect(
            host=config['redshift']['host'],
            port=config['redshift']['port'],
            dbname=config['redshift']['dbname'],
            user=username,
            password=password
        )
        logging.info(f"Successfully connected to Redshift DEV: {config['redshift']['host']}")
        logging.info(f"Database: {config['redshift']['dbname']}, User: {username}")
        del password  # Remove password from memory
        return connection
    except Exception as e:
        logging.error(f"Error connecting to Redshift: {e}")
        print(f"Error connecting to Redshift: {e}")
        return None


# Get all DDL/SQL files from the schema folder
def get_ddl_files(schema_folder_path):
    try:
        if not os.path.exists(schema_folder_path):
            logging.error(f"Schema path does not exist: {schema_folder_path}")
            return []

        ddl_files = [f for f in os.listdir(schema_folder_path) if f.endswith('.sql')]
        logging.info(f"Found {len(ddl_files)} SQL files in {schema_folder_path}")
        return ddl_files
    except Exception as e:
        logging.error(f"Error reading SQL files: {e}")
        return []


# Read DDL/SQL content from file
def read_ddl_file(schema_folder_path, file_name):
    try:
        file_path = os.path.join(schema_folder_path, file_name)

        # Check if file exists
        if not os.path.exists(file_path):
            logging.error(f"File does not exist: {file_path}")
            return None

        # Try different encodings
        encodings = ['utf-8', 'latin-1', 'cp1252', 'iso-8859-1']

        for encoding in encodings:
            try:
                with open(file_path, 'r', encoding=encoding) as file:
                    ddl_content = file.read()
                    if ddl_content.strip():  # If content is not empty
                        logging.debug(f"Successfully read {file_name} with encoding: {encoding}")
                        return ddl_content
            except UnicodeDecodeError:
                continue

        # If all encodings fail, log the error
        logging.error(f"Could not read file {file_name} with any encoding")
        return None

    except Exception as e:
        logging.error(f"Error reading SQL file {file_name}: {e}")
        logging.error(f"Full path attempted: {file_path}")
        return None


# Drop table if exists (for tables only)
def drop_table_if_exists(connection, schema_name, table_name):
    """
    Drops a table if it exists before creating it
    Only used for TABLE object type
    """
    try:
        cursor = connection.cursor()
        drop_sql = f"DROP TABLE IF EXISTS {schema_name}.{table_name} CASCADE;"
        cursor.execute(drop_sql)
        connection.commit()
        cursor.close()
        logging.info(f"  Dropped existing table (if any): {table_name}")
        return True
    except psycopg2.Error as e:
        connection.rollback()
        logging.warning(f"  Could not drop table {table_name}: {str(e).strip()}")
        return False
    except Exception as e:
        connection.rollback()
        logging.warning(f"  Unexpected error dropping table {table_name}: {str(e)}")
        return False


# Execute DDL/SQL and categorize results
def execute_ddl(connection, ddl_content, schema_name, object_name, object_type):
    try:
        # For tables, drop first
        if object_type.lower() == 'table':
            drop_table_if_exists(connection, schema_name, object_name)

        cursor = connection.cursor()
        cursor.execute(ddl_content)
        connection.commit()
        cursor.close()
        return True, None, None
    except psycopg2.Error as e:
        connection.rollback()
        error_message = str(e).strip()

        # Categorize errors
        if "permission denied" in error_message.lower() or "must be owner" in error_message.lower():
            error_type = "PERMISSION_ERROR"
        elif "does not exist" in error_message.lower():
            error_type = "DEPENDENCY_ERROR"
        elif "already exists" in error_message.lower():
            error_type = "ALREADY_EXISTS"
        elif "syntax error" in error_message.lower():
            error_type = "SYNTAX_ERROR"
        else:
            error_type = "OTHER_ERROR"

        return False, error_type, error_message
    except Exception as e:
        connection.rollback()
        return False, "UNKNOWN_ERROR", str(e)


# Validate a single view
def validate_view(connection, schema_name, view_name):
    """
    Validates a view by executing SELECT * LIMIT 0
    Returns (success: bool, error_message: str or None)
    """
    try:
        cursor = connection.cursor()
        validation_query = f"SELECT * FROM {schema_name}.{view_name} LIMIT 0;"
        cursor.execute(validation_query)
        cursor.close()
        connection.commit()  # Commit successful validation
        return True, None
    except psycopg2.Error as e:
        connection.rollback()  # CRITICAL: Rollback failed transaction
        error_message = str(e).strip()
        # Truncate error message if too long
        error_msg_short = error_message[:500] if len(error_message) > 500 else error_message
        return False, error_msg_short
    except Exception as e:
        connection.rollback()  # CRITICAL: Rollback failed transaction
        return False, str(e)


# Validate all created views
def validate_all_views(connection, created_file, schema_name):
    """
    Reads created.csv, validates each view, and updates the CSV with validation results
    Only runs if object_type is VIEW
    """
    try:
        logging.info("=" * 80)
        logging.info("STARTING VIEW VALIDATION")
        logging.info("=" * 80)

        # Read the created CSV
        views_to_validate = []
        with open(created_file, 'r', newline='', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                views_to_validate.append(row)

        if not views_to_validate:
            logging.info("No views to validate")
            return 0, 0

        logging.info(f"Found {len(views_to_validate)} view(s) to validate")

        validated_ok = 0
        validation_failed = 0

        # Validate each view
        for view in views_to_validate:
            view_name = view['object_name']

            success, error_message = validate_view(connection, schema_name, view_name)

            if success:
                logging.info(f"✓ Validation successful: {view_name}")
                view['validation_status'] = 'VALIDATED_OK'
                view['validation_error'] = ''
                validated_ok += 1
            else:
                logging.warning(f"✗ Validation failed: {view_name} - {error_message}")
                view['validation_status'] = 'VALIDATION_FAILED'
                view['validation_error'] = error_message
                validation_failed += 1

        # Rewrite the CSV with validation columns
        with open(created_file, 'w', newline='', encoding='utf-8') as f:
            fieldnames = ['object_name', 'schema_name', 'object_type', 'status',
                          'validation_status', 'validation_error', 'created_timestamp']
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(views_to_validate)

        logging.info("=" * 80)
        logging.info("VIEW VALIDATION SUMMARY")
        logging.info("=" * 80)
        logging.info(f"Total Views Validated: {len(views_to_validate)}")
        logging.info(f"✓ Validated Successfully: {validated_ok}")
        logging.info(f"✗ Validation Failed: {validation_failed}")
        logging.info(f"Validation Success Rate: {(validated_ok / len(views_to_validate) * 100):.2f}%")
        logging.info("=" * 80)

        return validated_ok, validation_failed

    except Exception as e:
        logging.error(f"Error during view validation: {e}")
        return 0, 0


# Initialize CSV files with dynamic names and timestamps
def initialize_csv_files(output_directory, run_identifier, object_type):
    try:
        # Create object-type specific output directory
        object_output_dir = os.path.join(output_directory, object_type.capitalize())
        os.makedirs(object_output_dir, exist_ok=True)

        # Add timestamp to CSV file names
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        created_file = os.path.join(object_output_dir, f"{run_identifier}_{timestamp}_created.csv")
        errored_file = os.path.join(object_output_dir, f"{run_identifier}_{timestamp}_errored.csv")

        # Created objects CSV - with validation columns for all types
        with open(created_file, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['object_name', 'schema_name', 'object_type', 'status',
                             'validation_status', 'validation_error', 'created_timestamp'])

        # Errored objects CSV
        with open(errored_file, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['object_name', 'schema_name', 'object_type', 'error_type', 'error_message', 'timestamp'])

        logging.info(f"Initialized CSV files with timestamp: {timestamp}")
        logging.info(f"  - Output Directory: {object_output_dir}")
        logging.info(f"  - Created: {created_file}")
        logging.info(f"  - Errored: {errored_file}")

        return created_file, errored_file
    except Exception as e:
        logging.error(f"Error initializing CSV files: {e}")
        return None, None


# Write to created CSV
def write_to_created_csv(created_file, object_name, schema_name, object_type):
    try:
        with open(created_file, 'a', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            # For views, validation columns will be filled later
            if object_type.lower() == 'view':
                writer.writerow([object_name, schema_name, object_type, 'SUCCESS',
                                 'PENDING', '', datetime.now().strftime('%Y-%m-%d %H:%M:%S')])
            else:
                writer.writerow([object_name, schema_name, object_type, 'SUCCESS',
                                 'N/A', '', datetime.now().strftime('%Y-%m-%d %H:%M:%S')])
    except Exception as e:
        logging.error(f"Error writing to created CSV: {e}")


# Write to errored CSV
def write_to_errored_csv(errored_file, object_name, schema_name, object_type, error_type, error_message):
    try:
        with open(errored_file, 'a', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            # Truncate error message if too long
            error_msg_short = error_message[:500] if len(error_message) > 500 else error_message
            writer.writerow([object_name, schema_name, object_type, error_type, error_msg_short,
                             datetime.now().strftime('%Y-%m-%d %H:%M:%S')])
    except Exception as e:
        logging.error(f"Error writing to errored CSV: {e}")


# Process all DDL files
def process_ddl_files(connection, config):
    ddl_base_path = config['paths']['ddl_base_path']
    schema_name = config['object_config']['schema_name']
    object_type = config['object_config']['object_type']
    run_identifier = config['object_config']['run_identifier']
    output_base_directory = config['paths']['output_directory']

    retry_enabled = config['execution']['retry_failed_objects']
    max_retries = config['execution']['max_retries']
    batch_size = config['execution']['batch_size']

    # Find the latest timestamped folder dynamically
    schema_folder_path, latest_folder_name = find_latest_schema_folder(ddl_base_path, object_type, schema_name)
    if not schema_folder_path or not latest_folder_name:
        logging.error("Could not find schema folder. Exiting.")
        return

    # USER CONFIRMATION
    print("\n" + "=" * 80)
    print("FOLDER CONFIRMATION")
    print("=" * 80)
    print(f"I am going to use this folder: {latest_folder_name}")
    print(f"Full path: {schema_folder_path}")
    print("=" * 80)
    confirmation = input("\nIs this correct? (Y/N): ").strip().upper()

    if confirmation != 'Y':
        print("\n❌ Operation cancelled by user.")
        logging.info("User cancelled operation - folder not confirmed")
        return

    print("\n✓ Confirmed. Proceeding with object creation...\n")
    logging.info("User confirmed folder selection")

    # Initialize CSV files in object-type specific directory
    created_file, errored_file = initialize_csv_files(
        output_base_directory, run_identifier, object_type
    )
    if not created_file or not errored_file:
        logging.error("Failed to initialize CSV files. Exiting.")
        return

    # Get all DDL files
    ddl_files = get_ddl_files(schema_folder_path)
    if not ddl_files:
        logging.warning("No SQL files found to process")
        return

    # Statistics
    total_objects = len(ddl_files)
    created_count = 0
    errored_count = 0
    dependency_errors = []

    logging.info("=" * 80)
    logging.info(f"Processing Configuration:")
    logging.info(f"  - Schema: {schema_name}")
    logging.info(f"  - Object Type: {object_type.upper()}")
    logging.info(f"  - Total Objects in Folder: {total_objects}")
    logging.info(f"  - Run Identifier: {run_identifier}")
    logging.info("=" * 80)

    # First pass: Try to create all objects
    for idx, file_name in enumerate(ddl_files, 1):
        object_name = file_name.replace('.sql', '')

        # Log progress every batch_size objects
        if idx % batch_size == 0:
            logging.info(f"Progress: {idx}/{total_objects} {object_type}s processed")

        # Read DDL content
        ddl_content = read_ddl_file(schema_folder_path, file_name)
        if not ddl_content:
            logging.error(f"Skipping {object_name} - Could not read SQL file")
            write_to_errored_csv(errored_file, object_name, schema_name, object_type,
                                 "FILE_READ_ERROR", "Could not read SQL file")
            errored_count += 1
            continue

        # Execute DDL
        success, error_type, error_message = execute_ddl(connection, ddl_content, schema_name, object_name, object_type)

        if success:
            logging.info(f"✓ Successfully created {object_type}: {object_name}")
            write_to_created_csv(created_file, object_name, schema_name, object_type)
            created_count += 1
        else:
            logging.warning(f"✗ Failed to create {object_type}: {object_name} - Error Type: {error_type}")
            write_to_errored_csv(errored_file, object_name, schema_name, object_type, error_type, error_message)
            errored_count += 1

            # Track dependency errors for retry
            if error_type == "DEPENDENCY_ERROR" and retry_enabled:
                dependency_errors.append((object_name, file_name))

    # Retry logic for dependency errors
    if retry_enabled and dependency_errors:
        logging.info("=" * 80)
        logging.info(f"Starting retry logic for {len(dependency_errors)} dependency errors")
        logging.info("=" * 80)

        retry_count = 0
        while dependency_errors and retry_count < max_retries:
            retry_count += 1
            logging.info(f"Retry attempt {retry_count}/{max_retries} for {len(dependency_errors)} {object_type}s")

            still_failing = []

            for object_name, file_name in dependency_errors:
                ddl_content = read_ddl_file(schema_folder_path, file_name)
                if not ddl_content:
                    still_failing.append((object_name, file_name))
                    continue

                success, error_type, error_message = execute_ddl(connection, ddl_content, schema_name, object_name,
                                                                 object_type)

                if success:
                    logging.info(f"✓ Successfully created {object_type} on retry: {object_name}")
                    write_to_created_csv(created_file, object_name, schema_name, object_type)
                    created_count += 1
                    errored_count -= 1
                elif error_type == "DEPENDENCY_ERROR":
                    still_failing.append((object_name, file_name))
                # If it's a different error now, it stays in the errored file

            if not still_failing:
                logging.info("All dependency errors resolved!")
                break

            if len(still_failing) == len(dependency_errors):
                logging.warning(f"No progress made in retry {retry_count}. Stopping retries.")
                break

            dependency_errors = still_failing

    # VIEW VALIDATION - Only run if object_type is VIEW
    validated_ok = 0
    validation_failed = 0
    if object_type.lower() == 'view' and created_count > 0:
        validated_ok, validation_failed = validate_all_views(connection, created_file, schema_name)

    # Final summary
    success_rate = (created_count / total_objects * 100) if total_objects > 0 else 0

    logging.info("=" * 80)
    logging.info("EXECUTION SUMMARY")
    logging.info("=" * 80)
    logging.info(f"Object Type: {object_type.upper()}")
    logging.info(f"Schema: {schema_name}")
    logging.info(f"Total Objects in Folder: {total_objects}")
    logging.info(f"Successfully Created: {created_count}")
    logging.info(f"Failed: {errored_count}")
    logging.info(f"Success Rate: {success_rate:.2f}%")

    # Add validation summary for views
    if object_type.lower() == 'view' and created_count > 0:
        overall_success = validated_ok
        overall_total = created_count
        overall_rate = (overall_success / overall_total * 100) if overall_total > 0 else 0
        logging.info("")
        logging.info("VIEW VALIDATION RESULTS:")
        logging.info(f"✓ Validated Successfully: {validated_ok}")
        logging.info(f"✗ Validation Failed: {validation_failed}")
        logging.info(f"Overall Success Rate (Created + Validated): {overall_rate:.2f}%")

    logging.info(f"Created objects saved to: {created_file}")
    logging.info(f"Errored objects saved to: {errored_file}")
    logging.info("=" * 80)

    print("\n" + "=" * 80)
    print("EXECUTION COMPLETED")
    print("=" * 80)
    print(f"Object Type: {object_type.upper()}")
    print(f"Schema: {schema_name}")
    print(f"Total Objects in Folder: {total_objects}")
    print(f"✓ Successfully created: {created_count} {object_type}s")
    print(f"✗ Failed: {errored_count} {object_type}s")
    print(f"Success Rate: {success_rate:.2f}%")

    # Add validation summary for views
    if object_type.lower() == 'view' and created_count > 0:
        overall_rate = (validated_ok / created_count * 100) if created_count > 0 else 0
        print(f"\nVIEW VALIDATION:")
        print(f"✓ Validated OK: {validated_ok} views")
        print(f"✗ Validation Failed: {validation_failed} views")
        print(f"Overall Success Rate (Created + Validated): {overall_rate:.2f}%")

    print(f"\nCreated objects: {created_file}")
    print(f"Errored objects: {errored_file}")
    print("=" * 80)


# Main function
def main():
    # Load configuration
    config = load_config()
    if not config:
        print("Failed to load configuration. Exiting.")
        return

    # Setup logging
    run_identifier = config['object_config']['run_identifier']
    log_directory = config['paths']['log_directory']
    log_file = setup_logging(log_directory, run_identifier)

    if not log_file:
        print("Failed to setup logging. Exiting.")
        return

    logging.info(f"Configuration loaded successfully")
    logging.info(f"Log file: {log_file}")

    # Connect to Redshift
    connection = connect_to_redshift(config)
    if not connection:
        logging.error("Failed to connect to Redshift. Exiting.")
        return

    try:
        # Process all DDL files
        process_ddl_files(connection, config)
    except Exception as e:
        logging.error(f"Unexpected error in main execution: {e}")
        print(f"Unexpected error: {e}")
    finally:
        # Close connection
        connection.close()
        logging.info("Connection closed. Script execution completed.")


if __name__ == "__main__":
    main()