CREATE OR REPLACE VIEW arc_goats_vws.bzfc_taxo_denorm_full AS

/* LOCKING TABLE arc_goats_tbls.taxo_denorm FOR ACCESS MODE */
SELECT
    taxo_vers_key,
    taxo_ver_dsc,
    taxo_typ_key,
    taxo_typ,
    lvl1_node_typ,
    lvl1_node_key,
    lvl1_node_cd,
    lvl1_node_nm,
    lvl2_node_typ,
    lvl2_node_key,
    lvl2_node_cd,
    lvl2_node_nm,
    lvl3_node_typ,
    lvl3_node_key,
    lvl3_node_cd,
    lvl3_node_nm,
    lvl4_node_typ,
    lvl4_node_key,
    lvl4_node_cd,
    lvl4_node_nm,
    lvl5_node_typ,
    lvl5_node_key,
    lvl5_node_cd,
    lvl5_node_nm,
    lvl6_node_typ,
    lvl6_node_key,
    lvl6_node_cd,
    lvl6_node_nm,
    lvl7_node_typ,
    lvl7_node_key,
    lvl7_node_cd,
    lvl7_node_nm,
    lvl8_node_typ,
    lvl8_node_key,
    lvl8_node_cd,
    lvl8_node_nm,
    lvl9_node_typ,
    lvl9_node_key,
    lvl9_node_cd,
    lvl9_node_nm,
    lvl10_node_typ,
    lvl10_node_key,
    lvl10_node_cd,
    lvl10_node_nm,
    valid_start_dt,
    valid_end_dt,
    dw_trans_ts,
    row_stat_cd
FROM hubwork_rep.arc_goats_tbls.taxo_denorm
WITH NO SCHEMA BINDING;