CREATE TABLE mktg_ops_tbls.adb_nmsrecipient (
    iaddrerrorcount integer NOT NULL ENCODE az64,
    iaddrquality integer NOT NULL ENCODE az64,
    iblacklist smallint NOT NULL ENCODE az64,
    iblacklistemail smallint NOT NULL ENCODE az64,
    iblacklistfax smallint NOT NULL ENCODE az64,
    iblacklistmobile smallint NOT NULL ENCODE az64,
    iblacklistphone smallint NOT NULL ENCODE az64,
    iblacklistpostalmail smallint NOT NULL ENCODE az64,
    iboolean1 smallint NOT NULL ENCODE az64,
    iboolean2 smallint NOT NULL ENCODE az64,
    iboolean3 smallint NOT NULL ENCODE az64,
    iemailformat smallint NOT NULL ENCODE az64,
    ifolderid integer NOT NULL ENCODE az64,
    igender smallint NOT NULL ENCODE az64,
    irecipientid integer NOT NULL ENCODE raw distkey,
    istatus smallint NOT NULL ENCODE az64,
    mdata character varying(4000) ENCODE lzo COLLATE case_sensitive,
    saccount character varying(30) ENCODE lzo COLLATE case_sensitive,
    saddress1 character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress2 character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress3 character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress4 character varying(150) ENCODE lzo COLLATE case_sensitive,
    scity character varying(75) ENCODE lzo COLLATE case_sensitive,
    scompany character varying(80) ENCODE lzo COLLATE case_sensitive,
    scountrycode character varying(3) ENCODE lzo COLLATE case_sensitive,
    semail character varying(128) ENCODE lzo COLLATE case_sensitive,
    sfax character varying(32) ENCODE lzo COLLATE case_sensitive,
    sfirstname character varying(100) ENCODE lzo COLLATE case_sensitive,
    slanguage character varying(32) ENCODE lzo COLLATE case_sensitive,
    slastname character varying(100) ENCODE lzo COLLATE case_sensitive,
    smiddlename character varying(30) ENCODE lzo COLLATE case_sensitive,
    smobilephone character varying(32) ENCODE lzo COLLATE case_sensitive,
    sorigin character varying(80) ENCODE lzo COLLATE case_sensitive,
    sphone character varying(32) ENCODE lzo COLLATE case_sensitive,
    ssalutation character varying(20) ENCODE lzo COLLATE case_sensitive,
    sstatecode character varying(3) ENCODE lzo COLLATE case_sensitive,
    stext1 character varying(180) ENCODE lzo COLLATE case_sensitive,
    stext2 character varying(180) ENCODE lzo COLLATE case_sensitive,
    stext3 character varying(180) ENCODE lzo COLLATE case_sensitive,
    stext4 character varying(180) ENCODE lzo COLLATE case_sensitive,
    stext5 character varying(180) ENCODE lzo COLLATE case_sensitive,
    szipcode character varying(20) ENCODE lzo COLLATE case_sensitive,
    tsaddrlastcheck timestamp without time zone ENCODE az64,
    tsbirth timestamp without time zone ENCODE az64,
    tscreated timestamp without time zone ENCODE az64,
    tslastmodified timestamp without time zone ENCODE az64,
    bicnst_mstr_id bigint NOT NULL ENCODE az64,
    birecipientid bigint NOT NULL ENCODE az64,
    dlastdonationamt double precision NOT NULL ENCODE raw,
    iblacklistemail_bio smallint NOT NULL ENCODE az64,
    iblacklistemail_fr smallint NOT NULL ENCODE az64,
    iblacklistemail_phss smallint NOT NULL ENCODE az64,
    iblacklistemail_vms smallint NOT NULL ENCODE az64,
    iblacklistmobile_bio smallint NOT NULL ENCODE az64,
    iblacklistmobile_fr smallint NOT NULL ENCODE az64,
    iblacklistmobile_phss smallint NOT NULL ENCODE az64,
    iblacklistmobile_vms smallint NOT NULL ENCODE az64,
    iblacklistphone_bio smallint NOT NULL ENCODE az64,
    iblacklistphone_fr smallint NOT NULL ENCODE az64,
    iblacklistphone_phss smallint NOT NULL ENCODE az64,
    iblacklistphone_vms smallint NOT NULL ENCODE az64,
    iblacklistpostalmail_bio smallint NOT NULL ENCODE az64,
    iblacklistpostalmail_fr smallint NOT NULL ENCODE az64,
    iblacklistpostalmail_phss smallint NOT NULL ENCODE az64,
    iblacklistpostalmail_vms smallint NOT NULL ENCODE az64,
    iblacklist_bio smallint NOT NULL ENCODE az64,
    iblacklist_fr smallint NOT NULL ENCODE az64,
    iblacklist_phss smallint NOT NULL ENCODE az64,
    iblacklist_vms smallint NOT NULL ENCODE az64,
    ifr_field_unit_dimension_id integer NOT NULL ENCODE az64,
    ifr_mkt_field_unit_dimension_id integer NOT NULL ENCODE az64,
    iisbio smallint NOT NULL ENCODE az64,
    iisfr smallint NOT NULL ENCODE az64,
    iisphss smallint NOT NULL ENCODE az64,
    iisvms smallint NOT NULL ENCODE az64,
    saddress1_bio character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress1_fr character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress1_phss character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress1_vms character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress2_bio character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress2_fr character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress2_phss character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress2_vms character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress3_bio character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress3_fr character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress3_phss character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress3_vms character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress4_bio character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress4_fr character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress4_phss character varying(150) ENCODE lzo COLLATE case_sensitive,
    saddress4_vms character varying(150) ENCODE lzo COLLATE case_sensitive,
    sbioaddrquality character varying(255) ENCODE lzo COLLATE case_sensitive,
    sbio_em_email character varying(128) ENCODE lzo COLLATE case_sensitive,
    scity_bio character varying(75) ENCODE lzo COLLATE case_sensitive,
    scity_fr character varying(75) ENCODE lzo COLLATE case_sensitive,
    scity_phss character varying(75) ENCODE lzo COLLATE case_sensitive,
    scity_vms character varying(75) ENCODE lzo COLLATE case_sensitive,
    scountrycode_bio character varying(3) ENCODE lzo COLLATE case_sensitive,
    scountrycode_fr character varying(3) ENCODE lzo COLLATE case_sensitive,
    scountrycode_phss character varying(3) ENCODE lzo COLLATE case_sensitive,
    scountrycode_vms character varying(3) ENCODE lzo COLLATE case_sensitive,
    sfraddrquality character varying(255) ENCODE lzo COLLATE case_sensitive,
    sfr_em_email character varying(128) ENCODE lzo COLLATE case_sensitive,
    sline6 character varying(80) ENCODE lzo COLLATE case_sensitive,
    smobilephone_bio character varying(32) ENCODE lzo COLLATE case_sensitive,
    smobilephone_fr character varying(32) ENCODE lzo COLLATE case_sensitive,
    smobilephone_phss character varying(32) ENCODE lzo COLLATE case_sensitive,
    smobilephone_vms character varying(32) ENCODE lzo COLLATE case_sensitive,
    sofferorigin character varying(100) ENCODE lzo COLLATE case_sensitive,
    sphone_bio character varying(32) ENCODE lzo COLLATE case_sensitive,
    sphone_fr character varying(32) ENCODE lzo COLLATE case_sensitive,
    sphone_phss character varying(32) ENCODE lzo COLLATE case_sensitive,
    sphone_vms character varying(32) ENCODE lzo COLLATE case_sensitive,
    sphssaddrquality character varying(255) ENCODE lzo COLLATE case_sensitive,
    sphss_em_email character varying(128) ENCODE lzo COLLATE case_sensitive,
    sprofilepicture character varying(1000) ENCODE lzo COLLATE case_sensitive,
    srolename character varying(100) ENCODE lzo COLLATE case_sensitive,
    sstatecode_bio character varying(3) ENCODE lzo COLLATE case_sensitive,
    sstatecode_fr character varying(3) ENCODE lzo COLLATE case_sensitive,
    sstatecode_phss character varying(3) ENCODE lzo COLLATE case_sensitive,
    sstatecode_vms character varying(3) ENCODE lzo COLLATE case_sensitive,
    svmsaddrquality character varying(255) ENCODE lzo COLLATE case_sensitive,
    svms_em_email character varying(128) ENCODE lzo COLLATE case_sensitive,
    szipcode_bio character varying(20) ENCODE lzo COLLATE case_sensitive,
    szipcode_fr character varying(20) ENCODE lzo COLLATE case_sensitive,
    szipcode_phss character varying(20) ENCODE lzo COLLATE case_sensitive,
    szipcode_vms character varying(20) ENCODE lzo COLLATE case_sensitive,
    tslastdonation timestamp without time zone ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64,
    PRIMARY KEY (irecipientid)
)
DISTSTYLE KEY
SORTKEY ( irecipientid );