CREATE TABLE mktg_ops_tbls.aprm_wb_apnd_outbnd_msgs (
    snapshot_ts timestamp without time zone NOT NULL ENCODE az64,
    actvty_nm character varying(75) ENCODE lzo COLLATE case_insensitive,
    cnfrmtn_msg character varying(255) ENCODE lzo COLLATE case_insensitive,
    context character varying(75) ENCODE lzo COLLATE case_insensitive,
    custom_html character varying(255) ENCODE lzo COLLATE case_insensitive,
    designer_pg_id integer ENCODE az64,
    fwd_custom_html character varying(75) ENCODE lzo COLLATE case_insensitive,
    fwd_lnk_msg character varying(2000) ENCODE lzo COLLATE case_insensitive,
    html_email_subject character varying(200) ENCODE lzo COLLATE case_insensitive,
    html_inbnd_optnty_msg character varying(255) ENCODE lzo COLLATE case_insensitive,
    include_four character varying(765) ENCODE lzo COLLATE case_insensitive,
    include_html_four character varying(765) ENCODE lzo COLLATE case_insensitive,
    include_html_one character varying(765) ENCODE lzo COLLATE case_insensitive,
    include_html_subject character varying(765) ENCODE lzo COLLATE case_insensitive,
    include_html_three character varying(765) ENCODE lzo COLLATE case_insensitive,
    include_html_two character varying(765) ENCODE lzo COLLATE case_insensitive,
    include_one character varying(765) ENCODE lzo COLLATE case_insensitive,
    include_subject character varying(765) ENCODE lzo COLLATE case_insensitive,
    include_three character varying(765) ENCODE lzo COLLATE case_insensitive,
    include_two character varying(765) ENCODE lzo COLLATE case_insensitive,
    lang character varying(765) ENCODE lzo COLLATE case_insensitive,
    opt_out_form_id integer ENCODE az64,
    outbnd_id integer ENCODE az64,
    physcl_mail_addr character varying(1000) ENCODE lzo COLLATE case_insensitive,
    plain_txt_email_subject character varying(200) ENCODE lzo COLLATE case_insensitive,
    plain_txt_inbnd_opptnty character varying(255) ENCODE lzo COLLATE case_insensitive,
    status character varying(765) ENCODE lzo COLLATE case_insensitive,
    tgt_grp character varying(765) ENCODE lzo COLLATE case_insensitive,
    ttl character varying(75) ENCODE lzo COLLATE case_insensitive,
    universe character varying(75) ENCODE lzo COLLATE case_insensitive,
    unsubscribe_msg character varying(255) ENCODE lzo COLLATE case_insensitive,
    use_html_designer character varying(765) ENCODE lzo COLLATE case_insensitive,
    view_as_a_web_pg_msg character varying(256) ENCODE lzo COLLATE case_insensitive,
    web_analytics_ind character varying(765) ENCODE lzo COLLATE case_insensitive,
    cnt_num integer ENCODE az64,
    enable_call_ctr integer ENCODE az64,
    enable_fax integer ENCODE az64,
    enable_html_email integer ENCODE az64,
    enable_mail_merge integer ENCODE az64,
    enable_plain_txt_email integer ENCODE az64,
    nmbr_of_friends integer ENCODE az64,
    trk_email_open integer ENCODE az64,
    dw_create_ts timestamp without time zone NOT NULL ENCODE az64,
    srcsys_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_updt_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_insensitive,
    appl_src_cd character(4) NOT NULL ENCODE lzo COLLATE case_insensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;