CREATE TABLE mktg_ops_tbls.aprm_email_sent_img (
    cnst_mstr_id bigint NOT NULL ENCODE az64,
    history_record_id integer ENCODE az64,
    history_record_date timestamp without time zone ENCODE az64,
    email_gen_run_id integer ENCODE az64,
    outbound_id integer ENCODE az64,
    outbound_title character varying(225) ENCODE lzo COLLATE case_insensitive,
    sent_date timestamp without time zone ENCODE az64,
    delivered_date timestamp without time zone ENCODE az64,
    activity_id integer ENCODE az64,
    activity_title character varying(225) ENCODE lzo COLLATE case_insensitive,
    segmentation_id integer ENCODE az64,
    segmentation_title character varying(225) ENCODE lzo COLLATE case_insensitive,
    segment_id integer ENCODE az64,
    segment_title character varying(225) ENCODE lzo COLLATE case_insensitive,
    from_display_name character varying(765) ENCODE lzo COLLATE case_insensitive,
    from_email character varying(765) ENCODE lzo COLLATE case_insensitive,
    reply_to_email character varying(765) ENCODE lzo COLLATE case_insensitive,
    to_email character varying(765) ENCODE lzo COLLATE case_insensitive,
    to_display_name character varying(765) ENCODE lzo COLLATE case_insensitive,
    to_domain character varying(525) ENCODE lzo COLLATE case_insensitive,
    is_forwarded integer ENCODE az64,
    forwarding_email character varying(765) ENCODE lzo COLLATE case_insensitive,
    abstract character varying(1500) ENCODE lzo COLLATE case_insensitive,
    email_id integer NOT NULL ENCODE az64,
    contxt_cd character(1) ENCODE lzo COLLATE case_insensitive,
    dw_srcsys_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_insensitive,
    appl_src_cd character(4) NOT NULL ENCODE lzo COLLATE case_insensitive,
    load_id integer NOT NULL ENCODE az64,
    upd_flg character(1) ENCODE lzo COLLATE case_insensitive
)
DISTSTYLE ALL;