CREATE TABLE mktg_ops_tbls.arc_phss_txn (
    cnst_mstr_id bigint NOT NULL ENCODE az64,
    cnst_hsld_id character varying(18) ENCODE lzo COLLATE case_insensitive,
    offer_id character varying(20) ENCODE lzo COLLATE case_insensitive,
    trans_srcsys_cd character varying(4) ENCODE lzo COLLATE case_insensitive,
    person_key integer ENCODE az64,
    person_num character varying(20) ENCODE lzo COLLATE case_insensitive,
    trans_zip_cd character varying(10) ENCODE lzo COLLATE case_insensitive,
    trans_longitude integer ENCODE az64,
    trans_latitude integer ENCODE az64,
    parntl_consnt_flg integer ENCODE az64,
    parntl_person_key integer ENCODE az64,
    instruct_flg character(1) ENCODE lzo COLLATE case_insensitive,
    org_key integer ENCODE az64,
    org_nm character varying(200) ENCODE lzo COLLATE case_insensitive,
    org_typ character varying(20) ENCODE lzo COLLATE case_insensitive,
    offer_crs_num character varying(20) ENCODE lzo COLLATE case_insensitive,
    course_key integer ENCODE az64,
    course_num character varying(100) ENCODE lzo COLLATE case_insensitive,
    nk_course character varying(20) ENCODE lzo COLLATE case_insensitive,
    course_exprtn_dt date ENCODE az64,
    course_nm character varying(1020) ENCODE lzo COLLATE case_insensitive,
    course_ver character varying(20) ENCODE lzo COLLATE case_insensitive,
    course_delivery_stat character varying(20) ENCODE lzo COLLATE case_insensitive,
    course_delivery_typ character varying(50) ENCODE lzo COLLATE case_insensitive,
    course_focis_ctg character varying(20) ENCODE lzo COLLATE case_insensitive,
    focis_pgm character varying(100) ENCODE lzo COLLATE case_insensitive,
    focs_line_of_svc character varying(1020) ENCODE lzo COLLATE case_insensitive,
    course_focis_loc character varying(20) ENCODE lzo COLLATE case_insensitive,
    subject_area character varying(100) ENCODE lzo COLLATE case_insensitive,
    private_offer_flg character varying(3) ENCODE lzo COLLATE case_insensitive,
    dervd_offer_type character varying(20) ENCODE lzo COLLATE case_insensitive,
    course_enrlmnt_stat character varying(20) ENCODE lzo COLLATE case_insensitive,
    course_compl_stat character varying(20) ENCODE lzo COLLATE case_insensitive,
    course_nxt_recert_dt date ENCODE az64,
    course_comp_cnt integer ENCODE az64,
    course_totl_comp_mastrd_cnt integer ENCODE az64,
    course_totl_comp_fail_cnt integer ENCODE az64,
    course_totl_comp_not_evltd_cnt integer ENCODE az64,
    course_attd_cnt integer ENCODE az64,
    course_tot_comp_1yrcert_cnt integer ENCODE az64,
    course_tot_comp_2yrcert_cnt integer ENCODE az64,
    course_tot_comp_3yrcert_cnt integer ENCODE az64,
    course_tot_comp_no_expr_cnt integer ENCODE az64,
    order_key integer ENCODE az64,
    order_key_typ character varying(10) ENCODE lzo COLLATE case_insensitive,
    order_appl_src_cd character varying(4) ENCODE lzo COLLATE case_insensitive,
    order_num character varying(100) ENCODE lzo COLLATE case_insensitive,
    order_paymnt_num character varying(200) ENCODE lzo COLLATE case_insensitive,
    order_status character varying(50) ENCODE lzo COLLATE case_insensitive,
    order_reg_method character varying(20) ENCODE lzo COLLATE case_insensitive,
    order_paymt_method character varying(50) ENCODE lzo COLLATE case_insensitive,
    order_coupon_cd character varying(255) ENCODE lzo COLLATE case_insensitive,
    order_coupon_typ character varying(20) ENCODE lzo COLLATE case_insensitive,
    order_coupon_dsc character varying(255) ENCODE lzo COLLATE case_insensitive,
    course_facility_key integer ENCODE az64,
    course_deliver_room_typ character varying(10) ENCODE lzo COLLATE case_insensitive,
    course_deliver_faclty_typ character varying(10) ENCODE lzo COLLATE case_insensitive,
    unit_key integer ENCODE az64,
    division_cd character(4) ENCODE lzo COLLATE case_insensitive,
    tot_payment_amt numeric(18,2) ENCODE az64,
    addl_chgs_amt numeric(18,2) ENCODE az64,
    reduced_chgs_amt numeric(18,2) ENCODE az64,
    coupn_amt numeric(18,2) ENCODE az64,
    cancel_fee_amt numeric(18,2) ENCODE az64,
    item_cancel_amt numeric(18,2) ENCODE az64,
    offer_price_amt numeric(18,2) ENCODE az64,
    offer_end_dt date ENCODE az64,
    offer_start_dt date ENCODE az64,
    course_discontinued_flg character varying(1) ENCODE lzo COLLATE case_insensitive,
    offer_cancellation_dt date ENCODE az64,
    course_renewal_period character(20) ENCODE lzo COLLATE case_insensitive,
    course_valid_for character(20) ENCODE lzo COLLATE case_insensitive,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_insensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE ALL;