CREATE TABLE mktg_ops_tbls.bzfc_adb_recipient_insrt_delta (
    igender integer ENCODE az64,
    irecipientid integer ENCODE raw,
    saddress1 character varying(80) ENCODE lzo COLLATE case_sensitive,
    saddress2 character varying(80) ENCODE lzo COLLATE case_sensitive,
    scity character varying(75) ENCODE lzo COLLATE case_sensitive,
    semail character varying(128) ENCODE lzo COLLATE case_sensitive,
    sfirstname character varying(200) ENCODE lzo COLLATE case_sensitive,
    slastname character varying(50) ENCODE lzo COLLATE case_sensitive,
    smiddlename character varying(50) ENCODE lzo COLLATE case_sensitive,
    smobilephone character varying(15) ENCODE lzo COLLATE case_sensitive,
    sorigin character varying(15) ENCODE lzo COLLATE case_sensitive,
    sphone character varying(15) ENCODE lzo COLLATE case_sensitive,
    ssalutation character varying(20) ENCODE lzo COLLATE case_sensitive,
    sstatecode character varying(2) ENCODE lzo COLLATE case_sensitive,
    szipcode character(5) ENCODE lzo COLLATE case_sensitive,
    tsbirth timestamp without time zone ENCODE az64,
    tslastmodified timestamp without time zone ENCODE az64,
    tscreated timestamp without time zone ENCODE az64,
    bicnst_mstr_id bigint ENCODE raw distkey,
    birecipientid integer ENCODE az64,
    dlastdonationamt numeric(13,2) ENCODE az64,
    ifr_field_unit_dimension_id integer ENCODE az64,
    fr_field_chapter_cd character(5) ENCODE lzo COLLATE case_sensitive,
    fr_field_region_cd character(5) ENCODE lzo COLLATE case_sensitive,
    ifr_mkt_field_unit_dimension_id integer ENCODE az64,
    fr_mkt_chapter_cd character varying(5) ENCODE lzo COLLATE case_sensitive,
    fr_mkt_region_cd character varying(5) ENCODE lzo COLLATE case_sensitive,
    iisbio smallint ENCODE az64,
    iisfr smallint ENCODE az64,
    iisphss smallint ENCODE az64,
    iisvms smallint ENCODE az64,
    saddress1_bio character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress1_fr character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress1_phss character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress1_vms character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress2_bio character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress2_fr character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress2_phss character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress2_vms character varying(100) ENCODE lzo COLLATE case_sensitive,
    sbio_em_email character varying(100) ENCODE lzo COLLATE case_sensitive,
    scity_bio character varying(100) ENCODE lzo COLLATE case_sensitive,
    scity_fr character varying(100) ENCODE lzo COLLATE case_sensitive,
    scity_phss character varying(100) ENCODE lzo COLLATE case_sensitive,
    scity_vms character varying(100) ENCODE lzo COLLATE case_sensitive,
    sfraddrquality character varying(40) ENCODE lzo COLLATE case_sensitive,
    sfr_em_email character varying(100) ENCODE lzo COLLATE case_sensitive,
    sbioaddrquality character varying(40) ENCODE lzo COLLATE case_sensitive,
    scompany character varying(150) ENCODE lzo COLLATE case_sensitive,
    smobilephone_bio character varying(15) ENCODE lzo COLLATE case_sensitive,
    smobilephone_fr character varying(15) ENCODE lzo COLLATE case_sensitive,
    smobilephone_phss character varying(15) ENCODE lzo COLLATE case_sensitive,
    smobilephone_vms character varying(15) ENCODE lzo COLLATE case_sensitive,
    sphone_bio character varying(15) ENCODE lzo COLLATE case_sensitive,
    sphone_fr character varying(15) ENCODE lzo COLLATE case_sensitive,
    sphone_phss character varying(15) ENCODE lzo COLLATE case_sensitive,
    sphone_vms character varying(15) ENCODE lzo COLLATE case_sensitive,
    sphssaddrquality character varying(40) ENCODE lzo COLLATE case_sensitive,
    sphss_em_email character varying(100) ENCODE lzo COLLATE case_sensitive,
    sstatecode_bio character(2) ENCODE lzo COLLATE case_sensitive,
    sstatecode_fr character(2) ENCODE lzo COLLATE case_sensitive,
    sstatecode_phss character(2) ENCODE lzo COLLATE case_sensitive,
    sstatecode_vms character(2) ENCODE lzo COLLATE case_sensitive,
    svmsaddrquality character varying(40) ENCODE lzo COLLATE case_sensitive,
    svms_em_email character varying(100) ENCODE lzo COLLATE case_sensitive,
    szipcode_bio character(5) ENCODE lzo COLLATE case_sensitive,
    szipcode_fr character(5) ENCODE lzo COLLATE case_sensitive,
    szipcode_phss character(5) ENCODE lzo COLLATE case_sensitive,
    szipcode_vms character(5) ENCODE lzo COLLATE case_sensitive,
    bidm_namelocatorkey bigint ENCODE az64,
    biem_namelocatorkey bigint ENCODE az64,
    biemaillocatorkey bigint ENCODE az64,
    biaddrlocatorkey bigint ENCODE az64,
    biprimphonelocatorkey bigint ENCODE az64,
    bimblphonelocatorkey bigint ENCODE az64,
    sdm_firstname_fr character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_middlename_fr character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_lastname_fr character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_firstname_bio character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_middlename_bio character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_lastname_bio character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_firstname_phss character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_middlename_phss character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_lastname_phss character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_firstname_vms character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_middlename_vms character varying(50) ENCODE lzo COLLATE case_sensitive,
    sdm_lastname_vms character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_firstname_fr character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_middlename_fr character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_lastname_fr character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_firstname_bio character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_middlename_bio character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_lastname_bio character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_firstname_phss character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_middlename_phss character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_lastname_phss character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_firstname_vms character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_middlename_vms character varying(50) ENCODE lzo COLLATE case_sensitive,
    sem_lastname_vms character varying(50) ENCODE lzo COLLATE case_sensitive,
    semailquality_fr character varying(40) ENCODE lzo COLLATE case_sensitive,
    semailquality_bio character varying(40) ENCODE lzo COLLATE case_sensitive,
    semailquality_phss character varying(40) ENCODE lzo COLLATE case_sensitive,
    semailquality_vms character varying(40) ENCODE lzo COLLATE case_sensitive,
    saddress4_fr character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress4_bio character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress4_phss character varying(100) ENCODE lzo COLLATE case_sensitive,
    saddress4_vms character varying(100) ENCODE lzo COLLATE case_sensitive,
    tslastdonation date ENCODE az64,
    sfr_ok_to_email_flg character varying(1) ENCODE lzo COLLATE case_sensitive,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive
)
DISTSTYLE KEY
SORTKEY ( irecipientid, bicnst_mstr_id );