CREATE TABLE mktg_ops_tbls.cnst_cdi_s_f_p_fr_email (
    cnst_mstr_id bigint NOT NULL ENCODE raw distkey,
    cnst_hsld_id character varying(36) ENCODE lzo COLLATE case_sensitive,
    cnst_dsp_deceased_cd character(2) ENCODE lzo COLLATE case_sensitive,
    cnst_data_src_cd character varying(25) ENCODE lzo COLLATE case_sensitive,
    locator_prsn_nm_key bigint ENCODE az64,
    cnst_prsn_nm_assessmnt_ctg character varying(128) ENCODE lzo COLLATE case_sensitive,
    cnst_prsn_prfx_nm character varying(150) ENCODE lzo COLLATE case_sensitive,
    cnst_prsn_f_nm character varying(150) ENCODE lzo COLLATE case_sensitive,
    cnst_prsn_m_nm character varying(150) ENCODE lzo COLLATE case_sensitive,
    cnst_prsn_l_nm character varying(150) ENCODE lzo COLLATE case_sensitive,
    cnst_prsn_sfx_nm character varying(150) ENCODE lzo COLLATE case_sensitive,
    cnst_prsn_full_nm character varying(255) ENCODE lzo COLLATE case_sensitive,
    cnst_alias_in_saltn_nm character varying(255) ENCODE lzo COLLATE case_sensitive,
    cnst_alias_out_saltn_nm character varying(255) ENCODE lzo COLLATE case_sensitive,
    locator_addr_key bigint ENCODE az64,
    cnst_addr_assessmnt_ctg character varying(128) ENCODE lzo COLLATE case_sensitive,
    cnst_line_1_addr character varying(400) ENCODE lzo COLLATE case_sensitive,
    cnst_line_2_addr character varying(400) ENCODE lzo COLLATE case_sensitive,
    cnst_city_nm character varying(400) ENCODE lzo COLLATE case_sensitive,
    cnst_st_cd character(10) ENCODE lzo COLLATE case_sensitive,
    cnst_zip_5_cd character(15) ENCODE lzo COLLATE case_sensitive,
    cnst_zip_4_cd character(25) ENCODE lzo COLLATE case_sensitive,
    cnst_addr_county_nm character varying(400) ENCODE lzo COLLATE case_sensitive,
    cnst_email character varying(255) ENCODE lzo COLLATE case_sensitive,
    cnst_email_key bigint ENCODE az64,
    cnst_email_assessmnt_ctg character varying(128) ENCODE lzo COLLATE case_sensitive,
    cnst_org_nm character varying(512) ENCODE lzo COLLATE case_sensitive,
    cnst_typ_dsc character varying(50) ENCODE lzo COLLATE case_sensitive
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );