CREATE TABLE mktg_ops_tbls.dim_delivery (
    delivery_key integer ENCODE zstd,
    nk_delivery_id integer ENCODE zstd distkey,
    campgn_key integer ENCODE zstd,
    campgn_id integer ENCODE zstd,
    delivery_label character varying(128) ENCODE zstd COLLATE case_sensitive,
    delivery_cd character varying(36) ENCODE zstd COLLATE case_sensitive,
    delivery_status_id integer ENCODE zstd,
    delivery_status_dsc character varying(30) ENCODE zstd COLLATE case_sensitive,
    delivery_state_id integer ENCODE zstd,
    delivery_state_dsc character varying(30) ENCODE zstd COLLATE case_sensitive,
    msg_sent_cnt integer ENCODE zstd,
    msg_deliver_cnt integer ENCODE zstd,
    msg_procsd_cnt integer ENCODE zstd,
    msg_open_cnt integer ENCODE zstd,
    msg_bounce_cnt integer ENCODE zstd,
    msg_unsubscrb_cnt integer ENCODE zstd,
    msg_click_cnt integer ENCODE zstd,
    msg_success_cnt integer ENCODE zstd,
    msg_success_noseed_cnt integer ENCODE zstd,
    msg_reject_cnt integer ENCODE zstd,
    msg_refused_cnt integer ENCODE zstd,
    mailbox_full_cnt integer ENCODE zstd,
    invalid_domain_cnt integer ENCODE zstd,
    msg_forward_cnt integer ENCODE zstd,
    xpromo_ind smallint ENCODE zstd,
    xpromo_flg character(1) ENCODE zstd COLLATE case_sensitive,
    xpromo_from character varying(25) ENCODE zstd COLLATE case_sensitive,
    xpromo_to character varying(25) ENCODE zstd COLLATE case_sensitive,
    exclude_rptng_ind smallint ENCODE zstd,
    is_trigg_msg_ind smallint ENCODE zstd,
    scid character varying(50) ENCODE zstd COLLATE case_sensitive,
    src_cd character varying(50) ENCODE zstd COLLATE case_sensitive,
    subsrc_cd character varying(50) ENCODE zstd COLLATE case_sensitive,
    mail_drop_dt date ENCODE zstd,
    srcsys_trans_ts timestamp without time zone NOT NULL ENCODE zstd,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE zstd,
    row_stat_cd character(1) NOT NULL ENCODE zstd COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE zstd COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE zstd
)
DISTSTYLE KEY
SORTKEY ( srcsys_trans_ts, dw_trans_ts );