CREATE TABLE mktg_ops_tbls.dim_bio_mstr_cust_appnd (
    mstr_cust_id character varying(50) NOT NULL ENCODE lzo COLLATE case_sensitive distkey,
    hospital_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    mstr_cust_typ_dsc character varying(50) ENCODE lzo COLLATE case_sensitive,
    cust_subclass_dsc character varying(50) ENCODE lzo COLLATE case_sensitive,
    grp_cd character varying(50) ENCODE lzo COLLATE case_sensitive,
    grp_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    grp_typ_dsc character varying(50) ENCODE lzo COLLATE case_sensitive,
    grp_subtyp_dsc character varying(50) ENCODE lzo COLLATE case_sensitive,
    lost_cust_flg character(1) ENCODE lzo COLLATE case_sensitive,
    contract_cust_flg character(1) ENCODE lzo COLLATE case_sensitive,
    self_collector_flg character(1) ENCODE lzo COLLATE case_sensitive,
    contract_end_dt date ENCODE az64,
    aha_id_txt character varying(50) ENCODE lzo COLLATE case_sensitive,
    bed_cnt integer ENCODE az64,
    territory_id character varying(50) ENCODE lzo COLLATE case_sensitive,
    cust_class_dsc character varying(50) ENCODE lzo COLLATE case_sensitive,
    territory_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    cancer_ctr_flg character(1) ENCODE lzo COLLATE case_sensitive,
    trauma_ctr_flg character(1) ENCODE lzo COLLATE case_sensitive,
    child_hosp_flg character(1) ENCODE lzo COLLATE case_sensitive,
    sales_director_id character varying(50) ENCODE lzo COLLATE case_sensitive,
    nataccts_flg character(1) ENCODE lzo COLLATE case_sensitive,
    physical_city character varying(50) ENCODE lzo COLLATE case_sensitive,
    physical_state character varying(50) ENCODE lzo COLLATE case_sensitive,
    physical_zip character varying(10) ENCODE lzo COLLATE case_sensitive,
    market_desc character varying(100) ENCODE lzo COLLATE case_sensitive,
    master_site_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    hs_region character varying(50) ENCODE lzo COLLATE case_sensitive,
    hs_division character varying(50) ENCODE lzo COLLATE case_sensitive,
    sss_bucket character varying(50) ENCODE lzo COLLATE case_sensitive,
    percent_arc character varying(50) ENCODE lzo COLLATE case_sensitive,
    latitude numeric(10,6) ENCODE az64,
    longitude numeric(10,6) ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64,
    PRIMARY KEY (mstr_cust_id)
)
DISTSTYLE KEY;