CREATE TABLE mktg_ops_tbls.fact_response_aprm (
    cnst_mstr_id bigint NOT NULL ENCODE raw distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE az64,
    cnst_hsld_id character varying(18) ENCODE lzo COLLATE case_sensitive,
    src_key bigint NOT NULL ENCODE az64,
    comnictn_src_key bigint NOT NULL ENCODE az64,
    comnictn_typ_key bigint NOT NULL ENCODE az64,
    response_typ_key bigint NOT NULL ENCODE az64,
    chan_typ_key bigint NOT NULL ENCODE az64,
    unit_key integer NOT NULL ENCODE az64,
    amt_typ_key bigint NOT NULL ENCODE az64,
    response_dt_key integer NOT NULL ENCODE az64,
    fr_last_ta_acct_id integer ENCODE az64,
    nk_tapg_acct_id integer ENCODE az64,
    nk_response_dt date ENCODE az64,
    response_ctg_cd character varying(10) ENCODE lzo COLLATE case_sensitive,
    response_typ_cd character varying(10) ENCODE lzo COLLATE case_sensitive,
    chapt_id character varying(5) ENCODE lzo COLLATE case_sensitive,
    comnictn_dsc character varying(300) ENCODE lzo COLLATE case_sensitive,
    offer_id integer ENCODE az64,
    treatment_id integer ENCODE az64,
    activity_id integer ENCODE az64,
    segmntn_id integer ENCODE az64,
    segmnt_id integer ENCODE az64,
    outbnd_id integer ENCODE az64,
    email_id integer ENCODE az64,
    cell_id integer ENCODE az64,
    cell_src_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    cell_subsrc_cd character varying(40) ENCODE lzo COLLATE case_sensitive,
    run_dt date ENCODE az64,
    run_id integer ENCODE az64,
    lead_amt numeric(11,2) ENCODE az64,
    closed_amt numeric(11,2) ENCODE az64,
    update_dt date ENCODE az64,
    note_txt character varying(10000) ENCODE lzo COLLATE case_sensitive,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64,
    srcsys_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );