CREATE TABLE mktg_ops_tbls.fact_phone_interaction (
    cnst_mstr_id bigint NOT NULL ENCODE az64 distkey,
    orig_cnst_mstr_id bigint NOT NULL ENCODE az64,
    recipient_key integer ENCODE az64,
    nk_recipient_id integer ENCODE az64,
    recipient_zip_cd character(5) ENCODE lzo COLLATE case_sensitive,
    cnst_hsld_id character varying(18) ENCODE lzo COLLATE case_sensitive,
    nk_intrctn_id integer ENCODE az64,
    delivery_key integer ENCODE az64,
    nk_delivery_id integer ENCODE az64,
    campaign_key integer ENCODE az64,
    nk_operation_id integer ENCODE az64,
    comnictn_src_key bigint ENCODE az64,
    comnictn_typ_key bigint ENCODE az64,
    chan_typ_key bigint ENCODE az64,
    chan_typ_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    unit_key integer ENCODE az64,
    nk_ecode character varying(5) ENCODE lzo COLLATE case_sensitive,
    intrctn_status_key integer ENCODE az64,
    nk_intrctn_status_dsc character varying(200) ENCODE lzo COLLATE case_sensitive,
    src_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    subsrc_cd character varying(40) ENCODE lzo COLLATE case_sensitive,
    intrctn_dt_key integer ENCODE az64,
    intrctn_dt date ENCODE az64,
    list_run_dt_key integer ENCODE az64,
    list_run_dt date ENCODE az64,
    segmnt_key integer ENCODE az64,
    nk_segmnt_cd character varying(50) ENCODE lzo COLLATE case_sensitive,
    gen_segmnt_key integer ENCODE az64,
    fr_last_ta_acct_id integer ENCODE az64,
    offer_key integer ENCODE az64,
    dm_locator_addr_key bigint ENCODE az64,
    reportcell_code_id integer ENCODE az64,
    nk_treatmnt_id integer ENCODE az64,
    treatmnt_key integer ENCODE az64,
    mktg_unit_key integer ENCODE az64,
    audience_typ character varying(255) ENCODE lzo COLLATE case_sensitive,
    call_ind smallint ENCODE az64,
    call_cnt integer ENCODE az64,
    call_result character varying(20) ENCODE lzo COLLATE case_sensitive,
    do_not_call_ind smallint ENCODE az64,
    supprsn_cnt integer ENCODE az64,
    last_dntn_dt date ENCODE az64,
    last_dntn_amt numeric(13,2) ENCODE az64,
    dm_intrctn_ind smallint ENCODE az64,
    srcsys_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY;