CREATE TABLE mktg_ops_tbls.gms_cnst_cdi_smry_fr_prfr (
    cnst_mstr_id bigint ENCODE az64,
    cnst_hsld_id character varying(18) ENCODE lzo COLLATE case_insensitive,
    cnst_arc_deceased_cd character(1) ENCODE lzo COLLATE case_insensitive,
    dm_prsn_nm_src_cd character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_data_src_cd character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_locator_prsn_nm_key bigint ENCODE az64,
    dm_cnst_prsn_nm_assessmnt_ctg character varying(40) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_prfx_nm character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_f_nm character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_m_nm character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_l_nm character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_sfx_nm character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_full_nm character varying(100) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_alias_in_saltn_nm character varying(120) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_alias_out_saltn_nm character varying(120) ENCODE lzo COLLATE case_insensitive,
    dm_pa_addr_check character varying(30) ENCODE lzo COLLATE case_insensitive,
    dm_locator_addr_key bigint ENCODE az64,
    dm_cnst_addr_assessmnt_ctg character varying(40) ENCODE lzo COLLATE case_insensitive,
    dpv_cd character varying(1) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_line_1_addr character varying(100) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_line_2_addr character varying(100) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_city_nm character varying(100) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_st_cd character(2) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_zip_5_cd character(5) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_zip_4_cd character(4) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_addr_county_nm character varying(100) ENCODE lzo COLLATE case_insensitive,
    cem_all_mail_override_flg character varying(1) ENCODE lzo COLLATE case_insensitive,
    cem_fr_mail_override_flg character varying(1) ENCODE lzo COLLATE case_insensitive,
    cem_all_mail_override_ind smallint ENCODE az64,
    cem_fr_mail_override_ind smallint ENCODE az64,
    ncoa_mail_override_flg character varying(1) ENCODE lzo COLLATE case_insensitive,
    ncoa_mail_override_ind smallint ENCODE az64,
    dm_cnst_email character varying(100) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_org_nm character varying(150) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_typ_dsc character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_prfx_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_f_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_m_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_l_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_sfx_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    dm_cnst_prsn_full_nm2 character varying(100) ENCODE lzo COLLATE case_insensitive,
    em_prsn_nm_src_cd character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_data_src_cd character varying(30) ENCODE lzo COLLATE case_insensitive,
    em_locator_prsn_nm_key bigint ENCODE az64,
    em_cnst_prsn_nm_assessmnt_ctg character varying(40) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_prfx_nm character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_f_nm character varying(200) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_m_nm character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_l_nm character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_sfx_nm character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_full_nm character varying(100) ENCODE lzo COLLATE case_insensitive,
    em_cnst_alias_in_saltn_nm character varying(120) ENCODE lzo COLLATE case_insensitive,
    em_cnst_alias_out_saltn_nm character varying(120) ENCODE lzo COLLATE case_insensitive,
    em_locator_addr_key bigint ENCODE az64,
    em_cnst_line_1_addr character varying(200) ENCODE lzo COLLATE case_insensitive,
    em_cnst_line_2_addr character varying(200) ENCODE lzo COLLATE case_insensitive,
    em_cnst_city_nm character varying(200) ENCODE lzo COLLATE case_insensitive,
    em_cnst_st_cd character varying(200) ENCODE lzo COLLATE case_insensitive,
    em_cnst_zip_5_cd character varying(5) ENCODE lzo COLLATE case_insensitive,
    em_cnst_zip_4_cd character varying(4) ENCODE lzo COLLATE case_insensitive,
    em_cnst_addr_county_nm character varying(100) ENCODE lzo COLLATE case_insensitive,
    em_cnst_email character varying(200) ENCODE lzo COLLATE case_insensitive,
    em_email_key bigint ENCODE az64 distkey,
    em_cnst_email_assessmnt_ctg character varying(40) ENCODE lzo COLLATE case_insensitive,
    em_cnst_org_nm character varying(150) ENCODE lzo COLLATE case_insensitive,
    em_cnst_typ_dsc character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_prfx_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_f_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_m_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_l_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_sfx_nm2 character varying(50) ENCODE lzo COLLATE case_insensitive,
    em_cnst_prsn_full_nm2 character varying(100) ENCODE lzo COLLATE case_insensitive,
    email_dlvrbl_ind smallint ENCODE az64,
    prim_cnst_phn character varying(25) ENCODE lzo COLLATE case_insensitive,
    prim_cnst_phn_source character varying(50) ENCODE lzo COLLATE case_insensitive,
    prim_cnst_phn_typ_dsc character varying(60) ENCODE lzo COLLATE case_insensitive,
    cnst_work_phn character varying(25) ENCODE lzo COLLATE case_insensitive,
    cnst_work_phn_source character varying(50) ENCODE lzo COLLATE case_insensitive,
    cnst_work_phn_typ_dsc character varying(60) ENCODE lzo COLLATE case_insensitive,
    cnst_mbl_phn character varying(25) ENCODE lzo COLLATE case_insensitive,
    cnst_mbl_phn_source character varying(50) ENCODE lzo COLLATE case_insensitive,
    cnst_mbl_phn_typ_dsc character varying(60) ENCODE lzo COLLATE case_insensitive,
    do_not_call_hm_phn_ind smallint ENCODE az64,
    do_not_call_mbl_phn_ind smallint ENCODE az64,
    do_not_call_work_phn_ind smallint ENCODE az64,
    do_not_email_ind smallint ENCODE az64,
    do_not_mail_ind smallint ENCODE az64,
    do_not_txt_ind smallint ENCODE az64,
    cnst_3rd_prty_segmtn_group_nm character varying(12) ENCODE lzo COLLATE case_insensitive,
    unit_key_src character varying(20) ENCODE lzo COLLATE case_insensitive,
    unit_key integer ENCODE az64,
    affl_lock_ind smallint ENCODE az64,
    sf_acct_fmd_ind smallint ENCODE az64,
    frf_status_cd character varying(20) ENCODE lzo COLLATE case_insensitive,
    portfolio_category character varying(100) ENCODE lzo COLLATE case_insensitive,
    rlshp_mgr_ownr_key bigint ENCODE az64,
    rlshp_mgr_nm character varying(100) ENCODE lzo COLLATE case_insensitive,
    rlshp_mgr_prefd_email_addr character varying(100) ENCODE lzo COLLATE case_insensitive,
    acct_in_salutn_nm character varying(100) ENCODE lzo COLLATE case_insensitive,
    acct_out_salutn_nm character varying(100) ENCODE lzo COLLATE case_insensitive,
    mktg_unit_key integer ENCODE az64,
    cnst_typ_cd character varying(2) ENCODE lzo COLLATE case_insensitive,
    org_typ_cd character varying(5) ENCODE lzo COLLATE case_insensitive,
    has_smry_profile_ind smallint ENCODE az64,
    inactvn_unf_fr_cnst_key integer ENCODE az64,
    inactvtn_reason_cd character varying(25) ENCODE lzo COLLATE case_insensitive,
    inactvtn_reason_dsc character varying(100) ENCODE lzo COLLATE case_insensitive,
    inactvtn_dt date ENCODE az64,
    inactvtn_reason_txt character varying(255) ENCODE lzo COLLATE case_insensitive,
    ag_bzd_sfid character varying(20) ENCODE lzo COLLATE case_insensitive,
    cntct_bzd_sfid character varying(20) ENCODE lzo COLLATE case_insensitive,
    mult_sf_cnst_ind smallint ENCODE az64,
    active_cnst_ind smallint ENCODE az64,
    active_email_cnst_ind smallint ENCODE az64,
    last_email_open_dt date ENCODE az64,
    last_email_intrctn_dt date ENCODE az64,
    last_dmail_intrctn_dt date ENCODE az64
)
DISTSTYLE AUTO;