CREATE TABLE mktg_ops_tbls.phone_interaction_pg_eoc (
    unq_id character varying(30) ENCODE lzo COLLATE case_sensitive distkey,
    cmpgn_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    pgm_typ character varying(10) ENCODE lzo COLLATE case_sensitive,
    cnst_mstr_id bigint ENCODE raw,
    orig_cnst_mstr_id bigint ENCODE az64,
    src_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    call_ts_src character varying(19) ENCODE lzo COLLATE case_sensitive,
    call_ts timestamp without time zone ENCODE az64,
    call_dt date ENCODE az64,
    sf_acct_id character varying(9) ENCODE lzo COLLATE case_sensitive,
    sf_cntct_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    sf_rm character varying(50) ENCODE lzo COLLATE case_sensitive,
    sf_mng_dnr_ind smallint ENCODE az64,
    nk_ecode character varying(256) ENCODE lzo COLLATE case_sensitive,
    ttl character varying(20) ENCODE lzo COLLATE case_sensitive,
    first_nm character varying(40) ENCODE lzo COLLATE case_sensitive,
    middle_nm character varying(40) ENCODE lzo COLLATE case_sensitive,
    last_nm character varying(80) ENCODE lzo COLLATE case_sensitive,
    sfx character varying(30) ENCODE lzo COLLATE case_sensitive,
    birth_dt_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    birth_dt date ENCODE az64,
    altrd_dt_flg character(1) ENCODE lzo COLLATE case_sensitive,
    drvd_age smallint ENCODE az64,
    lftm_gfts integer ENCODE az64,
    last_gift_dt_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    last_gift_dt date ENCODE az64,
    lrgst_gift_amt numeric(13,2) ENCODE az64,
    vlntr_flg character(1) ENCODE lzo COLLATE case_sensitive,
    biomed_flg character(1) ENCODE lzo COLLATE case_sensitive,
    trng_svc_flg character(1) ENCODE lzo COLLATE case_sensitive,
    pgwg_scr_val smallint ENCODE az64,
    pgcga_scr_val smallint ENCODE az64,
    pgbeq_scr_val smallint ENCODE az64,
    pg_lob character(2) ENCODE lzo COLLATE case_sensitive,
    cga_rspndr_ind smallint ENCODE az64,
    wg_rspndr_ind smallint ENCODE az64,
    srvy_rspndr_ind smallint ENCODE az64,
    lgcy_ind smallint ENCODE az64,
    non_rspndr_ind smallint ENCODE az64,
    addr_line1 character varying(50) ENCODE lzo COLLATE case_sensitive,
    addr_line2 character varying(50) ENCODE lzo COLLATE case_sensitive,
    addr_line3 character varying(50) ENCODE lzo COLLATE case_sensitive,
    city character varying(30) ENCODE lzo COLLATE case_sensitive,
    state character(2) ENCODE lzo COLLATE case_sensitive,
    zip_cd character varying(9) ENCODE lzo COLLATE case_sensitive,
    addr_line1_updt character varying(50) ENCODE lzo COLLATE case_sensitive,
    addr_line2_updt character varying(50) ENCODE lzo COLLATE case_sensitive,
    addr_line3_updt character varying(50) ENCODE lzo COLLATE case_sensitive,
    city_updt character varying(30) ENCODE lzo COLLATE case_sensitive,
    state_updt character(2) ENCODE lzo COLLATE case_sensitive,
    zip_cd_updt character varying(9) ENCODE lzo COLLATE case_sensitive,
    phn_num_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    phn_num_updt_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    home_phn_num character varying(256) ENCODE lzo COLLATE case_sensitive,
    home_phn_num_cln character varying(256) ENCODE lzo COLLATE case_sensitive,
    mbl_phn_num character varying(256) ENCODE lzo COLLATE case_sensitive,
    mbl_phn_num_cln character varying(256) ENCODE lzo COLLATE case_sensitive,
    phn_num_updt_cln character varying(256) ENCODE lzo COLLATE case_sensitive,
    phone_mobile_ind smallint ENCODE az64,
    phone_home_ind smallint ENCODE az64,
    email_addr character varying(50) ENCODE lzo COLLATE case_sensitive,
    email_addr_updt character varying(50) ENCODE lzo COLLATE case_sensitive,
    pg_rspns_typ character varying(20) ENCODE lzo COLLATE case_sensitive,
    do_not_mail_ind smallint ENCODE az64,
    do_not_call_ind smallint ENCODE az64,
    cmnt character varying(256) ENCODE lzo COLLATE case_sensitive,
    rpt_cell_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    rpt_cell_cd_id integer ENCODE az64,
    trtmnt_cd character varying(10) ENCODE lzo COLLATE case_sensitive,
    trtmnt_dsc character varying(100) ENCODE lzo COLLATE case_sensitive,
    trtmnt_id integer ENCODE az64,
    call_sgmt character varying(256) ENCODE lzo COLLATE case_sensitive,
    call_start_ts_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    call_start_ts timestamp without time zone ENCODE az64,
    call_end_ts_src character varying(256) ENCODE lzo COLLATE case_sensitive,
    call_end_ts timestamp without time zone ENCODE az64,
    elapsed_call_tm character varying(256) ENCODE lzo COLLATE case_sensitive,
    dspstn1 character(2) ENCODE lzo COLLATE case_sensitive,
    dspstn2 character(2) ENCODE lzo COLLATE case_sensitive,
    rcrdg_file_nm character varying(25) ENCODE lzo COLLATE case_sensitive,
    curr_prcsd_file_nm character varying(256) ENCODE lzo COLLATE case_sensitive,
    dw_trans_ts timestamp without time zone NOT NULL ENCODE az64,
    row_stat_cd character(1) NOT NULL ENCODE lzo COLLATE case_sensitive,
    appl_src_cd character varying(4) NOT NULL ENCODE lzo COLLATE case_sensitive,
    load_id integer NOT NULL ENCODE az64
)
DISTSTYLE KEY
SORTKEY ( cnst_mstr_id );