CREATE TABLE mktg_ops_tbls.replication_dim_person (
    person_key integer ENCODE az64,
    primary_org_key integer ENCODE az64,
    nk_person_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    nk_crs_id character varying(300) ENCODE lzo COLLATE case_sensitive,
    nk_crs_entry_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    unit_key integer ENCODE az64,
    instruct_flg character(1) ENCODE lzo COLLATE case_sensitive,
    title_nm character varying(20) ENCODE lzo COLLATE case_sensitive,
    first_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    mid_init character varying(20) ENCODE lzo COLLATE case_sensitive,
    last_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    full_nm character varying(20) ENCODE lzo COLLATE case_sensitive,
    addr character varying(200) ENCODE lzo COLLATE case_sensitive,
    city character varying(200) ENCODE lzo COLLATE case_sensitive,
    state character varying(20) ENCODE lzo COLLATE case_sensitive,
    zip_cd character varying(10) ENCODE lzo COLLATE case_sensitive,
    email character varying(100) ENCODE lzo COLLATE case_sensitive,
    person_typ character varying(100) ENCODE lzo COLLATE case_sensitive,
    home_phone character varying(100) ENCODE lzo COLLATE case_sensitive,
    work_phone character varying(100) ENCODE lzo COLLATE case_sensitive,
    cell_phone character varying(100) ENCODE lzo COLLATE case_sensitive,
    person_num character varying(10) ENCODE lzo COLLATE case_sensitive,
    gender character(1) ENCODE lzo COLLATE case_sensitive,
    status character varying(100) ENCODE lzo COLLATE case_sensitive,
    domn character varying(100) ENCODE lzo COLLATE case_sensitive,
    job_typ character varying(20) ENCODE lzo COLLATE case_sensitive,
    manager_nm character varying(100) ENCODE lzo COLLATE case_sensitive,
    start_dt date ENCODE az64,
    separation_dt date ENCODE az64,
    ethnicity character varying(20) ENCODE lzo COLLATE case_sensitive,
    birth_dt date ENCODE az64,
    volunteer_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    instruct_pay_typ character varying(20) ENCODE lzo COLLATE case_sensitive,
    instruct_stand character varying(20) ENCODE lzo COLLATE case_sensitive,
    dshr_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    merged_flg character(1) ENCODE lzo COLLATE case_sensitive,
    county character varying(20) ENCODE lzo COLLATE case_sensitive,
    old_lms_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    employee_id character varying(20) ENCODE lzo COLLATE case_sensitive,
    locale character varying(20) ENCODE lzo COLLATE case_sensitive,
    unit_cd character varying(20) ENCODE lzo COLLATE case_sensitive,
    user_nm character varying(1020) ENCODE lzo COLLATE case_sensitive,
    time_zone character varying(255) ENCODE lzo COLLATE case_sensitive,
    income character varying(255) ENCODE lzo COLLATE case_sensitive,
    type_desc character varying(20) ENCODE lzo COLLATE case_sensitive,
    instruct_flg_changed character(1) ENCODE lzo COLLATE case_sensitive,
    created_by character varying(100) ENCODE lzo COLLATE case_sensitive,
    create_ts timestamp without time zone ENCODE az64,
    last_updt_by character varying(100) ENCODE lzo COLLATE case_sensitive,
    last_updt_ts timestamp without time zone ENCODE az64,
    saba_archvd_flg character(1) ENCODE lzo COLLATE case_sensitive,
    saba_archvd_dt timestamp without time zone ENCODE az64,
    saba_archvd_by character varying(100) ENCODE lzo COLLATE case_sensitive,
    additional_info character varying(100) ENCODE lzo COLLATE case_sensitive,
    row_stat_cd character(1) ENCODE lzo COLLATE case_sensitive,
    dw_trans_ts timestamp without time zone ENCODE az64,
    appl_src_cd character varying(4) ENCODE lzo COLLATE case_sensitive,
    load_id integer ENCODE az64
)
DISTSTYLE EVEN;