CREATE OR REPLACE VIEW mods_bi.ufds_vws.bzfc_dim_unf_fr_indv AS
/*
Created BY: Soumya P
Created Date:08/03/2019
Purpose :Too fetch 'IN' records

Modified by : Aman Kumar
modified date :6-june-2019
purpose :added the prefd_county_cd and prefd_county_nm  columns
*/
SELECT
unf_fr_cnst_key ,
nk_gmp_cnst_id,
nk_gpp_cnst_seq,
nk_sf_acct_guid,
nk_sf_cntct_guid,
nk_ta_acct_id,
nk_ta_nm_id,
nk_chpt_sys_id,
nk_hema_intrnl_acct_id,
nk_hema_intrnl_cntct_id,
frf_acct_id,
frf_cntct_id,
cnst_mstr_id,
cnst_alt_id,
cnst_typ_cd,
cnst_typ_dsc,
dnr_typ_cd,
dnr_typ_dsc,
prfx_cd,
prfx_dsc,
first_nm,
midl_nm,
last_nm,
sfx_cd,
sfx_dsc,
job_title_nm,
nm_line,
empl_num,
prefd_addr_locator_key,
prefd_addr_typ,
prefd_addr_line_1,
prefd_addr_line_2,
prefd_city_nm,
prefd_state_cd,
prefd_state_dsc,
prefd_zip_cd,
prefd_country_cd,
prefd_country_nm,
prefd_county_cd,
prefd_county_nm,
prefd_phn_locator_key,
prefd_phn_typ,
prefd_phn_num,
prefd_email_locator_key,
prefd_email_typ,
prefd_email_addr,
prefd_lang_cd,
prefd_lang_dsc,
strt_dt,
death_dt,
frf_spotlighted_dt,
birth_dy,
birth_mth,
birth_yr,
active_ind,
frf_active_ind,
prim_ind,
deceased_ind,
--affl_lock_ind,
anon_ind,
prvt_ind,
has_cdi_mstr_brg_ind,
frf_acct_key,
frf_anon_ind,
frf_gift_mngd_dnr_ind,
frf_cur_mngd_dnr_ind,
frf_prvt_ind,
frf_visit_in_pairs_ind,
frf_spotlight_dnr_ind,
frf_upld_txt,
sustnr_ind,
plnd_gvng_confirm_ind,
plnd_gvng_info_rqst_ind,
inactvtn_reason_cd,
inactvtn_reason_dsc,
inactvtn_dt,
inactvtn_reason_txt,
frf_status_cd,
frf_spotlight_note_txt,
frf_num_of_lctn,
frf_gift_portfolio_ctg,
frf_cur_portfolio_ctg,
frf_industry_nm,
frf_acct_ownr_asgnd_dt,
frf_acct_modified_key,
frf_prev_acct_ownr_key,
frf_acct_ownr_key,
frf_rev_credit_key,
rev_credit_key,
bio_acct_mngr_nm,
bio_acct_mngr_email,
bio_acct_mngr_phn,
bio_acct_ind,
bio_annual_collect_tgt,
bio_annual_drive_tgt,
bio_rgn_nm,
bio_cllctn_zipcode_dtl_key,
bio_maintain_strat_ind,
backed_out_ind,
back_out_reason_cd,
vendor_src_cd,
grp_active_cnst_cnt,
grp_cnst_1_key,
grp_cnst_2_key,
grp_cnst_1_spouse_key,
grp_cnst_2_spouse_key,
grp_org_cnst_key,
grp_cnst_1_mstr_id,
grp_cnst_2_mstr_id,
grp_cnst_1_spouse_mstr_id,
grp_cnst_2_spouse_mstr_id,
grp_org_mstr_id,
grp_cnst_rmng_mstr_id,
grp_cnst_rmng_cnst_nm,
related_org_1_key,
related_org_2_key,
related_org_3_key,
appl_src_cd,
buyerattributes
FROM eda.ufds_vws.bzfc_dim_unf_fr_cnst
WHERE cnst_typ_cd IN ('IN', 'DW Unknown')
WITH NO SCHEMA BINDING;
GRANT ALL ON TABLE mods_bi.ufds_vws.bzfc_dim_unf_fr_indv TO role ds_mods_writer;
GRANT SELECT ON TABLE mods_bi.ufds_vws.bzfc_dim_unf_fr_indv TO role ds_mods_reader_vt;
