CREATE OR REPLACE VIEW mods_bi.ufds_vws.bzfc_dim_unf_fr_cnst AS
/*---------------------------------------------------------------------------
Updated By: GMS PBI Team
Updated On: May 28 2024
Purpose: Adding 3 new columns parent_id, parent_acct_cnst_key and parent_ind for GMS-37298
---------------------------------------------------------------------------*/
SELECT
unf_fr_cnst_key,
nk_gmp_cnst_id,
nk_gpp_cnst_seq,
nk_sf_acct_guid,
nk_sf_cntct_guid,
nk_ta_acct_id,
nk_ta_nm_id,
nk_chpt_sys_id,
nk_hema_intrnl_acct_id,
nk_hema_intrnl_cntct_id,
frf_acct_id,
frf_cntct_id,
cnst_mstr_id,
cnst_alt_id,
ent_org_id,
obslt_cnst_fsa_key,
cnst_typ_cd,
cnst_typ_dsc,
dnr_typ_cd,
dnr_typ_dsc,
prfx_cd,
prfx_dsc,
first_nm,
midl_nm,
last_nm,
sfx_cd,
sfx_dsc,
addressee,
salutn,
maiden_nm,
nick_nm,
alias_nm,
presidential_salutn,
job_title_nm,
org_nm,
nm_line,
empl_num,
prefd_addr_locator_key,
prefd_addr_typ,
prefd_addr_line_1,
prefd_addr_line_2,
prefd_city_nm,
prefd_state_cd,
prefd_state_dsc,
prefd_zip_cd,
prefd_country_cd,
prefd_country_nm,
prefd_county_cd,
prefd_county_nm,
prefd_phn_locator_key,
prefd_phn_typ,
prefd_phn_num,
prefd_email_locator_key,
prefd_email_typ,
prefd_email_addr,
prefd_lang_cd,
prefd_lang_dsc,
grp_active_cnst_cnt,
grp_cnst_1_key,
grp_cnst_2_key,
grp_cnst_1_spouse_key,
grp_cnst_2_spouse_key,
grp_org_cnst_key,
grp_cnst_1_mstr_id,
grp_cnst_2_mstr_id,
grp_cnst_1_spouse_mstr_id,
grp_cnst_2_spouse_mstr_id,
grp_org_mstr_id,
grp_cnst_rmng_mstr_id,
grp_cnst_rmng_cnst_nm,
related_org_1_key,
related_org_2_key,
related_org_3_key,
concat_hard_credit_gift_id,
concat_sc_gift_id,
TO_CHAR(CAST(strt_dt AS DATE), 'MM/DD/YYYY') AS strt_dt,
TO_CHAR(CAST(death_dt AS DATE), 'MM/DD/YYYY') AS death_dt,
frf_spotlighted_dt,
birth_dy,
birth_mth,
birth_yr,
active_ind,
frf_active_ind,
prim_ind,
frf_anon_ind,
trbt_notif_rcpnt_ind,
third_prty_contributor_ind,
ownr_ind,
deceased_ind,
anon_ind,
prvt_ind,
has_cdi_mstr_brg_ind ,
frf_gift_mngd_dnr_ind,
frf_cur_mngd_dnr_ind,
frf_prvt_ind,
frf_visit_in_pairs_ind,
frf_spotlight_dnr_ind,
frf_chan_design_ind,
sustnr_ind,
plnd_gvng_confirm_ind,
plnd_gvng_info_rqst_ind,
inactvtn_reason_cd,
inactvtn_reason_dsc,
inactvtn_dt,
inactvtn_reason_txt,
ownr_key,
acct_ownr_key,
frf_acct_key,
frf_status_cd,
frf_spotlight_note_txt,
frf_ent_org_id,
frf_num_of_lctn,
frf_ownr_role_nm,
frf_gift_portfolio_ctg,
frf_cur_portfolio_ctg,
frf_industry_nm,
frf_acct_ownr_asgnd_dt,
frf_acct_modified_key,
frf_prev_acct_ownr_key,
frf_acct_ownr_key,
frf_acct_rgn_key,
rev_credit_key,
frf_rev_credit_key,
frf_dnr_intrst_othr_txt,
frf_dnr_intrst_txt,
frf_issue_risk_txt,
frf_leverage_point_txt,
frf_rlshp_fit_txt,
frf_rlshp_gap_txt,
frf_upld_txt,
frf_vsblty_thrshld_excd_ind,
frf_vsblty_thrshld_excd_cnt,
frf_vsblty_thrshld_excd_dt,
bio_acct_mngr_nm,
bio_acct_mngr_email,
bio_acct_mngr_phn,
bio_acct_ind,
bio_annual_collect_tgt,
bio_annual_drive_tgt,
bio_rgn_nm,
bio_cllctn_zipcode_dtl_key,
bio_maintain_strat_ind,
mmp_last_updated_dt,
mmp_status,
backed_out_ind,
back_out_reason_cd,
vendor_src_cd,
gift_sf_acct_chapter_diff_ind,
gift_planning_ind,
honor_roll,
geographic_interests,
geographic_notes ,
revenue_opportunity_min,
revenue_opportunity_max,
prospect_start_dt,
CASE WHEN prospect_start_dt IS NULL THEN 0 ELSE (CURRENT_DATE - prospect_start_dt) END AS prospect_age,
last_stage_change_dt,
CASE WHEN last_stage_change_dt IS NULL THEN 0 ELSE (CURRENT_DATE - last_stage_change_dt) END AS current_stage_age,
parent_id, -- Added for GMS-37298
parent_acct_cnst_key, -- Added for GMS-37298
parent_ind, -- Added for GMS-37298
TO_CHAR(srcsys_create_ts, 'MM/DD/YYYY HH24:MI:SS') AS srcsys_create_ts,
TO_CHAR(srcsys_update_ts, 'MM/DD/YYYY HH24:MI:SS') AS srcsys_update_ts,
srcsys_created_by,
srcsys_modified_by,
row_status_cd,
TO_CHAR(dw_trans_ts, 'MM/DD/YYYY HH24:MI:SS') AS dw_trans_ts,
load_id,
appl_src_cd,
buyerattributes
FROM cdigms_rep.ufds_tbls.bzfc_dim_unf_fr_cnst
WHERE row_status_cd != 'L'
WITH NO SCHEMA BINDING;
GRANT ALL ON TABLE mods_bi.ufds_vws.bzfc_dim_unf_fr_cnst TO role ds_mods_writer;
GRANT SELECT ON TABLE mods_bi.ufds_vws.bzfc_dim_unf_fr_cnst TO role ds_mods_reader_vt;
